Add dynamic levels support [WIP]
openware/peatio pull request #1194
Opened 2018-05-24 13:00 UTC by andreymakovenko

2018-05-24 13:07 UTC, yivo requested changes

2018-05-24 13:07 UTC, yivo commented on app/enums/member/levels.rb
> +        num >= ENV.fetch('MINIMUM_LEVEL', 3).to_i ? :kyc_verified : :unverified
Please no ANY UNDOCUMENTED variables. It is not clear what this variable does: minimum level of what? Also, we use everywhere `identity_verified` instead of KYC.

2018-05-24 13:07 UTC, yivo commented on app/enums/member/levels.rb
> +        num >= ENV.fetch('MINIMUM_LEVEL', 3).to_i ? :kyc_verified : :unverified
Update application.yml.erb

2018-05-24 13:07 UTC, yivo commented on app/enums/member/levels.rb
> +        num >= ENV.fetch('MINIMUM_LEVEL', 3).to_i ? :kyc_verified : :unverified
We can't add this feature. Do you see we support also email & phone verification? That'w shy issue we marked as «Needs discussion». And I haven't assigned you for this. We need to wait and clarify.

2018-05-25 07:42 UTC, andreymakovenko commented on app/enums/member/levels.rb
> +        num >= ENV.fetch('MINIMUM_LEVEL', 3).to_i ? :kyc_verified : :unverified
It's just a WIP, of course there would be docs
If discussion is needed, please, let's start it, cause it's kind of urgent

2018-05-25 09:16 UTC, yivo commented on app/enums/member/levels.rb
> +        num >= ENV.fetch('MINIMUM_LEVEL', 3).to_i ? :kyc_verified : :unverified
@andreymakovenko It is not urgent for me. I am focused on perf problems.

2018-05-29 15:08 UTC, yivo commented
@andreymakovenko Please, rebase PR.

2018-05-29 15:46 UTC, calj commented
@yivo we can try to introduce 3 variables:
MIN_LEVEL_TRADE
MIN_LEVEL_DEPOSIT
MIN_LEVEL_WITHDRAW

2018-05-29 15:48 UTC, mod commented on app/controllers/application_controller.rb
> +    if current_user.level.present? && !current_user.level.kyc_verified?
I did not expect this patch to modify this line,
and to be this is legacy code that should be renovated.

2018-05-29 16:05 UTC, mod commented
@andreymakovenko I think you are modifying the wrong code,
I would change the minimum level at the grape api side and I don't think we need any changes

2018-05-30 16:02 UTC, yivo commented
Closed in favor of #1222.

2018-05-30 16:02 UTC, closed without merging