Add readiness_probe
openware/peatio pull request #1197
Opened 2018-05-24 14:03 UTC by maksim-litvinov

Closes #1190

2018-05-24 20:43 UTC, calj commented on config/routes.rb
> +  get 'health/liveness_probe', to: 'public/health#liveness_probe'
I would vote for
/health/ready
/health/alive

2018-05-29 13:50 UTC, yivo requested changes

2018-05-29 13:50 UTC, yivo commented on lib/health_checker.rb
> +      result = KlineDB.redis.ping
Use Rails.cache to access redis.

2018-05-29 13:50 UTC, yivo commented on lib/health_checker.rb
> +  HealthCheckError = Class.new(StandardError)
1) All exceptions must be placed in fixed dir like app/exceptions
2) We don't need this exception. Just remove it. Do simple things.

2018-05-29 13:50 UTC, yivo commented on lib/health_checker.rb
> +    def check_rabbitmq
@maksim-litvinov Can you write it in 1 line and use automatic close?

2018-05-29 13:50 UTC, yivo commented on lib/health_checker.rb
> +      Market.exists?
We need to try to connect to database, we may have zero markets in DB. It is OK.

2018-05-29 13:50 UTC, yivo commented on lib/health_checker.rb
> +      report_exception(e)
Use `report_exception_to_screen`.

2018-05-29 13:50 UTC, yivo commented on lib/health_checker.rb
> +      report_exception(e)
Use `report_exception_to_screen`. It may hurt Sentry.

2018-05-29 13:50 UTC, yivo commented on lib/health_checker.rb
> +    def alive
Ruby convention is to use `?`: `alive?`.

2018-05-29 13:50 UTC, yivo commented on lib/health_checker.rb
> +module HealthChecker
Please put to app/services.

2018-05-29 13:50 UTC, yivo commented on lib/health_checker.rb
> +  LIVE_CHECKS = %i[check_db check_redis check_rabbitmq].freeze
Incorrect English: Use LIVENESS_CHECKS.

2018-05-29 13:50 UTC, yivo commented on lib/health_checker.rb
> +  READY_CHECKS = %i[check_db].freeze
Use READINESS_CHECKS

2018-05-29 13:50 UTC, yivo commented on lib/health_checker.rb
> +    rescue Exception => e
Better rescue StandardException here.

2018-05-29 13:50 UTC, yivo commented on lib/health_checker.rb
> +    rescue Exception => e
Better rescue StandardException here.

2018-05-29 13:50 UTC, yivo commented on lib/health_checker.rb
> +    def all_checks_passed?(checks)
Try to use `check!` for this method.

2018-05-29 13:50 UTC, yivo commented on lib/health_checker.rb
> +      result == 'PONG' or raise HealthCheckError, "Redis.ping returned #{result.inspect}"
Try to just return `false`.

2018-05-29 13:50 UTC, yivo commented on app/controllers/public/health_controller.rb
> +      head(health ? 200 : 503)
Can you omit brackets?

2018-05-29 15:07 UTC, yivo commented
@maksim-litvinov Please, rebase PR.

2018-06-01 09:56 UTC, yivo requested changes

2018-06-01 09:56 UTC, yivo commented on app/services/services/health_checker.rb
> +        ActiveRecord::Base.establish_connection
@maksim-litvinov Can you prove this will not produce lot of zombie connections?

2018-06-04 16:34 UTC, mod commented on app/services/services/health_checker.rb
> +        ActiveRecord::Base.establish_connection
We could do a simple select of something instead @maksim-litvinov

2018-06-05 08:28 UTC, maksim-litvinov commented
![screenshot from 2018-06-05 11-27-11](https://user-images.githubusercontent.com/1058433/40964351-8f6d2582-68b3-11e8-9d95-ffc9dbc96993.png)

Prove of check_db method

2018-06-05 10:27 UTC, yivo approved these changes

2018-06-05 10:28 UTC, yivo commented
@maksim-litvinov Actually this can be only proved by checking mysql connections number

2018-06-05 11:09 UTC, merged