Add support for Barong 1.8 dynamic levels (closes #1134)
openware/peatio pull request #1222
Opened 2018-05-30 14:43 UTC by mitjok

2018-05-30 15:04 UTC, mitjok commented
@yivo @calj pls take a look ^^.

2018-05-30 15:05 UTC, subaru9 commented
See also https://github.com/rubykube/peatio/pull/1194 for references

2018-05-30 15:22 UTC, m-an requested changes

2018-05-30 15:22 UTC, m-an commented on app/api/api_v2/helpers.rb
> +      if current_user.level != ENV['MINIMUM_MEMBER_LEVEL_FOR_DEPOSIT'].to_i
it's a minimum required level, so we should not use '!=', it cat be bigger than it. use '>='

2018-05-30 15:22 UTC, m-an commented on app/api/api_v2/helpers.rb
> +      if current_user.level != ENV['MINIMUM_MEMBER_LEVEL_FOR_WITHDRAW'].to_i
same here

2018-05-30 15:22 UTC, m-an commented on app/api/api_v2/helpers.rb
> +      if current_user.level != ENV['MINIMUM_MEMBER_LEVEL_FOR_TRADING'].to_i
and here

2018-05-30 15:22 UTC, m-an commented on app/controllers/application_controller.rb
> +    if current_user.level.present? && !current_user.level == 3
what is 3? The main goal of your task is to make levels DYNAMIC
3 is a static number

2018-05-30 15:22 UTC, m-an commented on db/migrate/20180530122201_change_members_level_type.rb
> +    add_column :members, :level_int, :integer, null: false, default: 0
why level_int? why do we need to know what it is int?

2018-05-30 15:22 UTC, m-an commented on db/migrate/20180530122201_change_members_level_type.rb
> +    rename_column :members, :level_int, :level
oh, gosh, I see...
you can simply change the field type in migration, there is no need to do it like this

2018-05-30 15:22 UTC, m-an commented on db/migrate/20180530122201_change_members_level_type.rb
> +    else 0
as far as I know, maximum level is 4 for now, this change needs discussion and investigation if it will not brake anything

2018-05-30 15:22 UTC, m-an commented on lib/peatio/feeders/member_feeder.rb
> +        level: 3
let's better use some of ENV variables here

2018-05-30 15:22 UTC, m-an commented on spec/factories/deposits.rb
> +    member { create(:member, :level_3) }
what is the difference between this and 
member { create(:member, level: 3) } ?
answer for yourself

2018-05-30 15:46 UTC, mitjok commented on app/controllers/application_controller.rb
> +    if current_user.level.present? && !current_user.level == 3
Not sure which from newly introduced ENV vars to use here

2018-05-30 15:48 UTC, mitjok commented on db/migrate/20180530122201_change_members_level_type.rb
> +    rename_column :members, :level_int, :level
I need to migrate existing strings to integers, this method is simple and reliable

2018-05-30 15:48 UTC, mitjok commented on db/migrate/20180530122201_change_members_level_type.rb
> +    else 0
@yivo  pls advice

2018-05-30 15:49 UTC, mitjok commented on lib/peatio/feeders/member_feeder.rb
> +        level: 3
not sure which one form new env vars..

2018-05-30 15:52 UTC, mitjok commented on spec/factories/deposits.rb
> +    member { create(:member, :level_3) }
abstraction, need more generic name though

2018-05-30 17:12 UTC, m-an requested changes
I suggest to just change the field type with migration.
Anyway all the data will be in Member table with integers after jwt parse

2018-05-31 09:41 UTC, yivo commented on db/migrate/20180530122201_change_members_level_type.rb
> +    else 0
@mitjok this is OKAY. Levels will be recalculated every time user makes request. So it is OK.

2018-05-31 09:51 UTC, yivo requested changes

2018-05-31 09:51 UTC, yivo commented on app/api/api_v2/helpers.rb
> +      if current_user.level < ENV['MINIMUM_MEMBER_LEVEL_FOR_DEPOSIT'].to_i
@mitjok Please, use `Hash#fetch`

2018-05-31 09:51 UTC, yivo commented on app/api/api_v2/helpers.rb
> +      if current_user.level < ENV['MINIMUM_MEMBER_LEVEL_FOR_WITHDRAW'].to_i
@mitjok Please, use `Hash#fetch`

2018-05-31 09:51 UTC, yivo commented on app/api/api_v2/helpers.rb
> +      if current_user.level < ENV['MINIMUM_MEMBER_LEVEL_FOR_TRADING'].to_i
@mitjok Please, use `Hash#fetch`

2018-05-31 09:51 UTC, yivo commented on app/api/api_v2/helpers.rb
> +        raise Grape::Exceptions::Base.new(text: 'Please pass the corresponding verification step to withdraw funds.', status: 401)
Please, update message: `Please, pass the corresponding verification steps to withdraw funds.`.

2018-05-31 09:51 UTC, yivo commented on app/api/api_v2/helpers.rb
> +        raise Grape::Exceptions::Base.new(text: 'Please pass the corresponding verification step to enable trading.', status: 401)
Please, update message: `Please, pass the corresponding verification steps to enable trading.`.

2018-05-31 09:51 UTC, yivo commented on app/api/api_v2/helpers.rb
> +        raise Grape::Exceptions::Base.new(text: 'Please pass the corresponding verification step to deposit funds.', status: 401)
Please, update message: `Please, pass the corresponding verification steps to deposit funds.`.

2018-05-31 09:51 UTC, yivo commented on app/controllers/private/base_controller.rb
> +      if current_user.level < ENV['MINIMUM_MEMBER_LEVEL_FOR_DEPOSIT'].to_i
Use `Hash#fetch`.

2018-05-31 09:51 UTC, yivo commented on app/controllers/private/base_controller.rb
> +      if current_user.level < ENV['MINIMUM_MEMBER_LEVEL_FOR_WITHDRAW'].to_i
Use `Hash#fetch`.

2018-05-31 09:51 UTC, yivo commented on app/controllers/private/base_controller.rb
> +      if current_user.level < ENV['MINIMUM_MEMBER_LEVEL_FOR_TRADING'].to_i
Use `Hash#fetch`.

2018-05-31 09:51 UTC, yivo commented on app/models/member.rb
>  # == Schema Information
For me this schema seems not valid. Level must go after ID and be 1 byte integer, not null, default 0.

2018-05-31 09:51 UTC, yivo commented on config/locales/server.en.yml
> +        deposits_must_be_permitted: Please pass the corresponding verification steps to deposit funds.
Can you please update the messages here as in API?

2018-05-31 09:51 UTC, yivo commented on config/templates/application.yml.erb
> +  MINIMUM_MEMBER_LEVEL_FOR_DEPOSIT: 3
Please, add heading: `Configuration variables for dynamic Barong levels (1.8+).` and align values.

2018-05-31 09:51 UTC, yivo commented on db/migrate/20180530122201_change_members_level_type.rb
> +    Member.find_each do |m|
@mitjok Don't use models in migration. Use SQL.

2018-05-31 09:51 UTC, yivo commented on db/migrate/20180530122201_change_members_level_type.rb
> +    Member.find_each do |m|
Or, if you can't, stud Member model like `class Member < ActiveRecord::Base` directly in migration.

2018-05-31 09:51 UTC, yivo commented on spec/factories/member.rb
> +      after(:create) { |member| member.update_column(:level, 3) }
@mitjok Can you try to avoid extra query here?

2018-05-31 09:51 UTC, yivo commented on spec/factories/member.rb
> +    trait :high_level do
I think level_0, level_1 etc will play better.

2018-05-31 09:51 UTC, yivo commented on spec/factories/member.rb
> +      after(:create) { |member| member.update_column(:level, 3) }
![image](https://user-images.githubusercontent.com/7421323/40775658-44d62284-64d1-11e8-870a-32c4aadd1e20.png)

2018-05-31 11:15 UTC, mitjok commented
@yivo review fixes done

2018-05-31 12:45 UTC, yivo requested changes
You missed half of my comments. What's wrong?

2018-05-31 12:45 UTC, yivo commented on config/templates/application.yml.erb
> +  # Configuration variables for dynamic Barong levels (1.8+)
Please put dot at the end:

![image](https://user-images.githubusercontent.com/7421323/40782729-f2c0d300-64e8-11e8-8aec-bad03f9271a9.png)

2018-05-31 12:45 UTC, yivo commented on config/locales/server.en.yml
> +        deposits_must_be_permitted: Please, pass the corresponding verification step to deposit funds.
Please, update messages as I asked you.

2018-05-31 12:45 UTC, yivo commented on app/models/member.rb
> +# Schema version: 20180525101406
Schema still not updated.

2018-05-31 12:45 UTC, yivo commented on app/api/api_v2/helpers.rb
> +    def deposits_must_be_permitted!
Messages are not updated.

2018-05-31 12:45 UTC, yivo commented on db/schema.rb
>    create_table "members", force: :cascade do |t|
Schema outdated.

2018-06-01 10:52 UTC, mitjok commented on app/api/api_v2/helpers.rb
> +    def deposits_must_be_permitted!
fixed

2018-06-01 10:53 UTC, mitjok commented on db/migrate/20180530122201_change_members_level_type.rb
> +    Member.find_each do |m|
repeated `class Member` declaration in migration

2018-06-01 11:15 UTC, mitjok commented on app/models/member.rb
>  # == Schema Information
fixed

2018-06-01 11:19 UTC, mitjok commented on db/schema.rb
>    create_table "members", force: :cascade do |t|
level type and order among columns fixed

2018-06-04 12:11 UTC, yivo requested changes

2018-06-04 12:11 UTC, yivo commented on app/api/api_v2/auth/jwt_authenticator.rb
>          Member.find_or_initialize_by(email: fetch_email(payload)).tap do |member|
Please fix migration ASAP

![image](https://user-images.githubusercontent.com/7421323/40916744-898fe3c0-6809-11e8-8db6-946875b9b320.png)

2018-06-04 12:13 UTC, yivo commented on app/api/api_v2/auth/jwt_authenticator.rb
>          Member.find_or_initialize_by(email: fetch_email(payload)).tap do |member|
![image](https://user-images.githubusercontent.com/7421323/40916813-cb08b002-6809-11e8-8da4-a20d29f9b55a.png)

2018-06-04 12:41 UTC, yivo commented on app/api/api_v2/auth/jwt_authenticator.rb
>          Member.find_or_initialize_by(email: fetch_email(payload)).tap do |member|
![image](https://user-images.githubusercontent.com/7421323/40918016-c48390a4-680d-11e8-9a18-6d934e06d107.png)

2018-06-04 15:53 UTC, mitjok commented on app/api/api_v2/auth/jwt_authenticator.rb
>          Member.find_or_initialize_by(email: fetch_email(payload)).tap do |member|
@yivo fixed

2018-06-07 11:52 UTC, yivo approved these changes

2018-06-07 17:53 UTC, mod commented on app/api/api_v2/helpers.rb
> +      if current_user.level < ENV.fetch('MINIMUM_MEMBER_LEVEL_FOR_WITHDRAW').to_i
Could we validate ENV once in initializer or throw error, we can allow from 1 to 99 values or set default value to 3 with a log warning.

Later I would like to access the variable not using ENV.fetch

I would favor a Yaml config
minimum_level:
  withdrawal: 3
  deposit: 1
  trade: 1

2018-06-07 18:55 UTC, yivo commented
@mod I have added validation: https://github.com/rubykube/peatio/pull/1222/commits/7bb300ff0ea2c6274583e018aee8d942095793e2

NOTE: We allow zero level to get support for Auth0 & Google Auth.

2018-06-08 06:47 UTC, mod commented on app/controllers/private/base_controller.rb
> +      if current_user.level < ENV.fetch('MINIMUM_MEMBER_LEVEL_FOR_DEPOSIT').to_i
@yivo @mitjok I would only merge if we stop spreading ENV.fetch across the code
if we don't have better than figaro then we centralise variables into figaro or we can switch all to secrets.yml, or making a Peatio.config.thing.var

2018-06-08 06:48 UTC, mod requested changes
@yivo can you suggest a permanent solution for centralizing the loading of vars, validation on initialize to throw errors on boot, not runtime
define defaults and ability to set in file or using ENV.

2018-06-08 10:28 UTC, yivo commented
@mod What is wrong with variables? https://github.com/rubykube/peatio/pull/1222/files#diff-81b753b02c902d26e3b837d7814c5244R168

2018-06-08 14:49 UTC, merged