Check if both currencies are enabled on market enabling (closes #1242)
openware/peatio pull request #1243
Opened 2018-06-04 14:37 UTC by yssavchuk

2018-06-06 14:35 UTC, yssavchuk commented
@yivo review please

2018-06-07 12:45 UTC, yivo requested changes

2018-06-07 12:45 UTC, yivo commented on spec/factories/currencies.rb
> +      precision            2
Use 8

2018-06-07 12:45 UTC, yivo commented on spec/factories/currencies.rb
> +      quick_withdraw_limit 10
Set 1000

2018-06-07 12:45 UTC, yivo commented on app/models/market.rb
> +  validate  :units_must_be_enabled, if: -> (market){ market.enabled? }
Change to `if: :enabled?`

2018-06-07 12:45 UTC, yivo commented on app/models/market.rb
> +      errors.add(:base, 'Currencies must be enabled.') if Currency.lock.find_by_id(unit)&.disabled?
We need to do some updates to it.

The error should look like `errors.add(:ask_unit, 'is not enabled.')`

```
[:bid_unit, :ask_unit].each do |unit|
  errors.add(unit, 'is not enabled.') if Currency.lock.find_by_id(public_send(unit))&.disabled?
end
```

2018-06-07 13:53 UTC, yivo approved these changes

2018-06-07 17:26 UTC, merged