[WIP] #1249 Improvements for legacy benchmark tools
openware/peatio pull request #1254
Opened 2018-06-06 12:27 UTC by dinesh-skyach

Improvements for legacy benchmark tools #1249

2018-06-07 08:35 UTC, mod commented on lib/profiling/execution.rb
> +require 'ruby-prof'
@dinesh-skyach you must find a way to avoid code duplication
profiler should go in benchmark, improve benchmark usage eventually to configure smaller runs

2018-06-07 10:43 UTC, yivo requested changes

2018-06-07 10:43 UTC, yivo commented on Gemfile
> +  gem 'ruby-prof'
NEVER NEVER NEVER omit VERSION, AND DON'T require uneeded deps

2018-06-07 18:40 UTC, mod requested changes
@dinesh-skyach you misunderstand me,

we need the existing benchmark to be able to support profiling

we can do
```
# will run regular benchmark
rake benchmark:matching

# Will run the same benchmark code with ruby-prof
# lower number of rounds and count
rake profiling:matching
```

2018-06-08 06:35 UTC, dinesh-skyach commented
@mod I didn't get what you mean by "Will run the same benchmark code with ruby-prof". The code is almost the same only the difference is that we need to run the benchmark under Benchmark.benchmark { } block and 'ruby-prof' under RubyProf.profile { } block.

Also for this "rake profiling:matching" currently to run this we use rake benchmark:profiling['matching']. Here you mean to change this to rake profiling:matching.

2018-06-13 12:19 UTC, yivo approved these changes

2018-06-13 14:37 UTC, mod commented
you are duplicating code can you make the feature without duplicating the code ?
@dinesh-skyach

2018-06-14 11:45 UTC, dinesh-skyach commented
@mod  we need different files for profiling and benchmark, as they run under different blocks and also as we use 'ruby-prof' gem and this prints very large output because it  tracks the recursively called methods. So we save the output in a file.

2018-06-18 09:22 UTC, mod approved these changes

2018-06-18 09:22 UTC, mod commented
@dinesh-skyach I still think you could have refactored the code in order to get less repeating code

2018-06-18 09:23 UTC, merged