Add documentation for websocket api
openware/peatio pull request #1256
Opened 2018-06-06 19:06 UTC by ashanaakh

2018-06-07 07:41 UTC, mod requested changes

2018-06-07 07:41 UTC, mod commented on docs/api/websocket_api.md
> +```
We need the list of subscription channels and information between what message goes on public channel and which ones on private channel @yivo @ashanaakh

2018-06-07 07:41 UTC, mod commented on docs/api/websocket_api.md
> +| `trades`        | List of trades.                                         |
I believe there is other message types.

2018-06-07 12:13 UTC, ashanaakh commented
@mod as I see in the websocket protocol source code, here is **no** private/public channels.

https://github.com/rubykube/peatio/blob/8537db2b28e35ff71b64a35d494207bd302e6739/app/api/api_v2/websocket_protocol.rb#L47-L48

https://github.com/rubykube/peatio/blob/8537db2b28e35ff71b64a35d494207bd302e6739/app/api/api_v2/websocket_protocol.rb#L61-L62

I think it is initialized only once on the websocket connection.
Here:
https://github.com/rubykube/peatio/blob/8537db2b28e35ff71b64a35d494207bd302e6739/lib/daemons/websocket_api.rb#L19

Also for me important to mention, that API has on three main types of messages:
- `orderbook`
- `trade`
- `order`

2018-06-08 10:51 UTC, yivo requested changes

2018-06-08 10:51 UTC, yivo commented on docs/api/websocket_api.md
> +# Peatio WebSocket API
@ashanaakh Can you add some small Ruby script into this doc to demonstrate usage?

2018-06-08 13:53 UTC, mod commented
I don't understand how to use this as API by reading this md file, use more English words please describe make a drawing, do whatever it takes

2018-06-08 17:18 UTC, ashanaakh commented
@mod I think their no use to add drawing here. @yivo I've added ruby code in the bottom, looks much clear for me.

2018-06-13 12:19 UTC, yivo approved these changes

2018-06-13 14:29 UTC, merged