[WIP] Peatio to update database when user withdraws successfully on chain
openware/peatio pull request #1276
Opened 2018-06-12 09:52 UTC by yssavchuk

2018-07-02 18:07 UTC, yssavchuk commented
@yivo take a look please

2018-07-04 12:26 UTC, yivo requested changes

2018-07-04 12:26 UTC, yivo commented on app/models/withdraw.rb
> +#  confirmations :integer          default(0), not null
Should be 4 byte integer unsigned not null default 0 and located after rid.

2018-07-04 12:26 UTC, yivo commented on lib/daemons/withdraw_confirm.rb
> +  Withdraw.confirming.order(created_at: :asc).map(&:try_to_confirm!)
Never use created_at for ordering. It is not in the index list. Use `Withdraw::Coin.includes(:currency).find_each(bulk_size: 10) { |record| ... }`. Check if option `bulk_size` is correct, I am not sure.

You need to handle withdraw_confirmation = 0, first load confirmations for TXID, then reload record by acquiring lock on it and atomically update state.

2018-07-04 12:26 UTC, yivo commented on app/models/withdraws/coin.rb
> +    def try_to_confirm!
@yssavchuk Delete this method and move it to daemon.

2018-07-04 12:26 UTC, yivo commented on lib/daemons/withdraw_confirm.rb
> +  Withdraw.confirming.order(created_at: :asc).map(&:try_to_confirm!)
You also missed break unless running inside loop.

2018-07-04 15:18 UTC, yssavchuk commented
@yivo updated

2018-07-05 09:46 UTC, yivo requested changes

2018-07-05 09:46 UTC, yivo commented on app/models/withdraw.rb
> +    event :confirm do
Well it is not logical name for the state which means not finished operation. `withdraw.confirm` seems like it was confirmed in blockchain. Change name to something like `dispatch`.

2018-07-05 09:46 UTC, yivo commented on lib/daemons/withdraw_confirm.rb
> +    break if withdraw.txid.blank?
Why it should be blank here? Remove the like pls.

2018-07-05 10:03 UTC, yivo approved these changes

2018-07-06 09:56 UTC, ysv commented on lib/coin_api/bit_go.rb
> +      deposit.merge(entries: entries)
@yivo I found this solution. What do you think ?

2018-07-18 14:24 UTC, ysv commented
Closed in #1427

2018-07-18 14:24 UTC, closed without merging