[slim to erb] Admin pages
openware/peatio pull request #132
Opened 2017-12-19 16:10 UTC by spavlishak

2017-12-20 10:42 UTC, yivo requested changes

2017-12-20 10:42 UTC, yivo commented on app/views/admin/currency_deposits/new.html.erb
> +    <%= detail_section_tag "#{t('.deposit')}" %>
@spavlishak remove unnecessary interpolation (+ check all templates)

2017-12-20 10:42 UTC, yivo commented on app/views/admin/withdraws/banks/show.html.erb
> +            <span class="fa fa-copy" data-clipboard-text="<% bank_code_to_name @bank.fund_extra %>">
@spavlishak This does not output anything since it is missing `=`. Check this across all templates.

2017-12-20 17:03 UTC, yivo commented
@spavlishak any updates?

2017-12-21 18:16 UTC, mkuvshynnikov commented
[WIP]

**/admin**
Page

- [ ] Documents ( /admin/documents )

- documents do not create 
![screen shot 2017-12-21 at 7 16 36 pm](https://user-images.githubusercontent.com/29736025/34267407-5c75bc12-e685-11e7-9fa7-608942388629.png)

- [ ] Verify Account:

- Enter to any registered member by clicking button "View"

![vacc](https://user-images.githubusercontent.com/29736025/34267706-839f42e4-e686-11e7-87a8-7438771a782f.png)

1. Displaying link (should not be displayed there)

2. Button "Reject" do not works

- [ ] Proof:

- Click on page Proof > view that two pages highlighted
![proof1](https://user-images.githubusercontent.com/29736025/34268603-0be30a3e-e68a-11e7-9cda-b322b59a28bf.png)

- Click on button "Edit":

1. We can edit "Created at " and it looks weird 
![screen shot 2017-12-21 at 8 10 27 pm](https://user-images.githubusercontent.com/29736025/34269043-989d00f0-e68b-11e7-8887-f750395e8178.png)




 


E-mail verification do not works

2017-12-27 10:41 UTC, yivo commented
@spavlishak Please rebase.

2017-12-27 11:56 UTC, yivo requested changes

2017-12-27 11:56 UTC, yivo commented on app/views/admin/currency_deposits/new.html.erb
> +        <%= link_to t('actions.new'), admin_member_path(@member), target='_blank', class: 'btn btn-inverse' %>
@spavlishak You have Ruby syntax error here.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/currency_deposits/new.html.erb
> +      <%= detail_section_tag a.currency_text t('.accounts_title') %>
@spavlishak should be ` = detail_section_tag "#{a.currency_text} #{t('.accounts_title')}"`

2017-12-27 11:56 UTC, yivo commented on app/views/admin/dashboard/index.html.erb
> +<div class="row">
@spavlishak Please check original template at `app/views/admin/dashboard/index.html.slim`. There are lot of differences.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/deposits/banks/_table.html.erb
> +      <span><%= bank_code_to_name x.fund_extra x.fund_uid %></span>
@spavlishak Should be `span #{bank_code_to_name x.fund_extra} # #{x.fund_uid}`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/deposits/banks/_table.html.erb
> +      <span><%= x.aasm_state_text ' / ' %></span>
@spavlishak Should be `span = "#{x.aasm_state_text} / "`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/deposits/ripples/index.html.erb
> +      <span><%= ' / ' %></span>
@spavlishak No need for interpolation here.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/deposits/ripples/index.html.erb
> +  <% t.column :txid do |x| %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/deposits/ripples/index.html.erb
> +  <% t.column :created_at %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/deposits/ripples/index.html.erb
> +  <% t.column :currency_obj_key_text %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/deposits/ripples/index.html.erb
> +  <% t.column :member_name do |x| %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/deposits/ripples/index.html.erb
> +  <% t.column :amount do |x| %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/deposits/ripples/index.html.erb
> +  <% t.column :confirmations do |x| %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/deposits/ripples/index.html.erb
> +  <% t.column :state_and_actions do |x| %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/deposits/satoshis/index.html.erb
> +  <% t.column :created_at %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/deposits/satoshis/index.html.erb
> +      <span><%= ' / ' %></span>
@spavlishak No need for interpolation here.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/deposits/satoshis/index.html.erb
> +  <% t.column :currency_obj_key_text %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/deposits/satoshis/index.html.erb
> +  <% t.column :member_name do |x| %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/deposits/satoshis/index.html.erb
> +  <% t.column :amount do |x| %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/deposits/satoshis/index.html.erb
> +  <% t.column :confirmations do |x| %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/deposits/satoshis/index.html.erb
> +  <% t.column :state_and_actions do |x| %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/deposits/banks/_table.html.erb
> +    <% t.column :fund_source, t('.fund_source'), class: 'col-xs-5' do |x| %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/deposits/banks/_table.html.erb
> +    <% t.column :member_name, t('.name'), class: 'col-xs-3' do |x| %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/deposits/banks/_table.html.erb
> +    <% t.column :currency_obj_key_text, t('.currency'), class: 'col-xs-2' %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/deposits/banks/_table.html.erb
> +    <% t.column :created_at, class: 'col-xs-4' %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/deposits/banks/_table.html.erb
> +    <% t.column :sn, class: 'col-xs-2' %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/deposits/banks/_table.html.erb
> +    <% t.column :amount, class: 'col-xs-3' do |x| %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/deposits/banks/_table.html.erb
> +    <% t.column :state_and_actions, t('.action'), class: 'col-xs-3' do |x| %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/documents/_form.html.erb
> +  $ ->
@spavlishak You should convert the code to JS.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/id_documents/index.html.erb
> +<div class="card">
@spavlishak It totally differs from `app/views/admin/id_documents/index.html.slim`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/id_documents/show.html.erb
> +<div class="col-xs-18">
@spavlishak It totally differs from `app/views/admin/id_documents/show.html.erb`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/members/index.html.erb
> +<div class="row">
@spavlishak It totally differs from `app/views/admin/members/index.html.slim`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/members/show.html.erb
> +    <div class="card">
@spavlishak Should be `.panel.panel-info`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/members/show.html.erb
> +      <div class="card-header">Accounts Log</div>
@spavlishak Should be `.panel-heading Accounts Log`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/members/show.html.erb
> +      <div class="card-body">
@spavlishak Should be `.panel-body`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/members/show.html.erb
> +          <% t.column :created_at, class: 'col-xs-6' %>
@spavlishak No output here `=`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/members/show.html.erb
> +          <% t.column :fee, class: 'col-xs-2' do |x| %>
@spavlishak No output here `=`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/members/show.html.erb
> +          <% t.column :out, class: 'col-xs-3' do |x| %>
@spavlishak No output here `=`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/members/show.html.erb
> +          <% t.column :in, class: 'col-xs-3' do |x| %>
@spavlishak No output here `=`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/members/show.html.erb
> +          <% t.column :amount, class: 'col-xs-4' do |x| %>
@spavlishak No output here `=`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/members/show.html.erb
> +          <% t.column :reason_text, class: 'col-xs-3' %>
@spavlishak No output here `=`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/members/show.html.erb
> +          <% t.column :modifiable_type, class: 'col-xs-2' do |x| %>
@spavlishak No output here `=`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/members/show.html.erb
> +          <% t.column :currency_text, class: 'col-xs-1' %>
@spavlishak No output here `=`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/statistic/members/show.html.erb
> +        <% t.column :date, 'Date', class: 'col-xs-8' do |x| %>
@spavlishak No output here `=`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/statistic/members/show.html.erb
> +          <span><%= '/' %></span>
@spavlishak No need for ERB here.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/statistic/members/show.html.erb
> +        <% t.column :reg, 'Act / Reg', class: 'col-xs-10' do |x| %>
@spavlishak No output here `=`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/statistic/members/show.html.erb
> +        <% t.column :rate, 'Rate', class: 'col-xs-6' do |x| %>
@spavlishak No output here `=`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/tickets/index.html.erb
> +|&nbsp; &nbsp; &nbsp;
@spavlishak Please remove pipe.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/tickets/index.html.erb
> +              <span><%= "#{I18n.t("private.tickets.from")}: #{t.author.email}" %></span>
@spavlishak You don't need interpolation here.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/tickets/index.html.erb
> +              <%= "#{t('admin.tickets.comments_count')}(#{t.comments.count})" %>
@spavlishak No need for interpolation here.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/tickets/show.html.erb
> +| &nbsp; &nbsp; &nbsp;
@spavlishak Please remove pipe.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/tickets/show.html.erb
> +<br></br>
@spavlishak `br` is self-closing tag.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/tickets/show.html.erb
> +<br></br>
@spavlishak `br` is self-closing tag.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/tickets/show.html.erb
> +              <span><%= I18n.t('private.tickets.from'): @ticket.author.email %></span>
@spavlishak Ruby syntax error here. Also you need to use two ERB calls here.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/tickets/show.html.erb
> +    <br></br>
@spavlishak `br` is self-closing tag.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/tickets/show.html.erb
> +              <span><%= I18n.t('private.tickets.from'): c.author.email %></span>
@spavlishak Ruby syntax error here. You will need two ERB calls here.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/banks/_table.html.erb
> +  <% t.column :id, class: 'col-xs-2' %>
@spavlishak No output here `=`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/banks/_table.html.erb
> +  <% t.column :member_name, class: 'col-xs-3' do |x| %>
@spavlishak No output here `=`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/banks/_table.html.erb
> +  <% t.column :currency_obj_key_text, class: 'col-xs-2' %>
@spavlishak No output here `=`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/banks/_table.html.erb
> +  <% t.column :created_at, class: 'col-xs-3' %>
@spavlishak No output here `=`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/banks/_table.html.erb
> +  <% t.column :fund_source, class: 'col-xs-6' do |x| %>
@spavlishak No output here `=`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/banks/_table.html.erb
> +  <% t.column :amount, class: 'col-xs-3' do |x| %>
@spavlishak No output here `=`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/banks/_table.html.erb
> +  <% t.column :state_and_action, class: 'col-xs-3' do |x| %>
@spavlishak No output here `=`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/banks/_table.html.erb
> +      <%= x.aasm_state_text ' / '  %>
@spavlishak Should be `span = "#{x.aasm_state_text} / "` but using ERB.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/ripples/_table.html.erb
> +      <%= x.fund_extra x.fund_uid.truncate(22) %>
@spavlishak Should be `span #{x.fund_extra} # #{x.fund_uid.truncate(22)}`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/ripples/_table.html.erb
> +    <span><%= x.aasm_state_text ' / ' %></span>
@spavlishak Should be `span = "#{x.aasm_state_text} / "`.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/ripples/_table.html.erb
> +  <% t.column :id, class: 'col-xs-2' %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/ripples/_table.html.erb
> +  <% t.column :fund_source, class: 'col-xs-6' do |x| %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/ripples/_table.html.erb
> +  <% t.column :member_name, class: 'col-xs-3' do |x| %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/ripples/_table.html.erb
> +  <% t.column :currency_obj_key_text, class: 'col-xs-2' %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/ripples/_table.html.erb
> +  <% t.column :created_at, class: 'col-xs-3' %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/ripples/_table.html.erb
> +  <% t.column :state_and_action, class: 'col-xs-3' do |x| %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/ripples/_table.html.erb
> +  <% t.column :amount, class: 'col-xs-3' do |x| %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/satoshis/_table.html.erb
> +  <% t.column :state_and_action, class: 'col-xs-3' do |x| %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/satoshis/_table.html.erb
> +  <% t.column :amount, class: 'col-xs-3' do |x| %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/satoshis/_table.html.erb
> +  <% t.column :fund_source, class: 'col-xs-6' do |x| %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/satoshis/_table.html.erb
> +  <% t.column :member_name, class: 'col-xs-3' do |x| %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/satoshis/_table.html.erb
> +  <% t.column :currency_obj_key_text, class: 'col-xs-2' %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/satoshis/_table.html.erb
> +  <% t.column :created_at, class: 'col-xs-3' %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/satoshis/_table.html.erb
> +  <% t.column :id, class: 'col-xs-2' %>
@spavlishak No output here (`=`).

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/satoshis/_table.html.erb
> +      <%= x.fund_extra x.fund_uid.truncate(22)} %>
@spavlishak Should be `span #{x.fund_extra} # #{x.fund_uid.truncate(22)}` but using ERB.

2017-12-27 11:56 UTC, yivo commented on app/views/admin/withdraws/satoshis/_table.html.erb
> +    <span><%= x.aasm_state_text ' / ' %></span>
@spavlishak Should be `span = "#{x.aasm_state_text} / "`.

2018-01-03 14:54 UTC, yivo approved these changes

2018-01-03 15:43 UTC, merged