[WIP] #705 Specs for WS protocol API
openware/peatio pull request #1322
Opened 2018-06-18 12:05 UTC by dinesh-skyach

Specs for WS protocol API #705

2018-06-18 12:12 UTC, yivo requested changes

2018-06-18 12:12 UTC, yivo commented on spec/api/api_v2/websocket_protocol_spec.rb
> +require 'api_v2/websocket_protocol'
This is autoloaded, don't use require.

2018-06-18 12:12 UTC, yivo commented on Gemfile
> +  gem 'bunny-mock', '~> 1.7.0', require: false
You can skip require: false here since these gems will be required in spec/support. Also please align the dependencies.

2018-06-18 12:12 UTC, yivo commented on spec/socket_helper.rb
> +def start_server(opts = {})
Please don't expose any common `start_server` methods. It is confusing what it is for. web server? rails or what? Use better name.

2018-06-18 12:12 UTC, yivo commented on spec/spec_helper.rb
> +require 'socket_helper'
This is autoloaded too.

2018-06-18 12:12 UTC, yivo commented on spec/api/api_v2/websocket_protocol_spec.rb
> +            status[:was_clean].should be false
Don't use `should` syntax. Use `expect`.

2018-06-18 12:12 UTC, yivo commented on spec/api/api_v2/websocket_protocol_spec.rb
> +  let(:ws_client) { EventMachine::WebSocketClient.connect("ws://#{ENV['WEBSOCKET_HOST']}:#{ENV['WEBSOCKET_PORT']}/") }
Can you use `ENV.fetch` here?

2018-06-18 12:12 UTC, yivo commented on spec/socket_helper.rb
> +  EM::WebSocket.run({:host => ENV['WEBSOCKET_HOST'], :port => ENV['WEBSOCKET_PORT']}.merge(opts)) { |ws|
Use ENV.fetch

2018-06-18 12:12 UTC, yivo commented on spec/api/api_v2/websocket_protocol_spec.rb
> +    it "user successfully authenticated" do
Use single type of quotes.

2018-06-18 12:12 UTC, yivo commented on spec/api/api_v2/websocket_protocol_spec.rb
> +    it "user authentication failed" do
Can you write better descriptions? Like `it 'denies access'`.

2018-06-18 12:12 UTC, yivo commented on spec/api/api_v2/websocket_protocol_spec.rb
> +    it "user authentication failed" do
Can you write better descriptions? Like `it 'denies access'`.

2018-06-19 05:47 UTC, dinesh-skyach commented on spec/api/api_v2/websocket_protocol_spec.rb
> +require 'api_v2/websocket_protocol'
@yivo done. I had to rename the file to autoload it.

2018-06-19 05:48 UTC, dinesh-skyach commented on Gemfile
> +  gem 'bunny-mock', '~> 1.7.0', require: false
@done

2018-06-19 05:49 UTC, dinesh-skyach commented on spec/socket_helper.rb
> +def start_server(opts = {})
done

2018-06-19 05:54 UTC, dinesh-skyach commented on spec/spec_helper.rb
> +require 'socket_helper'
done

2018-06-19 05:54 UTC, dinesh-skyach commented on spec/api/api_v2/websocket_protocol_spec.rb
> +            status[:was_clean].should be false
done

2018-06-19 05:56 UTC, dinesh-skyach commented on spec/api/api_v2/websocket_protocol_spec.rb
> +  let(:ws_client) { EventMachine::WebSocketClient.connect("ws://#{ENV['WEBSOCKET_HOST']}:#{ENV['WEBSOCKET_PORT']}/") }
done

2018-06-19 05:57 UTC, dinesh-skyach commented on spec/socket_helper.rb
> +  EM::WebSocket.run({:host => ENV['WEBSOCKET_HOST'], :port => ENV['WEBSOCKET_PORT']}.merge(opts)) { |ws|
done

2018-06-19 05:57 UTC, dinesh-skyach commented on spec/api/api_v2/websocket_protocol_spec.rb
> +    it "user successfully authenticated" do
done

2018-06-19 05:58 UTC, dinesh-skyach commented on spec/api/api_v2/websocket_protocol_spec.rb
> +    it "user authentication failed" do
done

2018-06-19 05:58 UTC, dinesh-skyach commented on spec/api/api_v2/websocket_protocol_spec.rb
> +    it "user authentication failed" do
done

2018-06-26 07:57 UTC, dinesh-skyach commented
@yivo I have made the changes.

2018-06-27 12:22 UTC, yivo approved these changes

2018-06-28 08:55 UTC, mod approved these changes

2018-06-28 08:55 UTC, merged