[WIP] Trade execution oneshot
openware/peatio pull request #1323
Opened 2018-06-18 17:55 UTC by yssavchuk

2018-06-21 09:26 UTC, yivo requested changes

2018-06-21 09:26 UTC, yivo commented on bin/trade_execution_oneshot
> +def daemon(amqp_daemon)
This is not correct way to run daemon. You have to use separate threads. Don't forget to terminate them at the end of main program.

2018-06-21 09:26 UTC, yivo commented on bin/trade_execution_oneshot
> +        ask:           @current_market&.base_unit,
You can use ask_unit/bid_unit here.

2018-06-21 09:26 UTC, yivo commented on bin/trade_execution_oneshot
> +        state:         ::Order::WAIT,
`::` is not needed.

2018-06-21 09:26 UTC, yivo commented on bin/trade_execution_oneshot
> +  currency = Currency.find_by_id(attrs[:currency])
Never use Currency#find_by_id

2018-06-21 09:26 UTC, yivo commented on bin/trade_execution_oneshot
> +    txout: SecureRandom.hex(4))
This is not valid value

2018-06-21 09:26 UTC, yivo commented on bin/trade_execution_oneshot
> +    address: SecureRandom.hex(4),
Use Faker

2018-06-21 09:26 UTC, yivo commented on bin/trade_execution_oneshot
> +    txid: SecureRandom.hex(4),
Use Faker

2018-06-21 09:26 UTC, yivo commented on bin/trade_execution_oneshot
> +  "Deposits/#{currency.type}".camelize.constantize.create!(
Use `deposits/#{}` ...

2018-06-21 09:26 UTC, yivo commented on bin/trade_execution_oneshot
> +    .tap { |d| d.accept! }
Use tap(&:accept!)

2018-06-21 09:26 UTC, yivo commented on bin/trade_execution_oneshot
> +    member: @current_user,
Align attributes please

2018-06-21 09:26 UTC, yivo commented on bin/trade_execution_oneshot
> +    currency: Currency.find_by_id(:btc),
Never combine find_by_id and currency in this context

2018-06-21 09:26 UTC, yivo commented on bin/trade_execution_oneshot
> +    txid: "test1",
Don't mix quotes

2018-06-21 09:26 UTC, yivo commented on bin/trade_execution_oneshot
> +def deposit_attrs
What this is needed for?

2018-06-21 09:26 UTC, yivo commented on bin/trade_execution_oneshot
> +# def current_market
Remove comments

2018-06-21 09:26 UTC, yivo commented on bin/trade_execution_oneshot
> +# # 10.times do
Remove comments

2018-06-21 09:26 UTC, yivo commented on bin/trade_execution_oneshot
> +#binding.pry
Remove comments

2018-06-21 09:26 UTC, yivo commented on bin/trade_execution_oneshot
> +@current_market = Market.find_by(bid_unit: bid_unit, ask_unit: ask_unit)
Use Market#find

2018-07-03 09:37 UTC, mod commented
@yssavchuk  Can we move this to peatio-core

2018-07-03 09:37 UTC, closed without merging