deleted error with first nil element
openware/peatio pull request #134
Opened 2017-12-20 11:40 UTC by emasiuk

2017-12-20 11:57 UTC, yivo requested changes

2017-12-20 11:57 UTC, yivo commented on app/controllers/private/withdraws/satoshis_controller.rb
> +    def new
@emasiuk you should put this in `Withdraws::Withdrawable`

2017-12-20 17:09 UTC, yivo commented
@emasiuk could you please check tests?

2017-12-22 18:02 UTC, yivo approved these changes

2017-12-22 18:02 UTC, yivo commented
@emasiuk please rebase and run tests

2017-12-22 18:07 UTC, yivo commented
@emasiuk I believe Peatio doesn't has fully working `/withdraws/satoshis/new`. Probably it wasn't implemented or it was abandoned. We need to strip this functionality.

2017-12-22 18:07 UTC, closed without merging

2018-01-02 06:40 UTC, ApsOps commented
@yivo Hi. Satoshi withdraws are not working for me. Is this a known issue?