[WIP] #1290 Get data in specific time interval from GET /api/v2/k?
openware/peatio pull request #1342
Opened 2018-06-22 07:48 UTC by dinesh-skyach

Get data in specific time interval from GET /api/v2/k?  #1290

2018-06-25 09:36 UTC, yivo requested changes

2018-06-25 09:36 UTC, yivo commented on app/api/api_v2/k.rb
> +      optional :timestamp2, type: Integer, desc: "An integer represents the seconds elapsed since Unix epoch. If set, only k-line data till that time will be returned."
@dinesh-skyach You have to rename params and stop using names like timestamp1, timestamp2. Use time_from, time_to (both are inclusive, please test it).

2018-06-25 10:09 UTC, dinesh-skyach commented on app/api/api_v2/k.rb
> +      optional :timestamp2, type: Integer, desc: "An integer represents the seconds elapsed since Unix epoch. If set, only k-line data till that time will be returned."
@yivo done

2018-06-26 07:55 UTC, dinesh-skyach commented
@yivo I have made the changes.

2018-06-26 09:27 UTC, yivo approved these changes

2018-07-05 11:24 UTC, merged