[WIP] Fix error message in API endpoint
openware/peatio pull request #1343
Opened 2018-06-22 11:22 UTC by ritesh-skyach

Fix error message in API endpoint #1333

2018-06-25 09:48 UTC, yivo requested changes

2018-06-25 09:48 UTC, yivo commented on app/api/api_v2/helpers.rb
> +        raise Error.new(text: 'Please, pass the corresponding verification steps to deposit funds.', status: 401)
We need specs for this.

2018-06-26 06:13 UTC, dinesh-skyach commented
@yivo I have added specs.

2018-06-26 06:13 UTC, dinesh-skyach commented on app/api/api_v2/helpers.rb
> +        raise Error.new(text: 'Please, pass the corresponding verification steps to deposit funds.', status: 401)
@yivo done

2018-06-27 09:52 UTC, merged