Ability to register new blockchain and wallet
openware/peatio pull request #1422
Opened 2018-07-13 07:55 UTC by ritesh-skyach

Ability to list blockchains and wallets from admin panel #1412
Ability to register a new blockchain / wallet from admin panel #1413

2018-07-13 10:58 UTC, tamadamas requested changes

2018-07-13 10:58 UTC, rxx commented on app/controllers/admin/blockchains_controller.rb
> +      @blockchain = Blockchain.new
Why do you use assign_attributes here istead of `@blockchain = Blockchain.create(blockchain_params)`

2018-07-13 10:58 UTC, rxx commented on app/controllers/admin/blockchains_controller.rb
> +    def show
`show` action should be after `index` action before `new`

2018-07-13 10:58 UTC, rxx commented on app/controllers/admin/blockchains_controller.rb
> +        flash[:alert] = @blockchain.errors.full_messages.first
Just first error? What if model has two errors?

2018-07-13 10:58 UTC, rxx commented on app/controllers/admin/blockchains_controller.rb
> +
remove blank lines

2018-07-13 10:58 UTC, rxx commented on app/controllers/admin/blockchains_controller.rb
> +      @blockchains = Blockchain.all
Should we add a pagination here?

2018-07-13 10:58 UTC, rxx commented on app/controllers/admin/wallets_controller.rb
> +      @wallet.assign_attributes(wallet_params)
Why do you use assign_attributes here istead of @wallet = Blockchain.create(wallet_params)

2018-07-13 10:58 UTC, rxx commented on app/controllers/admin/wallets_controller.rb
> +        flash[:alert] = @wallet.errors.full_messages.first
same as above

2018-07-13 10:58 UTC, rxx commented on app/controllers/admin/wallets_controller.rb
> +        flash[:alert] = @wallet.errors.full_messages.first
same as above

2018-07-13 10:58 UTC, rxx commented on app/controllers/admin/wallets_controller.rb
> +
blank lines

2018-07-13 10:58 UTC, rxx commented on app/views/admin/blockchains/index.html.erb
> +    <%= link_to 'New currency', new_admin_blockchain_path, class: "btn btn-primary pull-right mb-3" %>
should we check CanCan rule here?

2018-07-13 10:58 UTC, rxx commented on app/views/admin/wallets/index.html.erb
> +    <%= link_to 'New currency', new_admin_wallet_path, class: "btn btn-primary pull-right mb-3" %>
should we check CanCan rule here?

2018-07-13 10:58 UTC, rxx commented on spec/controllers/admin/blockchains_controller_spec.rb
> +      blockchain = Blockchain.find_by_key('eth-rinkeby-new')
'eth-rinkeby-new' should be constant.
You can get all attributes and use one `expect` to match them all

2018-07-13 10:58 UTC, rxx commented on spec/controllers/admin/blockchains_controller_spec.rb
> +    it 'updates blockchain attributes' do
what do you test here? You tested `create` logic above
It should test "update" logic.

You can get all attributes and use one `expect` to match them all

2018-07-13 10:58 UTC, rxx commented on spec/controllers/admin/blockchains_controller_spec.rb
> +  describe 'routes' do
why routes test here? It should be another test file with `type: :routing`

2018-07-13 10:58 UTC, rxx commented on spec/controllers/admin/wallets_controller_spec.rb
> +      post :create, wallet: attributes
same as above

2018-07-13 10:58 UTC, rxx commented on spec/controllers/admin/wallets_controller_spec.rb
> +    it 'routes to WalletsController' do
same as above

2018-07-13 11:48 UTC, ritesh-skyach commented on spec/controllers/admin/blockchains_controller_spec.rb
> +      blockchain = Blockchain.find_by_key('eth-rinkeby-new')
@rxx I didn't get what do you mean by `'eth-rinkeby-new' should be constant.` ?

2018-07-13 14:36 UTC, rxx commented on spec/controllers/admin/blockchains_controller_spec.rb
> +      blockchain = Blockchain.find_by_key('eth-rinkeby-new')
`let(:blockchain_key) { 'eth-rinkeby-new' } `

2018-07-13 14:37 UTC, rxx commented on spec/controllers/admin/blockchains_controller_spec.rb
> +      blockchain = Blockchain.find_by_key('eth-rinkeby-new')
@ritesh-skyach

2018-07-14 12:13 UTC, merged

2018-07-16 10:05 UTC, ysv commented
Merged without rebase