Added Wallet/Blockchain validations
openware/peatio pull request #1429
Opened 2018-07-17 06:33 UTC by dinesh-skyach

Added Wallet/Blockchain validations

2018-07-17 07:05 UTC, tamadamas requested changes

2018-07-17 07:05 UTC, rxx commented on spec/models/blockchain_spec.rb
> +      record = Blockchain.new(valid_attributes)
Why not FactoryBot?

2018-07-17 07:05 UTC, rxx commented on spec/models/wallet_spec.rb
> +      record = Wallet.new(valid_attributes)
Why not FactoryBot?

2018-07-17 08:27 UTC, dinesh-skyach commented
@rxx I have made the changes. Please check now.

2018-07-17 11:05 UTC, tamadamas approved these changes
Looks good

2018-07-18 17:35 UTC, mod approved these changes

2018-07-18 17:36 UTC, merged