Archive Orders Stored Procedure
openware/peatio pull request #1431
Opened 2018-07-17 11:24 UTC by ritesh-skyach

Archive Orders Stored Procedure

2018-07-18 18:17 UTC, mod requested changes

2018-07-18 18:17 UTC, mod commented on db/migrate/20180716110346_add_archive_orders_stored_procedure.rb
> +    PREPARE create_table from @prepare_table;
@ritesh-skyach why using PREPARE and Execute statement,
the Stored procedure will be much more readable with simple statements.

a simple

CREATE TABLE `orders_201806` IF NOT EXIST
INSERT FROM SELECT `orders`
DELETE FROM `orders`

2018-07-19 08:09 UTC, ritesh-skyach commented on db/migrate/20180716110346_add_archive_orders_stored_procedure.rb
> +    PREPARE create_table from @prepare_table;
@mod We can not use variable name in SQL statement directly, So we have to use PREPARE and EXECUTE

2018-07-19 20:50 UTC, mod commented
I still think you can completely avoid the prepare statements, why do you user them ?

2018-07-24 13:16 UTC, ritesh-skyach commented
@mod We are using dynamic table name so it is not possible to use without prepare and execute.
Please correct me if i am wrong.

2018-08-08 22:37 UTC, mod requested changes
@ritesh-skyach Please update this SP with CREATE table statement with no PREPARE statements

2018-10-19 13:20 UTC, closed without merging