Add API endpoint for currencies
openware/peatio pull request #1433
Opened 2018-07-17 13:06 UTC by shal

2018-07-17 13:15 UTC, ysv requested changes

2018-07-17 13:15 UTC, ysv commented on app/api/api_v2/currencies.rb
> +      if params[:type].nil?
`params[:type].blank?`

2018-07-17 13:15 UTC, ysv commented on app/api/api_v2/entities/currency.rb
> +    end
expose only: 
id, symbol, type, deposit_fee, withdraw_fee, quick_withdraw_limit, deposit_confirmations, allow_multiple_deposit_addresses, base_factor, precision

2018-07-17 13:39 UTC, ysv approved these changes

2018-07-18 11:05 UTC, ysv requested changes

2018-07-18 11:05 UTC, ysv commented on spec/api/api_v2/currencies_spec.rb
> +      match { |x| not (x.dig(:price).nil? || x.dig(:volume).nil? || x.dig(:change).nil?) }
```ruby
match { |x| x[:price].present? && x[:volume].present? && x[:change].present? }
```

2018-07-18 11:06 UTC, ysv commented
Please update doc https://github.com/rubykube/peatio/blob/master/docs/api/member_api_v2.md

2018-07-18 13:23 UTC, shal commented
@ysv Travis CI will do this for us.
https://github.com/rubykube/peatio/blob/dc52324d4be87ab725056d922d5058b4ed60eda4/bin/bump#L35

2018-07-18 16:15 UTC, ysv commented
@shal I don't think we run bump in master

2018-07-18 16:18 UTC, shal commented
@ysv I think we do
https://github.com/rubykube/peatio/blob/dc52324d4be87ab725056d922d5058b4ed60eda4/ci/bump.rb#L103

2018-07-18 16:24 UTC, ysv commented
@shal I don't think so https://github.com/rubykube/peatio/blob/dc52324d4be87ab725056d922d5058b4ed60eda4/ci/bump.rb#L227

2018-07-18 16:33 UTC, shal commented
@ysv you won :smile:

2018-07-18 16:50 UTC, shal commented
@ysv I updated member API documentation according to this patch.

2018-07-19 13:07 UTC, shal commented
@ysv Ready.

2018-07-19 14:30 UTC, ysv commented
@shal looks good for me

2018-07-19 14:37 UTC, shal commented
@ysv Please, push this PR into `wb1` branch to test it.

2018-07-19 20:29 UTC, merged