[WIP] Bitcoin Blockchain Service
openware/peatio pull request #1444
Opened 2018-07-18 13:15 UTC by dinesh-skyach

Added Bitcoin Blockchain Service

2018-07-20 11:12 UTC, ysv commented
@dinesh-skyach can you share script which you used for bitcoin-data/1354419-1354420.json generations. Also can we somehow reduce the size of this file ?

2018-07-20 11:29 UTC, dinesh-skyach commented
@ysv I did it manually via this
```
curl --data '{"jsonrpc":"2.0", "method":"getblock","params":["00000000bbc746ed23eef6d08c855b9ca07e64de84cb5d3846a667f60b0528cc", 2]}' http://user:user@127.0.0.1:18332

```

2018-07-23 10:27 UTC, ysv commented on lib/client/bitcoin.rb
> +        next if address != normalize_address(item['scriptPubKey']['addresses'][0])
@dinesh-skyach why do we use only the first address ?
`item['scriptPubKey']['addresses'][0]`

2018-07-23 13:56 UTC, ysv requested changes

2018-07-23 13:56 UTC, ysv commented on spec/services/blockchain_service/bitcoin_spec.rb
> +        client.class.any_instance.stubs(:get_block).returns(block_data[0]["result"], block_data[1]["result"], block_data[2]["result"])
Use stub_request here (example in ethereum_spec.rb)

2018-07-23 15:27 UTC, dinesh-skyach commented on spec/services/blockchain_service/bitcoin_spec.rb
> +        client.class.any_instance.stubs(:get_block).returns(block_data[0]["result"], block_data[1]["result"], block_data[2]["result"])
@ysv done

2018-07-23 15:45 UTC, ysv commented on config/templates/seed/blockchains.yml.erb
> +  server:            http://user:user@127.0.0.1:18332
`json_rpc_endpoint: http://user:password@127.0.0.1:18332`

2018-07-24 17:14 UTC, ysv approved these changes

2018-07-24 17:43 UTC, merged