Removed Doorkeeper gem
openware/peatio pull request #145
Opened 2017-12-21 13:44 UTC by gfedorenko

2017-12-21 13:53 UTC, yivo requested changes

2017-12-21 13:53 UTC, yivo commented on app/controllers/private/api_tokens_controller.rb
> +      ids = APIToken.where(id: @oauth_api_tokens.map(&:oauth_access_token_id)).select('max(id) as id')
@gfedorenko we need to remove every oauth2 stuff. APIToken should be very very simple server2server token.

2017-12-21 13:53 UTC, yivo commented on app/models/api_token.rb
> +  belongs_to :oauth_access_token, dependent: :destroy
@gfedorenko Don't forget to cleanup database schema.

2017-12-21 19:45 UTC, mod requested changes
I am not comfortable to understand why they had doorkeeper in the first place

2017-12-21 19:45 UTC, mod commented on db/migrate/20171221131530_drop_doorkeeper_tables.rb
> +    remove_column :api_tokens, :oauth_access_token_id, :integer
I don't think api_tokens relates to doorkeeper.

2017-12-22 13:11 UTC, yivo requested changes

2017-12-22 13:11 UTC, yivo commented on db/migrate/20171221131530_drop_doorkeeper_tables.rb
> +    remove_column :api_tokens, :oauth_access_token_id, :integer
@gfedorenko Can you please remove `:integer` from the list?

2017-12-22 15:43 UTC, yivo approved these changes

2017-12-22 16:37 UTC, merged