[slim2erb] activations/ pages
openware/peatio pull request #146
Opened 2017-12-21 14:27 UTC by spavlishak

2017-12-21 14:43 UTC, rhombl4 commented
What is the reason for converting slim to erb?

2017-12-21 15:17 UTC, dkkoval commented
@rhombl4 simply because we are more comfortable with erb and we're going to change many pages.

2017-12-21 15:18 UTC, yivo requested changes

2017-12-21 15:18 UTC, yivo commented on app/views/activations/new.html.erb
> +      <span><%= t('.tip', email: current_user.email) %></span>
@spavlishak this output should not be escaped

2017-12-21 15:18 UTC, yivo commented on app/views/activations/new.html.erb
> +      <span><strong class='text-danger'><%= t('.spam') %></strong></span>
@spavlishak you should always use double quotes for HTML attributes

2017-12-21 15:18 UTC, yivo commented on app/views/activations/new.html.erb
> +    <span><%= t('helpers.submit.activation.update') %> </span>
@spavlishak extra space detected at the end

2017-12-22 16:40 UTC, yivo commented
@spavlishak Could you please squash commits and write good message (changelog):

`Convert views/activations Slim templates to ERB`

2017-12-22 16:40 UTC, yivo approved these changes

2017-12-22 18:17 UTC, merged