Support minimum price for Order (closes #1447)
openware/peatio pull request #1460
Opened 2018-07-19 22:26 UTC by shal

2018-07-23 14:25 UTC, ysv requested changes

2018-07-23 14:25 UTC, ysv commented on app/models/market.rb
> +#  min_ask_price :decimal(17, 16)  default(0.0), not null
place them after `bid_fee`

2018-07-23 14:25 UTC, ysv commented on spec/models/order_ask_spec.rb
> +      market.update(min_ask_price: 0.1)
Move this to `let(:market)`
```ruby 
let(:market) do
 Market.find(:btcusd).tap { |m| m.update(...)}
end
```

2018-07-23 14:27 UTC, ysv commented on spec/models/order_bid_spec.rb
> +      market.update(min_bid_price: 0.1)
Same as [here](https://github.com/rubykube/peatio/pull/1460/files#r204420540)

2018-07-23 14:29 UTC, ysv commented on app/models/market.rb
> +#  min_ask_price :decimal(17, 16)  default(0.0), not null
also don't forget to annotate models

2018-08-04 18:38 UTC, mod commented
I think it should be:
min_ask
max_bid

2018-08-06 21:00 UTC, mod commented
@shal please update

2018-08-07 08:29 UTC, shal commented
@mod Updated and rebased.

2018-08-07 14:13 UTC, shal commented
@mod it is ready.

2018-08-07 19:20 UTC, merged