[WIP] Replace Confirmation With Block Number
openware/peatio pull request #1463
Opened 2018-07-20 11:51 UTC by ritesh-skyach

Replace Confirmation With Block Number #1456

2018-07-24 10:32 UTC, mod commented on app/models/deposit.rb
> +#  block_number :integer
Please do not add field at the end of the table put it after aasm_state

2018-07-24 10:33 UTC, mod requested changes

2018-07-24 10:33 UTC, mod commented on app/models/deposits/coin.rb
> -    validates :confirmations, presence: true, numericality: { greater_than_or_equal_to: 0, only_integer: true }
can we validate a bit

2018-07-24 10:33 UTC, mod commented on app/models/deposits/coin.rb
> +                   confirmations:   confirmations)
how do we calculate confirmations ?

2018-07-25 13:44 UTC, rxx commented on app/models/deposits/coin.rb
> +                   confirmations:   confirmations)
@mod it's here https://github.com/skyach/peatio/blob/fcc27f32c6765db3ddcda960abda5f03763aeeb8/app/models/concerns/belongs_to_currency.rb#L29

2018-07-25 13:58 UTC, tamadamas requested changes

2018-07-25 13:58 UTC, rxx commented on app/models/deposit.rb
> +#  block_number :integer
block_number must have more higher position than created_at

2018-07-25 13:58 UTC, rxx commented on app/services/blockchain_service.rb
> -          deposit.accept! if deposit.confirmations >= blockchain.min_confirmations
I can see you update a block number on withdrawal. Should a block number be updated for deposit also?

2018-07-25 13:58 UTC, rxx commented on app/services/blockchain_service.rb
> -          deposit.accept! if deposit.confirmations >= blockchain.min_confirmations
Better to update than not to update ^_^

2018-07-25 13:58 UTC, rxx commented on app/services/services/blockchain_transaction_handler.rb
> +      # return if Deposits::Coin.where(currency: currency, txid: tx[:id]).exists?
Why did you comment it?

2018-07-25 13:59 UTC, rxx commented
Also specs are red

2018-07-25 14:06 UTC, ritesh-skyach commented on app/services/blockchain_service.rb
> -          deposit.accept! if deposit.confirmations >= blockchain.min_confirmations
@rxx `block_number` is in `deposit_hash` so no need to update again

2018-07-25 14:49 UTC, ritesh-skyach commented on app/models/deposits/coin.rb
> -    validates :confirmations, presence: true, numericality: { greater_than_or_equal_to: 0, only_integer: true }
@mod validation added

2018-07-25 14:50 UTC, ritesh-skyach commented on app/services/services/blockchain_transaction_handler.rb
> +      # return if Deposits::Coin.where(currency: currency, txid: tx[:id]).exists?
@rxx we don't need this service anymore

2018-07-25 16:41 UTC, ysv approved these changes

2018-07-26 10:24 UTC, merged