[WIP] Feature/ripple blockchain service
openware/peatio pull request #1464
Opened 2018-07-20 13:43 UTC by rxx

2018-08-27 08:26 UTC, ysv commented
@rxx Please rebase

2018-08-28 11:30 UTC, ysv requested changes

2018-08-28 11:30 UTC, ysv commented on config/templates/seed/blockchains.yml.erb
> +- key:               xrp-mainnet
@rxx Remove mainnet please

2018-08-28 11:30 UTC, ysv commented on spec/factories/wallet.rb
> +    trait :xrp_hot do
Can you check if we use warm wallets for xrp and eth if we don't remove them please

2018-08-28 11:30 UTC, ysv commented on spec/resources/ripple-data/transactions.json
> +{
I understand your point that ripple doesn't have blocks
But still please use name convention for this file as we do for other currencies
`start_block-end_block.json`

2018-08-28 11:30 UTC, ysv commented
@rxx Also rebase please

2018-08-28 12:19 UTC, rxx commented on spec/factories/wallet.rb
> +    trait :xrp_hot do
we use `eth_warm` at `models/wallet_spec.rb`

2018-08-29 16:53 UTC, ysv requested changes

2018-08-29 16:53 UTC, ysv commented on lib/wallet_client/rippled.rb
> +      address
We need to remove destination tag when we normalize address for example when we use bitgo as hot wallet
```
{"result"=>
  {"error"=>"invalidParams",
   "error_code"=>31,
   "error_message"=>"Invalid field 'tx_json.Destination'.",
   "request"=>
    {"command"=>"sign",
     "fee_mult_max"=>1000,
     "secret"=>"/P9jbbFEPt3FRtY)*DT!bDomY&aawSCKgQ89+V@nD488y4zgIgAy5$4+GVHFz)YO",
     "tx_json"=>
      {"Account"=>"rM76eUvB3RCzcF5q4Rj2Y4Y36VFbFt4csB",
       "Amount"=>"100000000",
       "Destination"=>"rfUKVVX5KJQ2FsWYrjS6JMedz3jdjPhRPZ?dt=32",
       "DestinationTag"=>32,
       "TransactionType"=>"Payment"}},
   "status"=>"error"}}
```

2018-08-30 13:51 UTC, ysv commented on lib/wallet_client/rippled.rb
> +      address
@rxx Also can you check if we can perform some withdrawals to addresses with tag
```
...
       "Destination"=>"rfUKVVX5KJQ2FsWYrjS6JMedz3jdjPhRPZ",
       "DestinationTag"=>32,
...
```

2018-09-07 13:17 UTC, ysv requested changes

2018-09-07 13:17 UTC, ysv commented on app/services/blockchain_service/ripple.rb
> +        update_or_create_deposits!(deposits)
https://github.com/rubykube/peatio/blob/master/app/services/blockchain_service/ethereum.rb#L30

2018-09-07 13:17 UTC, ysv commented on lib/wallet_client/rippled.rb
> +      end while PaymentAddress.where(currency_id: :xrp)
we don't want to have any models in lib

2018-09-07 13:17 UTC, ysv commented on lib/wallet_client/rippled.rb
> +        address: "#{wallet.address}?dt=#{generate_destination_tag}",
you can pass reserved destination tags in options

2018-09-11 11:54 UTC, ysv approved these changes

2018-09-13 15:03 UTC, merged