Add icon url to currency (closes #1449)
openware/peatio pull request #1465
Opened 2018-07-20 20:25 UTC by shal

2018-07-23 14:50 UTC, ysv requested changes

2018-07-23 14:50 UTC, ysv commented on app/models/currency.rb
> +#  icon_url             :string(255)
Place `icon_url` after `precision`
Add default value
Add validation `url: { allow_blank: true }`

2018-07-23 14:50 UTC, ysv commented on app/helpers/currency_helper.rb
> +    currency.icon_url || "yarn_components/cryptocurrency-icons/svg/color/#{currency.code}.svg"
I think more safe will be to use 
```ruby 
if currency.icon_url.blank?
```

2018-07-30 13:51 UTC, calj approved these changes

2018-08-09 00:39 UTC, merged