Update Readme
openware/peatio pull request #1468
Opened 2018-07-23 12:41 UTC by odidukh

2018-07-23 12:53 UTC, mod commented on README.md
> +We suggest you to start using Peatio by installing Workbench. Workbench which is based on [Docker containers](https://www.docker.com/what-docker) is a conveniet and straightforward way to start Peati
## Quick Install

Rubykube Peatio, uses a microservice architecture, and is composed of several services, The easiest way to install and evaluate peatio is to use the workbench.

Our Peatio use docker containers which are built and maintained publicly : https://hub.docker.com/r/rubykube
Workbench use a simple tool called docker-compose.

1. Install Docker on your computer: [Docker](https://docs.docker.com/install/)
2. Install Docker compose [Docker compose](https://docs.docker.com/compose/install/)

### Start Peatio with workbench

1. Recursive clone : `git clone --recursive https://github.com/rubykube/workbench.git`
2. Move to workbench `cd workbench`
3. Build the images: `make build`
4. Run the application: `make run`

This setup use a load balance configured with the following hosts to install in `etc/hosts`
```
0.0.0.0 api.wb.local
0.0.0.0 auth.wb.local

0.0.0.0 api.slanger.wb.local
0.0.0.0 ws.slanger.wb.local

0.0.0.0 pma.wb.local
0.0.0.0 monitor.wb.local
+```

2018-07-23 16:30 UTC, ianeinser commented
Hi, 
is it possible to get the latest stable versions of apps in /app/? some of the apps in /app are old versions. Thanks

2018-07-23 19:07 UTC, shal commented
@odidukh, `[ci slip]` looks wrong.

2018-07-24 17:30 UTC, AboShanab commented
@odidukh There's some typo's on this pull request:
Under Quick Install text:
4.  [Vagrant](https://www.vagrantup.com/downloads.html) -> 3.  [Vagrant](https://www.vagrantup.com/downloads.html)

Under Barong text:
[peatio.teck](https://peatio.tech/#/) -> [peatio.tech](https://peatio.tech/#/)

Under Start peatio with workbench text:
2. Build the images: `make build` -> 3. Build the images: `make build`
3. Run the application: `make run` -> 4. Run the application: `make run` 

'Simply start your local server. Now you're able to log in with your local Barong and Peatio.'
This sentence isn't required as well, we are actually running the Peatio by doing 'Run the application' commands, also what's the difference between [Peatio](https://hub.docker.com/r/rubykube/peatio/) docker and workbench? it looks the same..

You should write some clearify about Vagrant and why it required to be installed, AFAIK I never seen any idea by doing that..

2018-07-26 11:42 UTC, mod requested changes

2018-07-26 11:42 UTC, mod commented on README.md
> +
you can remove this chunk

2018-07-26 11:42 UTC, mod commented on README.md
> +
it doesn't mean anything and workbench starts everything

2018-07-26 11:42 UTC, mod commented on README.md
> +Barong is an important part of [peatio.teck](https://peatio.tech/#/) stack. Barong provides an OAuth server specially written for our service.
link is peatio.tech

2018-07-26 11:42 UTC, mod commented on README.md
> +Barong is an important part of [peatio.teck](https://peatio.tech/#/) stack. Barong provides an OAuth server specially written for our service.
can you give a feature list of Barong?

2018-08-09 00:36 UTC, mod commented
@odidukh Can you add the installation steps using : 
`docker-compose -f config/backend.yml up -d`

Can you also remove the dead links  ?

2018-08-09 09:45 UTC, odidukh commented
In which place I should add this command `docker-compose -f config/backend.yml up -d`?

2018-08-17 13:07 UTC, ysv commented
Progress in #1551

2018-08-17 13:08 UTC, closed without merging