[WIP] Added Withdraw Coin Daemon
openware/peatio pull request #1483
Opened 2018-07-27 14:41 UTC by dinesh-skyach

Added Withdraw Coin Daemon

2018-07-27 15:12 UTC, ysv requested changes

2018-07-27 15:12 UTC, ysv commented on lib/wallet_client/geth.rb
> +      PaymentAddress
No peatio specific code in wallet_client

2018-07-27 15:12 UTC, ysv commented on lib/wallet_client/geth.rb
> +      PaymentAddress
Move this to service

2018-07-27 15:12 UTC, ysv commented on lib/wallet_client/geth.rb
> +      normalize_address(currency.erc20_contract_address)
we don't have currency in WalletClient

2018-07-27 15:36 UTC, ysv requested changes

2018-07-27 15:36 UTC, ysv commented on app/workers/worker/withdraw_coin.rb
> +        wallet = Wallet.active.deposit.where(blockchain_key: currency.blockchain_key).first
Only withdraw wallets here

2018-07-28 08:15 UTC, dinesh-skyach commented
moved #1485

2018-07-28 08:15 UTC, closed without merging