Remove Unwanted Code From Currency MVC
openware/peatio pull request #1484
Opened 2018-07-28 06:33 UTC by ritesh-skyach

Remove Unwanted Code From Currency MVC

2018-07-30 23:55 UTC, ysv requested changes

2018-07-30 23:55 UTC, ysv commented on app/models/blockchain.rb
> +#  case_sensitive       :boolean          default(TRUE)
We don't want add `case_sensitive`

2018-08-01 05:05 UTC, ritesh-skyach commented on app/models/blockchain.rb
> +#  case_sensitive       :boolean          default(TRUE)
@ysv Done

2018-08-03 05:59 UTC, mod approved these changes

2018-08-03 05:59 UTC, merged