[slim2erb] layouts/ pages
openware/peatio pull request #149
Opened 2017-12-21 14:41 UTC by spavlishak

2017-12-21 15:40 UTC, yivo requested changes

2017-12-21 15:40 UTC, yivo commented on app/views/layouts/landing.html.erb
> +
@spavlishak where is viewport definition?

2017-12-21 15:40 UTC, yivo commented on app/views/layouts/landing.html.erb
> +    <%= render 'shared/meta' %>
@spavlishak where is render shared/html5?

2017-12-21 15:40 UTC, yivo commented on app/views/layouts/landing.html.erb
> +  <body data-lang="<%= locale_name %>">
@spavlishak body id is missing

2017-12-21 15:40 UTC, yivo commented on app/views/layouts/landing.html.erb
> +    <%= render('shared/header') %>
@spavlishak don't write brackets when calling "render"

2017-12-21 15:40 UTC, yivo commented on app/views/layouts/landing.html.erb
> +    <%= yield(:scripts) if content_for?(:scripts) %>
@spavlishak where did you get it from? there is not such code in slim template

2017-12-21 15:40 UTC, yivo commented on app/views/layouts/landing.html.erb
> +    <div class="main container">
@spavlishak body's internas are totally invalid

2017-12-21 15:40 UTC, yivo commented on app/views/layouts/admin.html.erb
> +  <body id="<% body_id %>">
@spavlishak missing `=` so this will not output anything

2017-12-21 15:40 UTC, yivo commented on app/views/layouts/admin.html.erb
> +              <%= link_to t(".menus.items.operating.documents"), admin_documents_path %>
@spavlishak use single quotes

2017-12-21 15:40 UTC, yivo commented on app/views/layouts/admin.html.erb
> +              <%= link_to 'javascript:;', class: 'dropdown-toggle', 'data-toggle' => 'dropdown' do %>
@spavlishak don't combine strings and symbols

2017-12-21 15:40 UTC, yivo commented on app/views/layouts/admin.html.erb
> +              <%= link_to 'javascript:;', class: 'dropdown-toggle', 'data-toggle' => 'dropdown' do %>
@spavlishak don't combine symbols & strings

2017-12-21 15:40 UTC, yivo commented on app/views/layouts/admin.html.erb
> +              <%= link_to t(".menus.sections.members"), admin_members_path %>
@spavlishak always use single quotes in rb when you don't need interpolation

2017-12-21 15:40 UTC, yivo commented on app/views/layouts/admin.html.erb
> +              <%= link_to t(".menus.items.operating.tickets"), admin_tickets_path %>
@spavlishak always use single quotes in rb when you don't need interpolation

2017-12-21 15:40 UTC, yivo commented on app/views/layouts/admin.html.erb
> +            <%= link_to 'javascript:;', class: 'dropdown-toggle', 'data-toggle' => 'dropdown' do %>
@spavlishak don't combine strings & symbols

2017-12-21 15:40 UTC, yivo commented on app/views/layouts/api_v2.html.erb
> +    <div class="navbar navbar-light navbar-static-top" role="navigation">
@spavlishak you have invalid class names, recheck please

2017-12-21 15:40 UTC, yivo commented on app/views/layouts/api_v2.html.erb
> +    <div class="navbar navbar-light navbar-static-top" role="navigation">
.navbar.navbar-default.navbar-static-top role='navigation'

2017-12-21 15:40 UTC, yivo commented on app/views/layouts/application.html.erb
> +        <%= render 'shared/alert' %>
@spavlishak `= render 'shared/alert'` should be direct child of body

2017-12-21 15:40 UTC, yivo commented on app/views/layouts/application.html.erb
> +    <%= content_for?(:header) ? yield(:header) : render('shared/header') %>
@spavlishak it should be in `#wrap`

2017-12-21 15:40 UTC, yivo commented on app/views/layouts/application.html.erb
> +    <%= content_for?(:footer) ? yield(:footer) : render('shared/footer') %>
@spavlishak it should be in `#wrap`. recheck whole template

2017-12-21 18:44 UTC, spavlishak commented on app/views/layouts/api_v2.html.erb
> +    <div class="navbar navbar-light navbar-static-top" role="navigation">
that's because in bs4 navbar-default is navbar-light, and i was moving it to bs4

2017-12-21 19:41 UTC, yivo commented on app/views/layouts/api_v2.html.erb
> +    <div class="navbar navbar-light navbar-static-top" role="navigation">
@spavlishak in this patch we don't add BS4. We convert slim to erb only.

2017-12-22 16:46 UTC, yivo approved these changes

2017-12-22 18:17 UTC, merged