Feature/blockchains wallets
openware/peatio pull request #1510
Opened 2018-08-08 16:16 UTC by dmk

2018-08-08 22:07 UTC, mod requested changes
@ritesh-skyach can you edit those in the morning

2018-08-08 22:07 UTC, mod commented on app/controllers/admin/currencies_controller.rb
> +    # just disabling for now, without destroying
rename to disable we can only support this for now

2018-08-08 22:07 UTC, mod commented on app/controllers/admin/markets_controller.rb
> +    def destroy
disable

2018-08-08 22:07 UTC, mod commented on app/controllers/admin/wallets_controller.rb
> +      Rails.logger.info { @wallet }
removing logging

2018-08-08 22:07 UTC, mod commented on db/migrate/20180808144704_change_wallet_structure.rb
> +    add_column :wallets, :settings, :json
please position correctly setting not in json format it fails in schema.rb

2018-08-08 22:07 UTC, mod commented on spec/controllers/admin/wallets_controller_spec.rb
> +        status:             'disabled',
are you sure this is up to date?

2018-08-09 04:49 UTC, ritesh-skyach commented
@mod I am working on it.

2018-08-09 11:45 UTC, skatkov commented on app/controllers/admin/currencies_controller.rb
> +      markets_list.each { |m| m.update(enabled: false) }
It seems that this will produce N+1 update to database. Have you considered using #update_all ?

`markets_list.update_all(enabled: false)`

Here is a qoute from documentation:
```
Updates all records in the current relation with details given. This method constructs a single SQL UPDATE statement and sends it straight to the database. It does not instantiate the involved models and it does not trigger Active Record callbacks or validations. However, values passed to update_all will still go through Active Record's normal type casting and serialization.
```

2018-08-09 11:45 UTC, skatkov commented on app/controllers/admin/currencies_controller.rb
> +      markets_list = Market.where(bid_unit: @currency.id) + Market.where(ask_unit: @currency.id)
If I understand this correctly, this code will produce 2 separate SQL requests to database. Maybe this could be achieved with one by using OR statement?

OR statements natively supported by Rails 5, but not in 4. But you can add it with a gem
https://rubygems.org/gems/active_record_or

Or using Arel:

```
t = Market.arel_table

results = Market.where(
  t[:bid_unit].eq(@currency.id).
  or(t[:ask_unit].eq(@currency.id))
)
```

2018-08-09 15:48 UTC, merged