[slim2erb] private/ pages
openware/peatio pull request #152
Opened 2017-12-21 14:50 UTC by spavlishak

2017-12-21 18:11 UTC, yivo requested changes

2017-12-21 18:11 UTC, yivo commented on app/views/private/api_tokens/_user_tokens.html.erb
> +                    | &nbsp;
@spavlishak check text content (remove pipe)

2017-12-21 18:11 UTC, yivo commented on app/views/private/assets/_btc_assets.html.erb
> +                <%= t('currency.icon.btc') %>
@spavlishak this should not escaped

2017-12-21 18:11 UTC, yivo commented on app/views/private/assets/_cny_assets.html.erb
> +                <%= t('currency.icon.cny') %>
@spavlishak this should not be escaped

2017-12-21 18:11 UTC, yivo commented on app/views/private/assets/_cny_assets.html.erb
> +        <%= t('.description', @cny_assets['accounts'].first.symbolize_keys) %>
@spavlishak this should not be escaped

2017-12-21 18:11 UTC, yivo commented on app/views/private/assets/_liability_data.html.erb
> +      <pre id="root_target"><%= proof.root.to_json %></pre>
@spavlishak you should set ID to variable, not fixed value

2017-12-21 18:11 UTC, yivo commented on app/views/private/assets/_liability_data.html.erb
> +          <%= t("currency.icon.#{proof.currency}") %>
@spavlishak this should not be escaped

2017-12-21 18:11 UTC, yivo commented on app/views/private/assets/_liability_data.html.erb
> +      <pre id="partial_tree_target"><%= partial_tree.json.to_json %></pre>
@spavlishak you should assign var here

2017-12-21 18:12 UTC, yivo commented
This is not a complete review. I will review again when current issues will be resolved.

2017-12-25 13:20 UTC, yivo commented
@spavlishak Please rebase.

2017-12-25 14:44 UTC, spavlishak commented
@yivo rebased

2018-01-03 16:20 UTC, yivo requested changes

2018-01-03 16:20 UTC, yivo commented on app/views/private/assets/_liability_data.html.erb
> +    <hr></hr>
@spavlishak `hr` is self-closing tag.

2018-01-03 16:20 UTC, yivo commented on app/views/private/assets/_xrp_assets.html.erb
> +                <%= t('currency.icon.xrp') %>
@spavlishak this should not be escaped.

2018-01-03 16:24 UTC, yivo commented
Rebased.

2018-01-04 13:12 UTC, gfedorenko commented on app/views/private/api_tokens/_oauth_tokens.html.erb
> +<div class="panel panel-default">
_oauth_tokens.html.slim was removed so _oauth_tokens.html.erb should be removed too

2018-01-04 13:12 UTC, gfedorenko commented on app/views/private/markets/_account_summary.html.erb
> +          <tr class="<% account.currency %> <%= @market.scope?(account) ? '' : 'hide' %>">
I guess it should be <%= account.currency %> as below

2018-01-04 13:12 UTC, gfedorenko commented on app/views/private/markets/_market_list.html.erb
> +<div class="has-right-dropdown" id="market_list_wrapper">
Do we really need 62-107 lines?

2018-01-04 13:12 UTC, gfedorenko commented on app/views/private/shared/_balances.html.erb
> +      <div class="row <%= account - account.currency %>">
Should be account-<%= account.currency %>

2018-01-04 13:12 UTC, gfedorenko commented on app/views/private/withdraws/index.html.erb
> +    <li class="list-group-item withdraws-channel-<% c.id %>">
Should be <%= c.id %>

2018-01-04 16:39 UTC, yivo commented
Rebased once again.

2018-01-05 12:25 UTC, yivo commented
@spavlishak Please, check your code and fix typos where you omit `=` in ERB output.

2018-01-08 18:03 UTC, yivo commented
Rebased.

2018-01-08 18:32 UTC, gfedorenko commented on app/views/private/assets/index.html.erb
> +      <li class="active" data-scroll-nav='0'>
Should be data-scroll-nav="0"

2018-01-08 18:32 UTC, gfedorenko commented on app/views/private/assets/index.html.erb
> +      <li data-scroll-nav='3'>
Same for all data-scroll-nav props

2018-01-08 18:32 UTC, gfedorenko commented on app/views/private/markets/_market_list.html.erb
> +              <tr class="market" id="market-list-<% market.id %>" class="quote-<% market.quote_unit%>" data-market="<% market.id %>">
Should be <%= market.id %> <%= market.quote_unit%> <%= market.id %>

2018-01-08 18:32 UTC, gfedorenko commented on app/views/private/markets/_range_switch.html.erb
> +        <a class="hand-point chart-switch" href="#" data-x="<% x %>">
<%= x %>

2018-01-08 18:32 UTC, gfedorenko commented on app/views/private/markets/_market_list.html.erb
> +            <a data-name="<% name %>" href="javascript:;">
<%= name %>

2018-01-08 18:32 UTC, gfedorenko commented on app/views/private/deposits/ripples/new.html.erb
> +        <a href="<% x.blockchain_url %>" target="_blank">
<%= x.blockchain_url %>

2018-01-08 18:32 UTC, gfedorenko commented on app/views/private/assets/_liability_tabs.html.erb
> +      <a class="btc-proof" href="#btc-proof" data-toggle="tab"><%= t('.verify-btc') %></a>
Check this file for missing html_safe

2018-01-08 18:32 UTC, gfedorenko commented on app/views/private/assets/_usd_assets.html.erb
> +                <%= t('currency.icon.usd') %>
Check for html_safe

2018-01-08 18:32 UTC, gfedorenko commented on app/views/private/markets/_header.html.erb
> +          <%= t('private.markets.mask.warning') %>
html_safe

2018-01-08 18:32 UTC, gfedorenko commented on app/views/private/markets/_mask.html.erb
> +    <p class="text-center"><%= "#{t('.warning')}" %></p>
html_safe

2018-01-08 19:47 UTC, yivo commented on app/views/private/markets/_mask.html.erb
> +    <p class="text-center"><%= "#{t('.warning')}" %></p>
Also string interpolation is not necessary here.

2018-01-09 14:26 UTC, yivo commented
@spavlishak Some issues: DON'T TOUCH CSS, ISSUE IS IN HTML

<img width="556" alt="screen shot 2018-01-09 at 4 17 44 pm" src="https://user-images.githubusercontent.com/7421323/34725129-aa7c7d06-f558-11e7-8e0e-4e83fbab7cd7.png">

2018-01-09 14:27 UTC, yivo commented
<img width="1278" alt="screen shot 2018-01-09 at 4 26 58 pm" src="https://user-images.githubusercontent.com/7421323/34725549-f15e5b30-f559-11e7-940e-9d1f29e94140.png">

But should be

![screen shot 2018-01-09 at 4 26 05 pm](https://user-images.githubusercontent.com/7421323/34725571-038dc05c-f55a-11e7-9224-7b9475bba4dd.png)

2018-01-09 14:31 UTC, yivo commented
Missing HTML safe at http://localhost:3000/exchange_assets (don't forget to exec rake task):

<img width="1168" alt="screen shot 2018-01-09 at 4 30 28 pm" src="https://user-images.githubusercontent.com/7421323/34725721-736bdc06-f55a-11e7-907b-f53f6c5c4514.png">

2018-01-10 00:27 UTC, yivo approved these changes

2018-01-10 00:30 UTC, yivo commented
@gfedorenko Could you please confirm that three issues above have been fixes?

Also please validate:
- [ ] There were no any HTML replacements for migration from Bootstrap 3 to 4.
- [ ] Confirm there are no visual glitches.
- [ ] Check `html_safe` issues & ERB output issues.

2018-01-10 15:37 UTC, gfedorenko commented
Missing active class on the buttons on history page 

![screenshot from 2018-01-10 17-35-23](https://user-images.githubusercontent.com/25289193/34780839-e047086e-f62c-11e7-9bea-31c615b6a348.png)

![screenshot from 2018-01-10 17-35-46](https://user-images.githubusercontent.com/25289193/34780840-e0632eb8-f62c-11e7-87d3-fe4ad545e6ba.png)

2018-01-10 15:39 UTC, gfedorenko commented
Missing top panel on the trade page
![screenshot from 2018-01-10 17-38-40](https://user-images.githubusercontent.com/25289193/34780954-32d4a2a8-f62d-11e7-9fb8-3a07af6b4065.png)
![screenshot from 2018-01-10 17-38-51](https://user-images.githubusercontent.com/25289193/34780955-32eea388-f62d-11e7-86e4-ce7fe1fa8f69.png)

2018-01-10 18:55 UTC, merged