Backport Inspect Address
openware/peatio pull request #1547
Opened 2018-08-16 13:34 UTC by ritesh-skyach

Backport Inspect Address

**Issue :**

- https://jira.openware.work/browse/PEATIO-74

2018-08-16 17:14 UTC, ysv requested changes

2018-08-16 17:14 UTC, ysv commented on lib/blockchain_client/ripple.rb
@ritesh-skyach Remove ripple stuff it's pending temporary

2018-08-16 17:14 UTC, ysv commented
@ritesh-skyach Backport specs also

2018-08-18 12:55 UTC, dinesh-skyach commented on lib/blockchain_client/ripple.rb
@ysv can't remove this, as this fails spec in some part.

2018-08-28 19:50 UTC, mod commented
conflict to solve

2018-08-29 13:22 UTC, ritesh-skyach commented
@mod Conflicts Resolved

2018-08-29 15:16 UTC, merged