Return Error if invalid from and to params (closes #1441)
openware/peatio pull request #1566
Opened 2018-08-22 10:21 UTC by kaiten-mahajan

Return Error if invalid from and to params #1441

2018-08-22 11:09 UTC, ysv requested changes

2018-08-22 11:09 UTC, ysv commented on app/api/api_v2/trades.rb
> +      validate_trade_params(params[:from], params[:to]) if params[:from].present? && params[:to].present?
All parameters validations should be in `params`

2018-08-22 11:09 UTC, ysv commented on app/api/api_v2/helpers.rb
> +      raise Error.new(text: "from should be less than to", status: 422) if from > to
Use single quotes
`'From should be less than to'`

2018-08-22 13:20 UTC, ysv commented
@kaiten-mahajan Please update

2018-08-22 13:53 UTC, kaiten-mahajan commented
@ysv I'm still working on this.

2018-08-22 15:48 UTC, kaiten-mahajan commented on app/api/api_v2/trades.rb
> +      validate_trade_params(params[:from], params[:to]) if params[:from].present? && params[:to].present?
@ysv done

2018-08-22 15:49 UTC, kaiten-mahajan commented
@ysv I have made the changes. Please have a look now.

2018-08-23 13:35 UTC, ysv requested changes

2018-08-23 13:35 UTC, ysv commented on spec/api/api_v2/trades_spec.rb
@kaiten-mahajan can you add spec with only from and only to parameter

2018-08-24 14:04 UTC, kaiten-mahajan commented
@ysv Done.

2018-08-24 14:05 UTC, kaiten-mahajan commented on spec/api/api_v2/trades_spec.rb
@ysv Done.

2018-08-27 18:17 UTC, merged