Ability to retrieve address in both formats cash and legacy via API #1590
openware/peatio pull request #1604
Opened 2018-08-28 13:00 UTC by dinesh-skyach

Ability to retrieve address in both formats cash and legacy via API #1590

2018-08-28 17:09 UTC, ysv commented
@dinesh-skyach what if currency doesn’t support cash address?

2018-08-29 06:13 UTC, dinesh-skyach commented
@ysv Yes, we need this validation too. Thanks

2018-08-29 10:05 UTC, ysv requested changes

2018-08-29 10:05 UTC, ysv commented on app/api/api_v2/validations.rb
> +    class CurrencyAddressFormat < Grape::Validations::Base
@dinesh-skyach Can you name this class `ValidateCurrencyAddressFormat`

2018-08-29 10:21 UTC, dinesh-skyach commented on app/api/api_v2/validations.rb
> +    class CurrencyAddressFormat < Grape::Validations::Base
@ysv done.

2018-08-29 10:33 UTC, ysv requested changes

2018-08-29 10:33 UTC, ysv commented on spec/api/api_v2/deposits_spec.rb
> +
I think will brake validation
```ruby
api_get '/api/v2/deposit_address', params: { currency: :btc, address_format: 'legacy' }, token: token
```

2018-08-29 10:39 UTC, dinesh-skyach commented on spec/api/api_v2/deposits_spec.rb
> +
@ysv All specs have passed. So, I don't think this will break validation.

2018-08-29 10:39 UTC, ysv commented on spec/api/api_v2/deposits_spec.rb
> +
@dinesh-skyach It's specs which you are missing
Double check please

2018-08-29 12:54 UTC, ysv approved these changes

2018-08-30 12:13 UTC, merged