Removed unwanted options in currency model and seed file #1611
openware/peatio pull request #1618
Opened 2018-08-30 09:40 UTC by dinesh-skyach

Removed unwanted options in currency model and seed file #1611

2018-09-03 08:03 UTC, ysv requested changes

2018-09-03 08:03 UTC, ysv commented on app/api/api_v2/deposits.rb
> -    desc 'Returns new deposit address for account you want to deposit to. ' \
@dinesh-skyach why did you remove this api call 
Now we allow to create multiple payment addresses for all currencies 
You need only to update `desc`.

2018-09-03 08:03 UTC, ysv commented on app/models/account.rb
> -  # Attempts to create additional deposit address for account.
@dinesh-skyach Don't need to delete this method

2018-09-03 08:03 UTC, ysv commented on config/templates/seed/currencies.yml.erb
> -  options:
Leave empty options

2018-09-04 07:37 UTC, dinesh-skyach commented on app/api/api_v2/deposits.rb
> -    desc 'Returns new deposit address for account you want to deposit to. ' \
@ysv this method depends on `allow_multiple_deposit_addresses` and `supports_hd_protocol`. If we are removing these values then, It think this method also needs to be removed.

2018-09-04 11:01 UTC, ysv requested changes

2018-09-04 11:01 UTC, ysv commented on app/api/api_v2/deposits.rb
> -    desc 'Returns new deposit address for account you want to deposit to. ' \
yes we this fields were removed because ability to generate multiple address doesn't depend on this values now

2018-09-04 14:09 UTC, ysv requested changes

2018-09-04 14:09 UTC, ysv commented on app/api/api_v2/deposits.rb
>           'IMPORTANT: The system may return the same response as GET /api/v2/deposit_address returns in case ' \
Remove everything after `f this case you should try again later.`

2018-09-05 04:23 UTC, dinesh-skyach commented on config/templates/seed/currencies.yml.erb
> -  options:
@ysv done

2018-09-05 04:23 UTC, dinesh-skyach commented on app/api/api_v2/deposits.rb
>           'IMPORTANT: The system may return the same response as GET /api/v2/deposit_address returns in case ' \
@ysv done

2018-09-05 10:41 UTC, ysv approved these changes

2018-09-05 18:39 UTC, merged