Add management api for markets (closes #786)
openware/peatio pull request #1633
Opened 2018-09-03 10:33 UTC by Naichuk

2018-09-03 10:44 UTC, kovetskiy commented on spec/api/management_api_v1/markets_spec.rb
> +    let(:data) { {} }
seems like unused :data variable

2018-09-03 11:09 UTC, ysv commented
@Naichuk fix specs

2018-09-03 11:52 UTC, Naichuk commented
@ysv Done

2018-09-06 14:28 UTC, ysv commented
@mnaichuk add new scopes to management_api_v1.yml.erb

2018-09-06 14:57 UTC, ysv commented
@mnaichuk add entities specs

2018-09-06 15:03 UTC, ysv requested changes

2018-09-06 15:03 UTC, ysv commented on app/api/management_api_v1/blockchains.rb
> +      optional :status, type: String, default: 'active', desc: 'Blockchain status'
`Blockchain status active or disabled`

2018-09-06 15:03 UTC, ysv commented on app/api/management_api_v1/blockchains.rb
> +      requires :key, type: String, desc: 'Blockchain key'
validate values

2018-09-06 15:03 UTC, ysv commented on app/api/management_api_v1/blockchains.rb
> +      present Blockchain.find_by(key: params[:key]), with: ManagementAPIv1::Entities::Blockchain
use `find_by!`

2018-09-06 15:03 UTC, ysv commented on app/api/management_api_v1/blockchains.rb
> +      blockchain = Blockchain.find_by(key: params[:key])
use `find_by!`

2018-09-06 15:03 UTC, ysv commented on app/api/management_api_v1/markets.rb
> +      optional :id, type: String, desc: 'Market id.'
remove id

2018-09-06 15:03 UTC, ysv commented on app/api/management_api_v1/markets.rb
> +      optional :bid_unit, type: String, desc: 'Market bid unit'
There are some read only fields in Market please check and remove

2018-09-06 15:03 UTC, ysv commented on app/api/management_api_v1/markets.rb
> +      market = Market.new
`market = Market.new(params)`
remove `market.assign_attributes`

2018-09-06 15:03 UTC, ysv commented on spec/api/management_api_v1/markets_spec.rb
> +    let(:expected_response) { Market.find(data[:id]).update('ask_fee': 0.1)}
remove this let

2018-09-11 10:56 UTC, ysv requested changes

2018-09-11 10:56 UTC, ysv commented on spec/api/management_api_v1/blockchains_spec.rb
> +    let(:do) { Blockchain.find_by!(key: data[:key]).update(min_confirmations: 5) }
This one is not used I think

2018-09-11 10:56 UTC, ysv commented on spec/api/management_api_v1/markets_spec.rb
> +describe ManagementAPIv1::Deposits, type: :request do
`ManagementAPIv1::Deposits`

2018-09-11 10:56 UTC, ysv commented on spec/api/management_api_v1/blockchains_spec.rb
> +describe ManagementAPIv1::Deposits, type: :request do
` ManagementAPIv1::Deposits`

2018-09-11 10:56 UTC, ysv commented on spec/api/management_api_v1/markets_spec.rb
> +    it 'creates new market with enabled state' do
it 'creates new market with expected attributes'

2018-09-11 10:56 UTC, ysv commented on spec/api/management_api_v1/blockchains_spec.rb
> +    it 'creates new blockchain with state active' do
it 'creates new blockchain with expected attributes'

2018-09-11 10:56 UTC, ysv commented on spec/api/management_api_v1/blockchains_spec.rb
> +    it 'updates blockchain' do
can you also add test that it doesn't allow to update read-only attributes. Example client

2018-09-11 10:56 UTC, ysv commented on spec/api/management_api_v1/markets_spec.rb
> +    it 'updates market' do
can you also add test that it doesn't allow to update read-only attributes. Example bid_unit

2018-12-10 15:38 UTC, closed without merging

2019-01-14 20:06 UTC, hardywu commented
is this feature gonna implemented?