Added wallet notify for bitcoin like currencies
openware/peatio pull request #1649
Opened 2018-09-06 09:08 UTC by dinesh-skyach

Added wallet notify for bitcoin like currencies

2018-09-06 12:52 UTC, ysv requested changes

2018-09-06 12:52 UTC, ysv commented on app/services/blockchain_service/bitcoin.rb
> +    def fetch_unconfirmed_deposits(latest_block, block_json = {})
Rails.logger.info { "Processing unconfirmed deposits." }

2018-09-06 13:27 UTC, dinesh-skyach commented on app/services/blockchain_service/bitcoin.rb
> +    def fetch_unconfirmed_deposits(latest_block, block_json = {})
@ysv done

2018-09-11 12:52 UTC, ysv requested changes

2018-09-11 12:52 UTC, ysv commented on app/models/deposits/coin.rb
> -      return latest_block_number - block_number if (latest_block_number - block_number) >= 0
this is wrong for eth leave as it was

2018-09-11 12:52 UTC, ysv commented on app/models/withdraws/coin.rb
> -      return latest_block_number - block_number if (latest_block_number - block_number) >= 0
this is wrong for eth leave as it was we will solve this later

2018-09-11 12:52 UTC, ysv commented
@dinesh-skyach please rebase

2018-09-11 12:59 UTC, dinesh-skyach commented on app/models/deposits/coin.rb
> -      return latest_block_number - block_number if (latest_block_number - block_number) >= 0
@ysv why is it wrong for eth? We have to include the block in which the txn is included.

2018-09-11 16:36 UTC, ysv requested changes

2018-09-11 16:36 UTC, ysv commented on app/models/deposits/coin.rb
> -      return latest_block_number - block_number if (latest_block_number - block_number) >= 0
latest_block_number for eth returns number of current block ( block which is mining right now)
but for btc it returns block with is mining right now - 1

2018-09-17 22:55 UTC, ysv approved these changes

2018-09-19 09:43 UTC, mod approved these changes

2018-09-19 09:43 UTC, merged