Safe
openware/peatio pull request #1678
Opened 2018-09-17 12:48 UTC by ymasiuk

2018-09-17 12:50 UTC, ysv requested changes

2018-09-17 12:50 UTC, ysv commented on config/database.yml
> -  database: peatio_development
What ?

2018-09-17 12:57 UTC, ymasiuk commented on config/database.yml
> -  database: peatio_development
@ysv fixed

2018-09-18 14:43 UTC, ysv commented
![screen shot 2018-09-18 at 4 42 15 pm](https://user-images.githubusercontent.com/19859122/45695525-e6035500-bb61-11e8-9b67-75998ef96ec5.png)

2018-09-18 14:51 UTC, tamadamas requested changes

2018-09-18 14:51 UTC, rxx commented on app/views/admin/accountments/_trade.html.erb
> +  <td><%= link_to Member.find_by_id(trade.ask_member_id).email, admin_member_path(trade.ask_member_id), target: '_blank' %></td>
it's very bad to do any db queries in the view level!

2018-09-18 14:52 UTC, tamadamas requested changes

2018-09-18 14:52 UTC, rxx commented on app/controllers/admin/accountments_controller.rb
> +      @trades = Trade.all.order('id desc').page(params[:page]).per(20)
`20` should be constant

2018-10-11 10:11 UTC, closed without merging