Improve admin panel with more information
openware/peatio pull request #1691
Opened 2018-09-20 08:44 UTC by ymasiuk

2018-09-20 08:59 UTC, gfedorenko commented on app/views/admin/trades/index.html.erb
> +    <% t.column :id, "ID" %>
Please, put single quotes for strings in erb tags

2018-09-27 15:18 UTC, ysv commented on config/templates/application.yml.erb
> +  COPYRIGHT_TITLE: Peatio.tech
Add description for this env

2018-09-27 15:24 UTC, ysv requested changes

2018-09-27 15:24 UTC, ysv commented on app/controllers/admin/members_controller.rb
>        @search_term  = params[:search_term]
do we need class variables here ?
may be
`search_field` and `search_term`

2018-09-27 15:34 UTC, chumaknadya commented on config/templates/application.yml.erb
> +  COPYRIGHT_TITLE: Peatio.tech
Done

2018-09-27 15:34 UTC, gfedorenko commented on app/controllers/admin/members_controller.rb
>        @search_term  = params[:search_term]
I think, it was used on the view

2018-11-23 17:15 UTC, closed without merging