Improve admin feature
openware/peatio pull request #1694
Opened 2018-09-20 16:47 UTC by vpetrusenko

* Remove ADMIN filed from ENV
* Add role to members table
* Bind role from JWT

2018-09-27 11:07 UTC, ysv commented on spec/api/api_v2/auth/jwt_authenticator_spec.rb
>        it 'should register new member and return instance' do
@vpetrusenko can you add spec where we first create Member with role :member from barong JWT and then we receive new JWT where role is :admin

2018-09-27 11:15 UTC, ysv requested changes

2018-09-27 11:15 UTC, ysv commented on app/models/member.rb
add
```ruby
validates :role, inclusion: { in: -> (_) { Member.roles.map(&:to_s) } }
```
```ruby
class << self
  def roles
      %i[member admin].freeze
  end
end

def role
  role&.inquiry
end
```

2018-09-27 13:05 UTC, ysv commented
@vpetrusenko https://github.com/rubykube/peatio/pull/1694/files#diff-99215219f23b3e704ba1b4ecadb52a71R32

```member.role     = info_hash.fetch('role')```

2018-09-27 13:15 UTC, ysv commented on app/models/member.rb
> +    super.inquiry
super&

2018-09-28 10:14 UTC, mod requested changes

2018-09-28 10:14 UTC, mod commented on db/schema.rb
>    create_table "members", force: :cascade do |t|
should we list UID in here ?

2018-09-28 10:14 UTC, mod commented on app/models/member.rb
> +      %i[member admin].freeze
I suggest adding accountant and operator roles here

2018-09-28 11:46 UTC, ysv commented on db/schema.rb
>    create_table "members", force: :cascade do |t|
@mod but we don't use UID in peatio
we only save it in authentications

2018-09-28 12:02 UTC, vpetrusenko commented on app/models/member.rb
> +      %i[member admin].freeze
i would like to add this roles in separate accountant patch

2018-11-29 21:52 UTC, closed without merging