Add min deposit amount for currencies and validation for small deposits
openware/peatio pull request #1721
Opened 2018-10-04 10:48 UTC by mnaichuk

2018-10-05 06:21 UTC, ysv requested changes
1. Add validation to Deposit model
2. Add new field to currencies.yml.erb

2018-10-11 14:05 UTC, ysv approved these changes

2018-10-12 07:10 UTC, ysv requested changes

2018-10-12 07:10 UTC, ysv commented on spec/models/deposit_spec.rb
> -      expect(deposit.errors.full_messages).to eq ['Amount must be greater than 0.0']
Lets use single quotes

2018-10-12 07:10 UTC, ysv commented on db/migrate/20181004114428_add_min_deposit_amount_to_currencies.rb
> +    add_column :currencies, :min_deposit_amount, :decimal, precision: 32, scale: 16, default: 0.0, null: false, after: 'quick_withdraw_limit'
use symbols here `after: :quick_withdraw_limit`

2018-10-12 07:10 UTC, ysv commented on app/services/blockchain_service/dash.rb
> +            if entry[:amount] <= payment_address.currency.min_deposit_amount
make this update everywhere
```ruby
# If deposit amount smaller then currency min deposit amount.
if entry[:amount] <= payment_address.currency.min_deposit_amount
  # Currently we just skip small deposits. Custom behavior will be implemented later.
next
end
```

2018-10-12 13:05 UTC, ysv requested changes

2018-10-12 13:05 UTC, ysv commented on app/services/blockchain_service/ripple.rb
> +              # Currently we just skip small deposits. Custom behavior will be implemented later.
Show message in logs

2018-10-25 12:36 UTC, merged

2018-11-21 05:47 UTC, Thedabest commented
can you add to gon?