Add opportunity to receive transaction with multiple addresses
openware/peatio pull request #1792
Opened 2018-10-31 09:16 UTC by mnaichuk

2018-10-31 22:25 UTC, ysv requested changes

2018-10-31 22:25 UTC, ysv commented on app/services/blockchain_service.rb
> +                    .find_or_create_by!(deposit_hash.slice(:txid, :address)) do |deposit|
we need to find_or_create_by txid and vout

2018-10-31 22:25 UTC, ysv commented on app/models/deposits/coin.rb
> -    validates :txid, uniqueness: { scope: %i[currency_id txout] }
This validation is still ok

2018-10-31 22:25 UTC, ysv commented on app/services/blockchain_service/bitcoin.rb
> +        payment_addresses_where(address: client.to_address(tx)).each_with_index do |payment_address, i|
I'm not sure if we need this changes
I reckon that the problem is in https://github.com/rubykube/peatio/pull/1792/files#diff-12ec28c62ee4ee7ef72503aae2a92392R54

2018-10-31 22:27 UTC, ysv commented
@mnaichuk Add specs for this context
1. Multiple vout with platform addresses
2. Multiple vout with same platform address (if this is possible)

2018-11-16 15:18 UTC, mnaichuk commented on lib/blockchain_client/ethereum.rb
> +    def build_transaction(txn, current_block_json, payment_address, currency)
`address`

2018-11-16 15:18 UTC, mnaichuk commented on lib/blockchain_client/ripple.rb
> +          txout:   0
`nil`

2018-11-16 15:18 UTC, mnaichuk commented on spec/services/blockchain_service/ethereum_spec.rb
> +            txid:     '0x826555325cec51c4d39b327e563ce3e8ee87e27be5911383f528724a62f0da5d'
`vout`

2018-11-16 15:18 UTC, mnaichuk commented on spec/services/blockchain_service/ethereum_spec.rb
> +            address:  '0xe3cb6897d83691a8eb8458140a1941ce1d6e6dab',
use another address

2018-11-19 16:13 UTC, ysv approved these changes

2018-11-19 20:47 UTC, mod commented
@pkucherenk0 do you confirm ?

2018-11-19 21:11 UTC, pkucherenk0 commented
Can confirm that BTC deposit to multiple addresses works well, but I haven't done ERC20 deposit to multiple addresses, yet.

2018-11-21 10:01 UTC, merged

2018-11-21 15:20 UTC, Fair-Exchange commented
Thank you so much, will try this tonight