Operations rubric
openware/peatio pull request #1820
Opened 2018-11-22 06:33 UTC by dinesh-skyach

Operations rubric

2018-11-23 13:06 UTC, ysv requested changes

2018-11-23 13:06 UTC, ysv commented on app/controllers/admin/balance_sheet_controller.rb
> +      @assets = ::Operations::Asset.group(:currency_id).sum(:credit)
@dinesh-skyach asset balance is difference between sum of credits and debits 
`sum(:credit) - sum(:debit)`

2018-11-23 13:06 UTC, mod commented
1- Do not nest Currencies inside Operations types
2- show all operations by default with an ability to filter with a dropdown currency selector
3- balance sheet is mistaken, liabilities must be equal to member balances.

2018-11-24 05:30 UTC, dinesh-skyach commented on app/controllers/admin/balance_sheet_controller.rb
> +      @assets = ::Operations::Asset.group(:currency_id).sum(:credit)
@ysv Done

2018-11-24 12:27 UTC, merged

2018-11-24 12:49 UTC, ysv commented on app/controllers/admin/operations/assets_controller.rb
> +        @assets = ::Operations::Asset.includes(:reference, :currency)
Do we need includes here ?

2018-11-24 12:49 UTC, ysv commented on app/views/admin/operations/shared/_table.html.erb
> +    <% x.currency.code.upcase %>
x.currency_id