Ability to manually loading withdraw with external txid
openware/peatio pull request #1846
Opened 2018-11-29 11:34 UTC by mnaichuk

2018-12-03 15:35 UTC, ysv requested changes

2018-12-03 15:35 UTC, ysv commented on app/controllers/admin/withdraws/coins_controller.rb
> +        when 'process'
```suggestion
        when 'process'
        process!
        when 'load'
        load!
```

2018-12-03 15:35 UTC, ysv commented on docs/api/member_api_v2.md
> +**Version:** 1.9.1-rc.27
rebase please

2018-12-03 15:35 UTC, ysv commented on app/controllers/admin/withdraws/coins_controller.rb
> +        case params.fetch(:state, 'all')
I think we need specs for this controller

2018-12-14 15:53 UTC, pkucherenk0 commented
Add ability to reject already confirming withdraw in case of input tx id error.
Currently the amount will be blocked forever.

2019-01-08 22:26 UTC, merged