JSON Editor For Currency options
openware/peatio pull request #1848
Opened 2018-11-30 05:28 UTC by dinesh-skyach

JSON Editor For Currencies 
closes #1844

2018-12-03 14:59 UTC, ysv requested changes

2018-12-03 14:59 UTC, ysv commented on app/assets/javascripts/admin/json_editor.js
> +                required: jQuery.parseJSON(gon.json_editor_required),
Don't use gon

2018-12-03 14:59 UTC, ysv commented on app/views/admin/currencies/show.html.erb
> +      json_editor.setValue(jQuery.parseJSON('<%= raw Hash[ *Currency::OPTIONS_ATTRIBUTES.collect { |v| [ v, @currency.options[v] ] }.flatten ].to_json %>'));
We need ability to add custom attributes into options dynamicly

2018-12-03 14:59 UTC, ysv commented on spec/controllers/admin/currencies_controller_spec.rb
> +        options:                          { "erc20_contract_address" => '12kamv8qxvqyosgzitfym6yzxk2sgovhq9'}
add some custom option
for example 
```json
{ "erc20_contract_address":  "12kamv8qxvqyosgzitfym6yzxk2sgovhq9", "custom_currency_option": "options value"}
```

2018-12-04 09:31 UTC, dinesh-skyach commented
@ysv I have made some changes. Please have a look again.

2018-12-04 11:01 UTC, ysv requested changes
Add options to currencies.yml.erb usd because it brakes `rake db:seed` with nil options

2018-12-04 11:01 UTC, ysv commented on app/controllers/admin/base_controller.rb
> +    skip_before_filter :set_gon
Do we need this ?

2018-12-04 11:01 UTC, ysv commented on app/views/layouts/admin.html.erb
> +  <%= include_gon %>
What is the purpose of this code ?

2018-12-04 11:07 UTC, dinesh-skyach commented on app/controllers/admin/base_controller.rb
> +    skip_before_filter :set_gon
@ysv Not required. I will remove this

2018-12-04 11:07 UTC, dinesh-skyach commented on app/views/layouts/admin.html.erb
> +  <%= include_gon %>
@ysv Not required. I will remove this

2018-12-05 13:41 UTC, dinesh-skyach commented
@ysv All changes done.

2018-12-13 11:22 UTC, ysv commented
@dinesh-skyach it's still doesn't work properly https://vimeo.com/user92770823/review/306159684/591d8c64f0

2018-12-17 19:35 UTC, ysv approved these changes

2018-12-17 19:36 UTC, ysv commented
@dinesh-skyach Open the same pr for 1-9 please

2018-12-19 09:45 UTC, dinesh-skyach commented
@ysv ok

2018-12-19 13:02 UTC, merged