Parity Blockchain/Wallet clients/services implementation
openware/peatio pull request #1933
Opened 2018-12-24 17:09 UTC by Ohill

2019-01-02 11:01 UTC, raidray approved these changes

2019-01-17 07:59 UTC, maulikbhai1 commented
@mod when this files will merge with master ?

2019-02-04 04:27 UTC, mnaichuk commented
Same for 1-9, please

2019-02-04 13:18 UTC, ysv requested changes
Also add comment to Ethereum services and clients that they are abstract

2019-02-04 13:18 UTC, ysv commented on app/models/wallet.rb
> +
Leave sing blank line here

2019-02-04 13:18 UTC, ysv commented on app/services/blockchain_service/geth.rb
> +module BlockchainService
We need migration where we update all blockchains with ethereum client to geth

2019-02-04 13:18 UTC, ysv commented on config/templates/seed/blockchains.yml.erb
> +  client:            geth               # API client name.
align # API client name.

2019-02-04 13:18 UTC, ysv commented on lib/wallet_client/parity.rb
> +    def create_eth_withdrawal!(issuer, recipient, amount, options = {})
This code is outdated
In a new version we require gas_limit and gas_price

I'm not even sure you need to override this methods

2019-02-04 13:18 UTC, ysv commented on spec/services/blockchain_service/geth_spec.rb
> +          # binding.pry
Remove this comment

2019-02-04 13:18 UTC, ysv commented on app/services/wallet_service/ethereum.rb
> +        if currency_options.key?(:gas_limit) && currency_options.key?(:gas_price)
@mnaichuk we need to fix issue you have faced here

2019-02-20 17:37 UTC, merged