Withdraw API With OTP
openware/peatio pull request #1959
Opened 2019-01-07 10:06 UTC by dinesh-skyach

Withdraw API With OTP

2019-01-08 21:29 UTC, ysv requested changes
Add vault to
1. Travis CI
2. backend.yml

2019-01-08 21:29 UTC, ysv commented on app/api/v2/account/withdraws.rb
> +            perform_action(withdraw, params[:action]) if params[:action]
Don't need to perform action. Only create and submit

2019-01-08 21:29 UTC, ysv commented on app/api/v2/account/withdraws.rb
> +          requires :uid,      type: String, desc: 'The shared user ID.'
Remove this param

2019-01-08 21:29 UTC, ysv commented on app/api/v2/account/withdraws.rb
> +          optional :tid,      type: String, desc: 'The shared transaction ID. Must not exceed 64 characters. Peatio will generate one automatically unless supplied.'
Remove this param

2019-01-08 21:29 UTC, ysv commented on app/api/v2/account/withdraws.rb
> +          optional :action,   type: String, values: %w[process], desc: 'The action to perform.'
Remove this param

2019-01-08 21:29 UTC, ysv commented on app/api/v2/account/withdraws.rb
> +          member   = Member.find_by(uid: params[:uid])
We uid in JWT

2019-01-08 21:29 UTC, ysv commented on app/api/v2/helpers.rb
> +      def perform_action(withdraw, action)
Remove this method

2019-01-08 21:29 UTC, ysv commented on spec/api/v2/account/withdraws_spec.rb
> +      btc_withdraws
Use let! instead

2019-01-08 21:29 UTC, ysv commented on spec/api/v2/account/withdraws_spec.rb
> +      it 'should validate missing otp param' do
Don't use should syntax
Better to use `it 'validates missing otp param'`

2019-01-09 13:19 UTC, ritesh-skyach commented
@ysv I have made the changes, Please review it again

2019-01-09 13:20 UTC, dinesh-skyach commented
@ysv I have made the changes, Please review it once.

2019-01-14 14:06 UTC, ysv commented
@dinesh-skyach

2019-01-14 14:35 UTC, ysv requested changes
Also withdrawal request should be available only if ACCOUNT_API_WITHDRAWAL is true. 
And add it to application.yml

2019-01-14 14:35 UTC, ysv commented on app/api/v2/account/withdraws.rb
> +        desc 'Creates new withdraw.' do
desc 'Creates new crypto withdraw'

2019-01-14 14:35 UTC, ysv commented on app/api/v2/account/withdraws.rb
> +          detail 'Creates new withdraw. The behaviours for fiat and crypto withdraws are different. ' \
Remove detail

2019-01-14 14:35 UTC, ysv commented on app/api/v2/account/withdraws.rb
> +          success API::V2::Management::Entities::Withdraw
Why do you use Management here ?

2019-01-14 14:35 UTC, ysv commented on app/api/v2/account/withdraws.rb
> +          requires :currency, type: String, values: -> { Currency.codes(bothcase: true) }, desc: 'The currency code.'
only coins

2019-01-14 14:35 UTC, ysv commented on app/api/v2/account/withdraws.rb
> +          requires :rid,      type: String, desc: 'The beneficiary ID or wallet address on the Blockchain.'
desc: 'Wallet address on the blockchain'

2019-01-14 14:35 UTC, ysv commented on app/api/v2/account/withdraws.rb
> +          withdraw = "withdraws/#{currency.type}".camelize.constantize.new \
Withdraws::Coin.new

2019-01-14 14:35 UTC, ysv commented on app/api/v2/account/withdraws.rb
> +            present withdraw, with: API::V2::Management::Entities::Withdraw
Why do you use Management::Entities here ?

2019-01-14 14:35 UTC, ysv commented on spec/api/v2/account/withdraws_spec.rb
> +      end
We need situation when there is no enough funds for withdrawal I think this will cause 500

2019-01-14 14:35 UTC, ysv commented on Gemfile
> +gem 'vault', '~> 0.12'
require: false in Gemfile and require explicitly in vault/totp.rb

2019-01-15 16:49 UTC, ysv requested changes

2019-01-15 16:49 UTC, ysv commented on app/api/v2/entities/withdraw.rb
> +        expose(
Don't need to expose tid

2019-01-15 16:49 UTC, ysv commented on bin/init_vault
> +DOCKER_VAULT_ID=`docker ps | grep vault  | awk '{ print $1 }'`
run this script in /bin/setup after 
`system "docker-compose -f config/backend.yml up -d"`

2019-01-15 16:49 UTC, ysv commented on spec/api/v2/account/withdraws_spec.rb
> +    it 'validate currency param' do
it 'validates ...'

add 's' in all specs

2019-01-15 16:49 UTC, ysv commented on config/templates/application.yml.erb
> +  ACCOUNT_API_WITHDRAWAL: true
add comment with description of this env usage

2019-01-15 16:49 UTC, ysv commented on app/api/v2/account/withdraws.rb
> +          if ENV.fetch('ACCOUNT_API_WITHDRAWAL') == 'false'
1. add spec for this context
2. use ENV.false?( 'ACCOUNT_API_WITHDRAWAL') (https://github.com/rubykube/peatio/blob/master/config.ru#L15)

2019-01-16 06:54 UTC, dinesh-skyach commented on app/api/v2/account/withdraws.rb
> +          if ENV.fetch('ACCOUNT_API_WITHDRAWAL') == 'false'
@ysv ENV.false?( 'ACCOUNT_API_WITHDRAWAL') is not working for specs

2019-01-21 14:57 UTC, ysv commented on app/api/v2/account/withdraws.rb
> +        desc 'Creates new crypto withdraw.'
Creates new crypto withdrawal.

2019-01-21 14:57 UTC, ysv commented on config/initializers/vault.rb
> +  config.token = ENV.fetch('VAULT_TOKEN', 'changeme')
remove default 'changeme' and add it for development env in application.yml

2019-01-21 17:22 UTC, merged