Add CORS headers
openware/peatio pull request #1966
Opened 2019-01-09 14:01 UTC by mnaichuk

2019-01-09 19:39 UTC, mod commented
I prefer using https://github.com/ruby-grape/grape#cors
Rack::Cors middleware as it's natively supported by grape
I should be smart behavior with OPTIONS requests.

2019-01-11 14:37 UTC, ysv requested changes

2019-01-11 14:37 UTC, ysv commented on Gemfile
> +gem 'rack-cors', '~> 1.0.2', :require => 'rack/cors'
require: false

Because we use it only in config.ru

2019-01-11 14:37 UTC, ysv commented on lib/cors/validations.rb
> +      if origins.include?("*")
May be origins=='*'

2019-01-11 14:37 UTC, ysv commented on lib/cors/validations.rb
> +        Rails.logger.info{ "WARNING: Usinng API_CORS_ORIGIN as '*'" }
WARNING: API_CORS_ORIGIN is set to '*'

2019-01-11 14:37 UTC, ysv commented on lib/cors/validations.rb
> +        Rails.logger.info{ "WARNING: Incorect or missing API_CORS_MAX_AGE value. Set default value: 3600" }
WARNING: Incorect or missing API_CORS_MAX_AGE value. Using default value: 3600

2019-01-14 11:03 UTC, ysv requested changes

2019-01-14 11:03 UTC, ysv commented on lib/cors/validations.rb
> +          return '*'
redundant return

2019-01-15 10:47 UTC, ysv approved these changes

2019-01-15 11:54 UTC, merged