[WIP] Upgrade To Rails 5.2
openware/peatio pull request #1979
Opened 2019-01-14 11:53 UTC by dinesh-skyach

Upgrade To Rails 5.2

2019-01-25 04:24 UTC, ianeinser commented
Bring it on dudes ASAP, for both v1.9 and v2.0 please.

2019-02-21 13:50 UTC, shal commented
@dinesh-skyach Could you rebase the patch?

2019-02-22 11:00 UTC, shal requested changes

2019-02-22 11:00 UTC, shal commented on Gemfile
> +  gem 'spring', '~> 2.0.2'
@dinesh-skyach Why do we need this gems: `spring` and `spring-watcher-listen`?

2019-02-22 11:00 UTC, shal commented on Gemfile
> +  gem 'rails-controller-testing', '~> 1.0.4'
I think later we should have a separate task to get rid of `rails-controller-testing`.
https://github.com/rails/rails/issues/1895

2019-02-22 11:00 UTC, shal commented on app/models/order.rb
> +    event = case state
Maybe let's keep:

```ruby
event = case after_save.dig('state', 1)
```

2019-02-22 11:00 UTC, shal commented on bin/setup
> +include FileUtils
I don't this is it necessary to include and require `FileUtils`. Just keep 
```rb
Dir.chdir APP_ROOT do
  ...
end
```

2019-02-22 11:00 UTC, shal commented on config/application.rb
> +require 'rails/all'
I afraid amount of unused libs may speed down the application.

2019-02-22 11:00 UTC, shal commented on config/application.rb
> +require 'rails/all'
Keep this:

```rb
require_relative 'boot'

require 'rails'

%w( active_record action_controller action_view sprockets ).each { |framework| require "#{framework}/railtie" }
```

2019-02-22 11:00 UTC, shal commented on config/credentials.yml.enc
> +nvyOF/IyR5uU8ouBSuMUepwoSYJbiAJ5uK+jXqp/Uy2s0BEktlGaRACEBxu+rAdiSNVAwKfm+/2ZSiBd4QXTZa8YGLOPTBjKhL9xoT8EFtLLngTp2KIz367L4dtCWZ2Cdv9Fqf4bnZtSKnPXk4oECN0OnsCmiUInZW4bVU9E5jFqTsAyzuD8P1KOkmFvjJAHxbuO/w1
Why do we need this?

2019-02-22 11:00 UTC, shal commented on config/environments/development.rb
> +  config.consider_all_requests_local = true
No need.

2019-02-22 11:00 UTC, shal commented on config/environments/development.rb
> +  config.assets.quiet = true
Try:
```rb
config.logger = ActiveSupport::Logger.new(STDOUT)
config.assets.quiet = true
```

2019-02-22 11:13 UTC, shal commented
@dinesh-skyach @mod In my opinion this patch is shoot into leg, it is too difficult to review all this changes and I think impossible to check everything.
I suggest to move slowly the version of rails.

Here is quote from rails main page:
https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#the-upgrade-process.

Let start from https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-2-to-rails-5-0 and then keep bumping the version slowly :smile_cat:

2019-03-04 11:51 UTC, shal commented
Closed via #2095.

2019-03-04 11:51 UTC, closed without merging