Update api 1-9 docs
openware/peatio pull request #2021
Opened 2019-01-24 10:29 UTC by Ohill

2019-01-24 14:21 UTC, mnaichuk requested changes

2019-01-24 14:21 UTC, mnaichuk commented on app/api/api_v2/entities/market.rb
> +      }
Also add other fields like in https://github.com/rubykube/peatio/blob/master/docs/api/peatio_user_api_v2.md#market

2019-01-24 14:21 UTC, mnaichuk commented on app/api/api_v2/fees.rb
> +    desc 'Returns withdraw fees for currencies.', deprecated: true
We wouldn't delete this APIs in 1-9 so no need for `deprecated: true`

2019-01-24 14:21 UTC, mnaichuk commented on app/api/api_v2/orders.rb
> +    desc 'Create multiple sell/buy orders.', scopes: %w[trade], success: APIv2::Entities::Order
is_array: true

2019-01-24 14:21 UTC, mnaichuk commented on app/api/api_v2/orders.rb
> +    desc 'Cancel all my orders.', scopes: %w[trade], success: APIv2::Entities::Order
is_array: true

2019-01-29 08:48 UTC, ysv approved these changes

2019-01-29 21:03 UTC, merged