Improve pagination for /markets /public APIs
openware/peatio pull request #2035
Opened 2019-02-01 16:01 UTC by mnaichuk

2019-02-05 13:56 UTC, ysv commented
use https://github.com/davidcelis/api-pagination and set pagination headers

2019-02-05 13:58 UTC, ysv requested changes
Use https://github.com/davidcelis/api-pagination instead

2019-02-06 15:38 UTC, ysv commented
Related pr https://github.com/davidcelis/api-pagination/pull/119

2019-02-06 15:48 UTC, ysv requested changes

2019-02-06 15:48 UTC, ysv commented on app/api/v2/entities/trade.rb
> +          if: ->(trade, options) { options[:side] || trade.side(options[:current_user]) },
`options[:side] || options[:current_user]`

2019-02-06 15:48 UTC, ysv commented on app/api/v2/market/orders.rb
> +          optional :order_by, type: String, values: %w(asc desc), default: 'desc', desc: 'If set, returned orders will be sorted in specific order, default to "asc".'
`If set, returned orders will be sorted in specific order, default to "desc"``

2019-02-06 15:48 UTC, ysv commented on app/api/v2/named_params.rb
> +        optional :limit,     type: Integer, range: 1..100, default: 100, desc: 'Limit the number of returned trades. Default to 50.'
`Limit the number of returned trades. Default to 50.` default is 100 now
Lets leave range: 1..1000 here

2019-02-06 15:48 UTC, ysv commented on app/api/v2/account/withdraws.rb
> +          optional :limit,    type: Integer, default: 100, range: 1..100, desc: 'Number of withdraws per page (defaults to 100, maximum is 1000).'
update desc

2019-02-06 15:48 UTC, ysv commented on config/initializers/kaminari_config.rb
> +  config.max_per_page = 100
put 1000

2019-02-07 07:22 UTC, mod requested changes

2019-02-07 07:22 UTC, mod commented on app/api/v2/account/deposits.rb
> -            .page(params[:page])
Why page is not in SQL query ?

2019-02-07 08:07 UTC, mnaichuk commented on app/api/v2/account/deposits.rb
> -            .page(params[:page])
Now we use `api-pagination` for return total amount in header and no need add page in query.

2019-02-07 09:39 UTC, ysv requested changes

2019-02-07 09:39 UTC, ysv commented on app/api/v2/account/deposits.rb
> -            .page(params[:page])
@mod page is in SQL query 
Query is executed in `paginate` method

2019-02-07 09:39 UTC, ysv commented on app/api/v2/public/markets.rb
>              present trades, with: API::V2::Entities::Trade
Why don't we use `present paginate(trades)` here ?

2019-02-07 09:39 UTC, ysv commented on app/api/v2/account/withdraws.rb
> +          present (paginate withdraws), with: API::V2::Entities::Withdraw
Put this present into tap everywhere so we will have
Make this refactoring everywhere
```ruby
.tap { |q| q.where!(currency: currency) if currency }
.tap { |q| present paginate(withdraws), with: API::V2::Entities::Withdraw }
```

2019-02-07 09:39 UTC, ysv commented on config/initializers/api_pagination.rb
> +  config.total_header = 'X-Total'
X - prefix in Headers is [deprecated](https://tools.ietf.org/html/rfc6648) so lets use default headers: Total, Per-Page ...
So you can remove this from initializer

2019-02-07 09:39 UTC, ysv commented on config/initializers/api_pagination.rb
> +  config.response_formats = [:json, :xml, :jsonapi]
Remove this line

2019-02-07 09:39 UTC, ysv commented on config/initializers/api_pagination.rb
> +  config.include_total = true
if it's set to true by default don't add it one more time

2019-02-07 09:45 UTC, mnaichuk commented on app/api/v2/public/markets.rb
>              present trades, with: API::V2::Entities::Trade
@ysv cause frontend team and R said that they don't need this feature

2019-02-07 11:57 UTC, ysv approved these changes

2019-02-07 12:16 UTC, merged