Remove Funds Page
openware/peatio pull request #2051
Opened 2019-02-11 06:26 UTC by ritesh-skyach

Remove Funds Page

2019-02-15 14:01 UTC, ysv commented
TODO: 

- [ ] Check application.yml.erb

- [ ] Check app/views

- [ ] Remove methods from models which were used by legacy controllers

2019-02-18 14:02 UTC, ysv commented
- [ ] update Dockerfile

- [ ] Do we need vendor/assets/yarn_components ?

- [ ] remove raven from FE side

2019-02-19 05:48 UTC, dinesh-skyach commented
@ysv Do we need to remove `* METADATA_` from application.yml.erb?

2019-02-19 13:54 UTC, mnaichuk commented
I think you can also remove this dropdown 
![deepinscreenshot_select-area_20190219154947](https://user-images.githubusercontent.com/26766307/53019858-648c5780-345e-11e9-965c-a989f86daecf.png)

2019-02-19 14:10 UTC, ysv commented
> @ysv Do we need to remove `* METADATA_` from application.yml.erb?

@dinesh-skyach Agree we still need this

2019-02-19 14:29 UTC, ysv commented
- [ ] Remove I18n stuff

- [ ] lib/market_constraints.rb

2019-02-21 17:07 UTC, ysv requested changes

2019-02-21 17:07 UTC, ysv commented on .travis.yml
>    - . $HOME/.nvm/nvm.sh
Don't need node too

2019-02-22 05:13 UTC, dinesh-skyach commented on .travis.yml
>    - . $HOME/.nvm/nvm.sh
@ysv Removed!

2019-02-22 19:51 UTC, shal commented
Looks nice

2019-02-22 22:59 UTC, ysv approved these changes

2019-02-23 19:15 UTC, mod approved these changes

2019-02-23 19:15 UTC, merged