Add filter by date in market/trades REST API call
openware/peatio pull request #2126
Opened 2019-03-18 10:54 UTC by mnaichuk

2019-03-18 11:48 UTC, ysv reviewed
You can try to use 
```ruby
coerce_with: ->(t) { Time.at(t.downcase) }
```

as mentioned here https://github.com/ruby-grape/grape#custom-types-and-coercions

But if this requires many changes lets merge as it is

2019-03-26 23:48 UTC, mod requested changes
Seems wrong to me
What we need is select by time range

2019-04-03 14:21 UTC, ysv approved these changes

2019-04-04 15:53 UTC, mod approved these changes

2019-04-04 15:53 UTC, merged