Delete pagination from API for liabilities and add optional fields
openware/peatio pull request #2140
Opened 2019-03-26 13:43 UTC by ymasiuk

2019-03-26 13:55 UTC, ysv requested changes

2019-03-26 13:55 UTC, ysv commented on app/api/v2/management/operations.rb
> +              .tap { |q| q.where!('created_at >= ?', time_from) if time_from.present? }
@ymasiuk use 
`Time.at(params[:timestamp])` and remove time_from

2019-03-26 13:55 UTC, ysv commented on app/api/v2/management/operations.rb
> +              .tap { |q| q.where!(reference_type: reference_type) if reference_type }
use reference_type from params

2019-03-26 13:55 UTC, ysv commented on app/api/v2/management/entities/operation.rb
> +         expose :reference_type,
@ymasiuk use downcased type

2019-03-26 13:55 UTC, ysv commented on app/api/v2/management/operations.rb
> -            optional :page,
reset pagination

2019-03-26 14:45 UTC, ymasiuk commented
@ysv updated

2019-04-03 12:23 UTC, ysv approved these changes

2019-04-03 23:03 UTC, mod reviewed
@calj can you review and explain

2019-04-04 08:41 UTC, ysv commented
@mod 
- There was missing reference type in API we added it
- We added time range filtering to operations API

2019-04-04 08:41 UTC, ysv requested changes

2019-04-04 08:41 UTC, ysv commented on app/api/v2/management/operations.rb
> +            optional :reference_type,
@ymasiuk add same params to assets, revenues and expenses

2019-04-04 11:02 UTC, ymasiuk commented on app/api/v2/management/operations.rb
> +            optional :reference_type,
@ysv done

2019-04-04 15:14 UTC, ysv requested changes

2019-04-04 15:14 UTC, ysv commented on app/api/v2/management/operations.rb
> +            optional :reference_type,
@ymasiuk what about time_from & time_to ?

2019-04-11 21:54 UTC, ysv approved these changes

2019-04-16 14:48 UTC, merged