Add wallets_history
openware/peatio pull request #2142
Opened 2019-03-27 16:27 UTC by maryna25

2019-03-27 19:54 UTC, calj commented on db/schema.rb
> +    t.integer  "liability_id", limit: 4,                             null: false
I think it's good to keep track of the liability_id.
I would store all information we need here to simplify queries as much as possible:
- operation_type
- debit
- credit

2019-03-27 19:57 UTC, calj commented on db/schema.rb
> +  add_index "wallets_history", ["liability_id"], name: "index_wallets_history_on_liability_id", using: :btree
I don't think this index will be useful.
You can add an index on created_at.

2019-03-27 22:32 UTC, ysv requested changes

2019-03-27 22:32 UTC, ysv commented on app/models/wallet_history.rb
> +class WalletHistory < ActiveRecord::Base
For me this model name is wrong 
Wallet is owned by platform not by user and this history doesn't relate to wallet at all

Better names are **Operations::History** / LiabilityHistory / AccountHistory

2019-03-27 22:32 UTC, ysv commented on app/models/wallet_history.rb
> +# Table name: wallets_history
This model doesn't looks like a mix of Deposit/Withdraw/Order/Trade 
As for me it's better to keep reference which is Deposit/Withdraw/Order/Trade so don't duplicate data

2019-03-27 22:32 UTC, ysv commented on app/workers/worker/pusher_wallet_history.rb
> +  class PusherWalletHistory
- [ ] We don't use pusher since 1.8 so better to name it right

- [ ] We put only amqp workers here and other are kept in lib/daemons

2019-03-27 22:32 UTC, ysv commented on app/workers/worker/pusher_wallet_history.rb
> +        .each do |l|
use `find_each` here

2019-03-27 22:32 UTC, ysv commented on app/workers/worker/pusher_wallet_history.rb
> +            market_id: ref.try(:market_id),
too many `try` looks nasty

2019-03-27 22:32 UTC, ysv commented on app/workers/worker/pusher_wallet_history.rb
> +          fee = ref.try(:fee) || Operations::Revenue.where(reference_id: ref.id, reference_type: l.reference_type, member_id: l.member_id).map(&:credit).sum
```Operations::Revenue.where(reference_id: ref.id, reference_type: l.reference_type, member_id: l.member_id). sum(:credit)```

2019-03-27 22:32 UTC, ysv commented on app/workers/worker/pusher_wallet_history.rb
> +          WalletHistory.create(
Use strict `create!`

2019-03-28 08:08 UTC, maryna25 commented on app/models/wallet_history.rb
> +# Table name: wallets_history
we created this table to simplify the query to get all needed info about deposit/withdraw/trade from liabilities table. So adding reference will not do the job

2019-03-29 07:31 UTC, calj commented on app/api/v2/account/history.rb
> +          history.limit!(params[:limit]) if params[:limit]
we would need to make it support pagination here, following the same approach as other api endpoint.

2019-03-29 07:33 UTC, calj commented on app/services/liability_history_service.rb
> +            balance: Operations::Liability.where(member_id: l.member_id).sum('credit-debit')
This give the current balance, not the balance after this operation.

2019-03-29 07:40 UTC, calj commented on db/migrate/20190327141643_create_liabilities_history.rb
> +class CreateLiabilitiesHistory < ActiveRecord::Migration
Where do we create index ?
We can test several approaches, I'm thinking that [member_id, operation_date] can be the most useful one.

2019-03-30 20:41 UTC, calj commented on app/services/liability_history_service.rb
> +            balance: Operations::Liability.where('member_id = ? AND id <= ?', l.member_id, l.id).sum('credit-debit')
filtering by liabilities id is no correct here, we need to select the full history for the user for the currency.

2019-03-30 20:48 UTC, calj commented on app/services/liability_history_service.rb
> +        .where("liabilities.reference_type IN ('Deposit', 'Withdraw', 'Trade') AND liabilities_history.id IS NULL")
how do we manage the problem of operation state that can change ?

2019-04-01 10:16 UTC, maryna25 commented on app/services/liability_history_service.rb
> +        .where("liabilities.reference_type IN ('Deposit', 'Withdraw', 'Trade') AND liabilities_history.id IS NULL")
we join operations that have another state than in liabilities_history for this operation. And update state in liabilities_history to aasm_state in operation

2019-04-09 15:25 UTC, mnaichuk requested changes

2019-04-09 15:25 UTC, mnaichuk commented on app/models/deposit.rb
> +        revenue_id: revenue.id
Use revenue&.id to avoid `nil` error

2019-04-09 15:25 UTC, mnaichuk commented on app/models/withdraw.rb
> +        revenue_id: revenue.id
Use revenue&.id to avoid nil error

2019-04-11 08:43 UTC, mnaichuk commented on app/api/v2/account/history.rb
> +          optional :start_date,
I think we need unify time format and name for columns for all API calls like in 
https://github.com/rubykube/peatio/blob/1cd37aa600c3137aa75d019d66f476f2225a99b8/app/api/v2/market/named_params.rb#L57

2019-04-11 08:43 UTC, mnaichuk commented on app/api/v2/account/history.rb
> +          optional :end_date,
https://github.com/rubykube/peatio/blob/1cd37aa600c3137aa75d019d66f476f2225a99b8/app/api/v2/market/named_params.rb#L57

2019-04-11 08:44 UTC, mnaichuk commented on app/api/v2/account/history.rb
> +          optional :limit,
Do we need default value?

2019-04-11 08:45 UTC, mnaichuk commented on app/api/v2/account/history.rb
> +          optional :order,
lets use `order_by`

2019-04-11 08:53 UTC, mnaichuk requested changes

2019-04-11 08:53 UTC, mnaichuk commented on app/api/v2/account/history.rb
> +                   values: { value: ['asc', 'desc'], message: 'account.history.order_invalid' },
```suggestion
                   values: { value: %w(asc desc), message: 'account.history.order_invalid' },
```

2019-04-11 08:53 UTC, mnaichuk commented on app/api/v2/account/history.rb
> +            .tap { |q| q.where!('operation_date BETWEEN ? AND ?', Date.parse(params[:start_date]), Date.parse(params[:end_date]) + 1.day) if params[:start_date] && params[:end_date] }
+1 day?

2019-04-11 08:53 UTC, mnaichuk commented on app/models/liability_history.rb
> +    if self.operation_type == 'Deposit'
no need `self`

2019-04-11 21:48 UTC, ysv requested changes

2019-04-11 21:48 UTC, ysv commented on app/api/v2/account/history.rb
> +            .tap { |q| q.where!('operation_date BETWEEN ? AND ?', Time.at(params[:time_from]), Time.at(params[:time_to])) if params[:time_from] && params[:time_to] }
as for me it's better to split this into 2 different `where` statements because:
- how this will work in case of single param passed
- if we want to filter only by time_to/time_from

2019-04-11 21:48 UTC, ysv commented on app/api/v2/account/history.rb
> +          optional :limit,
add default value to limit

2019-04-11 21:48 UTC, ysv commented on app/api/v2/account/history.rb
> +          history = paginate(history) if params[:limit]
we can't skip pagination in case there is no limit param
pagination is always required in this API because table is going to become huge

so alway call paginate

Make it similar to this one https://github.com/rubykube/peatio/blob/master/app/api/v2/account/deposits.rb#L42

2019-04-11 21:48 UTC, ysv commented on app/api/v2/entities/liability_history.rb
> +            desc: 'Operation fee.'
Currency which was used for paying operation fees

2019-04-11 21:48 UTC, ysv commented on app/models/operations/liability.rb
> +#  revenue_id     :integer
put it after member_id

2019-04-11 21:48 UTC, ysv commented on db/migrate/20190409143059_add_tx_height_to_liabilities_history.rb
> +    add_column :liabilities_history, :tx_height, :integer
add this to https://github.com/rubykube/peatio/pull/2142/files#diff-42d33821733f2ad03bcc19b387b890a2 lets avoid +1 migration

2019-04-11 21:48 UTC, ysv commented on app/api/v2/entities/liability_history.rb
> +            (operation.credit - operation.debit).abs
why do we expose `(credit - debit).abs` ?
this will cause that +5 & -5 operation will have the same amount
am I wrong ?

2019-04-11 21:48 UTC, ysv commented on app/api/v2/account/history.rb
> +          reference_types = params[:filter] ? params[:filter].split('+') : %w(trade deposit withdraw)
add default value to filter param so we don't need this line

2019-04-11 21:48 UTC, ysv commented on app/api/v2/account/history.rb
> +                   values: { value: ['trade', 'deposit+withdraw'], message: 'account.history.filter_invalid'},
is it the best solution to combine array elements with '+'

2019-04-11 21:48 UTC, ysv commented on app/api/v2/account/history.rb
> +          order           = params[:order_by] || 'desc'
add default values for sort and order_by params instead of params[:sort] || ...

2019-04-11 21:48 UTC, ysv commented on app/models/liability_history.rb
> +    if operation_type == 'Deposit'
Probably you can simplify
```
if operation_type.in?('Deposit', 'Withdraw') && operation.coin?
  operation.confirmations
end
```

2019-04-11 21:53 UTC, ysv commented on app/api/v2/entities/liability_history.rb
> +          :operation_type,
lets downcase operation type

2019-04-12 08:26 UTC, maryna25 commented on app/api/v2/account/history.rb
> +          optional :limit,
in our case we want to show all operations without any limit

2019-04-12 08:27 UTC, maryna25 commented on app/api/v2/account/history.rb
> +          history = paginate(history) if params[:limit]
in our case we don't need pagination
we want to show all operations 
at least for now

2019-04-12 08:29 UTC, maryna25 commented on app/models/liability_history.rb
> +    if operation_type == 'Deposit'
and how can we get operation in this way?

2019-04-12 08:36 UTC, maryna25 commented on app/api/v2/entities/liability_history.rb
> +            (operation.credit - operation.debit).abs
yes
is it wrong?
when you create Withdraw or Deposit you don't create negative amount. The same is here, no?

2019-04-12 08:36 UTC, maryna25 commented on app/api/v2/account/history.rb
> +                   values: { value: ['trade', 'deposit+withdraw'], message: 'account.history.filter_invalid'},
yes :)

2019-05-06 10:11 UTC, ysv commented
This story needs architecture improvements

2019-05-06 10:11 UTC, closed without merging