Add note to withdraw
openware/peatio pull request #2157
Opened 2019-04-02 13:31 UTC by maryna25

2019-04-02 13:38 UTC, ysv requested changes

2019-04-02 13:38 UTC, ysv commented on app/api/v2/account/withdraws.rb
> +          optional :note,
add validation to note length

2019-04-02 13:38 UTC, ysv commented on app/api/v2/account/withdraws.rb
>            present withdraw, with: API::V2::Entities::Withdraw
add note to `API::V2::Entities::Withdraw`

2019-04-02 13:38 UTC, ysv commented on app/models/withdraws/coin.rb
> +#  note         :string(20)
Why is it 20 chars max ?

2019-04-02 13:38 UTC, ysv commented on spec/api/v2/account/withdraws_spec.rb
> +      it 'creates new withdraw with note' do
add spec for response body

2019-04-02 15:39 UTC, ysv requested changes

2019-04-02 15:39 UTC, ysv commented on app/api/v2/account/withdraws.rb
> +                   values: { value: ->(v) { v.size <= 20 }, message: 'account.withdraw.too_long_note' },
size can be 20
```
v.size < 20
```

2019-04-02 15:39 UTC, ysv commented on app/models/withdraw.rb
> +#  note         :string(20)
put maximum length 256

2019-04-02 15:39 UTC, ysv commented on app/models/withdraw.rb
> +#  note         :string(20)
@maryna25 put 256 max note size same as [Bitgo](https://www.bitgo.com/api/v2/#operation/v2.wallet.tx.build) does

2019-04-02 15:40 UTC, ysv requested changes

2019-04-02 15:40 UTC, ysv commented on app/models/withdraw.rb
> +  validates :note, length: { maximum: 20 }, allow_blank: true
I think it's validated automatically by `validates_lengths_from_database` gem

2019-04-03 12:42 UTC, ysv commented on app/models/withdraw.rb
> +#  note         :string(256)
Single thing is missing is spec for long note in models

2019-04-03 12:43 UTC, ysv commented on app/api/v2/account/withdraws.rb
> +                   desc: 'Withdraw note.'
put something like this in desc
'Optional metadata to be applied to the transaction. Typically used to 'tag' transactions with memorable comments.'

2019-04-03 13:46 UTC, ysv approved these changes

2019-04-03 22:59 UTC, mod approved these changes

2019-04-03 23:00 UTC, merged