Add management API endpoint for trades
openware/peatio pull request #2182
Opened 2019-04-24 22:00 UTC by ymasiuk

2019-04-25 09:27 UTC, ysv requested changes

2019-04-25 09:27 UTC, ysv commented on app/api/v2/management/entities/trade.rb
> +        class Trade < Base
I suggest to return all Trade columns
And if you don't need something filter in applogic side

2019-04-25 09:29 UTC, ysv commented
@ymasiuk squash commits with the next title
`Add management API endpoint for listing trades`

2019-04-26 12:02 UTC, ymasiuk commented
@ysv updated

2019-04-26 13:23 UTC, ysv requested changes

2019-04-26 13:23 UTC, ysv commented on app/api/v2/management/trades.rb
> +            .tap { |q| present q, with: API::V2::Management::Entities::Trade }
add joins with members for avoiding n+1

2019-04-26 13:51 UTC, ysv commented on app/api/v2/management/trades.rb
> +            .tap { |q| present q, with: API::V2::Management::Entities::Trade }
```ruby
          Trade
            .order(id: :desc)
            .includes(:ask_member, :bid_member)
            .tap { |q| q.where!(market: market) if market }
            .tap { |q| q.where!("ask_member_id = #{member.id} OR bid_member_id = #{member.id}") if member }
            .page(params[:page])
            .per(params[:limit])
            .tap { |q| present q, with: API::V2::Management::Entities::Trade }
```

2019-04-26 13:59 UTC, ysv approved these changes

2019-05-14 08:50 UTC, mod approved these changes

2019-05-14 08:50 UTC, merged