Add deposits and withdraws history to one API endpoint
openware/peatio pull request #2207
Opened 2019-05-09 13:33 UTC by ymasiuk

2019-05-09 14:56 UTC, mnaichuk requested changes

2019-05-09 14:56 UTC, mnaichuk commented on app/api/v2/account/history.rb
> +                    type: { value: Integer, message: 'account.history.non_integer_time_from' },
add
allow_blank: { value: false, message: 'account.history.empty_time_from' },

2019-05-09 14:56 UTC, mnaichuk commented on app/api/v2/account/history.rb
> +                    type: { value: Integer, message: 'account.history.non_integer_time_to' },
allow_blank: { value: false, message: 'market.trade.empty_time_to' },

2019-05-09 14:56 UTC, mnaichuk commented on app/api/v2/account/history.rb
> +           optional :page,
rewrite :page and :limit like in https://github.com/rubykube/peatio/blob/e9ccb2abedd1a018cd2aae02bf601531fe4b0b2d/app/api/v2/market/named_params.rb#L47

2019-05-09 14:56 UTC, mnaichuk commented on app/api/v2/account/history.rb
> +            .tap { |q| q.delete_if { |t| t['currency_id'] != params[:currency] } if params[:currency] }
please use 'select' or 'reject', cause delete_if change collection.
and you can avoid using `tap`
.select { ... }
.select { ... }
.tap {  |q| present paginate(q)  }

2019-05-14 18:25 UTC, ysv requested changes
The main idea is described here
https://gist.github.com/ysv/6c4444c4a76db1a8068be8bae4e459da

2019-07-16 09:07 UTC, calj commented on config/database.yml
> +  database: peatio_production
I don't think you want to commit that :sweat_smile:

2019-07-19 14:56 UTC, ysv requested changes

2019-07-19 14:56 UTC, ysv commented on app/api/v2/account/history.rb
> +          sql = "SELECT currency_id, amount, fee, address, aasm_state, NULL AS note, txid, updated_at, type FROM deposits WHERE member_id=#{current_user.id} \
Looks like ORDER BY is applied only to second SELECT
Could you prepare spec for this scenario

2019-07-19 14:58 UTC, mod commented
SELECT FROM (SELECT UNION SELECT) order by q1.updated_at DESC

2019-10-18 08:53 UTC, ysv approved these changes

2019-10-18 08:57 UTC, ysv commented
@ymasiuk we need the same for master

2019-10-31 11:15 UTC, mnaichuk approved these changes

2019-11-11 15:11 UTC, pkucherenk0 commented
This pr is working, but I would add filter:

by type: Deposit/Withdraw
by state: accepted/succeed/processing/...
Might deprecate api account/deposits, account/withdraws eventually.

Have similar feature/bug to mentioned above api endpoints.
If some currency is visible:false we will be able to see it in the transaction history without filters, but when we will add filter by this currency we will see an error account.transactions.currency_doesnt_exist

2019-11-11 15:12 UTC, pkucherenk0 commented
Filtering by currency returned ``` "errors": [
        "server.internal_error"
    ]```

2019-11-12 17:20 UTC, merged