Add ranger call for market order execute event
openware/peatio pull request #2208
Opened 2019-05-09 15:16 UTC by mnaichuk

2019-05-22 16:37 UTC, ysv requested changes

2019-05-22 16:37 UTC, ysv commented on app/models/order.rb
> +      price:            order_price&.to_s('F'),
return both price and avg_price

2019-06-24 10:18 UTC, ysv approved these changes

2019-06-24 10:36 UTC, ysv requested changes

2019-06-24 10:36 UTC, ysv commented on app/models/order.rb
>        id:               id,
I suggest to send event compatible with old WS event and REST API too
So we keep kind and at but also add REST API fields

2019-06-24 12:37 UTC, ysv approved these changes

2019-06-26 15:22 UTC, mod approved these changes

2019-06-26 15:23 UTC, merged