Add missing messages for third party trading engine integration
openware/peatio pull request #2215
Opened 2019-05-21 16:42 UTC by ysv

2019-05-24 13:45 UTC, denisfd commented on app/models/order.rb
> +      volume:    volume,
Would be great to get `uid` in order payload.

2019-05-28 11:06 UTC, denisfd commented on lib/daemons/account.rb
> +      "Liabilities number didn't change since last update",
It produces a lot of "empty" logs, hard to read

2019-05-28 12:11 UTC, dnfd requested changes

2019-05-28 12:11 UTC, denisfd commented on lib/daemons/account.rb
> +                                                member_id: legacy_account.member_id)
`currency: currency.id,`

2019-05-28 12:11 UTC, denisfd commented on lib/daemons/account.rb
> +                                               member_id: legacy_account.member_id)
`currency: currency.id,`

2019-05-29 11:44 UTC, denisfd commented on app/models/order.rb
> +      volume:     volume,
Add origin_volume, please :)

2019-05-29 13:04 UTC, ysv commented
account.rb SQL query example
```
Operations::Account Load (0.6ms)  SELECT  `operations_accounts`.* FROM `operations_accounts` WHERE `operations_accounts`.`type` = 'liability' AND `operations_accounts`.`kind` = 'main' AND `operations_accounts`.`currency_type` = 'fiat' LIMIT 1
  ↳ lib/daemons/account.rb:36
  Operations::Account Load (0.4ms)  SELECT  `operations_accounts`.* FROM `operations_accounts` WHERE `operations_accounts`.`type` = 'liability' AND `operations_accounts`.`kind` = 'locked' AND `operations_accounts`.`currency_type` = 'fiat' LIMIT 1
  ↳ lib/daemons/account.rb:42
  Account Load (0.3ms)  SELECT  `accounts`.* FROM `accounts` WHERE `accounts`.`currency_id` = 'usd' ORDER BY `accounts`.`id` ASC LIMIT 1000
  ↳ lib/daemons/account.rb:48
   (0.2ms)  BEGIN
  ↳ lib/daemons/account.rb:49
   (0.3ms)  SELECT SUM(credit - debit) FROM `liabilities` WHERE `liabilities`.`code` = 201 AND `liabilities`.`member_id` = 1 AND `liabilities`.`currency_id` = 'usd'
  ↳ lib/daemons/account.rb:54
   (0.3ms)  SELECT SUM(credit - debit) FROM `liabilities` WHERE `liabilities`.`code` = 211 AND `liabilities`.`member_id` = 1 AND `liabilities`.`currency_id` = 'usd'
  ↳ lib/daemons/account.rb:59
   (0.2ms)  COMMIT
```

2019-05-30 12:36 UTC, merged