Initailize RBAC logic
openware/peatio pull request #2217
Opened 2019-05-27 13:32 UTC by mnaichuk

2019-05-30 10:47 UTC, mnaichuk commented on app/models/abilities/accountant_ability.rb
> +  class AccountantAbility
lets rename this classes to simple Admin, Accountant and etc..

2019-05-30 10:47 UTC, mnaichuk commented on app/models/abilities/superadmin_ability.rb
> +end
add empty line

2019-05-30 10:48 UTC, mnaichuk commented
Add specs for each role please

2019-05-31 10:48 UTC, ysv commented
We need to commit table with user roles and permissions either in md or directly inside `module Abilities`

2019-05-31 14:52 UTC, mnaichuk reviewed
Add can? for members view

2019-05-31 14:52 UTC, mnaichuk commented on app/views/admin/deposits/fiats/index.html.erb
> +      <% if can? :write, Deposit %>
can? :manage

2019-06-03 11:25 UTC, mnaichuk reviewed
also check ./app/views/shared/admin

2019-06-03 11:25 UTC, mnaichuk commented on app/views/admin/deposits/fiats/new.html.erb
> +  <% if can? :write, Deposit %>
:manage

2019-06-03 12:22 UTC, ysv requested changes

2019-06-03 12:22 UTC, ysv commented on spec/spec_helper.rb
> +require "cancan/matchers"
use single quotes here

2019-06-03 12:22 UTC, ysv commented on app/models/abilities.rb
> +module Abilities
Add comment that full list of roles abilities could be found on docs/roles.md

2019-06-03 12:34 UTC, ysv approved these changes

2019-06-04 13:18 UTC, pkucherenk0 commented
As far as i know we already have member with role broker and trades on barong, same permissions as a member. This members just a preparation for upcoming possibility's, but we should add them anyway.

2019-06-07 04:04 UTC, ysv approved these changes

2019-06-13 12:36 UTC, mod requested changes

2019-06-13 12:36 UTC, mod commented on app/models/abilities/support.rb
> +      can :read, Operations::Account
Support cannot see low level accounting

2019-06-13 12:36 UTC, mod commented on app/models/abilities/support.rb
> +      can :read, PaymentAddress
Dont show this one

2019-06-13 12:36 UTC, mod commented on app/models/abilities/technical.rb
> +      can :manage, Wallet
can :read, Member
      can :read, Deposit
      can :read, Withdraw
      can :read, Account
      can :read, PaymentAddress

2019-06-13 12:36 UTC, mod commented on app/models/abilities/accountant.rb
> +      can :read, Operations::Revenue
create deposit but not accept

2019-06-13 13:56 UTC, merged