Add admin API module
openware/peatio pull request #2226
Opened 2019-06-06 08:20 UTC by chumaknadya

2019-06-07 05:34 UTC, ysv commented
@chumaknadya I advice to use https://github.com/activerecord-hackery/ransack for this.
There are 2 possible ways to use integrate it into our API's:
## 1. We request frontend to send params in ransack format and then we just use #ransack method:
```ruby
params = 
{ ord_type_eq: :limit,
  state_not_eq: :pending,
  price_gteq: 10,
  volume_lt: 0.01,
  side_in: [:bid, :ask]}

Order.ransack(params)
```

Here is the full list of search params https://github.com/activerecord-hackery/ransack#search-matchers
Also there are many examples in ransack specs:
 - spec/ransack/adapters/active_record/base_spec.rb
- spec/ransack/search_spec.rb

NOTE: Custom scopes could be added by ActiveRecord::Base#scope E.g. UID 

```ruby
class Order
...
scope :member_uid_eq, lambda { |uid| where(member_id: Member.find_by(uid: uid)) }
```
More examples spec/support/schema.rb

**Also you could use 2 method for some params which are not convenient for FE**

## 2. Frontend sends parameters in convenient for them format and we build ransack format from them.

```ruby
params = {
  ord_type: :limit,
  state: :pending,
  created_at_from: '1559885173',
  updated_at_from: '1559885173',
  updated_at_to: '1559885173',
}

ransack_params = {
  ord_type_eq: params[:ord_type],
  state_eq_not_eq: params[:state],
  '1' => {
      a: ['created_at_from', 'updated_at_from'],
      p: 'greater', v: [params[:created_at_from], params[:create_at_to]], m: 'or' },
}

Order.ransack(ransack_params)
```

2019-06-24 08:37 UTC, mnaichuk requested changes

2019-06-24 08:37 UTC, mnaichuk commented on app/api/v2/admin/blockchain_params.rb
> +                   type: { value: String, message: 'admin.blockchain.non_string_key'},
no need error message for String type

2019-06-24 08:37 UTC, mnaichuk commented on app/api/v2/admin/blockchain_params.rb
> +                   type: { value: String, message: 'admin.blockchain.non_string_name'},
please check everywhere String type

2019-06-24 08:37 UTC, mnaichuk commented on app/api/v2/admin/blockchain_params.rb
> +                   values: { value: -> (p){ p > 0 }, message: 'admin.blockchain.invalid_min_confirmations' },
p.try(:positive?)

2019-06-24 08:37 UTC, mnaichuk commented on app/api/v2/admin/blockchain_params.rb
> +                   values: { value: -> (p){ p > 0 }, message: 'admin.blockchain.invalid_min_confirmations' },
admin.blockchain.non_positive_min_confirmations

2019-06-24 08:37 UTC, mnaichuk commented on app/api/v2/admin/blockchain_params.rb
> +          optional :step,
same as in min_confirmations

2019-06-24 08:37 UTC, mnaichuk commented on app/api/v2/admin/blockchains.rb
> +        desc 'Creates new blockchain.' do
Create

2019-06-24 08:37 UTC, mnaichuk commented on app/api/v2/admin/currency_params.rb
> +                   values: { value: %w(coin fiat), message: 'admin.currency.invalid_type' },
::Currency.types

2019-06-24 08:37 UTC, mnaichuk commented on spec/api/v2/admin/markets_spec.rb
> +    it 'validate usk_unit param' do
ask_unit

2019-07-01 09:29 UTC, merged