Update lost db connection behavior in daemons
openware/peatio pull request #2231
Opened 2019-06-14 14:38 UTC by mnaichuk

2019-07-04 16:16 UTC, ysv requested changes

2019-07-04 16:16 UTC, ysv commented on app/workers/amqp/deposit_coin_address.rb
> +        raise e
1. put comment why you reraise this error 
2. Move `# Don't re-enqueue this` before second rescue
3. Add TODO for fix of address generation loop

2019-07-04 16:16 UTC, ysv commented on app/workers/amqp/deposit_coin_address.rb
> +            Rails.logger.warn { "Payment address was created for #{acc.currency_id.upcase} account with id #{acc.id}" }
Define AMQP::Base class and put here:
1. logger
2. abstract process method
3. Constant which defines exceptions which should be reraised

2019-07-04 16:16 UTC, ysv commented on app/workers/amqp/deposit_coin_address.rb
> +      rescue Mysql2::Error, ActiveRecord::StatementInvalid => e
rewrite with single rescue

2019-07-04 16:16 UTC, ysv commented on app/workers/daemons/slave_book.rb
> +        Rails.logger.debug { "SlaveBook (#{market_id}) updated" }
update logging to more strict level with better message

2019-07-04 16:16 UTC, ysv commented on lib/daemons/amqp_daemon.rb
> +        retries < 5 ? retry : report_exception(e)
Don't use  ternary operator here

2019-07-04 16:16 UTC, ysv commented on spec/workers/slave_book_spec.rb
> -describe Workers::AMQP::SlaveBook do
move to appropriate directory

2019-07-09 16:12 UTC, ysv requested changes
1. Fix indentation everywhere
2. Rename PR title
3. Add log for re-raising DB errors
4. Add patch description

2019-07-09 16:12 UTC, ysv commented on app/workers/amqp/base.rb
> +      DB_EXCEPTIONS = [Mysql2::Error, ActiveRecord::StatementInvalid]
Rename this constant and add a comment

2019-07-09 16:12 UTC, ysv commented on app/workers/amqp/deposit_coin_address.rb
> +        raise e if DB_EXCEPTIONS.any? { |exception| e.is_a?(exception) }
add comment why do we reraise it and log error

2019-07-09 16:12 UTC, ysv commented on app/workers/amqp/deposit_collection.rb
> +        logger.info  deposit_id: payload['id'],
remove Time.now

2019-07-09 16:12 UTC, ysv commented on app/workers/amqp/deposit_collection.rb
> +        logger.info  deposit_id: payload['id'],
deposit.id

2019-07-09 16:12 UTC, ysv commented on app/workers/amqp/deposit_collection.rb
> +          raise e if DB_EXCEPTIONS.any? { |exception| e.is_a?(exception) }
add comment

2019-07-09 16:12 UTC, ysv commented on app/workers/daemons/base.rb
> +            raise e if DB_EXCEPTIONS.any? { |exception| e.is_a?(exception) } || RABBIT_MQ_EXCEPTIONS.any? { |exception| e.is_a?(exception) }
DB_EXCEPTIONS + RABBIT_MQ_EXCEPTIONS

2019-07-09 16:12 UTC, ysv commented on lib/daemons/amqp_daemon.rb
> +require 'pry-byebug'
remove

2019-07-09 16:12 UTC, ysv commented on lib/daemons/daemons.rb
> +    begin
```ruby
def retry_rmq
  begin
    retries ||= 0
    Bunny.run(AMQPConfig.connect) { |c| c.connected? }
  rescue Bunny::TCPConnectionFailedForAllHosts => e
    sleep_time = ((retries += 1)**1.5).round
    Rails.logger.warn { "#{retries} retry. Waiting for connection #{sleep_time} seconds..." }
    sleep sleep_time
    retry if retries < 5
    report_exception(e)
    raise e
  else
    Rails.logger.warn { 'Connection established' }
    retries = 0
  end
end

begin
  worker.run
rescue StandardError => e
  if e.is_a?(Bunny::TCPConnectionFailedForAllHosts) || e.is_a?(Bunny::ConnectionClosedError)
    Rails.logger.warn { 'Try recconecting to rabbitmq.' }
    retry_rmq
    retry
  end
end
```

2019-07-12 10:07 UTC, ysv requested changes

2019-07-12 10:07 UTC, ysv commented on app/workers/amqp/base.rb
> +      def process
I think this method always has payload `parameter`
For making interface clear

2019-07-12 10:07 UTC, ysv commented on app/workers/amqp/base.rb
> +      def process
If it doesn't because I saw some daemon with 3 params refactor all of them to single and remove params arity magic from amqp_daemon.rb

2019-07-12 10:07 UTC, ysv commented on app/workers/amqp/deposit_collection_fees.rb
> +          logger.warn id: payload['id'], message: 'The deposit with such id doesn\'t exist.'
deposit_id

2019-07-12 10:07 UTC, ysv commented on app/workers/amqp/deposit_coin_address.rb
> +        # Reraise db connection errors to starting retry logic
Change to:
`Reraise db connection errors to start retry logic.`

Don't forget about dot in the end

2019-07-12 10:07 UTC, ysv commented on lib/daemons/amqp_daemon.rb
> +        terminate.call unless Retry.db
nack before terminating

2019-07-12 10:07 UTC, ysv commented on lib/peatio/retry.rb
> +        next
don't need next

2019-07-12 10:07 UTC, ysv commented on lib/daemons/amqp_daemon.rb
> +      terminate.call unless Retry.db
Add log about daemon killing

2019-07-12 14:18 UTC, mnaichuk commented on app/workers/amqp/deposit_collection_fees.rb
> +          logger.warn id: payload['id'], message: 'The deposit with such id doesn\'t exist.'
unless deposit -_-

2019-07-12 16:50 UTC, mod approved these changes

2019-07-15 11:02 UTC, ysv commented on lib/daemons/amqp_daemon.rb
> +      worker.method(:process).call(JSON.parse(payload))
we could replace with `worker.process(JSON.parse(payload))` for simplicity

2019-07-15 11:02 UTC, ysv commented on lib/peatio/retry.rb
> +class Retry
1. make it module because we never instantiate it
2. May be you have better name in mind

2019-07-15 11:06 UTC, ysv commented
write more details in patch description

2019-07-15 14:29 UTC, ysv approved these changes

2019-08-15 14:02 UTC, closed without merging