Update logs in withdraw_coin worker
openware/peatio pull request #2234
Opened 2019-06-18 12:55 UTC by denisfd

2019-07-03 13:27 UTC, ysv requested changes

2019-07-03 13:27 UTC, ysv commented on app/workers/worker/withdraw_coin.rb
> +      Rails.logger.warn worker: __FILE__, id: payload[:id], message: 'Received request for processing withdraw.'
1. You can initialize logger once with class name and use it e.g:
```ruby
logger = DaemonsLogger.new(self.class.name)

logger.warn id: payload[:id], message: "Something"
```

2. Or we can inherit all AMQP daemons from Base class and define logger method here

I prefer the second way

2019-07-04 15:56 UTC, ysv requested changes

2019-07-04 15:56 UTC, ysv commented on app/workers/amqp/withdraw_coin.rb
> +        rescue StandardError => e
keep `Exceptions` here we will update it in separate patch

2019-07-04 15:56 UTC, ysv commented on lib/peatio/tagged_logger.rb
> +        msg = "#{@tags.map { |k, v| "#{k}: #{v}" }.join(', ')}. #{msg}"
@denisfd if it's a string use 
```@tags.merge(message: msg)```

2019-07-05 10:04 UTC, mnaichuk approved these changes

2019-07-05 13:35 UTC, ysv approved these changes

2019-07-05 17:10 UTC, mod approved these changes

2019-07-05 17:10 UTC, mod commented on app/workers/worker/withdraw_coin.rb
> +                            max_balance: wallet.max_balance.to_s,
remove

2019-07-05 17:10 UTC, merged