Improve sentry-raven error reporting
openware/peatio pull request #2236
Opened 2019-06-19 10:18 UTC by mnaichuk

2019-06-21 11:04 UTC, mnaichuk commented on app/api/v2/exception_handlers.rb
> +          Raven.capture_exception(e) if defined?(Raven)
we can delete it

2019-07-03 13:11 UTC, ysv requested changes

2019-07-03 13:11 UTC, ysv commented on app/controllers/application_controller.rb
> +  before_action :raven_context
I would prefer
```
before_action :raven_context, if: -> { defined?(Raven) }
```

2019-07-03 13:11 UTC, ysv commented on app/api/v2/auth/jwt_authenticator.rb
> +          raven_context(current_user) if defined?(Raven)
@mnaichuk I would prefer to separate this method from authenticate
Usage:
```ruby
before { authenticate! }
before { set_raven_context! } # find better name
```

2019-07-04 15:45 UTC, ysv requested changes

2019-07-04 15:45 UTC, ysv commented on app/api/v2/public/mount.rb
> +        before { set_ets_context! }
Use another ets_context for public and management API

2019-07-04 15:45 UTC, ysv commented on app/api/v2/helpers.rb
> +          Peatio_Version: Peatio::Application::VERSION
rename to `peatio_version`

2019-07-05 13:33 UTC, ysv requested changes

2019-07-05 13:33 UTC, ysv commented on app/controllers/application_controller.rb
> +  before_action :set_raven_context!, if: -> { defined?(Raven) }
you use `set_raven_context` but method name is `set_ets_context`

2019-07-05 13:34 UTC, ysv commented on app/controllers/application_controller.rb
> +      Peatio_Version: Peatio::Application::VERSION
`peatio_version`

2019-07-05 17:09 UTC, mod approved these changes

2019-07-05 17:09 UTC, merged