Update market model precision & price columns
openware/peatio pull request #2241
Opened 2019-06-24 14:25 UTC by ysv

2019-06-25 14:18 UTC, mnaichuk commented on app/models/order.rb
>    def is_limit_order?
maybe we can use `inquiry` here?

2019-06-26 14:58 UTC, mnaichuk requested changes

2019-06-26 14:58 UTC, mnaichuk commented on app/models/market.rb
>    def fix_number_precision(type, d)
rename this method

2019-06-26 14:58 UTC, mnaichuk commented on app/models/order.rb
> +    self.price = config.fix_number_precision(:price, price.to_d) if price
let's delete method `config`

2019-06-26 16:59 UTC, mod requested changes

2019-06-26 16:59 UTC, mod commented on app/models/market.rb
> +  def round(type, d)
Shouldn't we always round to 16 ?

2019-06-26 16:59 UTC, mod commented on app/models/market.rb
> +  def round(type, d)
Better check if value is amount or price or make 2 methods it may be faster

2019-06-27 06:47 UTC, ysv commented on app/models/market.rb
> +  def round(type, d)
No we can't round to 16 because then price & amount precision doesn't make sense and also if we multiply two 16 rounded values we could get 32 precision

Regarding 2 separate methods I agree

2019-06-27 13:32 UTC, mnaichuk approved these changes

2019-06-27 14:39 UTC, mod commented
[ ] rename ask unit, bid unit in base,quote
[ ] Change enabled to "state" accept value hidden, expose in API results with state

2019-06-28 12:08 UTC, ysv commented
@mod I did it in the next way, is it right ?
- enabled: user can see and trade on this market
- disabled: user can see but can't trade
- hidden: admin can see and change config

2019-07-01 13:20 UTC, merged