Reorganization ruby and amqp workers
openware/peatio pull request #2242
Opened 2019-06-25 12:02 UTC by mnaichuk

2019-06-25 13:45 UTC, ysv requested changes
It's better to use Workers as a module name

2019-06-25 13:45 UTC, ysv commented on app/worker/daemons/k.rb
> +    class K < Worker::Daemons::Base
```ruby
class K < Base
```

2019-06-25 13:45 UTC, ysv commented on app/worker/daemons/base.rb
> +            process
I would prefer to put sleep here

2019-06-25 14:01 UTC, ysv requested changes

2019-06-25 14:01 UTC, ysv commented on lib/daemons/daemons.rb
> +  @worker.stop
Initialize worker before it's usage
Don't use instance variable for it '@'

2019-06-27 06:55 UTC, ysv commented on lib/daemons/daemons.rb
> +worker = "Workers::Daemons::#{name.camelize}".constantize.new(running)
remove running from initialization

2019-06-27 07:04 UTC, ysv commented
Don't forget to update god.
Check if any doc need updates I would prefer the next:
1. Rename daemons.md -> workers.md (so we have directory and doc naming convention)
2. Prefix all daemons in daemons.md with `daemon` so we will have something like:
```md
## amqp:deposit_collection

This daemon transfer incoming deposits from deposit wallet to withdraw wallets (hot, warm, cold).

## daemon:withdraw_audit

This daemon validates withdrawals and sends them to amqp:withdraw_coin.
```

2019-07-01 10:54 UTC, ysv approved these changes

2019-07-01 11:31 UTC, mod approved these changes

2019-07-01 11:31 UTC, merged