Refactor blockchain worker
openware/peatio pull request #2257
Opened 2019-07-09 11:20 UTC by shal

2019-07-11 13:33 UTC, ysv requested changes

2019-07-11 13:33 UTC, ysv commented on app/workers/daemons/blockchain.rb
> +
define initializer as first method

2019-07-11 13:33 UTC, ysv commented on app/workers/daemons/blockchain.rb
> +        super
I'm not sure if we still  need to call super here clarify with @mnaichuk please

2019-07-11 13:33 UTC, ysv commented on app/workers/daemons/blockchain.rb
> +        @workers = ::Blockchain.active.map do |bc|
1. Don't start threads in this step do it in process method
2. Also there was ability to start daemon for specific blockchain by listing it in env
3. `@workers` not the best name

2019-07-11 13:33 UTC, ysv commented on app/workers/daemons/blockchain.rb
> +        @workers.map(&:join) unless running
I think we don't need `unless running` here

2019-07-11 13:33 UTC, ysv commented on config/blockchains.yml
> +version: '2'
do we need this file ?

2019-07-11 13:33 UTC, ysv commented on lib/peatio/bitcoin/client.rb
> +        f.adapter :net_http_persistent
1. Is it possible to explicitly define number of persistent connections ?
Or add comment for clarifying what is default value

2. Is it possible to write spec for this ? For being sure that it works in the way we expect

2019-07-11 13:33 UTC, ysv commented on app/workers/daemons/blockchain.rb
> +      def process_blocks(bc)
this method should be named `process` it adds some magic

2019-07-11 13:33 UTC, ysv commented on app/workers/daemons/blockchain.rb
> +            report_exception(e)
I think we need to add some warn log here before sleeping

2019-07-11 13:33 UTC, ysv commented on app/workers/daemons/blockchain.rb
> +              sleep(10)
Write a message in logs that we are sleeping for 10 seconds

2019-07-11 13:58 UTC, mod commented on config/blockchains.yml
> +version: '2'
We do

2019-07-11 14:18 UTC, shal commented on app/workers/daemons/blockchain.rb
> +        super
We need it, because we have to support graceful shutdown, that's why we use `running` variable.

2019-07-11 14:19 UTC, shal commented on app/workers/daemons/blockchain.rb
> +        @workers.map(&:join) unless running
In this way, we won't have ability to gracefully stop blockchain daemon.

2019-07-11 15:10 UTC, shal commented on app/workers/daemons/blockchain.rb
> +        @workers.map(&:join) unless running
We need, as I explained earlier.

2019-07-11 15:10 UTC, shal commented on app/workers/daemons/blockchain.rb
> +
Done.

2019-07-11 15:10 UTC, shal commented on app/workers/daemons/blockchain.rb
> +      def process_blocks(bc)
No, this is different, because we use separate thread for each blockchain. 
Actually process method is not needed at all.

2019-07-11 15:10 UTC, shal commented on app/workers/daemons/blockchain.rb
> +        super
@mnaichuk am I right, that we need to call `super`?

2019-07-11 15:10 UTC, shal commented on lib/peatio/bitcoin/client.rb
> +        f.adapter :net_http_persistent
1. I don't know how to test this kind of stuff, because we stub all calls in the tests.
2. I think code related to gem shouldn't be tested in the peatio, it should be tested in the gem.

2019-07-11 19:45 UTC, calj commented on app/workers/daemons/blockchain.rb
> +          rescue Peatio::Blockchain::ClientError => e
I would rescue StandardError here, to reduce the risk of thread death.

2019-07-11 19:49 UTC, shal commented on app/workers/daemons/blockchain.rb
> +          rescue Peatio::Blockchain::ClientError => e
Agree

2019-07-12 09:46 UTC, ysv reviewed
TODO:

- [x] Rename process to run and process_block to process

- [x] Rename config/blockchains.yml -> e.g config/cryptonodes.yml

- [x] Still I'm not sure if we need `unless running` before joining threads

- [x] Add spec for Headers added by net_http_persistent

- [ ] Add spec that faraday returns the same connection instead of initializing new one

- [x] Try to inspect gem for vulnerabilities for being sure

2019-07-12 12:32 UTC, mod approved these changes

2019-07-12 12:40 UTC, merged