Admin api module for New tower
openware/peatio pull request #2264
Opened 2019-07-14 13:19 UTC by mod

2019-07-30 11:17 UTC, ysv requested changes
- [x] Comment update controllers for deposit and withdrawal for now

- [ ] Add better description in entities
      E.g 
      Currency code is okay because it's obvious one.
      But blockchain_key should be something like: 'Associated blockchain key which will perform transactions synchronization for currency.'
      Or type: 'Currency type defines if currency is fiat or crypto. Possible values are fiat, coin'
      https://idratherbewriting.com/learnapidoc/docapis_doc_parameters.html#examples-of-parameters

- [x] Check parameter names in current API because it's different
       E.g: market bid_fee, ask_fee should be base_currency_fee, quote_currency_fee etc

- [x] Use some convention for **all** parameters desc don't mix please: 'Unique wallet id', 'Trade ID', 'Order id' should be 'Unique wallet identifier in database'

2019-07-30 11:17 UTC, ysv commented on app/api/v2/admin/blockchain_params.rb
> +                   type: String,
Could you add spec with key longer than 255
What error we will get in response ?

2019-07-30 11:17 UTC, ysv commented on app/api/v2/admin/blockchain_params.rb
> +                   type: String,
Could you add validation of blockchain client in model and also here
```
class Blockchain
    validates :client, inclusion: { in: ->(_){ Blockchain.clients.map(&:to_s) } }
...
end
```
and same in controller

2019-07-30 11:17 UTC, ysv commented on app/api/v2/admin/blockchain_params.rb
> +          optional :step,
we will remove it soon so probably don't need here

2019-07-30 11:17 UTC, ysv commented on app/api/v2/admin/blockchains.rb
> +          search = Blockchain.ransack()
could you remove empty parentheses everywhere

2019-07-30 11:17 UTC, ysv commented on app/api/v2/admin/blockchains.rb
> +          if blockchain.update(declared(params, include_missing: false))
save declared_params in variable before and then use it in update

2019-07-30 11:17 UTC, ysv commented on app/api/v2/admin/currency_params.rb
> +          requires :id,
It's better to use code instead of id everywhere
They are equal in usage now

2019-07-30 11:17 UTC, ysv commented on app/api/v2/admin/deposit_params.rb
> +        params :update_deposit_params do
I think for simplicity reason we will leave only get controllers for deposits and withdrawals

2019-07-30 11:17 UTC, ysv commented on app/api/v2/admin/deposits.rb
> +        post '/deposits/update' do
comment it for now

2019-07-30 11:17 UTC, ysv commented on app/api/v2/admin/entities/blockchain.rb
> +          expose(
remove please

2019-07-30 11:17 UTC, ysv commented on app/api/v2/admin/entities/currency.rb
> +            :id,
code

2019-07-30 11:17 UTC, ysv commented on app/api/v2/admin/entities/currency.rb
> +          expose(
we don't have this in currency table anymore

2019-07-30 11:17 UTC, ysv commented on app/api/v2/admin/entities/currency.rb
> +            :explorer_address,
we don't have this in currency table anymore

2019-07-30 11:17 UTC, ysv commented on app/api/v2/admin/wallet_params.rb
> +                   values: { value: -> { ::Blockchain.pluck(:client) }, message: 'admin.wallet.gateway_doesnt_exist' },
`Wallet.gateways`

2019-07-30 11:17 UTC, ysv commented on app/api/v2/admin/withdraw_params.rb
> +          optional :done_at_from,
use either completed_at of done_at in both Withdraw and Deposit
I vote for completed_at

2019-07-30 11:17 UTC, ysv commented on app/api/v2/exception_handlers.rb
> +        rescue_from Grape::Exceptions::MethodNotAllowed do |_e|
why do we need it here ?
may be we need to move it to admin API mount

2019-07-30 11:17 UTC, ysv commented on app/api/v2/helpers.rb
> +        current_user or raise Peatio::Auth::Error
use || instead of or

2019-07-30 11:17 UTC, ysv commented on app/api/v2/helpers.rb
> +        current_user or raise Peatio::Auth::Error
you can also update authenticate

2019-07-30 11:25 UTC, denisfd commented on app/api/v2/exception_handlers.rb
> +        rescue_from Grape::Exceptions::MethodNotAllowed do |_e|
It will prevent 404 Not found error for existing routes but with wrong request methods.

2019-07-30 14:43 UTC, dnfd commented on app/api/v2/admin/blockchains.rb
> +          if blockchain.update(declared(params, include_missing: false))
why? it is used once per method

2019-07-31 12:29 UTC, dnfd commented
> * [ ]  Check parameter names in current API because it's different
>   E.g: market bid_fee, ask_fee should be base_currency_fee, quote_currency_fee etc

parameters are user according to schema
base_currency_fee, quote_currency_fee do not exist in the project

2019-08-05 16:46 UTC, dnfd commented on app/api/v2/admin/members.rb
> +          use :date_picker, keys: %w[updated_at created_at]
additional params (`keys`) are not used anymore

2019-08-09 17:12 UTC, mod commented on app/api/v2/admin/deposits.rb
> +                             .build(type_eq: params[:type].present? ? "Deposits::#{params[:type]}" : nil)
ransack_params = Helpers::RansackBuilder.new(params)
                             .translate(:state => :aasm_state, :uid => :member_uid, :currency => :currency_id)
                             .eq(:id, :txid, :tid, :address, :state, :uid, :currency)
                             .with_pagination.with_daterange
                             .merge({type: params[:type].present? ? "Deposits::#{params[:type]}" : nil})

also why do you rename member_uid into uid, why don't we use directly the correct parameter
also where is pagination and date range ?

2019-08-12 12:02 UTC, ysv reviewed
- [x] Update RansackBuilder
- [ ] Update entities desc (optional)
- [x] Remove commented code in controllers
- [ ] Inspect code for n + 1 
- [x] Entities can inherit only from `API::V2::Entities` otherwise define new entity
- [x] Update params according to next changes https://github.com/rubykube/peatio/commit/283f7dd7c5291b91f46c34cb1b90c9c928438407
- [x] Avoid adding from & to params implicitly as mentioned [here](https://github.com/rubykube/peatio/pull/2264#pullrequestreview-273260429) :
```ruby
@build.merge!("#{@params[:range]}_at_gteq" => Time.at(@params[:from])) if @params[:from]
@build.merge!("#{@params[:range]}_at_lt" => Time.at(@params[:to])) if @params[:to]
```

2019-08-12 12:02 UTC, ysv commented on app/api/v2/admin/currencies.rb
> +          OPTIONAL_CURRENCY_PARAMS = {
Add comment description

2019-08-12 12:02 UTC, ysv commented on app/api/v2/admin/deposits.rb
> +          COIN_ACTIONS = %w(accept collect collect_fee)
remove for now

2019-08-12 12:02 UTC, ysv commented on app/api/v2/admin/deposits.rb
> +                             .build(type_eq: params[:type].present? ? "Deposits::#{params[:type]}" : nil)
It's inside RansackBuilder
I will rewrite it with more obvious usage

2019-08-12 12:02 UTC, ysv commented on app/api/v2/admin/helpers.rb
> +                   values:  { value: -> (v) {Member.find_by(uid: v) }, message: 'admin.user.doesnt_exist' },
use `exists?`

2019-08-12 12:02 UTC, ysv commented on app/api/v2/admin/helpers.rb
> +        params :date_picker do |options|
do we still need options ?

2019-08-12 12:02 UTC, ysv commented on app/api/v2/admin/markets.rb
> +          OPTIONAL_MARKET_PARAMS = {
add comment

2019-08-12 12:02 UTC, ysv commented on app/api/v2/admin/operations.rb
> +          def ransack_params
are we gonna still use it ?

2019-08-12 12:02 UTC, ysv commented on app/api/v2/admin/wallets.rb
> +          OPTIONAL_WALLET_PARAMS = {
add comment desc

2019-08-12 12:02 UTC, ysv commented on app/api/v2/admin/wallets.rb
> +          search = Wallet.ransack
do we need to use ransack if we have only sorting ?
I think we will need filter by currency, blockchain and kind then we can use ransack

2019-08-12 12:02 UTC, ysv commented on app/api/v2/admin/withdraws.rb
> +          COIN_ACTIONS = %w(process load reject)
remove this constants for now

2019-08-12 12:02 UTC, ysv commented on app/api/v2/admin/withdraws.rb
> +        # desc 'Update withdraw.' do
remove

2019-08-12 12:02 UTC, ysv commented on app/api/v2/entities/deposit.rb
> +          as: :blockchain_txid,
Why did we rename it ?

2019-08-12 12:02 UTC, ysv commented on app/api/v2/entities/deposit.rb
> +          as: :done_at,
do we need this renaming ?

2019-08-12 12:02 UTC, ysv commented on app/api/v2/exception_handlers.rb
> +          error!({ errors: 'server.method_not_allowed' }, 405)
add this to errors.md

2019-08-12 12:02 UTC, ysv commented on app/api/v2/helpers.rb
> +        current_user || raise(Peatio::Auth::Error)
I'm not sure we need to raise `Peatio::Auth::Error` here because authorize is called after authenticate so may be we can consider current_user already defined ?

2019-08-12 12:02 UTC, ysv commented on app/models/blockchain.rb
> +  validates :client, inclusion: { in: -> (_) { clients.map(&:to_s) } }
add spec

2019-08-12 12:02 UTC, ysv commented on spec/api/v2/admin/deposits_spec.rb
> +  # describe 'POST /api/v2/admin/deposits/update' do
remove

2019-08-12 12:28 UTC, dnfd commented on app/api/v2/entities/deposit.rb
> +          as: :done_at,
https://github.com/rubykube/peatio/pull/2264/commits/db26229f2458e0a86e109abcbd17695cc24cfec8

2019-08-12 12:30 UTC, dnfd commented on app/api/v2/entities/deposit.rb
> +          as: :blockchain_txid,
https://github.com/rubykube/peatio/pull/2264/commits/db26229f2458e0a86e109abcbd17695cc24cfec8

2019-08-12 12:38 UTC, ysv commented on app/api/v2/entities/deposit.rb
> +          as: :done_at,
Does it rename? It just generates doc isn't it ?

2019-08-12 12:39 UTC, ysv commented on app/api/v2/entities/deposit.rb
> +          as: :blockchain_txid,
Does it rename? It just generates doc isn't it ?

2019-08-12 14:39 UTC, dnfd commented on app/api/v2/entities/deposit.rb
> +          as: :done_at,
Yes, my bad, sorry.

2019-08-12 14:39 UTC, dnfd commented on app/api/v2/entities/deposit.rb
> +          as: :blockchain_txid,
Yes, my bad, sorry.

2019-08-12 16:04 UTC, dnfd commented on app/api/v2/admin/operations.rb
> +          def ransack_params
I think yes, these are shared.

2019-08-12 16:42 UTC, dnfd commented on app/models/blockchain.rb
> +  validates :client, inclusion: { in: -> (_) { clients.map(&:to_s) } }
./spec/api/v2/admin/blockchains_spec.rb:119
./spec/models/blockchain_spec.rb:19

2019-08-19 10:22 UTC, mnaichuk commented
- [ ] Admin can get orders for disabled Market;

- [ ] Should we drop old stuff from Wallet model? `nsig`, `parent` -> @mod, @ysv

2019-08-19 10:35 UTC, pkucherenk0 commented
1. Amin should be able to see orders and trades if the market is disabled.
2. Remove deprecated params from the Wallets (nsig, parent ...)
3. On csv download, I suggest supporting filters or at least limit (downloading 80k of operations killed my pc)

2019-08-19 12:53 UTC, matass commented
+10,567 −49 ..

This is fcking crazy:))))
I suggest to separate admin api and core.

insane.......

2019-08-19 14:51 UTC, ysv approved these changes

2019-08-20 16:28 UTC, merged