Add Test::SupportController which now provides HTTP GET /test/support/members
openware/peatio pull request #227
Opened 2018-01-05 14:20 UTC by yivo

It returns feeded members including email, password, JWT.

2018-01-05 15:46 UTC, mod requested changes
It's not I expected but it open up new topic to discuss about feeders and test environment,
I really would like to have a complete framework for testing.

2018-01-05 15:46 UTC, mod commented on app/controllers/test/support_controller.rb
> +  class SupportController < ActionController::Base
I was thinking to load users in database
and iterate to create their jwt tokens

2018-01-05 15:46 UTC, mod commented on config/routes.rb
> +  namespace :test do
why not just test/members

2018-01-05 15:46 UTC, mod commented on lib/peatio/feeders/admins_feeder.rb
> +      admin.define_singleton_method(:jwt)      { JWT.encode({ email: email }, APIv2::Auth::Utils.jwt_shared_secret_key, 'RS256') }
if we would store our user in db we wouldn't need
what about making a load from controller ?
test/tearup
test/members
test/markets
test/teardown

2018-01-05 15:46 UTC, mod commented on lib/peatio/feeders/member_feeder.rb
> +        aasm_state:         :verified
Would it be possible to actually delete user creation in peatio because it's auth0 or google auth or barong

2018-01-05 15:50 UTC, yivo commented on lib/peatio/feeders/admins_feeder.rb
> +      admin.define_singleton_method(:jwt)      { JWT.encode({ email: email }, APIv2::Auth::Utils.jwt_shared_secret_key, 'RS256') }
@mod We store members in database. https://github.com/rubykube/peatio/blob/master/lib/peatio/feeders/member_feeder.rb#L15

2018-01-05 15:52 UTC, yivo commented on app/controllers/test/support_controller.rb
> +  class SupportController < ActionController::Base
@mod It works exactly so.

2018-01-05 15:52 UTC, yivo commented on config/routes.rb
> +  namespace :test do
@mod Okay.

2018-01-05 15:53 UTC, yivo commented on lib/peatio/feeders/member_feeder.rb
> +        aasm_state:         :verified
@mod Didn't catch this.

2018-01-05 15:55 UTC, yivo commented on lib/peatio/feeders/admins_feeder.rb
> +      admin.define_singleton_method(:jwt)      { JWT.encode({ email: email }, APIv2::Auth::Utils.jwt_shared_secret_key, 'RS256') }
@mod I am not sure what you want to achieve. It now simple generates members, persists them and returns in action. In future we will update it with new structure if it will be required.

2018-01-05 15:57 UTC, yivo commented on lib/peatio/feeders/admins_feeder.rb
> +      admin.define_singleton_method(:jwt)      { JWT.encode({ email: email }, APIv2::Auth::Utils.jwt_shared_secret_key, 'RS256') }
@mod `password` and `jwt` are both required since they are not defined on member. I don't want to add extra unknown attributes to member model. Check here: https://github.com/rubykube/peatio/blob/master/app/models/member.rb

Although I will remove `admin?` since it is defined on `Member` and works the same way by checking `ENV['ADMIN']`.

2018-01-05 16:40 UTC, yivo commented
@mod Could you please check this once again? I have pushed changes.

2018-01-08 21:38 UTC, mod requested changes
I would prefer to load and return user from database, tester might update users and expects changes also we will have many data to feed in this way.

2018-01-09 17:33 UTC, yivo commented
@mod Fixed.

2018-01-09 17:58 UTC, merged