[WIP] Fix double spending issue on withdraw
openware/peatio pull request #2271
Opened 2019-07-18 09:48 UTC by shal

2019-07-19 11:11 UTC, shal commented
- [ ] Working on adding feature to process/fail timed_out withdraw from admin panel.

2019-07-19 15:44 UTC, ysv requested changes

2019-07-19 15:44 UTC, ysv commented on app/models/currency.rb
> +# Schema version: 20190624102330
reset this changes pls

2019-07-19 15:44 UTC, ysv commented on app/models/trigger.rb
> +# Schema version: 20190624102330
reset this changes pls

2019-07-19 15:44 UTC, ysv commented on app/workers/amqp/withdraw_coin.rb
> +        rescue StandardError => e
I'm thinking about other flow here. We have the next 2 types of errors
1. Error in case of which we are sure that withdrawal was not send e.g. Faraday::ResourceNotFound, so we fail it
2. All other errors including SystemStackError and other Exception subclasses in this case we set to :timed_out state (but actually I'm thinking about renaming it)

2019-07-19 15:44 UTC, ysv commented on app/views/admin/withdraws/coins/show.html.erb
> +              <% if @withdraw.timed_out? && @withdraw.may_success? %>
could we add also button for processing withdrawal one more time

2019-07-19 15:44 UTC, ysv commented on lib/peatio/bitcoin/client.rb
> +    def initialize(endpoint, idle_timeout = 1)
It's better to use optional named parameter:
```ruby
def initialize(ednpoint, idle_timeout: 1)
...
end
```

2019-07-19 15:44 UTC, ysv commented on lib/peatio/ethereum/client.rb
> +    def initialize(endpoint, idle_timeout = 1)
It's better to use optional named parameter:
```ruby
def initialize(ednpoint, idle_timeout: 1)
...
end
```

2019-07-19 15:44 UTC, ysv commented on spec/workers/withdraw_coin_spec.rb
> +    it 'doesn\'t retry on timeout error' do
actually we doesn't test that we did not retry withdraw
I think you need to add that `AMQPQueue.enqueue(:withdraw_coin, id: id)` was not called
Something like `AMQPQueue.expects(:enqueue).never`

2019-07-19 15:44 UTC, ysv commented on lib/peatio/bitcoin/client.rb
> +      if e.is_a?(Faraday::TimeoutError)
I think about adding wrapped error into ConnectionError and wrap Faraday error into it

2019-07-19 15:44 UTC, ysv commented on app/models/withdraw.rb
> +    state :timed_out
I think we need to rename this state something like indefinite

2019-07-19 20:07 UTC, shal commented on app/views/admin/withdraws/coins/show.html.erb
> +              <% if @withdraw.timed_out? && @withdraw.may_success? %>
We already have `process` button.

2019-07-19 20:07 UTC, shal commented on app/views/admin/withdraws/coins/show.html.erb
> +              <% if @withdraw.timed_out? && @withdraw.may_success? %>
![image](https://user-images.githubusercontent.com/15674738/61562462-05b52380-aa7a-11e9-8eac-0022b2deb9ff.png)

2019-07-22 12:01 UTC, shal commented on app/models/currency.rb
> +# Schema version: 20190624102330
Done.

2019-07-22 12:01 UTC, shal commented on app/models/trigger.rb
> +# Schema version: 20190624102330
Done.

2019-07-23 20:11 UTC, closed without merging