Add MySQL procedure for liabilities compaction
openware/peatio pull request #2273
Opened 2019-07-19 11:08 UTC by shal

2019-07-19 11:22 UTC, mod reviewed
You are missing jobs table
We don't have a way to verify job run and when
also job_id will be in reference_id of the new compressed `liabilities`
Also table in archive are not temporary

2019-07-19 11:22 UTC, mod commented on db/migrate/20190719103057_add_account_recalculation_procedure.rb
> +        CREATE TEMPORARY TABLE IF NOT EXISTS archive_liabilities AS (SELECT * FROM liabilities);
I changed my mind:
CREATE DATABASE IF NOT EXISTS `peatio_archive`;
CREATE TABLE IF NOT EXISTS peatio_archive.liabilities LIKE `liabilities`;

2019-07-19 11:22 UTC, mod commented on db/migrate/20190719103057_add_account_recalculation_procedure.rb
> +        (
avoid putting (...)
This usually mean a SUB-query, which will create a temporary table, it's a heavy.
In this case I don't know what the SQL engine will do.

2019-07-19 11:22 UTC, mod commented on db/migrate/20190719103057_add_account_recalculation_procedure.rb
> +        UPDATE accounts SET
I didn't knew this syntax, did you run this over 26 Millions records?

2019-07-19 14:47 UTC, mod commented on db/migrate/20190719103057_add_account_recalculation_procedure.rb
> +        UPDATE accounts SET
SELECT code INTO @account_main FROM operations_accounts WHERE type = 'liability' AND kind = 'main'

UPDATE `accounts` JOIN `liabilities` AS `la` ON
 liabilities.member_id = accounts.member_id AND liabilities.currency_id = accounts.currency_id AND liabilities.code
 IN @account_main
SET accounts.balance = IFNULL(SUM(credit) - SUM(debit), 0);

2019-07-22 08:32 UTC, mod commented on db/migrate/20190719103057_create_jobs.rb
> +      t.integer :rows, null: false, default: 0
We should add string :state to track success of the job

2019-07-22 08:33 UTC, mod commented on db/migrate/20190719134706_add_account_recalculation_procedure.rb
> +      DROP DATABASE IF NOT EXISTS peatio_archive;
that isn't going to work, test your ROLLBACK, this syntax doesnt work

2019-07-22 08:37 UTC, mod requested changes

2019-07-22 08:37 UTC, mod commented on db/migrate/20190719134706_add_account_recalculation_procedure.rb
> +      DROP PROCEDURE IF EXISTS compact_and_recalculate;
verify this too

2019-07-22 08:37 UTC, mod commented on db/migrate/20190719134706_add_account_recalculation_procedure.rb
> +        DROP TABLE IF EXISTS peatio_archive.liabilities;
the main purpose of archives is to NOT be deleted
We need a clean create table with an index on (code, currency_id, member_id, debit, credit)

2019-07-22 08:37 UTC, mod commented on db/migrate/20190719134706_add_account_recalculation_procedure.rb
> +        TRUNCATE TABLE liabilities;
space your SQL

2019-07-22 08:37 UTC, mod commented on db/migrate/20190719134706_add_account_recalculation_procedure.rb
> +        UPDATE accounts SET
switch to a UPDATE JOIN

2019-07-22 08:37 UTC, mod commented on db/migrate/20190719134706_add_account_recalculation_procedure.rb
> +        UPDATE jobs SET `rows` = ROW_COUNT() WHERE id = LAST_INSERT_ID();
There is plenty of inserts above, it's unlikely LAST_INSERT_ID is correct
use: SELECT id, data INTO @x, @y FROM test.t1 LIMIT 1;
https://dev.mysql.com/doc/refman/8.0/en/select-into.html

2019-07-22 11:28 UTC, shal commented on db/migrate/20190719134706_add_account_recalculation_procedure.rb
> +        DROP TABLE IF EXISTS peatio_archive.liabilities;
Done

2019-07-22 11:28 UTC, shal commented on db/migrate/20190719134706_add_account_recalculation_procedure.rb
> +        TRUNCATE TABLE liabilities;
Done

2019-07-22 11:29 UTC, shal commented on db/migrate/20190719134706_add_account_recalculation_procedure.rb
> +      DROP PROCEDURE IF EXISTS compact_and_recalculate;
Done

2019-07-22 11:29 UTC, shal commented on db/migrate/20190719134706_add_account_recalculation_procedure.rb
> +      DROP DATABASE IF NOT EXISTS peatio_archive;
Done

2019-07-22 11:29 UTC, shal commented on db/migrate/20190719103057_create_jobs.rb
> +      t.integer :rows, null: false, default: 0
Done

2019-07-22 11:29 UTC, shal commented on db/migrate/20190719134706_add_account_recalculation_procedure.rb
> +        UPDATE jobs SET `rows` = ROW_COUNT() WHERE id = LAST_INSERT_ID();
I did `SET @job_id = LAST_INSERT_ID();`

2019-07-22 11:59 UTC, shal commented on db/migrate/20190719134706_add_account_recalculation_procedure.rb
> +        UPDATE accounts SET
To be honest I don't clearly understand how to JOIN in this case.

2019-07-22 14:28 UTC, mod commented
```sql
-- Declaring variables

DECLARE job_id INT DEFAULT -1;
DECLARE tmp_table VARCHAR(32);

-- Prepare job
INSERT INTO jobs (`description`, `state`, created_at, updated_at) VALUES ('compact', 'created', NOW(), NOW());

SELECT LAST_INSERT_ID() INTO job_id;
SELECT CONCAT('temp_liabilities_', job_id) INTO tmp_table;

-- Exporting raw liabilities

INSERT INTO export_liabilities
  (
    SELECT NULL, code, currency_id, member_id, reference_type, reference_id, debit, credit, created_at, updated_at
    FROM liabilities WHERE reference_type != 'Compactor'
  );

-- Compacting the ledgers
CREATE TEMPORARY TABLE tmp_table
SELECT NULL, code, currency_id, member_id, 'Compactor', job_id, SUM(debit) as debit, SUM(credit) AS credit, NOW(), NOW()
FROM liabilities GROUP BY code, currency_id, member_id;

-- Updating liabilities from temp
TRUNCATE tmp_table
INSERT INTO liabilities SELECT * FROM tmp_table;

-- Update balances

CREATE TEMPORARY TABLE `temp_balance` SELECT ac.member_id, ac.currency_id, SUM(lb.credit) - SUM(lb.debit) AS `balance` FROM `accounts` AS `ac` JOIN `liabilities` AS `lb` ON lb.code IN (SELECT code FROM operations_accounts WHERE type = 'liability' AND kind = 'main') AND ac.member_id = lb.member_id AND ac.currency_id = lb.currency_id GROUP BY lb.code, lb.currency_id, lb.member_id;

UPDATE `accounts` AS `ac` INNER JOIN `temp_balance` AS `tb` USING(member_id,currency_id)
SET ac.balance = tb.balance, `created_at` = NOW(), `updated_at` = NOW();
```

2019-07-25 14:24 UTC, ysv commented on app/models/job.rb
> +  def failed?
you could try to use inquiry for state
```ruby
def state
  super&.inquiry
end
```

2019-08-13 10:31 UTC, closed without merging