Drop step from blockchain model
openware/peatio pull request #2282
Opened 2019-07-29 09:10 UTC by shal

2019-08-05 09:13 UTC, mnaichuk commented on app/services/blockchain_service.rb
> +  def fetch_current_height
I think it's confusing name for this method, cause we call through `blockchain_service` `fetch_current_height` and then adapter call `latest_block_number`

2019-08-05 09:13 UTC, mnaichuk commented on app/models/concerns/has_one_blockchain_through_currency.rb
> +    if block_number.blank?
why you add this condition? I can just change previous realization

2019-08-05 11:13 UTC, ysv requested changes

2019-08-05 11:13 UTC, ysv commented on app/models/concerns/has_one_blockchain_through_currency.rb
> +  def confirmations(height: blockchain.processed_height)
1. I think it's better we keep method without params because it's not clear enough but inside service we use it in other way.
2. Regarding rewriting it with if/else I prefer @shal variant

2019-08-05 11:13 UTC, ysv commented on app/services/blockchain_service.rb
> +    @current_height = @adapter.latest_block_number
do you want to add lazy loading for current_height ?
because you will always rewrite it by calling latest_block_number
may be you wanted to use `||=` ?

```ruby
def latest_block_number
  @current_height ||= @adapter.latest_block_number
end
```

Looks like you are mixing attribute with method I think we can keep one and I prefer `latest_block_number` with caching

2019-08-05 11:13 UTC, ysv commented on app/services/blockchain_service.rb
> +    elsif transaction.status.success? && withdrawal.confirmations(height: current_height) >= @blockchain.min_confirmations
I'm thinking about other way of doing this
It's better you don't use confirmations method but calculate it explicitly and comment that we are doing it in this way because blockchain heigh is not updated yet
```ruby
... && current_height - withdrawal.block_number >= @blockchain.min_confirmations
```

2019-08-05 11:13 UTC, ysv commented on app/services/blockchain_service.rb
> +    if deposit.confirmations(height: current_height) >= @blockchain.min_confirmations && deposit.accept!
I'm thinking about other way of doing this
It's better you don't use confirmations method but calculate it explicitly and comment that we are doing it in this way because blockchain heigh is not updated yet
```ruby
... && current_height - deposit.block_number >= @blockchain.min_confirmations
```

2019-08-05 11:13 UTC, ysv commented on app/workers/daemons/blockchain.rb
> +        ::Blockchain.active.map { |b| Thread.new { process(b) } }.map(&:join)
Add TODO that newly created blockcahins will not start sync

2019-08-05 11:13 UTC, ysv commented on config/backend.yml
> +      DUMMY_JWT_TTL: 86400
why do we need this one ?

2019-08-05 11:43 UTC, shal commented on app/services/blockchain_service.rb
> +    @current_height = @adapter.latest_block_number
No, that's was the plan, as I wanted to store latest call of `adapter.latest_block_number`, but don't cache the `current_height`. That's why I called this method `fetch_block_number`.

2019-08-05 11:43 UTC, shal commented on app/services/blockchain_service.rb
> +    if deposit.confirmations(height: current_height) >= @blockchain.min_confirmations && deposit.accept!
Yep, first iteration was just like this, but I think better to isolate it.
We may use this already implemented better `confirmations` method it in some other places, don't we?

2019-08-05 11:43 UTC, shal commented on app/workers/daemons/blockchain.rb
> +        ::Blockchain.active.map { |b| Thread.new { process(b) } }.map(&:join)
Something like:

```
# TODO: Start synchronization of blockchains created in run-time.
```

2019-08-05 11:45 UTC, shal commented on config/backend.yml
> +      DUMMY_JWT_TTL: 86400
It gives ability to avoid gateway.

For me it is better, because there is some problems with running peatio on mac.

2019-08-05 12:34 UTC, ysv requested changes

2019-08-05 12:34 UTC, ysv commented on app/services/blockchain_service.rb
> +    @current_height = @adapter.latest_block_number
I think we need to add `reset!` method to BlockchainService
For now this method will only set @latest_block_number to nil but it's possible that we will have more variables which will be chached.
And also we keep latest_block_number method:
```ruby
def latest_block_number
  @latest_block_number ||= @adapter.latest_block_number
end
```

2019-08-05 12:34 UTC, ysv commented on app/workers/daemons/blockchain.rb
> +        ::Blockchain.active.map { |b| Thread.new { process(b) } }.map(&:join)
yes

2019-08-05 12:34 UTC, ysv commented on app/services/blockchain_service.rb
> +    if deposit.confirmations(height: current_height) >= @blockchain.min_confirmations && deposit.accept!
I think we just can calculate it manually here because confirmation method reference number in DB

2019-08-07 10:28 UTC, ysv commented on app/services/blockchain_service.rb
> +    # Manually calculationg deposit confirmations, because blockchain height is not updated yet.
spelling: calculationg

2019-08-07 10:28 UTC, ysv commented on app/services/blockchain_service.rb
> +    # Manually calculationg withdrawal confirmations, because blockchain height is not updated yet.
spelling: calculationg

2019-08-07 10:28 UTC, ysv commented on app/workers/daemons/blockchain.rb
> +            bc_service.reset!
Optional: Add comment here.

2019-08-09 13:08 UTC, ysv approved these changes

2019-08-09 15:36 UTC, merged

2019-08-30 06:40 UTC, krtschmr commented
this seem to fix my issue https://github.com/rubykube/peatio/issues/2311 ?