FeeSplit model for referral fees story
openware/peatio pull request #2283
Opened 2019-07-29 14:54 UTC by ysv

2019-07-29 18:16 UTC, mod commented on db/migrate/20190529142209_create_triggers.rb
> +    # create_table :triggers do |t|
I'm not in favor of deleting this table, within 3 weeks we will get back to this topic

2019-07-29 19:35 UTC, martianatwork commented
Can we do something like Pluggable currencies? We can create strategies as plugins. There are people who may want to change the strategy or pay the referral fees for first 30 days and so on, Making this pluggable will help in future.

Let me know your plan if possible, I will help in development resources.

2019-07-29 19:39 UTC, mod requested changes

2019-07-29 19:39 UTC, mod commented on db/migrate/20190729134807_create_fee_splits.rb
> +    create_table :fee_splits do |t|
possible table name : 
- commissions
- shares
- revshares

referrer is confusing I would name
member_id
referrer_id
percentage
state

shares is not bad, even more explicit than commissions
this can also be `payment_shares`

This table will be used not only in fees splitting

2019-07-29 19:39 UTC, mod commented on db/migrate/20190729124305_add_state_to_trade.rb
> +        add_column :trades, :state, :integer, null: false, limit: 1, index: true
make sure to place it correctly

2019-07-29 19:39 UTC, mod commented on db/migrate/20190729134807_create_fee_splits.rb
> +      t.decimal :percentage, null: false, precision: 4, scale: 2, unsigned: true
to be honest I would take a number on 1000 for example
255 is 25.5% we avoid decimal and can fit in UNSIGNED SMALLINT(65535)
we can also fit a 10,000 for higher precision, maybe it's not weird.

2019-07-30 09:00 UTC, ysv commented
@martianatwork our plan actually is to make it even more flexible.
We will add management API to create/update fee_split via Management API.
It will give ability to define custom business logic in Applogic and create fee_split.

2019-08-01 12:42 UTC, mod commented
- [ ] rename revene_shares
- [ ] rename field to pptt
- [ ] Fees will be collected into revenues with new account code type
- [ ] Job processing trades, deposits, withdrawal move to lock liability and expense +10L, -10E
- [ ] Liabilities and Expenses paid must have a reference_type to be defined
- [ ] Reference type is likely to be transfer_id
- [ ] revshares must have a scope like trade or withdrawal
- [ ] revenue_types with values created if not-exists
- [ ] revenue_shares (revenue_type_id)
- [ ] revenue_payout(revenue_type, uid, amount, currency)

2019-08-01 15:59 UTC, merged

2019-08-02 10:01 UTC, ysv commented
Moved to #2291