Add rake task for load users and balances
openware/peatio pull request #2287
Opened 2019-07-31 15:42 UTC by mnaichuk

2019-07-31 15:59 UTC, ysv requested changes

2019-07-31 15:59 UTC, ysv commented on lib/tasks/import.rake
> +    errors_users_file = File.open("errors_users_file.txt", "w")
write to /log/import_something.log

2019-07-31 15:59 UTC, ysv commented on lib/tasks/import.rake
> +    CSV.parse(csv_table, headers: true).map do |row|
use each

2019-07-31 15:59 UTC, ysv commented on lib/tasks/import.rake
> +      email = row['email']
```ruby
:role=>:member, :state=>:active} 
2.6.3 :002 > row = {email: 'kek@lol.com', uid: '1234', level: 1}
 => {:email=>"kek@lol.com", :uid=>"1234", :level=>1} 
2.6.3 :003 > row.reverse_merge(defaults)
 => {:level=>1, :role=>:member, :state=>:active, :email=>"kek@lol.com", :uid=>"1234"} 
```

2019-07-31 15:59 UTC, ysv commented on lib/tasks/import.rake
> +    rescue => e
use StandardError

2019-07-31 15:59 UTC, ysv commented on lib/tasks/import.rake
> +      Member.create!(uid: composed_uid, email: email, level: level, role: role, state: state)
don't forget about composed_uid

2019-07-31 15:59 UTC, ysv commented on lib/tasks/import.rake
> +    Kernel.puts "Created #{count} members"
Optional: Add also number of errored members

2019-07-31 15:59 UTC, ysv commented on lib/tasks/import.rake
> +      account = Account.find_or_create_by!(member: member, currency_id: currency)
use currency: currency

2019-07-31 15:59 UTC, ysv commented on lib/tasks/import.rake
> +        account&.update!(balance: main_balance, locked: locked_balance)
remove &

2019-07-31 15:59 UTC, ysv commented on lib/tasks/import.rake
> +      message = { error: e.message, accoutn_id: row['AccountId'], composed_uid: composed_uid }
uid

2019-07-31 15:59 UTC, ysv commented on lib/tasks/import.rake
> +        Operations::Asset.create!(code: asset_code, currency_id: currency.id, credit: main_balance + locked_balance)
use `credit!` instead of create!

2019-07-31 21:04 UTC, ysv requested changes

2019-07-31 21:04 UTC, ysv commented on docs/databases/import.md
> +## How to import users and account balances database Peatio
May be we move to doc/tasks

2019-07-31 21:04 UTC, ysv commented on docs/databases/import.md
> +  |      uid      | email          | level |    role      |  state  | referral_id  |
Do we actually need referral_id ?
If yes probably need to be renamed to referral_uid

2019-07-31 21:04 UTC, ysv commented on lib/tasks/import.rake
> +      row = row.to_hash.symbolize_keys!.delete_if { |_k, v| v.nil? }
`row.to_h.symbolize_keys.compact` - looks better for me

may be even move it to map:
```ruby
CSV.parse(csv_table, headers: true).map(&:to_h).map(&:symbolize_keys) ...
```

Also check maybe it's possible to symbolize or parse step I think there should be some option
may be even compact option

2019-07-31 21:14 UTC, mnaichuk commented on docs/databases/import.md
> +  |      uid      | email          | level |    role      |  state  | referral_id  |
Yes, I want create template for peatio and barong. Agreed, will change to referral_uid

2019-08-01 08:55 UTC, ysv approved these changes

2019-08-01 09:04 UTC, merged