Switch to maker taker fee for markets and orders
openware/peatio pull request #2292
Opened 2019-08-02 12:57 UTC by mnaichuk

2019-08-07 10:00 UTC, ysv requested changes
- [ ] Notify frontend team about changes

- [ ] Update charts

- [x] Update Trade Model like in https://www.zmwolski.com/Organizing-Ruby-on-Rails-Models

2019-08-07 10:00 UTC, ysv commented on app/models/order.rb
> +    self.maker_fee = market.maker_fee
Could you add comment why do we need to save maker_fee & taker_fee inside order.

2019-08-07 10:00 UTC, ysv commented on app/api/v2/entities/market.rb
>              desc: "Market ask fee."
Update desc

2019-08-07 10:00 UTC, ysv commented on app/api/v2/entities/market.rb
>              desc: "Market bid fee."
Update desc

2019-08-07 10:00 UTC, ysv commented on app/models/order.rb
> +#  maker_fee      :decimal(32, 16)  default(0.0), not null
It's better to use decimal(17,16) same as here https://github.com/rubykube/peatio/pull/2292/files#diff-9c5e7fe4e4ca3998300c6ffd244b19fcR210

2019-08-07 10:00 UTC, ysv commented on app/models/trade.rb
>      # We multiply ask outcome by bid fee.
Remove or update comment it's outdated now

2019-08-07 10:00 UTC, ysv commented on app/models/trade.rb
> +    if bid == taker
1. It looks strange for me that for calculating ask_currency_income you use bid.taker_fee / bid.maker_fee. As for me it should be:
```ruby
if ...
ask_currency_income = volume - volume * ask.taker_fee
bid_currency_income = funds - funds * bid.maker_fee
else
ask_currency_income = volume - volume * ask.maker_fee
bid_currency_income = funds - funds * bid.taker_fee
```
And add spec for this behavior.
The best spec will be:
1. you create first order
2. update both maker & taker fee for appropriate market
3. create second order
4. check revenues


2. I advice to add method #bid_fee, #ask_fee
```ruby
def bid_fee
  bid == taker ? bid.taker_fee : bid.maker_fee
end
```

And use it here without if
```ruby
ask_currency_income = volume - volume * ask_fee
bid_currency_income = funds - funds * bid_fee
```

2019-08-07 10:00 UTC, ysv commented on app/models/trade.rb
> +    if bid == taker
same as here https://github.com/rubykube/peatio/pull/2292/files#diff-8a2c0ff208b63fa96db8cc5d9e2fa35cR103

2019-08-07 10:00 UTC, ysv commented on app/models/withdraw.rb
> +# Schema version: 20190730140453
reset

2019-08-07 10:00 UTC, ysv commented on app/models/withdraws/coin.rb
> +# Schema version: 20190730140453
reset

2019-08-07 10:00 UTC, ysv commented on app/models/withdraws/fiat.rb
> +# Schema version: 20190730140453
reset

2019-08-07 10:00 UTC, ysv commented on app/serializers/serializers/event_api/trade_completed.rb
> +          buyer_income_maker_fee:   (trade.volume * trade.bid.maker_fee).to_s('F'),
no this one is wrong
buyer_income_fee is single value and will not split into two buyer_income_maker_fee, buyer_income_taker_fee

buyer_income_fee is equal to bid_currency_fee in #record_revenues! https://github.com/rubykube/peatio/pull/2292/files#diff-8a2c0ff208b63fa96db8cc5d9e2fa35cR153

2019-08-07 10:00 UTC, ysv commented on app/serializers/serializers/event_api/trade_completed.rb
> +          seller_income_maker_fee:  (trade.funds * trade.ask.maker_fee).to_s('F'),
same as here https://github.com/rubykube/peatio/pull/2292/files#diff-7a3e5fe6af9dc29d3988d79ced7b0cd3R15

2019-08-07 10:00 UTC, ysv commented on app/trading/matching/executor.rb
> +      fee = if order == trade.taker
Check may be it will be possible to use #bid_fee #ask_fee here as I mentioned here https://github.com/rubykube/peatio/pull/2292/files#diff-8a2c0ff208b63fa96db8cc5d9e2fa35cR103

2019-08-07 10:00 UTC, ysv commented on config/templates/seed/markets.yml.erb
> +  maker_fee:         0.0015
May be we change default values to the same as Binance/Bitfinex have ?
As for me they should be different at least

2019-08-07 10:00 UTC, ysv commented on db/migrate/20190730140453_update_markets_ask_fee_bid_fee.rb
> +    add_column    :orders, :taker_fee, :decimal, null: false, default: 0, precision: 32, scale: 16, after: :maker_fee
1. I think we will use `precision: 17`
2. We need to update all maker_fee, and taker_fee for orders after we add this column because it will be strange if we have 0 for all taker_fee column for historical orders

2019-08-08 16:55 UTC, ysv submitted a review, later dismissed

2019-08-12 18:30 UTC, mnaichuk commented on app/models/trade.rb
> +      side:           side(member).side,
check this one @ysv

2019-08-12 18:30 UTC, mnaichuk commented on app/models/trade.rb
> +    sell, buy = maker_order.side == 'sell' ? [maker_order, taker_order] : [taker_order, maker_order]
this one too

2019-08-12 18:30 UTC, mnaichuk commented on app/trading/matching/executor.rb
> +      @amount  = payload[:amount].to_d
check this file too

2019-08-12 18:32 UTC, mnaichuk commented on app/api/v2/entities/trade.rb
> +          options[:side] || trade.side(options[:current_user]).side
Problem that we have to `def side` in order and in trade

2019-08-12 19:37 UTC, ysv requested changes

2019-08-12 19:37 UTC, ysv commented on app/api/v2/entities/trade.rb
> +          options[:side] || trade.side(options[:current_user]).side
https://github.com/rubykube/peatio/pull/2292#discussion_r313092422

2019-08-12 19:37 UTC, ysv commented on app/api/v2/entities/trade.rb
> +            if trade.maker_id == options[:current_user].id
Optional: Add this to Trade model

2019-08-12 19:37 UTC, ysv commented on app/api/v2/management/entities/trade.rb
> +            if trade.maker_id == options[:current_user].id
Optional: Add this to Trade model

2019-08-12 19:37 UTC, ysv commented on app/models/trade.rb
> +      side:           side(member).side,
as I've already mentioned I prefer to rename this method to more explicit

2019-08-12 19:37 UTC, ysv commented on app/models/trade.rb
> +    sell, buy = maker_order.side == 'sell' ? [maker_order, taker_order] : [taker_order, maker_order]
what about adding sell_order & buy_order methods to trade ?

2019-08-12 19:37 UTC, ysv commented on app/models/trade.rb
> +#  total          :decimal(32, 16)  not null
locate total after amount I'm even thinking about dropping it (actually replacing with total method).
What is your opinion is it gonna take a lot of time ?

2019-08-13 00:20 UTC, ysv requested changes
- [x] Check that we have equal messages for Orders & Trades on WS and REST now. If no make the same since we still breaking FE

2019-08-13 00:20 UTC, ysv commented on app/api/v2/management/entities/trade.rb
> +            :amount,
Pleas ask if none use trades Management API 
If no then okay, if yes then we need to make it compatible with previous versions

2019-08-13 00:20 UTC, ysv commented on app/api/v2/management/entities/trade.rb
> +            trade.taker_order.side == 'sell' ? :sell : :buy
as mentioned here https://github.com/rubykube/peatio/pull/2292#discussion_r313092422

2019-08-13 00:20 UTC, ysv commented on app/api/v2/management/entities/trade.rb
> +            options[:side] || trade.side(options[:current_user])
as far as I understand `trade.side(options[:current_user])` will return Order, is not it ?
stick to https://github.com/rubykube/peatio/pull/2292#discussion_r313092422

2019-08-13 00:20 UTC, ysv commented on app/models/order.rb
> +  # Order can be as Maker and Taker, so we need each field in order model
Single Order can produce multiple Trades with different fee types (maker and taker).
Since we can't predict fee types on order creation step and Market fees configuration can change we need to store fees on Order creation.

2019-08-13 00:20 UTC, ysv commented on app/models/trade.rb
> +
Move include and extend to top of Constants

2019-08-13 00:20 UTC, ysv commented on app/models/trade.rb
> +    seller_currency_income = amount - amount * order_fee(buy)
if you sell you will receive total
if you buy you receive amount
so I think it should be
```ruby
seller_income = total - total * order_fee(sell)
buyer_income = amount - amount * order_fee(buy)
```
I think about removing *currency*

2019-08-13 00:20 UTC, ysv commented on app/models/trade.rb
> +      currency:  buy.currency,
Also I suggest to define income_currency & outcome_currency in Order (and deprecate or remove currency)
So final view of method will be. Please check 100 times if logic is right
```ruby
def record_liability_credit!
    seller_income = total - total * order_fee(sell_order)
    buyer_income = amount - amount * order_fee(buy_order)


    # Credit main fiat/crypto Liability account for member who created ask.
    Operations::Liability.credit!(
      amount:    buyer_income,
      currency:  buy_order.income_currency,
      reference: self,
      kind:      :main,
      member_id: buy_order.member_id
    )

    # Credit main fiat/crypto Liability account for member who created bid.
    Operations::Liability.credit!(
      amount:    seller_income,
      currency:  sell_order.income_currency,
      reference: self,
      kind:      :main,
      member_id: sell_order.member_id
    )
  end
```

2019-08-13 00:20 UTC, ysv commented on app/models/trade.rb
> +    sell, buy = maker_order.side == 'sell' ? [maker_order, taker_order] : [taker_order, maker_order]
same changes as in #record_liability_credit!

2019-08-13 00:20 UTC, ysv commented on app/models/trade.rb
> +    sell, buy = maker_order.side == 'sell' ? [maker_order, taker_order] : [taker_order, maker_order]
same changes as in #record_liability_credit!

2019-08-13 00:20 UTC, ysv commented on app/models/trade.rb
> +    [maker_order, taker_order].each do |order|
same changes as in #record_liability_credit!

2019-08-13 00:20 UTC, ysv commented on app/serializers/serializers/event_api/trade_completed.rb
> +          maker_uid:             Member.uid(trade.maker_id),
May be `trade.maker.uid` ?

2019-08-13 00:20 UTC, ysv commented on app/serializers/serializers/event_api/trade_completed.rb
> +          taker_uid:             Member.uid(trade.taker_id),
May be `trade.taker.uid` ?

2019-08-13 00:20 UTC, ysv commented on app/trading/matching/engine.rb
> +      maker_order, taker_order = ask.id < bid.id ? [ask, bid] : [bid, ask]
may be we don't need ask, bid anymore here ?
just define maker_order, taker_order directly

2019-08-13 00:20 UTC, ysv commented on app/trading/matching/engine.rb
> +                       total: funds },
rename this funds

2019-08-13 00:20 UTC, ysv commented on app/trading/matching/executor.rb
> +      raise_error(3001, 'Ask price exceeds strike price.') if @maker_order.ord_type == 'limit' && @maker_order.price > @price
update error messages

2019-08-13 00:38 UTC, ysv commented on app/trading/matching/executor.rb
> +        maker_currency_outcome = @maker_order.side == 'buy' ? @maker_order.bid : @maker_order.ask
I don't know how to make it elegant for now
Check it once more after you add new methods to Trade
I think there should be solution

2019-08-13 22:18 UTC, ysv commented on app/models/order.rb
> +  def outcome_currency
I would prefer to put this into OrderBid & OrderAsk
What do you think ?

2019-08-13 22:18 UTC, ysv commented on app/models/trade.rb
> +  def sell_order
Optional:
```ruby
def sell_order
  [maker_order, taker_order].find { |o| o.side == 'sell' }
end
```

2019-08-13 22:18 UTC, ysv commented on app/views/admin/markets/show.html.erb
> +            <%= f.text_field :maker_fee, class: 'form-control mb-3' %>
use number_field with step: :any

2019-08-13 22:18 UTC, ysv commented on app/views/admin/markets/show.html.erb
> +            <%= f.text_field :taker_fee, class: 'form-control mb-3' %>
use number_field with step: :any

2019-08-14 07:58 UTC, mnaichuk commented on app/models/order.rb
> +  def outcome_currency
Actually I don't like this OrderBid and OrderAsk, but if keep them, it will be more clear if we put these methods there

2019-08-14 07:58 UTC, mnaichuk commented on app/models/trade.rb
> +  def sell_order
thanks!

2019-08-14 09:17 UTC, ysv reviewed
- [x] Update patch title and description

2019-08-14 20:21 UTC, ysv commented on app/trading/matching/executor.rb
> +        Order.lock.where(id: [@payload[:maker_order_id], @payload[:taker_order_id]]).to_a.tap do |orders|
I think if we will `.include` currencies it will improve performance a bit
We can analyze SQL query and include everything we need

2019-08-14 20:21 UTC, ysv commented on app/trading/matching/executor.rb
> +        volume:      @amount,
amount

2019-08-14 20:21 UTC, ysv commented on db/migrate/20190813121822_update_markets_ask_fee_bid_fee.rb
> +    rename_column :markets, :ask_fee, :maker_fee if column_exists?(:markets, :ask_fee)
I've just noticed that migration is bit wrong for maker & taker. 
You rename ask to maker and bid to taker (both order & member) but in some orders in the past in may not be true. 
I think we need to rename columns and then go one by one and update ids to maker-taker business logic in the similar way as we did for `orders.taker_fee`

2019-08-14 20:21 UTC, ysv commented on db/migrate/20190813121822_update_markets_ask_fee_bid_fee.rb
> +    add_column :trades, :trend, :integer, null: false
counterpart for this line is missing in down     
`execute('UPDATE orders SET orders.taker_fee = orders.maker_fee')`

Don't forget also about this comment https://github.com/rubykube/peatio/pull/2292/files#diff-cc920be06b18b2e19519d55014f00394R3

2019-08-15 10:21 UTC, ysv approved these changes

2019-08-15 10:30 UTC, merged