Prepare management API for Revenue Share
openware/peatio pull request #2293
Opened 2019-08-02 13:06 UTC by shal

* Create new revenue share
* List all revenue shares with filters (member/parent/state)
* Update state/percent of existing revenue share
* Get revenue share by unique identifier.

2019-08-05 12:49 UTC, ysv requested changes

2019-08-05 12:49 UTC, ysv commented on app/api/v2/management/entities/revenue_share.rb
> +          states = [
`STATES` looks better for me

2019-08-05 12:49 UTC, ysv commented on app/api/v2/management/revenue_shares.rb
> +              .includes(:member, :parent)
I think it's better we use joins

2019-08-05 12:49 UTC, ysv commented on app/api/v2/management/revenue_shares.rb
> +          ::RevenueShare.order(id: :asc)
I think it's better you add ordered scope to RevenueShare model and use it instead

2019-08-05 12:49 UTC, ysv commented on app/api/v2/management/revenue_shares.rb
> +          member = Member.find_by!(uid: params[:member_uid]) if params[:member_uid].present?
What is gonna happen if member with member_uid/parent_uid doesn't exist ?
Could you add spec ?

2019-08-05 12:49 UTC, ysv commented on app/api/v2/management/revenue_shares.rb
> +        desc 'Creates new revenue share with state set to «disabled».' do
'Creates new revenue share with state set to «disabled».' - we can create revenue share with active state directly. And active is default value for it

2019-08-05 12:49 UTC, ysv commented on app/api/v2/management/revenue_shares.rb
> +          optional :state,      type: String,     desc: 'The state of revenue share.', values: -> { RevenueShare::STATES }
There is default value :active

2019-08-05 12:49 UTC, ysv commented on app/api/v2/management/revenue_shares.rb
> +          member = Member.find_by(uid: params[:member_uid])
could you add spec for cases if member doesn't exist ?

2019-08-05 12:49 UTC, ysv commented on app/api/v2/management/revenue_shares.rb
> +          data          = { member: member, parent: parent }
I prefer specifying all attributes explicitly here:
```ruby
attributes = params.slice(:percent, :state).merge(member: member, parent: parent)
```

so we don't need `.tap` after initializing revenue share

2019-08-05 12:49 UTC, ysv commented on app/api/v2/management/revenue_shares.rb
> +          optional :state,   type: String,     desc: 'The new state to apply.', values: -> { RevenueShare::STATES }
there is grape helper `at least  one of` or something like this. It's better we use it for validating that we have either state or percent or both of them

2019-08-05 12:49 UTC, ysv commented on app/api/v2/management/revenue_shares.rb
> +          revenue_share = ::RevenueShare.find_by!(params.slice(:id)).tap do |rs|
```ruby
revenue_share = ::RevenueShare.find_by!(id: params[:id]_

if revenue_share.update(params.slice(:state, :percent)
...
```

2019-08-05 12:49 UTC, ysv commented on spec/api/v2/management/revenue_shares_spec.rb
> +  describe 'create deposits' do
create revenue shares

2019-08-05 12:49 UTC, ysv commented on spec/api/v2/management/revenue_shares_spec.rb
> +    it 'returns deposit by TID' do
update it message

2019-08-05 12:49 UTC, ysv commented on spec/api/v2/management/revenue_shares_spec.rb
> +    let(:record) { RevenueShare.create!(member: member, parent: parent, percent: percent) }
use factories

2019-08-05 12:52 UTC, ysv commented on spec/api/v2/management/revenue_shares_spec.rb
> +    it 'creates new revenue share with state «active»' do
it's default state here could you add also spec with disabled state

2019-08-06 01:02 UTC, streetcrypto7 commented
Please add support for revenew wallet!

2019-08-06 14:16 UTC, shal commented on app/api/v2/management/revenue_shares.rb
> +          data          = { member: member, parent: parent }
Nice!

2019-08-06 14:16 UTC, shal commented on app/api/v2/management/revenue_shares.rb
> +          optional :state,   type: String,     desc: 'The new state to apply.', values: -> { RevenueShare::STATES }
Nice!

2019-08-06 14:16 UTC, shal commented on spec/api/v2/management/revenue_shares_spec.rb
> +    it 'returns deposit by TID' do
Done

2019-08-06 14:16 UTC, shal commented on spec/api/v2/management/revenue_shares_spec.rb
> +    let(:record) { RevenueShare.create!(member: member, parent: parent, percent: percent) }
Done

2019-08-06 14:16 UTC, shal commented on spec/api/v2/management/revenue_shares_spec.rb
> +    it 'creates new revenue share with state «active»' do
Done

2019-08-06 14:16 UTC, shal commented on spec/api/v2/management/revenue_shares_spec.rb
> +  describe 'create deposits' do
Done

2019-08-06 14:16 UTC, shal commented on app/api/v2/management/revenue_shares.rb
> +          revenue_share = ::RevenueShare.find_by!(params.slice(:id)).tap do |rs|
Done

2019-08-06 14:16 UTC, shal commented on app/api/v2/management/revenue_shares.rb
> +          optional :state,      type: String,     desc: 'The state of revenue share.', values: -> { RevenueShare::STATES }
Done

2019-08-06 14:16 UTC, shal commented on app/api/v2/management/revenue_shares.rb
> +        desc 'Creates new revenue share with state set to «disabled».' do
Done

2019-08-06 14:16 UTC, shal commented on app/api/v2/management/revenue_shares.rb
> +          ::RevenueShare.order(id: :asc)
Done, but I would like to call it `reverted`

2019-08-06 14:49 UTC, shal commented on app/api/v2/management/revenue_shares.rb
> +              .includes(:member, :parent)
Done

2019-08-06 15:05 UTC, shal commented on app/api/v2/management/revenue_shares.rb
> +          member = Member.find_by!(uid: params[:member_uid]) if params[:member_uid].present?
Done

2019-08-07 10:58 UTC, ysv requested changes

2019-08-07 10:58 UTC, ysv commented on spec/api/v2/management/revenue_shares_spec.rb
> +      expect(response.body).to match(/couldn't find record/i)
I reckon that 'couldn't find record' is bad error message here because it looks like we can't find RevenueShare.
There are two right solutions as for me:
1. Return empty array because there is no RevenueShares for member with uid 1234567890
2. Return error that member with such uid doesn't exist

2019-08-07 10:58 UTC, ysv commented on spec/api/v2/management/revenue_shares_spec.rb
> +      expect(response.body).to match(/couldn't find record/i)
same as here https://github.com/rubykube/peatio/pull/2293/files#diff-bc2ee5fc4156a9244fe67d5b7e3e6e4dR68

2019-08-07 10:58 UTC, ysv commented on app/api/v2/management/entities/revenue_share.rb
> +          «disabled» – initial state.
disabled is not initial state.
For me next description is better:

- active - revenue share takes part on dividing shares between users
- disabled - revenue share doesn't take part on dividing shares between users. Since deleting of revenue share is not permitted disabling is equal to removing

2019-08-07 10:58 UTC, ysv commented on app/api/v2/management/entities/revenue_share.rb
> +              desc: 'Member unique identifier.'
Member user identifier. Defines member whose fees will be divided during revenue sharing.

2019-08-07 10:58 UTC, ysv commented on app/api/v2/management/entities/revenue_share.rb
> +              desc: 'Parent unique identifier.'
Parent user identifier. Defines parent who will receive part of fees paid by member during revenue sharing.

2019-08-07 10:58 UTC, ysv commented on app/api/v2/management/entities/revenue_share.rb
> +              desc: 'Percentage of revenue share.'
Percentage of revenue share. Defines fees part which parent will receive during revenue sharing.

2019-08-13 22:22 UTC, ysv approved these changes

2019-08-14 09:26 UTC, ysv approved these changes

2019-08-14 09:27 UTC, merged