Fail ethereum withdrawal in case of `fail` status in blockchain
openware/peatio pull request #2302
Opened 2019-08-06 14:27 UTC by mnaichuk

2019-08-07 10:24 UTC, ysv requested changes
I think we need:  
1. create ticker in Jira for updating peatio-core because we will forget
2. or prepare pr for peatio-core

2019-08-07 10:24 UTC, ysv commented on app/services/blockchain_service.rb
> +    transaction = adapter.fetch_transaction(transaction) if @adapter.respond_to?(:fetch_transaction) && transaction.status.pending?
1. Add comment because it is not obvious
2. Don't we need to add same on deposit processing ?

2019-08-07 10:24 UTC, ysv commented on lib/peatio/ethereum/blockchain.rb
> -          status:        transaction_status(block_txn) }
I prefer defining status here explicitly. Better you put `status: :pending`

2019-08-07 10:24 UTC, ysv commented on spec/services/blockchain_service_spec.rb
> +    context 'fail withdrawal if transaction has status :fail' do
could you add spec for success transaction
with the same scenario:
1. Returns transaction with pending status
2. Refetch for full transaction info

2019-08-15 13:58 UTC, ysv approved these changes

2019-08-15 17:47 UTC, merged

2019-08-15 17:48 UTC, mod commented
@mnaichuk we need this on v2.2