Update management/transfers
openware/peatio pull request #2307
Opened 2019-08-06 17:13 UTC by dnfd

- Update specs

2019-08-07 12:54 UTC, ysv requested changes
Specs are broken

2019-08-07 12:54 UTC, ysv commented on app/models/transfer.rb
> +        transfer.send(:update_legacy_balances)
Make update_legacy_balances public

2019-08-07 12:54 UTC, ysv commented on spec/api/v2/management/entities/transfer_spec.rb
> +                        .represent(record.reload.assets)
why did we add this `reload` ?

2019-08-07 12:54 UTC, ysv commented on app/api/v2/management/transfers.rb
> +          attrs = declared_params.slice(:key, :kind, :desc)
Optional: If you have an idea how to make this controller elegant you can improve since it's a bit complex now

2019-08-07 13:15 UTC, dnfd commented on spec/api/v2/management/entities/transfer_spec.rb
> +                        .represent(record.reload.assets)
record is without attached operations without reloading

2019-08-08 12:17 UTC, ysv requested changes

2019-08-08 12:17 UTC, ysv commented on app/models/transfer.rb
> +  after_save :update_legacy_balances
no we can't update legacy balance in separate MySQL transaction
We want to rollback transfer creation in case of balance update error

Let's keep do_transfer for now

2019-08-08 12:17 UTC, ysv commented on app/models/transfer.rb
> +      case l.account.kind
I preferre previous variant

2019-08-08 12:17 UTC, ysv commented on spec/api/v2/management/entities/transfer_spec.rb
> +                        .represent(record.reload.assets)
Got it now

I advice to refactor factories/transfer.rb. This should help
```ruby
trait :with_assets do
  assets { build_list(:asset, assets_number, reference: t) }
end
```

2019-08-08 12:32 UTC, dnfd commented on app/models/transfer.rb
> +  after_save :update_legacy_balances
No, it's not a separate one

2019-08-08 13:14 UTC, dnfd commented on spec/api/v2/management/entities/transfer_spec.rb
> +                        .represent(record.reload.assets)
reference is a problem

2019-08-09 13:00 UTC, merged