Integrate vault-rails
openware/peatio pull request #2310
Opened 2019-08-07 12:25 UTC by dnfd

2019-08-07 13:31 UTC, ysv requested changes
- [x] I advice to use `vault_lazy_decrypt!`

- [x] Could we add some specs

2019-08-07 13:31 UTC, ysv commented on Gemfile
> +gem 'vault-rails', '~> 0.5.0', git: 'http://github.com/dnfd/vault-rails'
Ask owner if they are going to merge it soon
Otherwise we will probably fork it to rubykube

Also could you check pls that patch you applied on top of master doesn't contain vulnerabilities

2019-08-07 13:31 UTC, ysv commented on app/models/payment_address.rb
> +#  secret_encrypted  :string(255)
should be before timestamps

2019-08-07 13:31 UTC, ysv commented on app/models/wallet.rb
> +  SETTING_ATTRIBUTES.each do |accessor|
`.each do |attribute|` - looks better for me

2019-08-07 13:31 UTC, ysv commented on app/models/wallet.rb
> +      self.settings = self.settings.merge({ accessor.to_s => value })
I think you could use `.merge!` and avoid hash in params
```ruby
self.setting.merge!(attribute => value)
```

2019-08-07 13:31 UTC, ysv commented on config/initializers/vault.rb
> +
could we somehow avoid configuring in twice ?
May be we configure Vault and it will configure both of them ?

2019-08-07 13:31 UTC, ysv commented on db/migrate/20190807092706_add_encrypted_secret_to_payment_address.rb
> +    add_column :wallets, :settings_encrypted , :string
looks like you did not run migration for Wallet because model annotation was not updated

2019-08-07 13:31 UTC, ysv commented on db/migrate/20190807092706_add_encrypted_secret_to_payment_address.rb
> +  def change
- [ ] Put columns before timestamps

- [ ] What is the string limit for encrypted attribute ? May be default string(255) is too many or we need more for wallet settings which is actually a long string

- [ ] You can't just remove column you need to transfer existing data to vault before

2019-08-07 13:48 UTC, dnfd commented on Gemfile
> +gem 'vault-rails', '~> 0.5.0', git: 'http://github.com/dnfd/vault-rails'
https://github.com/hashicorp/vault-rails/pull/67#issuecomment-505481907

2019-08-07 14:33 UTC, dnfd commented on app/models/wallet.rb
> +      self.settings = self.settings.merge({ accessor.to_s => value })
I prefer `self.settings=`, it is a method call actually, and `merge!` modifies a hash returned, with `settings` getter method

2019-08-09 12:43 UTC, ysv requested changes

2019-08-09 12:43 UTC, ysv commented on app/models/wallet.rb
> +      update(settings: self.settings.merge(attribute.to_s => value))
`update` will save record in db ?

2019-08-09 12:43 UTC, ysv commented on app/models/wallet.rb
> +  # temporary solution
Start comment from capital letter and end with dot

2019-08-09 12:50 UTC, dnfd commented on app/models/wallet.rb
> +      update(settings: self.settings.merge(attribute.to_s => value))
I added specs :slightly_smiling_face:

2019-08-09 12:51 UTC, matass commented on config/initializers/vault.rb
> +  config.application = 'peatio'
Maybe fetch from ENV?

2019-08-09 13:06 UTC, ysv commented on config/initializers/vault.rb
> +  config.application = 'peatio'
yes we will do

2019-08-09 16:23 UTC, merged

2019-08-09 16:53 UTC, krtschmr commented
It seems like `Enterprise Platform` pricing is required otherwise no failover in case of emergency. What's pricing on that?