[WIP] Add adjustments
openware/peatio pull request #2325
Opened 2019-08-16 15:59 UTC by dnfd

2019-08-23 12:38 UTC, ysv requested changes

2019-08-23 12:38 UTC, ysv commented on app/api/v2/admin/adjustments.rb
> +          adjustment = Adjustment.new(declared(params))
does it mean that all admin can create adjustment ?
I think `authorize!` is missing

2019-08-23 12:38 UTC, ysv commented on app/api/v2/admin/adjustments.rb
> +          adjustment = Adjustment.find(params[:id])
I think `authorize!` is missing

2019-08-23 12:38 UTC, ysv commented on app/api/v2/admin/adjustments.rb
> +          adjustment = Adjustment.find(params[:id])
I think `authorize!` is missing

2019-08-23 12:38 UTC, ysv commented on app/api/v2/admin/adjustments.rb
> +          adjustment = Adjustment.find(params[:id])
I think `authorize!` is missing

2019-08-23 12:38 UTC, ysv commented on app/api/v2/admin/adjustments.rb
> +          authorize! :read, Adjustment
adjustment abilities are missing 
Update `app/models/abilities` and doc

2019-08-23 12:38 UTC, ysv commented on app/api/v2/admin/entities/adjustment.rb
> +          expose(
I would like to expose asset, liability, expense and revenue separately

2019-08-23 12:38 UTC, ysv commented on app/api/v2/admin/entities/adjustment.rb
> +            :asset_account_code,
counterpart_account_code I reckon

2019-08-23 12:38 UTC, ysv commented on app/api/v2/admin/entities/adjustment.rb
> +            :creator_id,
I think we need to expose uid

2019-08-23 12:38 UTC, ysv commented on app/api/v2/admin/entities/adjustment.rb
> +            :validator_id,
I think we need to expose uid

2019-08-23 12:38 UTC, ysv commented on app/models/adjustment.rb
> +  extend Enumerize
I prefer using AASM for state because of complexity

2019-08-23 12:38 UTC, ysv commented on app/models/adjustment.rb
> +  def accept(validator:)
rewrite with AASM ?

2019-08-23 12:38 UTC, ysv commented on app/models/adjustment.rb
> +  def accept!(validator:)
rewrite with AASM

2019-08-23 12:38 UTC, ysv commented on app/models/adjustment.rb
> +  def reject(validator:)
rewrite with AASM

2019-08-23 12:38 UTC, ysv commented on app/models/adjustment.rb
> +
I prefer adding has_one :asset, :liability, :revenue, :expense

2019-08-23 12:38 UTC, ysv commented on app/models/adjustment.rb
> +      next unless op.is_a? Operations::Liability
it's better to use liability here after adding has_one association

2019-08-23 12:38 UTC, ysv commented on app/models/adjustment.rb
> +  def update_legacy_balance
Also I'm thinking about moving this method to Operations module

2019-08-26 14:36 UTC, ysv requested changes

2019-08-26 14:36 UTC, ysv commented on app/models/adjustment.rb
> +    @operations = [
avoid using `@operations` variable

2019-08-26 14:36 UTC, ysv commented on app/models/adjustment.rb
> +    klass = Operations::Liability if code.starts_with?('2')
use Operations.klass_for(402) or Operations for account number

2019-08-26 14:36 UTC, ysv commented on app/models/adjustment.rb
> +    code, uid = counterpart_account_code.split('-')
counterpart_account_code also contains currency_id

2019-08-26 14:36 UTC, ysv commented on app/api/v2/admin/entities/adjustment.rb
> +            :asset_account_code,
I think we will expose it as 3 separate strings:
1. code (102)
2. uid (UID123445)
3. currency_id (BTC)

2019-08-26 14:36 UTC, ysv commented on app/api/v2/admin/adjustments.rb
> +          optional :counterpart_account_code
probably consists for 3 parts

2019-08-26 14:36 UTC, ysv commented on app/api/v2/admin/adjustments.rb
> +          requires :counterpart_account_code
probably consists for 3 parts

2019-08-26 14:36 UTC, ysv commented on app/api/v2/admin/adjustments.rb
> +          requires :name
1. Add params types
2. Add validation for params

2019-08-26 14:36 UTC, ysv commented on app/api/v2/admin/adjustments.rb
> +          counterpart_account_name = Adjustment.build_account_name(params[:currency_id], params[:counterpart_account_code], params[:counterpart_member_uid])
Operations.build_account_number(currency_id: , account_code: ...)
create app/models/operations.rb

2019-08-26 14:36 UTC, ysv commented on app/api/v2/admin/adjustments.rb
> +          adjustment = Adjustment.new(declared(params)
add creator here

2019-08-26 14:36 UTC, ysv commented on app/api/v2/admin/adjustments.rb
> +          counterpart_account_name = Adjustment.build_account_name(params[:currency_id], params[:counterpart_account_code], params[:counterpart_member_uid])
Since admin can change currency_id rebuild `counterpart_account_name` and update record

2019-08-26 14:36 UTC, ysv commented on app/models/adjustment.rb
> +  has_one :asset, -> { where(reference_type: 'Adjustment') }, class_name: 'Operations::Asset', foreign_key: :reference_id
Try something like this
```ruby
class Adjustment
  has_one :liability, as: :accountable
end

class Withdraw
  has_many :liability, as: :accountable
end

class Operations::Liability
  belongs_to :accountable, polymorphic: true
end
```

If this does not succeed 
1. Add comment why do we use scoping here
2. Add specs if they are missing

2019-08-26 14:36 UTC, ysv commented on app/models/adjustment.rb
> +      after do
1. try to use before here
2. remove error

2019-08-26 14:36 UTC, ysv commented on app/models/adjustment.rb
> +  def check_operations
remove this method and never does it

2019-08-26 14:36 UTC, ysv commented on app/models/adjustment.rb
> +    return prebuild_operations if pending? || rejected?
rewrite without return

2019-08-26 14:36 UTC, ysv commented on app/models/adjustment.rb
> +  def prebuild_operations
Implement from scratch

2019-08-26 14:36 UTC, ysv commented on app/api/v2/admin/adjustments.rb
> +        post '/adjustments/accept' do
/adjustements/action
```ruby 
# Pseudo code
params do
  requires :id
  # Optional: validate action depending on id. Probably AASM allows to list available events by 
state
# job.aasm.states(permitted: true).map(&:name)
#=> [:sleeping]
  requires :action, type: String
  given: :action do
    # if action accept requires something
    # if action reject requires other
  end
```

2019-08-26 14:36 UTC, ysv commented on app/models/adjustment.rb
> +  belongs_to :creator, class_name: :Member
required: true

2019-08-26 14:36 UTC, ysv commented on app/api/v2/admin/entities/adjustment.rb
> +            if: ->(adjustment, _options) { adjustment.creator }
remove

2019-08-26 14:36 UTC, ysv commented on app/api/v2/admin/entities/adjustment.rb
> +            :aasm_state,
remove aasm prefix

2019-08-26 14:36 UTC, ysv commented on app/api/v2/admin/entities/adjustment.rb
> +          expose(
expose as 3 separate parts

2019-08-26 14:36 UTC, ysv commented on app/models/adjustment.rb
> +  def load_operations
here it's also possible to revenue

2019-08-26 14:36 UTC, ysv commented on app/models/adjustment.rb
> +  def update_legacy_balance
https://github.com/rubykube/peatio/pull/2291/files

2019-08-26 14:36 UTC, ysv commented on app/models/adjustment.rb
> +  def fetch_operations
Optional
```ruby
%I[asset liability revenue expense].each do |op_type|
  define_method("fetch_#{op_type}") do
    ...
  end
end
```

2019-08-26 14:36 UTC, ysv commented on db/migrate/20190826024908_create_adjustments.rb
> +      t.string :counterpart_account_name, null: false, limit: 63
1. counterpart_account_number
2. Add comment what is number vs code in Operations module

2019-08-27 01:59 UTC, mnaichuk commented on app/api/v2/admin/adjustments.rb
> +        post '/adjustments/accept' do
Adjustment.aasm.states.map(&:name)

2019-08-27 12:19 UTC, ysv commented
@mnaichuk We have discussed adjustments with Business Analyst.
We don't need UPDATE of adjustments for now. So you can remove all related code

2019-08-27 13:05 UTC, ysv requested changes

2019-08-27 13:05 UTC, ysv commented on app/api/v2/admin/adjustments.rb
> +          adjustment.public_send("#{params[:action]}!", validator: current_user)
do we need to add TODO: here for cases when there will be some errors ?

2019-08-27 13:05 UTC, ysv commented on app/api/v2/admin/adjustments.rb
> +                   values: { value: -> { Adjustment.aasm.events.map(&:name).map(&:to_s) }, message: 'admin.adjustment.invalid_action' },
yeas but this will return all available events for Adjustment but you need for this record:
`Adjustment.find(params[:id]).events.map(&:name).map(&:to_s)` may be use given also here

2019-08-27 13:05 UTC, ysv commented on app/models/adjustment.rb
> +  extend Enumerize
1. Do we still need Enumerize ?
2. Use model structure
```
# == Constants ============================================================

  # == Attributes ===========================================================

  # == Extensions ===========================================================

  # == Relationships ========================================================

  # == Validations ==========================================================

  # == Scopes ===============================================================

  # == Callbacks ============================================================

  # == Class Methods ========================================================

  # == Instance Methods =====================================================
```

2019-08-27 13:05 UTC, ysv commented on app/models/adjustment.rb
> +          update_legacy_balance
I would like to see test case when `update_legacy_balance` raise error

2019-08-27 13:05 UTC, ysv commented on app/models/adjustment.rb
> +          prebuild_operations.map(&:valid?).exclude? false
1. I think it's good to validate operations on adjustment create also
2. prebuild_operations.map(&:valid?).all?(true)

2019-08-27 13:05 UTC, ysv commented on app/models/adjustment.rb
> +  def operations
do we need this method ?

2019-08-27 13:05 UTC, ysv commented on app/models/adjustment.rb
> +    # Should we return prebuild operations for `rejected` state?
`Should we return prebuild operations for `rejected` state?` - probably yes because we still want to show them on admin

2019-08-27 13:05 UTC, ysv commented on app/models/adjustment.rb
> +  def update_legacy_balance
Also I'm thinking about moving this method to Operations module !!!

2019-08-27 13:05 UTC, ysv commented on app/models/adjustment.rb
> +  class << self
do we need this one ?
Move to Operations

2019-08-27 13:05 UTC, ysv commented on app/models/adjustment.rb
> +  def load_operations
here it's also possible to contain revenue operation

2019-08-27 13:05 UTC, ysv commented on app/models/adjustment.rb
> +  def prebuild_operations
I would like to see more specs for this one. For all possible account pairs all possible amounts

2019-08-28 08:13 UTC, mnaichuk commented on app/api/v2/admin/adjustments.rb
> +                   values: { value: -> { Adjustment.aasm.events.map(&:name).map(&:to_s) }, message: 'admin.adjustment.invalid_action' },
> yeas but this will return all available events for Adjustment but you need for this record:
> `Adjustment.find(params[:id]).events.map(&:name).map(&:to_s)` may be use given also here

we can't get `params[:id]` inside params

2019-08-28 14:25 UTC, ysv requested changes

2019-08-28 14:25 UTC, ysv commented on app/api/v2/admin/adjustments.rb
> +        desc 'Update adjustment.',
let's remove it

2019-08-28 14:25 UTC, ysv commented on app/api/v2/admin/adjustments.rb
> +          adjustment.public_send("#{params[:action]}!", validator: current_user)
check if action is possible may_#{action}

2019-08-28 14:25 UTC, ysv commented on app/models/adjustment.rb
> +          Operations.update_legacy_balance(Operations::Liability.find_by(reference: self))
Operations.update_legacy_balance(liability)

2019-08-28 14:25 UTC, ysv commented on app/models/adjustment.rb
> +    event :fail do
remove pls

2019-08-28 14:25 UTC, ysv commented on app/models/adjustment.rb
> +    member = Member.find_by(uid: uid)
member = Member.find_by(uid: account_number_hash[:member_uid]) if account_number_hash.key?(:member_uid)

2019-08-28 14:25 UTC, ysv commented on app/models/adjustment.rb
> +    params.merge!(credit: debit.to_d, debit: credit.to_d) if klass == Operations::Expense
add comment to this one

2019-08-28 14:25 UTC, ysv commented on app/api/v2/admin/adjustments.rb
> +          optional :counterpart_member_uid,
counterpart_member_uid should be:
1. required in case of liability
2. optional in case of revenue
3. can't be in case of expense/asset

2019-08-28 14:25 UTC, ysv commented on app/models/adjustment.rb
> +    %i[liability revenue expense].each do |op_type|
operations << .map

2019-08-28 14:25 UTC, ysv commented on app/models/adjustment.rb
> +#  amount                     :decimal(10, )    not null
`:decimal(10, )` ?

2019-08-28 14:25 UTC, ysv commented on app/models/operations.rb
> +    def build_account_number(currency_id: nil, account_code: nil, member_uid: nil)
`currency_id: nil, account_code: nil` can't be nil

2019-08-28 14:25 UTC, ysv commented on db/migrate/20190826024908_create_adjustments.rb
> +      t.decimal :amount, null: false
change amount precision and scale

2019-08-28 14:25 UTC, ysv commented on db/migrate/20190826024908_create_adjustments.rb
> +      t.string :currency_id, null: false
index by currency & currency, state

2019-08-28 14:25 UTC, ysv commented on app/api/v2/admin/adjustments.rb
> +          use :currency
ability to filter by state

2019-08-28 14:25 UTC, ysv commented on app/models/adjustment.rb
> +  belongs_to :validator, class_name: :Member
add validator presence on all states except :pending

2019-08-28 14:25 UTC, ysv commented on spec/api/v2/admin/adjustments_spec.rb
> +    context 'with rejected/accepted' do
add specs with 
1. filtered states
2. currency filter
3. currency & state filete

2019-08-28 14:25 UTC, ysv commented on spec/api/v2/admin/adjustments_spec.rb
> +        counterpart_account_code: '202',
Why is it string ?
check in API

2019-08-28 14:25 UTC, ysv commented on spec/api/v2/admin/adjustments_spec.rb
> +  describe 'POST /api/v2/admin/adjustments/update' do
remove

2019-08-28 14:25 UTC, ysv commented on spec/api/v2/admin/adjustments_spec.rb
> +
add it 'return error'

2019-08-28 14:25 UTC, ysv commented on spec/api/v2/admin/adjustments_spec.rb
> +    context 'accepted' do
try to accept rejected adjustment

2019-08-28 14:25 UTC, ysv commented on spec/api/v2/admin/adjustments_spec.rb
> +    context 'rejected' do
try to reject accepted adjustment

2019-08-28 14:25 UTC, ysv commented on spec/models/adjustment_spec.rb
> +  subject { Adjustment.create(name: 'a',
use factories

2019-08-28 14:25 UTC, ysv commented on spec/models/adjustment_spec.rb
> +RSpec.describe Adjustment do
use describe without RSpec

2019-08-28 14:25 UTC, ysv commented on spec/models/adjustment_spec.rb
> +  context 'counterpart_account_number' do
check this specs

2019-08-29 07:16 UTC, ysv commented on app/models/adjustment.rb
> +  validates :validator, presence: { unless: :pending? }
Does it work, I did not see such usage before ?
May be it should be something like this:
```ruby
validates :validator, presence: true, if: ->(a){ !a.pending? }
```
Add spec for this one please

2019-08-29 07:16 UTC, ysv commented on app/models/operations.rb
> +  class << self
add TODO to write specs for this one

2019-08-29 07:17 UTC, ysv commented
Also add description & co-authors

2019-08-29 23:52 UTC, mod requested changes
Please try Active record enum like in beneficiaries
For category define enum

```
asset_registration
investment
minting_token
balance_anomaly
refund
compensation
incentive
bank_fees
bank_interest
minor
misc
```

I also reordered and renamed some fields
We need additional helpers or model method account_number
Account.create_number(code:...)
Account.validate_number
acc.to_number

I think account number limit 63 is a typo

2019-08-29 23:52 UTC, mod commented on app/models/adjustment.rb
> +#  name                       :string(255)      not null
#  creator_id                 :bigint           not null
#  validator_id               :bigint
#  reason                       :string(64)      not null
#  description                      TEXT
category integer size 1; unsigned
#  amount                     :decimal(32, 16)  not null
#  currency               :string(???)      not null
#  asset_account_code         :integer          not null
Limit 2, unsigned
#  receiving_account_number :string(63)       not null
#  state                 :string(255)      not null
Can try integer limit 1
#  created_at                 :datetime         not null
#  updated_at

2019-08-30 11:41 UTC, mnaichuk commented on app/models/adjustment.rb
> +  belongs_to :validator, class_name: :Member
https://github.com/rubykube/peatio/pull/2325/files#diff-2d61976dd4871bee34449bac8d255ebfR136

2019-08-30 22:39 UTC, ysv commented on app/api/v2/admin/adjustments.rb
> +          requires :reason,
I would like to validate reason in this step

2019-08-30 22:39 UTC, ysv commented on app/models/adjustment.rb
> +#  category                 :integer          unsigned
small int should be enough
integer, limit: 1

2019-08-30 22:39 UTC, ysv commented on spec/factories/adjustment.rb
> +    currency_id { :btc }
use `currency {Currency.all.sample}` because setting currency_id can cause mistakes

2019-09-01 06:43 UTC, ysv requested changes

2019-09-01 06:43 UTC, ysv commented on app/api/v2/admin/adjustments.rb
> +            binding.pry
1. binding.pry
2. since you forget it but CI is happy it means that there is no spec for this one so it should be added

2019-09-01 06:43 UTC, ysv commented on app/models/adjustment.rb
> +  validates :validator, presence: { unless: :pending? }
Does it work, I did not see such usage before ?
May be it should be something like this:
```ruby
validates :validator, presence: true, if: ->(a){ !a.pending? }
```
Add spec for this one please

2019-09-01 13:34 UTC, ysv approved these changes

2019-09-01 14:21 UTC, mod approved these changes

2019-09-01 14:22 UTC, merged