Add Admin and Management API for TradingFees
openware/peatio pull request #2334
Opened 2019-08-22 10:35 UTC by mnaichuk

2019-08-23 10:07 UTC, mnaichuk commented
- [ ] Add `data` to TradingFee

2019-08-28 01:16 UTC, mnaichuk commented on spec/api/v2/admin/trading_fees_spec.rb
> +describe API::V2::Management::TradingFees, type: :request do
Change to Admin module

2019-08-28 01:16 UTC, mnaichuk commented on spec/api/v2/admin/trading_fees_spec.rb
> +    it 'returns updated trading fee table with new group' do
With new markert

2019-08-28 01:16 UTC, mnaichuk commented on spec/api/v2/admin/trading_fees_spec.rb
> +    it 'returns updated trading fee table with new group' do
With new maker, taker

2019-08-28 01:16 UTC, mnaichuk commented on spec/api/v2/management/trading_fees_spec.rb
> +    it 'returns trading fee with btcusd market_id and vip-0 group' do
It returns all trading fees tables

2019-08-28 01:16 UTC, mnaichuk commented on app/api/v2/admin/trading_fees.rb
> +                   default: ::TradingFee::ANY,
Delete this

2019-08-28 01:28 UTC, mnaichuk commented on spec/api/v2/admin/trading_fees_spec.rb
> +  describe 'POST /trading_fees/new' do
add spec for creating new trading fees table without passing market and group id (creating default table).

2019-08-28 01:29 UTC, mnaichuk commented
Add description for this PR please.

2019-08-28 02:18 UTC, mnaichuk commented
Remove old columns in `admin/markets` views (show, index)

2019-08-28 02:23 UTC, mnaichuk commented
also we need /api/v2/public/trading_fees for FE are you agree @ysv

2019-08-28 14:30 UTC, ysv commented
> also we need /api/v2/public/trading_fees for FE are you agree @ysv
> Or we need join market with with current trading_fee for user when you log in and when you don't just don't show fees like in https://www.binance.com/en/trade/NEO_BTC
> 
> I suggest to add `maker/taker_fee` entity for `public/markets` and use `TradingFee.def for(group:, market_id:)` for fetching right trading_fee table with maker/taker_fee values @ysv @dnfd

yes we need it

2019-08-29 05:36 UTC, mnaichuk commented
> > also we need /api/v2/public/trading_fees for FE are you agree @ysv
> > Or we need join market with with current trading_fee for user when you log in and when you don't just don't show fees like in https://www.binance.com/en/trade/NEO_BTC
> > I suggest to add `maker/taker_fee` entity for `public/markets` and use `TradingFee.def for(group:, market_id:)` for fetching right trading_fee table with maker/taker_fee values @ysv @dnfd
> 
> yes we need it

so I will do in another patch

2019-08-29 09:28 UTC, ysv requested changes

2019-08-29 09:28 UTC, ysv commented on app/api/v2/admin/trading_fees.rb
> +        desc 'Creates new trading fees table',
it creates trading fees record

2019-08-29 09:28 UTC, ysv commented on app/api/v2/admin/trading_fees.rb
> +        desc 'Update trading fees table',
it updates trading fees record

2019-08-29 09:28 UTC, ysv commented on app/api/v2/admin/trading_fees.rb
> +        desc 'Deletes trading fees table',
it deletes trading fees record

2019-08-29 23:14 UTC, ysv approved these changes

2019-08-29 23:35 UTC, merged