Add Account Kind to Operation's response
openware/peatio pull request #2351
Opened 2019-09-02 16:01 UTC by dnfd

2019-09-03 05:51 UTC, mod commented on app/api/v2/admin/deposits.rb
> +          if deposit.fiat?
use a single switch case

2019-09-03 05:51 UTC, mod requested changes
we can reduce the case to a single one

2019-09-04 14:05 UTC, ysv requested changes

2019-09-04 14:05 UTC, ysv commented on app/api/v2/admin/withdraws.rb
> +          withdraw.update(txid: declared_params[:txid]) if declared_params[:txid].present?
We need to make this changes in single SQL transaction with 
`withdraw.public_send("#{declared_params[:action]}!")`

Something like
```ruby
  if withdraw.public_send("may_#{declared_params[:action]}?")
    withdraw.transaction do
      withdraw.update(txid: declared_params[:txid]) if declared_params[:txid].present?
      withdraw.public_send("#{declared_params[:action]}!")
    end 
  end
```

2019-09-04 14:05 UTC, ysv commented on app/api/v2/admin/deposits.rb
> +        desc 'Update deposit.',
Take action on the deposit

2019-09-04 14:05 UTC, ysv commented on app/api/v2/admin/withdraws.rb
> +        desc 'Update withdraw.',
Take action on the withdrawal

2019-09-04 14:05 UTC, ysv commented on app/api/v2/admin/entities/operation.rb
> +              desc: 'Operation\'s account type (locked or main).'
account kind

2019-09-04 14:05 UTC, ysv commented on spec/api/v2/admin/withdraws_spec.rb
> +      it 'load coin with txid' do
what if we try to load fiat with/without txid

2019-09-05 08:51 UTC, dnfd commented on spec/api/v2/admin/withdraws_spec.rb
> +      it 'load coin with txid' do
should it ignore txid or return error?

2019-09-05 10:05 UTC, dnfd commented on app/api/v2/admin/withdraws.rb
> +          withdraw.update(txid: declared_params[:txid]) if declared_params[:txid].present?
can be tricky, because transition guard in `if` statement disables setting `txid` with `update` if it is not set

2019-09-05 11:40 UTC, ysv commented on spec/api/v2/admin/withdraws_spec.rb
> +      it 'load coin with txid' do
better to return error

2019-09-05 11:49 UTC, ysv commented on app/api/v2/admin/withdraws.rb
> +          withdraw.update(txid: declared_params[:txid]) if declared_params[:txid].present?
I didn't get what you mean. 
I prefer doing it in transaction because it's how it was works in rails controller  https://github.com/rubykube/peatio/blob/master/app/controllers/admin/withdraws/coins_controller.rb#L68

And what is the logic if we load withdrawal with txid but withdraw state will not change but txid is set ? Could you test this one also pls

2019-09-05 12:55 UTC, dnfd commented on app/api/v2/admin/withdraws.rb
> +          withdraw.update(txid: declared_params[:txid]) if declared_params[:txid].present?
I mean I can't use suggested flow, I wrapped that into a transaction https://github.com/rubykube/peatio/blob/c17bbeece93f5bba5e2cf7d2f29eb5daf092e3f6/app/api/v2/admin/withdraws.rb#L78

2019-09-05 12:56 UTC, dnfd commented on spec/api/v2/admin/withdraws_spec.rb
> +      it 'load coin with txid' do
Spec for that https://github.com/rubykube/peatio/blob/c17bbeece93f5bba5e2cf7d2f29eb5daf092e3f6/spec/api/v2/admin/withdraws_spec.rb#L170

2019-09-05 14:02 UTC, ysv requested changes

2019-09-05 14:02 UTC, ysv commented on app/api/v2/admin/deposits.rb
> +            present deposit with API::V2::Admin::Entities::Deposit
Do you have at least single test for this ?
You are missing coma in arguments and test don't fail

2019-09-05 14:02 UTC, ysv commented on app/api/v2/admin/withdraws.rb
> +          transited = withdraw.transaction do
That is how I want it to behave

```ruby
  if withdraw.coin? && declared_params[:txid].present?
            body errors: ["admin.withdraw.redundant_txid"]
            status 422
          end

          transited = withdraw.transaction do
            withdraw.update!(txid: declared_params[:txid])
            raise ActiveRecord::Rollback unless withdraw.public_send("#{declared_params[:action]}!")
          end
```

2019-09-05 14:10 UTC, dnfd commented on app/api/v2/admin/withdraws.rb
> +          transited = withdraw.transaction do
Is txid required for load, dispatch and success, or it can remain optional?
Are there any other states which need txid?

2019-09-05 14:19 UTC, ysv commented on app/api/v2/admin/withdraws.rb
> +          transited = withdraw.transaction do
No it's not required 

> Is txid required for load, dispatch and success, or it can remain optional?

Looks like no for now
> Are there any other states which need txid?

2019-09-05 15:24 UTC, ysv approved these changes

2019-09-05 16:00 UTC, merged