Add details about fees in trade API
openware/peatio pull request #2363
Opened 2019-09-11 14:34 UTC by dnfd

2019-09-11 14:39 UTC, mod commented
I would show only maker_fee amount and currency

2019-09-11 14:43 UTC, ysv requested changes

2019-09-11 14:43 UTC, ysv commented on app/api/v2/admin/entities/trade.rb
> +          ) { |trade| trade.maker_order.maker_fee * trade.maker_order.funds_received }
it's wrong see here how I fetch it https://github.com/rubykube/peatio/pull/2337/files#diff-7a3e5fe6af9dc29d3988d79ced7b0cd3

2019-09-11 14:43 UTC, ysv commented on app/api/v2/admin/entities/trade.rb
> +          ) { |trade| trade.taker_order.taker_fee * trade.taker_order.funds_received }
it's wrong see here how I fetch it https://github.com/rubykube/peatio/pull/2337/files#diff-7a3e5fe6af9dc29d3988d79ced7b0cd3

2019-09-11 14:44 UTC, ysv requested changes
Add tests

2019-09-12 19:29 UTC, ysv commented on app/api/v2/entities/trade.rb
> +        expose(
Also add fee & fee currency

2019-09-12 21:03 UTC, ysv approved these changes

2019-09-13 10:09 UTC, merged