Crash daemons on Mysql connection error
openware/peatio pull request #2367
Opened 2019-09-17 13:17 UTC by dnfd

2019-09-17 13:53 UTC, ysv requested changes
1. Avoid code copy-paste.
You can define method for avoiding copy-paste `db_connection_error?(e)` 
```ruby
raise e if db_connection_error?(e)
```

2. Test it locally please

2019-09-17 13:53 UTC, ysv commented on app/workers/amqp/deposit_coin_address.rb
> +        raise e if e.is_a?(Mysql2::Error::ConnectionError) || e.cause.is_a?(Mysql2::Error::ConnectionError)
That is how it was done and tested before https://github.com/rubykube/peatio/pull/2231/files#diff-b41435130afbb55bcfbae9825c262322R32 check that you cover all situations pls

2019-09-18 09:14 UTC, ysv approved these changes

2019-09-18 16:26 UTC, mod approved these changes

2019-09-18 16:26 UTC, merged