Add visible, deposit_enabled, withdrawal_enabled columns to Currency
openware/peatio pull request #2374
Opened 2019-09-23 11:47 UTC by mnaichuk

…model

2019-09-24 11:33 UTC, ysv requested changes

2019-09-24 11:33 UTC, ysv commented on app/models/currency.rb
> +  scope :withdrawal_enabled, -> { where(withdrawal_enabledz: true) }
`withdrawal_enabledz` 

Please add specs for this scopes to make sure we don't have mistake

2019-09-24 11:33 UTC, ysv commented on db/schema.rb
> +    t.index ["visible"], name: "index_currencies_on_enabled_and_code"
looks wrong for me

2019-09-24 11:33 UTC, ysv commented on app/api/v2/account/withdraws.rb
> +            error!({ errors: ['account.currency.withdrawal_disabled'] }, 422)
Think if we need this validation in beneficiaries controller also

2019-09-24 11:33 UTC, ysv commented on app/models/account.rb
> +  scope :enabled, -> { joins(:currency).merge(Currency.where(visible: true)) }
I would prefer renaming this to visible if possible

2019-09-24 11:33 UTC, ysv commented on app/models/currency.rb
> +  scope :enabled, -> { where(visible: true) }
I would prefer renaming this to visible if possible

2019-09-26 09:55 UTC, mod requested changes
Check if rails / mysql support binary mask

2019-09-26 09:55 UTC, mod commented on app/models/currency.rb
> +#  withdrawal_enabled    :boolean          default(TRUE), not null
We could see if we can use binary mask
Like
enabled = DEPOSIT | WITHDRAWAL

2019-09-26 14:19 UTC, ysv commented on app/api/v2/admin/helpers.rb
> +                   values: { value: -> { Currency.visible.codes(bothcase: true) }, message: 'admin.currency.doesnt_exist' },
This param and it's usage seems strange for me 
I think admin should see all currencies 
Please double check

May be we need to add specs for this one ?

2019-09-26 14:19 UTC, ysv commented on app/models/currency.rb
> +    !visible
Check if we still use this one

2019-09-26 14:19 UTC, ysv commented on app/models/currency.rb
> +#  withdrawal_enabled    :boolean          default(TRUE), not null
I was thinking about this kind of solution but we decided to keep it simple.
I reckon that we can avoid optimization on this table because it does not look like someone is gonna have more than 200 record here

2019-09-26 16:44 UTC, ysv approved these changes

2019-09-26 17:05 UTC, mod approved these changes

2019-09-26 17:06 UTC, merged