Reraise errors in #submit and #cancel methods
openware/peatio pull request #2375
Opened 2019-09-23 14:17 UTC by dnfd

2019-09-24 11:44 UTC, ysv requested changes

2019-09-24 11:44 UTC, ysv commented on lib/daemons/amqp_daemon.rb
> +      terminate.call() if worker.is_db_connection_error?(e)
This will finish process with status 0 and inside k8s it will look like successfully finished pod but we want error here and non zero status

2019-09-24 16:33 UTC, mnaichuk requested changes

2019-09-24 16:33 UTC, mnaichuk commented on lib/daemons/amqp_daemon.rb
> +        logger.error(db: :unhealthy, message: e.message)
same for ruby daemons, please

2019-09-25 09:13 UTC, ysv approved these changes

2019-09-25 09:19 UTC, mnaichuk approved these changes

2019-09-25 10:08 UTC, mod approved these changes

2019-09-25 10:08 UTC, merged