Support beneficiary_id in management API create withdraw
openware/peatio pull request #2378
Opened 2019-09-27 15:50 UTC by shal

2019-09-27 16:06 UTC, ysv requested changes

2019-09-27 16:06 UTC, ysv commented on app/api/v2/management/withdraws.rb
> +
1. need to validate  that beneficiary exists before with active state
2. We need to add check that withdraw is enabled for this coin (same for deposits)
3. use `merge`

2019-09-30 15:26 UTC, ysv approved these changes

2019-09-30 16:32 UTC, mod approved these changes

2019-09-30 16:32 UTC, merged