Ability to edit market through management API
openware/peatio pull request #2384
Opened 2019-10-02 15:23 UTC by shal

2019-10-03 17:50 UTC, mnaichuk requested changes

2019-10-03 17:50 UTC, mnaichuk commented on app/api/v2/management/markets.rb
> +end
add an empty line, please

2019-10-04 09:57 UTC, mnaichuk approved these changes

2019-10-04 13:24 UTC, ysv approved these changes

2019-10-04 18:03 UTC, mod approved these changes

2019-10-04 18:03 UTC, merged