Feature: Add tid to /account deposits endpoints
openware/peatio pull request #2393
Opened 2019-10-24 16:24 UTC by Anna-Kulakova

2019-10-28 11:18 UTC, ysv requested changes

2019-10-28 11:18 UTC, ysv commented on app/api/v2/entities/deposit.rb
> +            desc: 'term ID'
The shared transaction ID

2019-10-28 18:35 UTC, ysv approved these changes

2019-11-01 11:08 UTC, pkucherenk0 commented
Why only Deposit endpoint?
On Withdrawal we also have tid and its used for withdrawal succeed email.

2019-11-12 17:21 UTC, merged