remove two-factor verification
openware/peatio pull request #24
Opened 2017-11-21 10:06 UTC by vpetrusenko

2017-11-21 11:08 UTC, dmk requested changes
Looks good, but needs to be updated
Also please remove two-factor tests

2017-11-21 11:08 UTC, dmk commented on config/routes.rb
> +  #resources :two_factors, only: [:show, :index, :update]
just remove this line

2017-11-21 11:08 UTC, dmk commented on config/routes.rb
> +   ; post '/pusher/auth', to: 'pusher#auth'
I think it's wrong :)

2017-11-21 11:08 UTC, dmk commented on config/routes/admin.rb
> +    #resources :two_factors, only: [:destroy]
remove

2017-11-21 11:33 UTC, yivo commented
@vpetrusenko have you removed gem dependencies related to this feature?

2017-11-21 11:34 UTC, yivo commented
@vpetrusenko Also could you please check that tests are not broken?

2017-11-23 11:33 UTC, yivo commented
@vpetrusenko Why there are 2 the same PRs? https://github.com/rubykube/peatio/pull/25

2017-11-23 15:15 UTC, vpetrusenko commented
@yivo sorry have some troubles with this PR , make some changes in new PR

2017-11-24 00:05 UTC, closed without merging