Add ability to set member group, select member by uid and get all exi…
openware/peatio pull request #2401
Opened 2019-11-06 11:46 UTC by mnaichuk

…sting groups

2019-11-11 16:15 UTC, pkucherenk0 commented
1. We probably should add search by group.
2. We probably shouldn't allow space or empty group (`" "`, `""`). We might dont want all symbols to be allowed. 
3. We might want to expose group to a user private api (user will be able to identify fees level) public api (users will be able to know the level system). Off course if there is no applogic to do it but i think peatio should expose thous.

2019-11-11 23:34 UTC, martianatwork commented
I have a suggestion, 
We should be able to track back the fees group of the user, we can define fees group id in orders table.

2019-11-12 07:42 UTC, ysv requested changes

2019-11-12 07:42 UTC, ysv commented on app/models/member.rb
> +      Member.pluck(:group).uniq
I disagree with this 
1. To fetch all available member groups you should use `FeeGroup.pluck(:group)`

2. What is more I think right solution would be to select uniq on MySQL side
May be `Model.pluck("DISTINCT rating")`

3. Don't forget to append 'any'

2019-11-15 10:21 UTC, ysv approved these changes

2019-11-15 14:08 UTC, merged

2019-12-06 11:17 UTC, ysv commented
@martianatwork I would agree but what is the purpose of it ?
Since group, maker & taker may change it does not make sense to store reference to group that is why we store only fee percentage
It's still not ideal but we store  the most important data

2019-12-06 12:47 UTC, martianatwork commented
@ysv 
currently we have to perform some logic to get the member's old group which slows down overall process.

It will be great to have an analytical data and easier way for the marketing team to see the performance of the marketing strategy or a fees group. 
this is based on our experience but i think other people will require the same as they grow.