Fueature: rake tasks for drop accounting and extract configs
openware/peatio pull request #2426
Opened 2019-12-05 15:32 UTC by ymasiuk

2019-12-05 16:31 UTC, mod commented on lib/tasks/database.rake
> +namespace :database do
maybe

clear:accounting

2019-12-06 11:06 UTC, ysv requested changes

2019-12-06 11:06 UTC, ysv commented on lib/tasks/clear.rake
> +  desc 'Clear accounting.'
could you write more explicit description because this one is not clear for me

2019-12-06 11:06 UTC, ysv commented on lib/tasks/clear.rake
> +    table_names = ['accounts', 'adjustments', 'assets', 'beneficiaries',
accounting_tables = %w[accounts adjustments ...]

2019-12-06 11:06 UTC, ysv commented on lib/tasks/export.rake
> +    result = ActiveRecord::Base.connection.exec_query("SELECT * FROM blockchains").to_hash
`Blockchain.all.map { |b| b.attributes.except('created_at', 'updated_at') }` - use this variant for other models also

2019-12-06 11:06 UTC, ysv commented on lib/tasks/export.rake
> +       file.write result.to_yaml
Make sure that generated yml is human readable

2019-12-06 11:06 UTC, ysv commented on lib/tasks/export.rake
> +    File.open("config/seed/blockchains.yml","w") do |file|
I'm not sure that we want to rewrite existing blockchains.yml

2019-12-06 11:06 UTC, ysv commented on lib/tasks/export.rake
> +      w['settings'] = Wallet.find_by(address: w['address']).settings
looks strange for me

2019-12-06 11:06 UTC, ysv commented on lib/tasks/export.rake
> +# encoding: UTF-8
as far as I can see the process of exporting is pretty same for all models so I advice to make single method which receive argument(s)
```ruby
def export(model_name)
  # 1. select all objects and store them as array of hashes
  # 2. remove timestamp columns
  # 3. format BigDecimal values
end
```

2019-12-06 11:17 UTC, dnfd commented on lib/tasks/clear.rake
> +  desc 'Clear accounting.'
Nice pun :D

2020-02-07 16:58 UTC, mnaichuk approved these changes

2020-02-07 17:03 UTC, ysv approved these changes

2020-02-11 20:18 UTC, mod approved these changes

2020-02-11 20:19 UTC, merged