Remove :touch_account after currency creation
openware/peatio pull request #2429
Opened 2019-12-16 16:03 UTC by mnaichuk

2019-12-17 10:44 UTC, ysv requested changes

2019-12-17 10:44 UTC, ysv commented on app/models/currency.rb
> -  after_create { Member.find_each(&:touch_accounts) }
It's gonna fail in two cases:
1. User tries to create payment address but account does not exist yet
2. User get credite in trading executor but account does not exist yet

2019-12-17 10:49 UTC, ysv commented
I advice to create account on fly if one doesn’t exist:
```ruby
class Account
  def self.change_balance(member_id, currency_id, amount, locked)
    # use something like upsert here https://medium.com/@retrorubies/upcoming-rails-6-bulk-insert-upsert-feature-2d642419557d
  end
end
```

2020-02-11 20:20 UTC, mod commented
Is this relevant ?

2020-02-12 08:47 UTC, ysv approved these changes

2020-02-12 09:45 UTC, merged