Features and improvements pack
openware/peatio pull request #2433
Opened 2019-12-30 17:43 UTC by baturich

* Close TODOs in Dockerfile (COPY chown)
* Improve performance of concurrency tools (concurrent-ruby-ext gem providing native concurrency C extension)
* Add support to NewRelic Application Performance Monitoring (we prefer this over Scout)
* AMQP: Add ability to configure auto_delete option, queue length and pass custom arguments (at last max queue length is required to make sure RabbitMQ doesn't crash in case lot of messages are being stuck)
* Close TODOs in User API JWT authenticator (use UID instead of email)
* Drop unused CSS classes
* Add specs to Operations. build_account_number
* Add hot reload to Workers:: Daemons:: Blockchain (close TODO)
* Enable JS compressor (it was disabled)
* Use optimized JSON parses in Grape (20-50% improvement), allow to customize
* Add specs to Ethereum::Wallet#prepare_deposit_collection (close TODO)
* Fixed few errors in words and few code formatting issues

2019-12-30 17:47 UTC, baturich commented
Hey there

We recently started with Peatio deployment and found few things which could be improved.

2019-12-30 17:47 UTC, baturich commented
Attaching RSpec logs

```
Randomized with seed 54586
.......................................................................................................................................................................................................*............................................................................................................................................................................................................................................**.*..............****...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................***......................................................................................................................................................................................................................................................................................................................*.................................................................................................................................................................................................................................................................................................................................

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Admin::MarketsController#update updates market attributes
     # Temporarily skipped with xit
     # ./spec/controllers/admin/markets_controller_spec.rb:63

  2) Withdraw coin withdraw #audit! should accept withdraw with clean history
     # Temporarily skipped with xit
     # ./spec/models/withdraw_spec.rb:64

  3) Withdraw coin withdraw #audit! should be rejected if address is invalid
     # Temporarily skipped with xit
     # ./spec/models/withdraw_spec.rb:29

  4) Withdraw coin withdraw #audit! sum less than quick withdraw limit should approve quick withdraw directly
     # Temporarily skipped with xit
     # ./spec/models/withdraw_spec.rb:72

  5) Withdraw CashAddr valid CashAddr address
     # Temporarily skipped with xit
     # ./spec/models/withdraw_spec.rb:590

  6) Withdraw CashAddr valid legacy address
     # Temporarily skipped with xit
     # ./spec/models/withdraw_spec.rb:603

  7) Withdraw CashAddr invalid legacy address
     # Temporarily skipped with xit
     # ./spec/models/withdraw_spec.rb:608

  8) Withdraw CashAddr invalid CashAddr address
     # Temporarily skipped with xit
     # ./spec/models/withdraw_spec.rb:595

  9) API::V2::Account::Deposits GET /api/v2/account/deposit_address/:currency successful return cash address
     # Temporarily skipped with xit
     # ./spec/api/v2/account/deposits_spec.rb:149

  10) API::V2::Account::Deposits GET /api/v2/account/deposit_address/:currency successful doesn't expose sensitive data
     # Temporarily skipped with xit
     # ./spec/api/v2/account/deposits_spec.rb:144

  11) API::V2::Account::Deposits GET /api/v2/account/deposit_address/:currency successful return legacy address
     # Temporarily skipped with xit
     # ./spec/api/v2/account/deposits_spec.rb:154

  12) Admin::WalletsController#update updates wallet attributes
     # Temporarily skipped with xit
     # ./spec/controllers/admin/wallets_controller_spec.rb:50


Finished in 18 minutes 21 seconds (files took 2.81 seconds to load)
1648 examples, 0 failures, 12 pending

Randomized with seed 54586```

2019-12-30 18:17 UTC, mod commented on app/api/v2/constraints.rb
> +            req.env['api_v2.authentic_member_uid']
Could explain this change,
We are moving to a rack middleware I think there is a pull request related

2019-12-30 18:45 UTC, baturich commented on app/api/v2/constraints.rb
> +            req.env['api_v2.authentic_member_uid']
@mod I followed this TODO https://github.com/openware/peatio/blob/master/app/api/v2/auth/middleware.rb#L11

Now I see rack-jwt in pull requests. Do you want me to rollback that change?

2019-12-31 16:34 UTC, baturich commented on app/api/v2/constraints.rb
> +            req.env['api_v2.authentic_member_uid']
@mod I removed UID change.

2020-02-07 01:38 UTC, baturich commented
Hey guys
Any updates? Why it's taking so long to merge small PR?

@mod @ysv @mnaichuk @chumaknadya

2020-02-13 16:44 UTC, mod commented
@baturich Hello can you contact me on telegram: t.me/modhelios

2020-03-19 13:25 UTC, mod commented
@akulakovaa can you rebase, remove new_relic, oj/grape changes,

2020-03-19 13:26 UTC, mod requested changes

2020-03-19 13:26 UTC, mod commented on app/workers/daemons/blockchain.rb
>      class Blockchain < Base
remove this change

2020-03-19 14:36 UTC, closed without merging