Feature: Rake task for revert trading activity for particular user
openware/peatio pull request #2437
Opened 2020-01-15 10:06 UTC by mnaichuk

2020-01-15 10:42 UTC, mod requested changes
Revert must be in Member model

2020-01-15 14:35 UTC, ysv commented on app/models/member.rb
> +    trades.each do |t|
Jut for you to not forget )
`trades.each(&:revert_trade)`

2020-01-15 14:35 UTC, ysv commented on app/models/member.rb
> +      term = "%#{term}%"
nice solution !

2020-01-15 14:35 UTC, ysv commented on lib/tasks/revert.rake
> +    # For each trade create revert Liabilities, Revenues and update User balances
as an option you may pass trade ids through environment (same as member_email)

2020-01-15 14:35 UTC, ysv commented on spec/lib/tasks/revert_spec.rb
> +Rails.application.load_tasks
It's better you test either Trade #revert_trade or Member #revert_trades!

2020-02-10 11:08 UTC, ysv approved these changes

2020-02-11 20:17 UTC, mod approved these changes

2020-02-11 20:17 UTC, merged