Add ability to filter zero user balances
openware/peatio pull request #2444
Opened 2020-02-07 07:43 UTC by dpatsora

2020-02-07 07:46 UTC, dpatsora commented on app/api/v2/account/balances.rb
> +            present paginate(current_user.accounts.visible.ordered.where.not(balance: 0)),
where.not(balance: 0, locked: 0)?

2020-02-07 07:55 UTC, mnaichuk requested changes

2020-02-07 07:55 UTC, mnaichuk commented on app/api/v2/account/balances.rb
> +          if params[:not_empty] == "true"
Add validations for this param.

2020-02-07 07:55 UTC, mnaichuk commented on app/api/v2/account/balances.rb
> +            present paginate(current_user.accounts.visible.ordered.where.not(balance: 0)),
Or you can write like `where('balance != 0')` but it's up to you

2020-02-07 07:55 UTC, mnaichuk commented on spec/api/v2/account/balances_spec.rb
> +    context 'not nil balances' do
non zero balances

2020-02-07 07:55 UTC, mnaichuk commented on spec/api/v2/account/balances_spec.rb
> +        expect(result).to contain_exactly(
something wrong with your indentation

2020-02-07 12:11 UTC, mnaichuk requested changes

2020-02-07 12:11 UTC, mnaichuk commented on app/api/v2/account/balances.rb
> +                   values: { value: ["true", "false"], message: 'not allowed'},
value: %w(true false)
And fix error message it should be dot separated like here https://github.com/openware/peatio/pull/2444/files#diff-329848d08811e38fcdf3da1955c974ffR42

2020-02-07 12:11 UTC, mnaichuk commented on spec/api/v2/account/balances_spec.rb
> +      it { expect(response).to have_http_status 200 }
please add specs for negative scenarios

2020-02-07 12:11 UTC, mnaichuk commented on app/api/v2/account/balances.rb
> +                   values: { value: ["true", "false"], message: 'not allowed'},
Add there is Boolean type for Grape validators

2020-02-07 12:11 UTC, mnaichuk commented on app/api/v2/account/balances.rb
> +                   values: { value: ["true", "false"], message: 'not allowed'},
Also please set a default value

2020-02-07 12:13 UTC, mnaichuk requested changes

2020-02-07 12:13 UTC, mnaichuk commented on app/api/v2/account/balances.rb
> +                   type: String,
And then you can rewrite condition with a boolean value

2020-02-07 15:46 UTC, mnaichuk requested changes

2020-02-07 15:46 UTC, mnaichuk commented on spec/api/v2/account/balances_spec.rb
> +    context 'use non_empty parameter == false' do
and with non boolean value

2020-02-26 12:09 UTC, mnaichuk requested changes

2020-02-26 12:09 UTC, mnaichuk commented on app/api/v2/account/balances.rb
> +          optional :not_empty,
please use another name

2020-03-02 15:16 UTC, mnaichuk commented on app/api/v2/account/balances.rb
> +                   type: { value: Boolean, message: 'account.balances.non_expected_value' },
invalid_nonzero

2020-03-02 15:17 UTC, mnaichuk requested changes

2020-03-02 15:17 UTC, mnaichuk commented on app/api/v2/account/balances.rb
> +                   type: { value: Boolean, message: 'account.balances.non_expected_value' },
invalid_nonzero

2020-03-06 12:53 UTC, ysv approved these changes

2020-03-06 14:38 UTC, mnaichuk approved these changes

2020-03-06 14:43 UTC, merged