Enhancement: Add validation for trading fees
openware/peatio pull request #2464
Opened 2020-03-02 13:09 UTC by chumaknadya

2020-03-02 17:38 UTC, mod requested changes
there is no point of rejecting things like "Any" or "Any   " or "   ANY   "

you must clean the string and lowercase it
No need to reject at API level, especially it will break since current tower change case by mistake

2020-03-03 09:28 UTC, mnaichuk requested changes
Also, put validation for setting user group

2020-03-03 09:28 UTC, mnaichuk commented on app/models/blockchain.rb
> +  before_create { self.key = self.key.downcase }
please put strip here too

2020-03-03 09:28 UTC, mnaichuk commented on app/models/trading_fee.rb
> +  before_create { self.group = self.group.downcase }
please put strip here too

2020-03-03 09:28 UTC, mnaichuk commented on app/models/transfer.rb
> +  before_create { self.key = self.key.downcase }
please put strip here too

2020-03-03 10:00 UTC, mnaichuk approved these changes

2020-03-06 14:46 UTC, merged