Enhancement: Delete total header from admin API endpoints
openware/peatio pull request #2468
Opened 2020-03-03 13:42 UTC by chumaknadya

2020-03-03 14:19 UTC, mnaichuk requested changes
For adjustments, blockchains, currencies, makrets, members, trading_fees and wallets we can keep.
We need for tables with a large amount of data like all operations, order and trades.

2020-03-03 14:19 UTC, mnaichuk commented on app/api/v2/helpers.rb
> +      def paginate(collection, options = {})
use can set here default for true

2020-03-03 14:19 UTC, mnaichuk commented on app/api/v2/helpers.rb
> +        include_total   = options[:include_total].nil? ? ApiPagination.config.include_total : options[:include_total]
and put here only options check if we pass false it will not include if it use true it will incude

2020-03-03 15:59 UTC, mnaichuk approved these changes

2020-03-03 23:53 UTC, mod requested changes
If I understand you copied and modified helper paginate from the gem ?
Do we need the gem at all ?
How will be the usage with just Kaminari

This code doesn't feel right

2020-03-05 14:12 UTC, mnaichuk requested changes

2020-03-05 14:12 UTC, mnaichuk commented on app/api/v2/helpers.rb
> +        per_page = params[:limit].present? ? params[:limit].to_i : Kaminari.config.default_per_page
par_page = params[:limit] || Kaminari.config.default_per_page

2020-03-06 14:46 UTC, merged