Remove sign in and sign up
openware/peatio pull request #252
Opened 2018-01-09 13:00 UTC by vpetrusenko

2018-01-10 00:38 UTC, yivo requested changes
- [ ] no migrations for password column, tokens, password resets and lot more stuff. Please install connect to mysql server and check what schema we have.
- [ ] Auth using OAuth protocol should be kept.
- [ ] Tests for signin & signup should be removed, existing tests which use signin should be updated.
- [ ] lot of views related to signin/up are still in the project
Please, use IDE.

2018-01-10 00:38 UTC, yivo commented on Gemfile
> -gem 'omniauth',               '~> 1.2.1'
@vpetrusenko You should keep this gem. It is necessary for OAuth to work. We don't need `omniauth-identity` anymore.

2018-01-10 00:38 UTC, yivo commented on app/controllers/identities_controller.rb
>    before_filter :auth_anybody!, only: :new
@vpetrusenko We probably don't need this controller at all.

2018-01-10 00:38 UTC, yivo commented on app/views/welcome/index.html.erb
>        <% offset -= 2 if ENV['GOOGLE_OAUTH2_SIGN_IN'] %>
@vpetrusenko I will help you with styling these buttons. We need only to update offsets.

2018-01-10 00:38 UTC, yivo commented on config/initializers/omniauth.rb
> -module OmniAuth
@vpetrusenko This is OK. No more `identity` strategy should exist.

2018-01-10 00:38 UTC, yivo commented on config/initializers/omniauth.rb
> -OmniAuth.config.on_failure = lambda do |env|
@vpetrusenko This should be kept.

2018-01-10 00:38 UTC, yivo commented on config/initializers/omniauth.rb
> -OmniAuth.config.logger = Rails.logger
@vpetrusenko This should be kept.

2018-01-10 00:38 UTC, yivo commented on db/migrate/20130810162023_create_reset_passwords.rb
> -class CreateResetPasswords < ActiveRecord::Migration
@vpetrusenko Stop! Migrations are READONLY. Don't delete them!.

2018-01-10 16:06 UTC, yivo requested changes

2018-01-10 16:06 UTC, yivo commented on config/routes.rb
>    namespace :authentications do
@vpetrusenko We can remove this set of routes completely and also remove `AuthenticationsController`.

2018-01-10 16:06 UTC, yivo commented on config/routes.rb
>    scope :constraints => { id: /[a-zA-Z0-9]{32}/ } do
@vpetrusenko This set of routes can also be removed.

2018-01-10 18:49 UTC, vpetrusenko commented on config/routes.rb
>    scope :constraints => { id: /[a-zA-Z0-9]{32}/ } do
@yivo it's done

2018-01-11 12:09 UTC, yivo requested changes

2018-01-11 12:09 UTC, yivo commented on Gemfile
> -gem 'omniauth',               '~> 1.8.1'
@vpetrusenko please bring back this gem!

2018-01-11 12:09 UTC, yivo commented on Gemfile
>  gem 'omniauth-identity',      '~> 1.1.1'
@vpetrusenko remove this gem

2018-01-11 12:09 UTC, yivo commented on config/routes.rb
>    scope :constraints => { id: /[a-zA-Z0-9]{32}/ } do
@vpetrusenko fully remove this

2018-01-12 17:44 UTC, yivo approved these changes

2018-01-15 16:49 UTC, merged