Feature: Impove user addresses generation for ETH and ERC20
openware/peatio pull request #2575
Opened 2020-05-25 18:22 UTC by mnaichuk

2020-08-13 18:27 UTC, calj commented on spec/api/v2/admin/wallets_spec.rb
> +      api_post '/api/v2/admin/wallets/new', params: { name: 'Test', kind: 'deposit', currencies: 'eth', address: 'blank', blockchain_key: 'btc-testnet', gateway: 'geth', settings: { uri: 'http://127.
is currencies a coma separated array?
you should add a test or two with an array example

2020-08-17 09:33 UTC, ysv commented on app/api/v2/admin/wallets.rb
> +          optional :currencies,
Is it gonna filter by all currencies ? Like wallet should have :eth,:usdt currencies only then API will return it ? If yes then I'm not 100% sure it's convenient filter

2020-08-17 09:33 UTC, ysv commented on app/api/v2/admin/wallets.rb
> +                   values: { value: ->(v) { [*v].all? { |value| value.in? ::Currency.codes } }, message: 'admin.wallet.currency_doesnt_exist' },
It's recommended to use `Array.wrap` instead of `[*v]` https://apidock.com/rails/Array/wrap/class

2020-08-17 09:33 UTC, ysv commented on app/api/v2/admin/wallets.rb
> +                   values: { value: ->(v) { [*v].all? { |value| value.in? ::Currency.codes } }, message: 'admin.wallet.currency_doesnt_exist' },
It's recommended to use `Array.wrap` instead of `[*v]` https://apidock.com/rails/Array/wrap/class

2020-08-17 09:33 UTC, ysv commented on app/api/v2/admin/wallets.rb
> +          requires :currencies,
Personally I would also support legacy currency attribute for some time so FE isn't broken if we deploy new peatio with old FE and we don't have this version compatibility issue

2020-08-17 09:33 UTC, ysv commented on app/models/currency.rb
> +  def validate_options
I would migrate options to MySQL JSON column using string here is a bit strange because we have native JSON support
It may be done in separate PR

2020-08-17 09:33 UTC, ysv commented on app/models/currency_wallet.rb
> +class CurrencyWallet < ApplicationRecord
1. frozen string
2. Schema annotation is missing
3. `validates :currency_id, uniqueness: { scope: :wallet_id }` 

But what if we have 2 wallets:
- Ethereum deposit 
- Ethereum hot

Then we should have 2 CurrencyWallet records with the same currency_id. Am I right ?

2020-08-17 09:33 UTC, ysv commented on app/api/v2/account/deposits.rb
> +          wallet = Wallet.deposit.joins(:currencies).find_by('currencies.id': currency.id)
1. I would move it into scope because I see this code repetition a lot of times
2. Also `Wallet.deposit.joins(:currencies).find_by(currencies: {id: currency.id})` - as for me is more rails syntax but it's not as important

2020-08-17 09:33 UTC, ysv commented on app/workers/amqp/deposit_coin_address.rb
> +        return unless member
move `return unless member` before `wallet = Wallet.find_by_id(payload[:wallet_id])`

2020-08-21 08:39 UTC, mnaichuk commented on app/models/currency_wallet.rb
> +class CurrencyWallet < ApplicationRecord
yes you are right

2020-08-31 21:09 UTC, ysv commented on app/api/v2/admin/entities/wallet.rb
> +            :currency_ids,
type should be changed isn't it ? to array ?

2020-08-31 21:09 UTC, ysv commented on app/api/v2/admin/wallets.rb
> +                   types: [String, Array], coerce_with: ->(c) { [*c] },
in coerce_with you can also use Array.wrap

2020-08-31 21:09 UTC, ysv commented on app/api/v2/admin/wallets.rb
> +                   values: { value: ->(v) { Array.wrap(v).all? { |value| value.in? ::Currency.codes } }, message: 'admin.wallet.currency_doesnt_exist' },
as performance improvement you can do the next. Check other similar places also

```ruby
(Array.wrap(v) - ::Currency.codes).blank?
```

2020-08-31 21:09 UTC, ysv commented on app/api/v2/admin/wallets.rb
> +          exactly_one_of :currencies, :currency, message: 'admin.wallet.missing_currency_or_currencies_fields'
Minor: error message is not clear

2020-08-31 21:09 UTC, ysv commented on app/api/v2/admin/wallets.rb
> +            c_w = CurrencyWallet.new(currency_id: c_id, wallet_id: params[:id])
I would do it in single transaction so either everything or nothing is created

2020-08-31 21:09 UTC, ysv commented on app/api/v2/admin/wallets.rb
> +            CurrencyWallet.find_by!(currency_id: c_id, wallet_id: params[:id]).destroy!
I would do it in single transaction so either everything or nothing is created

2020-08-31 21:09 UTC, ysv commented on app/models/currency_wallet.rb
> +class CurrencyWallet < ApplicationRecord
so why do you keep this validation & index then ?

2020-08-31 21:09 UTC, ysv commented on app/models/currency_wallet.rb
> +#
As for me having created_at ts makes sense here also ? but not updated at 100%

2020-08-31 21:09 UTC, ysv commented on app/models/wallet.rb
> +  def attributes
This is core method redefining it is risky

2020-08-31 21:09 UTC, ysv commented on app/models/wallet.rb
> +  rescue StandardError
Why do we need this rescue ?

2020-08-31 21:09 UTC, ysv commented on app/services/blockchain_service.rb
> +    addresses = PaymentAddress.where(wallet: Wallet.deposit.joins(:currencies).where(currencies: { id: @currencies.codes }), address: block.transactions.map(&:to_address)).pluck(:address)
Why have you decided to no move `Wallet.joins(:currencies).where(currencies:` into scope/class method ?

2020-08-31 21:09 UTC, ysv commented on app/models/currency.rb
> +  before_validation :initialize_defaults
BTW you can use `after_initialize` callback here it's very convenient for such cases

2020-09-07 22:18 UTC, mod requested changes
we need to think very hard if your change in payment_address is the right way
maybe we don't delete the data and keep currency_id and account_id
also I think we could guess the wallet_id from currency_id
we can probably guess the member_id from account_id

TODO: Rename payment_addresses table to deposit_addresses ?

2020-09-07 22:18 UTC, mod commented on lib/tasks/export.rake
> +    binding.pry
please remove

2020-09-07 22:18 UTC, mod commented on db/migrate/20200907133518_create_currencies_wallets.rb
> +        PaymentAddress.find_in_batches do |batch|
comment and explain this one,
I think you can use a join in AR, but really I don't understand the need to update PA table

2020-09-07 22:18 UTC, mod commented on db/migrate/20200907133518_create_currencies_wallets.rb
> +        create_table :currencies_wallets do |t|
use `create_join_table :currencies, :wallets`

2020-09-07 22:18 UTC, mod commented on db/schema.rb
> +    t.datetime "created_at"
I don't think timestamp is needed here

2020-09-08 14:17 UTC, merged