Raketask for fake data
openware/peatio pull request #26
Opened 2017-11-22 20:14 UTC by spavlishak

2017-11-24 00:08 UTC, mod requested changes

2017-11-24 00:08 UTC, mod commented on lib/tasks/data.rake
> +    ENV.fetch('n', 1).to_i.times do
just feed 10 users,
but some admins, some verified, some not
also they might be other tables
you should write code in lib or somewhere we can test and re-use
i think I would use factories

2017-11-27 08:55 UTC, yivo requested changes
@spavlishak You can organize your feeders like so:

```
app/feeders/abstract_feeder.rb
app/feeders/member_feeder.rb
app/feeders/admin_feeder.rb
```

And contains:
```
class AbstractFeeder
  def feed
  
  end
end  

class MemberFeeder < AbstractFeeder
  def feed
    Member.create!(...)
  end
end

class AdminFeeder < MemberFeeder
  def feed
    super.update!(admin: true)
  end
end
```

Which can be used in `lib/tasks/feed.rb` by running `bundle exec rake feed`
```
feeder = MemberFeeder.new
10.times { feeder.feed }
```

I believe factories are good for testing but if we will need custom behaviour we will stuck with issues. 

What do you think?
cc @dkkoval @mod

2017-11-27 08:55 UTC, yivo commented on lib/tasks/data.rake
> +      member.two_factors.each(&:active!)
@spavlishak You can safely remove this as we will not have any 2-factor auth in peatio.

2017-11-27 08:55 UTC, yivo commented on lib/tasks/data.rake
> +      member.id_document.update(
@spavlishak You should always use "bang" methods. This raises exception if your model doesn't pass validations. So this protects your db from shit and bugs.

2017-11-27 08:56 UTC, yivo commented
@spavlishak Could you please mark the PR as WIP? You can look for examples on the PR listing page.

2017-11-27 18:18 UTC, mod approved these changes

2017-11-29 10:18 UTC, yivo requested changes

2017-11-29 10:18 UTC, yivo commented on app/feeders/admin_feeder.rb
> +    super.update!(admin: true)
@spavlishak This actually isn't truth. I wrote it for example. You should update this to reflect real columns / logic.

2017-11-29 10:18 UTC, yivo commented on app/feeders/member_feeder.rb
> +    identity = Identity.find_or_create_by(email: email)
@spavlishak Better to use `find_or_initialize_by` since we are going to save the record.

2017-11-29 10:18 UTC, yivo commented on app/feeders/member_feeder.rb
> +    member = Member.find_or_create_by!(email: email)
@spavlishak Same here: better to use `find_or_initialize_by`.

2017-11-29 10:18 UTC, yivo commented on lib/tasks/data.rake
> +    feeder = MemberFeeder.new
@spavlishak You should generate admin users too.

2017-12-04 22:28 UTC, mod commented
@yivo @spavlishak please update the status

2017-12-05 10:08 UTC, yivo commented
@mod Still in progress

@spavlishak ping

2017-12-07 13:54 UTC, yivo commented
@spavlishak ping

2017-12-12 13:29 UTC, yivo commented
@spavlishak ping

2017-12-13 19:02 UTC, closed without merging