Add jobs table
openware/peatio pull request #2649
Opened 2020-08-04 09:48 UTC by mnaichuk

2020-08-04 10:02 UTC, mod requested changes

2020-08-04 10:02 UTC, mod commented on db/migrate/20200804091304_create_jobs.rb
> +      t.integer :state, default: 0, null: false
- rename to status (can be unsigned short int) 0-255
- add pointer unsigned INT
- add counter INT

2020-08-04 12:40 UTC, mod approved these changes

2020-08-04 12:40 UTC, merged

2022-01-28 10:32 UTC, IronOnet commented
What is the pointer attribute in the job table used for?