Feature: added z_type in deposit and withdraw
openware/peatio pull request #2663
Opened 2020-08-13 15:17 UTC by dinesh-skyach

Feature: added z_type in deposit and withdraw

2020-08-14 14:20 UTC, mnaichuk requested changes

2020-08-14 14:20 UTC, mnaichuk commented on app/models/deposit.rb
> +  Z_TYPE = { wire: 0, card: 1, sepa: 2 , blockchain: 3 }.freeze
can you change wire to the `swift` please?

2020-08-15 05:16 UTC, dinesh-skyach commented on app/models/deposit.rb
> +  Z_TYPE = { wire: 0, card: 1, sepa: 2 , blockchain: 3 }.freeze
Sure, I will make the changes.

2020-08-15 05:52 UTC, dinesh-skyach commented on app/models/deposit.rb
> +  Z_TYPE = { wire: 0, card: 1, sepa: 2 , blockchain: 3 }.freeze
I have made the changes.

2020-08-17 07:00 UTC, mnaichuk approved these changes

2020-08-17 07:01 UTC, merged