Feature: Global Withdraw limits
openware/peatio pull request #2670
Opened 2020-08-25 14:18 UTC by mnaichuk

2020-08-31 21:21 UTC, ysv commented on app/api/v2/admin/withdraw_limits.rb
> +            body errors: withdraw_limit.errors.full_messages
Do we return active record errors as they are in API ?

2020-08-31 21:21 UTC, ysv commented on app/api/v2/admin/withdraw_limits.rb
> +        post '/withdraw_limits/new' do
why don't we use standard REST endpoints here ?
POST /withdraw_limits
DELETE /withdraw_limits/:id
PUT /withdraw_limits/:id

2020-08-31 21:21 UTC, ysv commented on app/api/v2/admin/withdraw_limits.rb
> +        post '/withdraw_limits/update' do
why not PUT `/withdraw_limits` ?

2020-08-31 21:21 UTC, ysv commented on app/api/v2/admin/withdraw_limits.rb
> +        post '/withdraw_limits/delete' do
DELETE /withdraw_limits/:id

2020-08-31 21:21 UTC, ysv commented on app/models/withdraw_limit.rb
> +class WithdrawLimit < ApplicationRecord
1. I would name it
```
class Withdraw
  class Limit
  end
end
```

2. Right name for sure is withdrawal but since we have this legacy withdraw we can keep as it's

2020-08-31 21:25 UTC, ysv commented on app/models/withdraw.rb
> +    sum_withdraws_24_hours = member.withdraws.succeed_processing.where('created_at > ?', 24.hours.ago).sum(:sum) + sum
why do you sum all user withdrawal without recalculation by rates ?
Please recheck this method

2020-09-01 13:00 UTC, mnaichuk commented on app/api/v2/admin/withdraw_limits.rb
> +        post '/withdraw_limits/new' do
yeah, updating

2020-09-01 13:00 UTC, mnaichuk commented on app/api/v2/admin/withdraw_limits.rb
> +            body errors: withdraw_limit.errors.full_messages
yes

2020-09-01 13:05 UTC, mod commented on app/api/v2/account/withdraws.rb
> +        get '/withdraws/sums' do
why do we need this endpoint ?
is that matching a UI requirement,
To me limit should be express in per 24h and per 72h limits
what's the purpose of the 1 month limit ?

2020-09-01 13:19 UTC, mod requested changes

2020-09-01 13:19 UTC, mod commented on app/api/v2/admin/withdraw_limits.rb
> +        post '/withdraw_limits/new' do
I need the UI for this

2020-09-01 13:19 UTC, mod commented on app/api/v2/public/withdraw_limits.rb
> +
no we need to stop creating 1 endpoint for each config

2020-09-01 13:19 UTC, mod commented on app/models/trading_fee.rb
> +    Rails.cache.delete_matched("trading_fees*")
wow

2020-09-01 13:19 UTC, mod commented on app/models/withdraw.rb
> +        process! if ENV.false?('WITHDRAW_ADMIN_APPROVE') && currency.coin?
is that something new ?

2020-09-01 13:19 UTC, mod commented on app/models/withdraw.rb
> +    sum_withdraws_24_hours = member.withdraws.succeed_processing.where('created_at > ?', 24.hours.ago).sum(:sum) + sum
same question

2020-09-01 13:19 UTC, mod commented on db/schema.rb
> +  end
1. I don't agree gaving currency_id in here, it doesn't sound global at all
2. group and kyc_level is likely the same thing, problem is we don't have success with group, I don't know what does work in this logic
3. Can't we re-use limits in currencies, I way prefer 24h and 72h
4. In which currency is expressed the limits ?

2020-09-01 13:44 UTC, mnaichuk commented on app/api/v2/account/withdraws.rb
> +        get '/withdraws/sums' do
This endpoint will return to the user current sums for withdrawals and it will be easier to understand how much he can withdraw

2020-09-01 13:46 UTC, mnaichuk commented on app/api/v2/public/withdraw_limits.rb
> +
Better to have these endpoints too and then schedule a small sprint for FE and BE to prepare Global config with one endpoint.

2020-09-01 13:49 UTC, mnaichuk commented on app/models/withdraw.rb
> +        process! if ENV.false?('WITHDRAW_ADMIN_APPROVE') && currency.coin?
I did withdrawal limits check on the creation level. And add this config to be able to configure the withdraw flow from the admin perspective. We can set this env to true and admin will need to process each withdraw and by default, the system will process withdrawals automatically.

2020-09-01 13:51 UTC, mnaichuk commented on db/schema.rb
> +  end
I leave WL system pretty flexible. You can set only group or kyc_level or currency id. Check pls my comments here:
https://github.com/openware/peatio/blob/dea16cea281b149b8102e3917affd78adf0218f8/app/models/withdraw_limit.rb#L59

2020-09-01 13:52 UTC, mnaichuk commented on db/schema.rb
> +  end
# Withdraw limit suitability expressed in weight.
  # Withdraw limit with the greatest weight selected.
  # Kyc_level has greater weight then group and group has greater weight then currency_id match.
  # E.g Withdrawal for member with kyc_level 2, group 'vip-0' and currency_id 'btc'
  # (kyc_level == 2     && group == 'vip-0' && currency_id == 'btc') >
  # (kyc_level == 2     && group == 'vip-0' && currency_id == 'any') >
  # (kyc_level == 2     && group == 'any'   && currency_id == 'btc') >
  # (kyc_level == 'any' && group == 'vip-0' && currency_id == 'btc') >
  # (kyc_level == 'any' && group == 'vip-0' && currency_id == 'any') >
  # (kyc_level == 'any' && group == 'any'   && currency_id == 'btc') >
  # (kyc_level == 'any' && group == 'any'   && currency_id == 'any') >

2020-09-02 08:06 UTC, calj commented on app/models/withdraw.rb
> +    sum_withdraws_24_hours = member.withdraws.succeed_processing.with_currency(currency_id).where('created_at > ?', 24.hours.ago).sum(:sum) + sum
Here it should be selecting everything in the date range and convert into the currency_id

2020-09-02 08:06 UTC, calj commented on app/models/withdraw.rb
> +      errors.add(:withdraw, '72h_limit_exceeded')
typo here

2020-09-08 16:27 UTC, mod approved these changes

2020-09-08 16:27 UTC, merged

2021-02-25 02:00 UTC, crackfoo commented
Where does one configure these limits so they are printed to the API endpoint? Can opendax set these values or tower?