Feature: Add token type to currency model
openware/peatio pull request #2672
Opened 2020-08-31 11:50 UTC by chumaknadya

2020-09-01 09:47 UTC, mnaichuk requested changes

2020-09-01 09:47 UTC, mnaichuk commented on app/api/v2/admin/currencies.rb
> +          given type: ->(val) { val == 'coin' || val == 'token' } do
val.in? Currency::CRYPTO_TYPES

2020-09-01 09:47 UTC, mnaichuk commented on app/api/v2/admin/currencies.rb
> +            types = params[:type] == 'fiat'  ? params[:type] : Currency::CRYPTO_TYPES
better add the ability to select with array and allow to select tokens and coins separately

2020-09-01 09:47 UTC, mnaichuk commented on app/models/currency.rb
> +  def account_type
name legacy_type better and add TODO to rewrite it later

2020-09-01 13:26 UTC, mod requested changes

2020-09-01 13:26 UTC, mod commented on app/models/currency.rb
> +      token: token? }
what ?
why not just type: fiat/token/coin

2020-09-01 13:26 UTC, mod commented on db/schema.rb
> +    t.string "parent_id"
do we need a parent id of an account ?
I really don't think there is a relationship between ETH and USDT account balance.

2020-09-01 13:26 UTC, mod commented on app/models/currency.rb
> +  def account_type
that legacy type is really confusing, it's deprecated, where is it being used ?

2020-09-01 13:46 UTC, chumaknadya commented on db/schema.rb
> +    t.string "parent_id"
@mod Its parent_id of currency table, not account
Currency with type 'token' only have parent_id

2020-09-01 14:05 UTC, mnaichuk commented on app/models/currency.rb
> +  def account_type
@mod before we were using just attribute `type` in accounting tables. With a new type, we will not be able to use it. Because we will not have new accounting code and record
E.g:
- code:           102
  type:           asset
  kind:           main
  currency_type:  coin
  description:    Main Crypto Assets Account
  scope:          platform

2020-09-01 14:06 UTC, mnaichuk commented on app/models/currency.rb
> +  def account_type
So we need to have this helper to replace `token` type to just `coin`. Maybe you can suggest a better name that will not confuse.

2020-09-02 07:10 UTC, mnaichuk commented on app/api/v2/admin/deposits.rb
> +          optional :type,
I think this will break FE?

2020-09-02 07:12 UTC, mnaichuk commented on app/api/v2/entities/currency.rb
> +        expose(
do we need this for the public endpoint?

2020-09-02 07:16 UTC, mnaichuk commented on app/models/deposit.rb
> +  def fiat?
I don't think that we need these helpers, check concerns folder

2020-09-02 07:26 UTC, chumaknadya commented on app/models/deposit.rb
> +  def fiat?
The problem here was that deposit types were inherited from currency model
Coin deposit should include both token and coin, as I understand

2020-09-02 07:31 UTC, mnaichuk commented on app/models/deposit.rb
> +  def fiat?
then you delegate `crypto?` method and use it

2020-09-02 07:46 UTC, mnaichuk approved these changes

2020-09-03 11:26 UTC, mnaichuk requested changes

2020-09-03 11:26 UTC, mnaichuk commented on app/models/currency.rb
> +  CRYPTO_TYPES = %i[token coin].freeze
remove this

2020-09-03 11:26 UTC, mnaichuk commented on app/models/currency.rb
> +  def account_type
remove this

2020-09-03 14:25 UTC, merged