Feature: add admin currencies fetch filters
openware/peatio pull request #2678
Opened 2020-09-03 08:56 UTC by oyershov

2020-09-03 09:07 UTC, mnaichuk requested changes

2020-09-03 09:07 UTC, mnaichuk commented on app/api/v2/admin/currencies.rb
> +            .eq(:type, :deposit_enabled, :withdrawal_enabled, :visible)
you should add new params in params section: check line 108 and example you can see at line 189

2020-09-03 09:07 UTC, mnaichuk commented on spec/api/v2/admin/currencies_spec.rb
> +    it 'list of deposit_enabled currencies' do
add negative cases, please

2020-09-03 11:55 UTC, oyershov commented on app/api/v2/admin/currencies.rb
> +            .eq(:type, :deposit_enabled, :withdrawal_enabled, :visible)
fixed

2020-09-03 11:55 UTC, oyershov commented on spec/api/v2/admin/currencies_spec.rb
> +    it 'list of deposit_enabled currencies' do
done

2020-09-03 13:50 UTC, mnaichuk requested changes

2020-09-03 13:50 UTC, mnaichuk commented on app/api/v2/admin/entities/currency.rb
> +          expose(
no need to add it here because this class inherit from API::V2::Entities::Entities and this class already exposed it

2020-09-03 13:50 UTC, mnaichuk commented on spec/api/v2/admin/adjustments_spec.rb
> -      .and change { Operations::Liability.count }.by(1)
I don't think that you can delete it

2020-09-03 13:50 UTC, mnaichuk commented on app/api/v2/admin/currencies.rb
> +            .eq(:type, :deposit_enabled, :withdrawal_enabled, :visible)
no, should be like:
deposit_enabled: {
              type: { value: Boolean, message: 'admin.currency.non_boolean_deposit_enabled' },
              default: true,
              desc: -> { API::V2::Admin::Entities::Currency.documentation[:deposit_enabled][:desc] }
            }
for all params that you added

2020-09-03 13:50 UTC, mnaichuk commented on spec/api/v2/admin/currencies_spec.rb
> +    it 'list of deposit enabled currencies' do
after you will add params declaration you need to negative cases like if you will send params with the wrong type, check pls line 153:
it 'returns error in case of invalid type' do
      api_get '/api/v2/admin/currencies', params: { type: 'invalid' }, token: token
      expect(response).to have_http_status 422
    end

2020-09-03 14:51 UTC, oyershov commented on app/api/v2/admin/currencies.rb
> +            .eq(:type, :deposit_enabled, :withdrawal_enabled, :visible)
done

2020-09-03 14:52 UTC, oyershov commented on app/api/v2/admin/entities/currency.rb
> +          expose(
fixed

2020-09-04 13:18 UTC, mnaichuk commented on spec/api/v2/admin/currencies_spec.rb
> +      expect(result.size).to eq Currency.coins.select { |c| c['visible'] == false }.count
just FYI you can use Currency.coins.where(visible: false)

2020-10-09 08:00 UTC, calj approved these changes

2020-10-09 08:00 UTC, calj commented
please rebase

2020-11-23 09:49 UTC, mnaichuk approved these changes

2020-11-23 09:50 UTC, merged