Feature: add ability to generate deposit address by admin
openware/peatio pull request #2679
Opened 2020-09-03 11:07 UTC by oyershov

2020-09-03 14:04 UTC, mnaichuk requested changes

2020-09-03 14:04 UTC, mnaichuk commented on app/api/v2/admin/entities/deposit.rb
> +          expose(
no need to add this we have it in the parent class

2020-09-03 14:04 UTC, mnaichuk commented on app/api/v2/admin/deposits.rb
> +        get '/deposit_address' do
better to use POST here. From API addresses returns from `/api/v2/peatio/admin/members/UID` endpoint. So here it should be like you send POST request to generate a deposit address for user and then you can get update from call that I sent before

2020-09-03 14:04 UTC, mnaichuk commented on app/api/v2/admin/deposits.rb
> +        desc 'Returns deposit address for account you want to deposit to by currency.',
change title here

2020-09-04 09:03 UTC, mnaichuk requested changes

2020-09-04 09:03 UTC, mnaichuk commented on app/api/v2/admin/deposits.rb
> +          admin_authorize! :create, Deposit
: create, Payment Address

2020-09-04 15:54 UTC, mnaichuk approved these changes

2020-10-09 07:58 UTC, calj commented
Please squash/rebase and final check

2020-10-15 08:15 UTC, merged