Feature: Add CMC integration
openware/peatio pull request #2696
Opened 2020-09-24 15:17 UTC by chumaknadya

2020-09-25 11:44 UTC, mnaichuk requested changes

2020-09-25 11:44 UTC, mnaichuk commented on app/api/v2/coin_market_cap/assets.rb
> +          Currency.coins.ordered.map do |currency|
we can use redis here

2020-09-25 11:44 UTC, mnaichuk commented on app/api/v2/coin_market_cap/summary.rb
> +          ::Market.ordered.map do |market|
we can use redis here

2020-09-25 11:44 UTC, mnaichuk commented on app/api/v2/coin_market_cap/ticker.rb
> +          # Clarify: visible or all?
we can use redis here

2020-09-25 19:01 UTC, calj commented on spec/api/v2/coin_market_cap/assets_spec.rb
> +            stub_request(:get, "http://pro-api.coinmarketcap.com/v1/cryptocurrency/map?CMC_PRO_API_KEY=UNIFIED-CRYPTOASSET-INDEX&"\
can we use https in every request to CMC?

2020-09-28 07:52 UTC, mnaichuk commented on app/api/v2/coin_market_cap/helpers.rb
> +            timestamp:    DateTime.now.strftime('%Q').to_i, # mandatory [integer]: Unix timestamp in milliseconds for when the transaction occurred
Trade time

2020-09-28 11:40 UTC, mnaichuk approved these changes

2020-09-29 09:44 UTC, merged