WIP: Introduce CoinGecko API Endpoints
openware/peatio pull request #2698
Opened 2020-09-24 19:54 UTC by dpatsora

2020-09-25 11:41 UTC, mnaichuk requested changes

2020-09-25 11:41 UTC, mnaichuk commented on app/api/v2/coin_gecko/entities/pair.rb
> +            "#{market[:base_unit].upcase}_#{market[:quote_unit].upcase}"
can be the helper in the market model

2020-09-25 11:41 UTC, mnaichuk commented on app/api/v2/coin_gecko/entities/pair.rb
> +            market[:base_unit].upcase
can be the helper in the market model

2020-09-25 11:41 UTC, mnaichuk commented on app/api/v2/coin_gecko/entities/pair.rb
> +            market[:quote_unit].upcase
can be the helper in the market model

2020-09-25 11:41 UTC, mnaichuk commented on app/api/v2/coin_gecko/helpers.rb
> +              ticker_id: "#{market[:base_unit].upcase}_#{market[:quote_unit].upcase}",
can be the helpers in the market model

2020-09-25 11:41 UTC, mnaichuk commented on app/api/v2/coin_gecko/pairs.rb
> +          enabled_markets = ::Market.enabled
we can use redis here

2020-09-25 11:41 UTC, mnaichuk commented on app/api/v2/coin_gecko/tickers.rb
> +            format_ticker(TickersService[market].ticker, market)
we can use redis here

2020-10-01 08:12 UTC, mnaichuk commented on app/api/v2/coin_gecko/historical_trades.rb
> +            trades_query += " AND created_at>=%{end_time}"
fix this please

2020-10-01 08:25 UTC, mnaichuk commented on app/api/v2/coin_gecko/historical_trades.rb
> +          unless params[:limit].to_d.zero?
I'm 100% sure that we should have some limit or we should have a limitation between start_at and end_at

2020-10-01 08:26 UTC, mnaichuk commented on app/api/v2/coin_gecko/historical_trades.rb
> +          Trade.public_from_influx_with_filters(market.id, trades_query, filters).each do |trade|
each_with_object({'buy' => [], 'sell' => []})

2020-10-05 07:18 UTC, calj approved these changes

2020-10-05 07:18 UTC, mnaichuk approved these changes

2020-10-05 07:26 UTC, merged