Optional sign in with Google account
openware/peatio pull request #28
Opened 2017-11-23 13:33 UTC by yivo

2017-11-24 00:06 UTC, mod commented
please rebase

2017-11-24 00:13 UTC, mod requested changes
can we add some tests ?

2017-11-24 00:13 UTC, mod commented on config/initializers/omniauth.rb
> +
I think we should activate things from application.yml configs not ENV
same for Auth0

2017-11-24 10:34 UTC, yivo commented on config/initializers/omniauth.rb
> +
@mod Peatio uses figaro gem for dealing with application.yml. figaro loads all values to the ENV. 

`Figaro parses a Git-ignored YAML file in your application and loads its values into ENV.`

https://github.com/laserlemon/figaro

2017-11-24 10:35 UTC, yivo commented on config/initializers/omniauth.rb
> +
@mod I can add example values to the application.yml so users will understand how to configure auth.

2017-11-24 12:59 UTC, yivo commented
@mod 

```
Finished in 2 minutes 5.7 seconds (files took 9.07 seconds to load)
656 examples, 0 failures, 11 pending
```

2017-11-27 08:56 UTC, yivo commented
@dkkoval Could you please take a look on it?

2017-11-27 10:31 UTC, mod requested changes
We just need to take out database.yml
Later we would need conditional auth0 or google oauth
Question @yivo can they both work at the same time ?

2017-11-27 10:31 UTC, mod commented on config/database.yml
> +  password: root
we can't take this change you need to export user / password using
export DATABASE_USER=root
export DATABASE_PASS=root

or change but not commit your database.yml

2017-11-27 10:34 UTC, yivo commented
@mod Yes, they can work both as the same time. Now I will take a screenshot.

2017-11-27 10:36 UTC, yivo commented
@mod 

<img width="1274" alt="screen shot 2017-11-27 at 12 36 22 pm" src="https://user-images.githubusercontent.com/7421323/33262644-9ddfcb3a-d36f-11e7-9495-f1206fc52920.png">

2017-11-27 16:20 UTC, mod approved these changes

2017-11-27 16:22 UTC, merged