WIP: Internal transfers
openware/peatio pull request #2802
Opened 2021-01-21 07:04 UTC by akulakovaa

2021-01-21 09:15 UTC, mnaichuk requested changes

2021-01-21 09:15 UTC, mnaichuk commented on app/api/v2/account/helpers.rb
> +        def get_direction()
this should be model helper

2021-01-21 09:15 UTC, mnaichuk commented on app/api/v2/account/internal_transfers.rb
> +          InternalTransfer
try to use Ranscack here

2021-01-21 09:15 UTC, mnaichuk commented on app/api/v2/account/internal_transfers.rb
> +            .page(params[:page])
no need to put page and per here

2021-01-21 09:15 UTC, mnaichuk commented on app/api/v2/account/internal_transfers.rb
> +          receiver = Member.find_by(nickname: params[:nickname]) # or Member.find_by(uid: params[:uid])
if params[:nickname]
  Find by nickname
else
  Find by uid
end

2021-01-21 09:15 UTC, mnaichuk commented on app/api/v2/account/internal_transfers.rb
> +          receiver = Member.find_by(nickname: params[:nickname]) # or Member.find_by(uid: params[:uid])
return error if receiver doesn't exist

2021-01-21 09:15 UTC, mnaichuk commented on app/api/v2/account/internal_transfers.rb
> +            error!({ errors: ['account.withdraw.invalid_otp'] }, 422)
not withdraw

2021-01-21 09:15 UTC, mnaichuk commented on app/api/v2/account/internal_transfers.rb
> +          internal_transfer = ::InternalTransfer.new(data)
why you didn't do
::InternalTransfer.new(
  member: member,
  currency: currency,
  ....)

2021-01-21 09:15 UTC, mnaichuk commented on app/api/v2/account/internal_transfers.rb
> +            account
account?

2021-01-21 09:15 UTC, mnaichuk commented on app/api/v2/admin/internal_transfers.rb
> +          internal_transfer = InternalTransfer.find_by!(id: params[:id])
just `find` if you are using search by id

2021-01-21 09:15 UTC, mnaichuk commented on app/api/v2/entities/internal_tranfer.rb
> +          as: :sender,
you need to return here uid of user, with this it will return id

2021-01-21 09:15 UTC, mnaichuk commented on app/api/v2/entities/internal_tranfer.rb
> +          :direction,
please check how to send here params, send current_use and use helper from model

2021-01-21 09:18 UTC, mnaichuk requested changes

2021-01-21 09:18 UTC, mnaichuk commented on app/models/internal_transfer.rb
> +    update_legacy_balances
this function already implemented on Operations.
also, you need to create liabilities before check `transfer` method in Operation model.

2021-01-21 09:18 UTC, mnaichuk commented on app/models/internal_transfer.rb
> +    liabilities.where.not(member_id: nil).find_each { |l| Operations.update_legacy_balance(l) }
this function already implemented on Operations.

2021-01-21 09:28 UTC, mnaichuk requested changes

2021-01-21 09:28 UTC, mnaichuk commented on app/api/v2/account/internal_transfers.rb
> +          optional :uid,      type: String,  desc: 'The shared user ID.'
this shouldn't be here, you should use current_user

2021-01-21 09:28 UTC, mnaichuk commented on app/api/v2/account/internal_transfers.rb
> +          @settings[:scope] = :write_internal_transfers
you are mixing MNG api with user API here, delete this

2021-01-21 09:28 UTC, mnaichuk commented on app/api/v2/account/internal_transfers.rb
> +        get '/internal_transfers' do
you can namespace internal_transfers and put all calls definition inside of this block

2021-01-21 09:28 UTC, mnaichuk commented on app/api/v2/account/internal_transfers.rb
> +module API
please use convention:
GET /internal_transfers for list of transfers
POST /internal_transfers for create
PUT /internal_transfers/:id for update (just example)
DELETE /internal_transfer/:id for delete (just example)

2021-01-25 14:21 UTC, mnaichuk commented on app/api/v2/account/internal_transfers.rb
> +              if params[:username]
receiver = if params[:username].present?
  Member.find_by(username: params[:username])
elsif params[:uid].present?
  Member.find_by(uid: params[:uid])
end
error!({ errors: ['account.internal_transfer.receiver_not_fount'] }, 422) if receiver.nil?

2021-01-25 14:23 UTC, mnaichuk commented on app/api/v2/entities/internal_transfer.rb
> +          :id,
move to admin entity

2021-01-25 14:23 UTC, mnaichuk commented on app/api/v2/entities/internal_transfer.rb
> +          :transfer_type,
this field doesn't exist

2021-01-25 14:23 UTC, mnaichuk commented on app/api/v2/admin/entities/internal_transfer.rb
> +          :type,
move type to user endpoint

2021-01-25 14:27 UTC, mnaichuk commented on app/models/internal_transfer.rb
> +  validates :currency, :amount, :sender, :receiver, :state, :type, presence: true
validate state to be in STATES, check: https://github.com/openware/peatio/blob/ee222e53fb5522adb04af2f5d49fcf84f39d1656/app/models/order.rb#L16

2021-01-25 14:27 UTC, mnaichuk commented on app/models/internal_transfer.rb
> +  validates :currency, :amount, :sender, :receiver, :state, :type, presence: true
same for type

2021-01-25 14:28 UTC, mnaichuk commented on app/models/internal_transfer.rb
> +#  state       :integer          default("completed"), not null
do not use DB default in migrations. Better to use model defaults, then will be easy to change the value

2021-01-27 00:09 UTC, akushniruk commented
- [ ] add specs for changing user balance after the transfer
- [ ] add specs for filtering
- [ ] add new params (filtering) for admin api

2021-01-27 07:38 UTC, calj commented on app/api/v2/account/internal_transfers.rb
> +            optional :username,
let's make one field for username_or_uuid

2021-01-27 07:38 UTC, calj commented on app/api/v2/account/internal_transfers.rb
> +            receiver = if params[:username].present?
Then we search first by uid and if not found by username.

2021-01-27 12:42 UTC, akushniruk commented
Ready for review

2021-01-27 22:03 UTC, mnaichuk requested changes

2021-01-27 22:03 UTC, mnaichuk commented on app/api/v2/account/internal_transfers.rb
> +            optional :state, type: String, default: 1, desc: 'The state to filter by.'
remove default here

2021-01-27 22:03 UTC, mnaichuk commented on app/api/v2/admin/entities/internal_transfer.rb
> +            :sender_id, ## display UID
return here sender UID

2021-01-27 22:03 UTC, mnaichuk commented on app/api/v2/admin/entities/internal_transfer.rb
> +            :receiver_id, ## display UID
return here receiver UID

2021-01-27 22:03 UTC, mnaichuk commented on app/api/v2/entities/internal_transfer.rb
> +          :sender_id, ## display UID
return here receiver UID

2021-01-27 22:03 UTC, mnaichuk commented on app/api/v2/entities/internal_transfer.rb
> +          :receiver_id, ## display UID
return here receiver UID

2021-01-27 22:03 UTC, mnaichuk commented on app/api/v2/admin/entities/internal_transfer.rb
> +        class InternalTransfer < API::V2::Entities::InternalTransfer
if you are using inheritance here you don't need to expose same keys

2021-01-27 22:03 UTC, mnaichuk commented on app/models/internal_transfer.rb
> +#  state       :integer          default("completed"), not null
please fix this

2021-01-27 22:03 UTC, mnaichuk commented on spec/api/v2/account/internal_transfer_spec.rb
> +    # deposit_eth.accept!
clean up commented lines

2021-01-27 22:03 UTC, mnaichuk commented on spec/api/v2/account/internal_transfer_spec.rb
> +    Ability.stubs(:user_permissions).returns({ 'member' => { 'read' => ['InternalTransfer'], 'create' => ['InternalTransfer'] } })
why we need this stub?

2021-01-28 08:06 UTC, dpatsora commented on app/api/v2/admin/entities/internal_transfer.rb
> +            :sender_id, ## display UID
do |internal_transfer|
internal_transfer.sender.uid
end

2021-01-28 09:35 UTC, akushniruk commented on spec/api/v2/account/internal_transfer_spec.rb
> +    Ability.stubs(:user_permissions).returns({ 'member' => { 'read' => ['InternalTransfer'], 'create' => ['InternalTransfer'] } })
we do not need it

2021-02-03 07:38 UTC, mnaichuk requested changes

2021-02-03 07:38 UTC, mnaichuk commented on app/api/v2/entities/internal_transfer.rb
> +            transfer.sender&.username
basically, you should have validation for the presence of sender and receiver and then you don't need to put & here

2021-02-03 07:38 UTC, mnaichuk commented on app/api/v2/entities/internal_transfer.rb
> +          :sender_id,
you can do just expose(
   :sender_uid, ......
) do |...

2021-02-03 07:38 UTC, mnaichuk commented on app/api/v2/entities/internal_transfer.rb
> +          }
please add this https://github.com/openware/peatio/blob/ee222e53fb5522adb04af2f5d49fcf84f39d1656/app/api/v2/entities/trade.rb#L46 also here

2021-02-03 07:38 UTC, mnaichuk commented on app/api/v2/entities/internal_transfer.rb
> +          format_with: :decimal,
I'm not sure that we need this?

2021-02-04 10:09 UTC, akulakovaa commented on app/api/v2/entities/internal_transfer.rb
> +            transfer.sender&.username
I validate presence of username, cause we'll have it only on Nairaex

2021-02-15 06:45 UTC, mnaichuk approved these changes

2021-02-15 09:44 UTC, calj commented on app/api/v2/account/internal_transfers.rb
> +            receiver = if Member.find_by(uid: params[:username_or_uid]).present?
let's move this logic into Member#find_by_username_or_uid

2021-02-19 07:41 UTC, mnaichuk approved these changes

2021-02-19 08:12 UTC, akushniruk commented on app/models/member.rb
> +    def find_by_username_or_uid(uid_or_email)
```
  def self.find_by_uid_or_username(uid_or_username)
    member = Member.find_by(uid: uid_or_username)
    member.present? ? member : Member.find_by(username: uid_or_username)
  end
```

2021-02-19 15:29 UTC, merged