Whitelisted smart contracts implementation
openware/peatio pull request #2810
Opened 2021-01-28 15:56 UTC by vpetrusenko

2021-02-02 07:31 UTC, mnaichuk requested changes

2021-02-02 07:31 UTC, mnaichuk commented on app/api/v2/admin/whitelisted_smart_contracts.rb
> +        post '/whitelisted_smart_contracts/update' do
put '/whitelisted_smart_contracts'

2021-02-02 07:31 UTC, mnaichuk commented on app/api/v2/admin/whitelisted_smart_contracts.rb
> +        post '/whitelisted_smart_contracts/new' do
post '/whitelisted_smart_contracts'

2021-02-02 07:31 UTC, mnaichuk commented on app/api/v2/admin/whitelisted_smart_contracts.rb
> +        get '/whitelisted_smart_contracts/:id' do
get '/whitelisted_smart_contract/:id'

2021-02-02 07:31 UTC, mnaichuk commented on app/models/wallet.rb
> +  # before_validation do
this should be commented

2021-02-02 07:31 UTC, mnaichuk commented on app/models/whitelisted_smart_contract.rb
> +  validates :address, presence: true, uniqueness: { scope: :blockchain_key}
add empty space before last }

2021-02-02 07:31 UTC, mnaichuk commented on app/models/whitelisted_smart_contract.rb
> +    blockchain.explorer_address.gsub('#{address}', address) if blockchain
as I remember you can just explorer_address from blockchain and FE will handle

2021-02-02 07:31 UTC, mnaichuk commented on db/migrate/20210128144535_create_whitelisted_smart_contracts.rb
> +      t.string  :address,        default: '', null: false
we don't need defaults here

2021-02-02 07:31 UTC, mnaichuk commented on spec/spec_helper.rb
> +    %i[usd eur btc eth trst ring tom].each { |ccy| FactoryBot.create(:currency, ccy) }
do not add more factories here you can create them if needed in spec

2021-02-02 07:31 UTC, mnaichuk commented on lib/peatio/ethereum/blockchain.rb
> +            c.dig(:options, :erc20_contract_address) == address ||
maybe more clear will be check if `normalize_address(tx.fetch('to'))` in @whitelisted_addresses ?

2021-02-02 07:46 UTC, vpetrusenko commented on app/models/whitelisted_smart_contract.rb
> +    blockchain.explorer_address.gsub('#{address}', address) if blockchain
Alex ask me to expose it, but sure i can remove it

2021-02-02 15:50 UTC, mnaichuk commented on spec/spec_helper.rb
> +    %i[ address_1 address_2 address_3 address_4 ].each { |ccy| FactoryBot.create(:whitelisted_smart_contract, ccy) }
don't need to create this in spec_helper

2021-02-02 15:53 UTC, mnaichuk commented on app/models/whitelisted_smart_contract.rb
> +    blockchain.explorer_address.gsub('#{address}', address) if blockchain
yes, please remove this, Alex agree

2021-02-02 15:54 UTC, mnaichuk commented
Also please add a callback on smart contract creation to update `updated_at` of his blockhain

2021-02-03 07:32 UTC, vpetrusenko commented
@mnaichuk updated

2021-02-03 13:51 UTC, chumaknadya requested changes

2021-02-03 13:51 UTC, chumaknadya commented on app/api/v2/admin/whitelisted_smart_contracts.rb
> +          whitelisted_address = ::WhitelistedSmartContract.create!(declared(params))
Create! will raise an error, so your save will not be executed

You can use .new and .save

2021-02-03 13:51 UTC, chumaknadya commented on app/models/whitelisted_smart_contract.rb
> +
Can you do frozen array of states here ?
And here just use this const, so it will make it reusable

2021-02-03 14:10 UTC, mnaichuk commented
Also, we need to have the ability to import contacts from seeds please check the import rake task and add this functionality there

2021-02-03 14:26 UTC, chumaknadya requested changes

2021-02-03 14:26 UTC, chumaknadya commented on app/api/v2/admin/whitelisted_smart_contracts.rb
> +            status 201
you can do without status here

2021-02-03 14:26 UTC, chumaknadya commented on app/api/v2/admin/whitelisted_smart_contracts.rb
> +          CSV.parse(params[:file][:tempfile], headers: true, quote_empty: false).each do |row|
will it be always :tempfile variable here ?

2021-02-03 14:26 UTC, chumaknadya commented on app/api/v2/admin/whitelisted_smart_contracts.rb
> +            next if address.blank? || blockchain_key.blank? || !::Blockchain.pluck(:key).include?(blockchain_key)
```::Blockchain.pluck(:key).exclude?(blockchain_key)``` insead of ```!::Blockchain.pluck(:key).include?(blockchain_key)```

2021-02-03 14:26 UTC, chumaknadya commented on app/api/v2/admin/whitelisted_smart_contracts.rb
> +                   type: File
put description

2021-02-03 14:26 UTC, chumaknadya commented on spec/api/v2/admin/whitelisted_smart_contracts_spec.rb
> +  let!(:addresses_1) { FactoryBot.create(:whitelisted_smart_contract, :address_1) }
you can use just create(: whitelisted_smart_contract)

2021-02-03 15:25 UTC, vpetrusenko commented on app/api/v2/admin/whitelisted_smart_contracts.rb
> +          CSV.parse(params[:file][:tempfile], headers: true, quote_empty: false).each do |row|
should be, i write it with airdrop csv parse logic as example

2021-02-03 15:45 UTC, vpetrusenko commented
@vpetrusenko @chumaknadya updated

2021-02-05 11:22 UTC, closed without merging