Feature: Whitelisted smart contracts implementation
openware/peatio pull request #2815
Opened 2021-02-05 11:25 UTC by vpetrusenko

2021-02-15 10:02 UTC, calj commented
Please add bitstamp smart contract address in the default seed:

https://etherscan.io/address/0x1522900b6dafac587d499a862861c0869be6e428

2021-02-16 08:04 UTC, chumaknadya commented on app/api/v2/admin/whitelisted_smart_contracts.rb
> +          admin_authorize! :read, WhitelistedSmartContract
can you check here that person who doesn't have access to WhitelistedSmartContract will get an error ?

Cause I saw such behavior previously ```admin_authorize! :read, ::WhitelistedSmartContract```

2021-02-16 08:04 UTC, chumaknadya commented on app/api/v2/admin/whitelisted_smart_contracts.rb
> +          admin_authorize! :read, WhitelistedSmartContract
same here

2021-02-16 08:29 UTC, chumaknadya requested changes

2021-02-16 08:29 UTC, chumaknadya commented on app/models/whitelisted_smart_contract.rb
> +end
i dont see migration here

2021-02-16 08:29 UTC, chumaknadya commented on app/api/v2/admin/entities/whitelisted_smart_contract.rb
> +              desc: 'Whitelisted smart contract description'
you had dot in the end of description everywhere

2021-02-16 08:29 UTC, chumaknadya commented on app/api/v2/admin/whitelisted_smart_contracts.rb
> +          present ::WhitelistedSmartContract.find(params[:id]), with: API::V2::Admin::Entities::WhitelistedSmartContract
you have find here, it means that if there is no smart contract it will raise an error
Can you check which error we will get in this case?

2021-02-16 08:29 UTC, chumaknadya commented on app/api/v2/admin/whitelisted_smart_contracts.rb
> +          whitelisted_address = ::WhitelistedSmartContract.find(params[:id])
same here with find
Can you check an error in rspec?

2021-02-16 08:29 UTC, chumaknadya commented on app/api/v2/admin/whitelisted_smart_contracts.rb
> +            body errors: whitelisted_address.errors.full_messages
can you check this case too?

2021-02-16 08:29 UTC, chumaknadya commented on lib/tasks/import.rake
> +      next if address.blank? || blockchain_key.blank? || !::Blockchain.pluck(:key).include?(blockchain_key)
exclude

2021-02-16 14:36 UTC, chumaknadya commented
Add documentation here

2021-02-16 17:08 UTC, martianatwork commented on app/services/blockchain_service.rb
> +    @whitelisted_addresses = blockchain.whitelisted_smart_contracts.active
@vpetrusenko  shouldn't we include erc20_contract addresses from the currencies? the user will have to enter it on 2 different locations.

2021-02-16 17:08 UTC, martianatwork commented on db/migrate/20210128144535_create_whitelisted_smart_contracts.rb
> +class CreateWhitelistedSmartContracts < ActiveRecord::Migration[5.2]
i believe that we have to add migrations for converting the contract addresses from currency to the WhitelistedSmartContract

2021-02-19 12:19 UTC, mnaichuk commented on app/services/blockchain_service.rb
> +    @whitelisted_addresses = blockchain.whitelisted_smart_contracts.active
@martianatwork Hello! this patch was about to detect eth and erc20 deposits from the third party contracts

2021-02-19 15:49 UTC, calj commented on lib/peatio/ethereum/blockchain.rb
> +      @whitelisted_addresses = settings[:whitelisted_addresses]
please convert to [].to_set for fast lookup

https://ruby-doc.org/stdlib-2.7.1/libdoc/set/rdoc/Set.html

2021-02-19 15:49 UTC, calj commented on lib/peatio/ethereum/blockchain.rb
> +          address = @whitelisted_addresses.map(&:address).include?(tx.fetch('to')) && normalize_address(tx.fetch('to'))
better to write this in 4 readable lines

2021-02-20 06:08 UTC, calj commented
Please fix tests and write a documentation

2021-02-22 19:16 UTC, merged