Fix missing position from markets/list mng api
openware/peatio pull request #2819
Opened 2021-02-15 06:59 UTC by kengio

2021-02-16 07:13 UTC, chumaknadya requested changes

2021-02-16 07:13 UTC, chumaknadya commented on app/api/v2/management/markets.rb
> +          present ::Market.ordered, with: API::V2::Management::Entities::Market
can you check that this `position` present on spec test

2021-02-17 07:16 UTC, kengio commented on app/api/v2/management/markets.rb
> +          present ::Market.ordered, with: API::V2::Management::Entities::Market
Fixed.

2021-02-17 07:57 UTC, chumaknadya approved these changes

2021-02-19 15:53 UTC, merged