[WIP] Fix errors causing fiat deposits to be broken
openware/peatio pull request #288
Opened 2018-01-12 17:03 UTC by vpetrusenko

2018-01-12 17:04 UTC, yivo requested changes

2018-01-12 17:04 UTC, yivo commented on app/controllers/private/fund_sources_controller.rb
> +    skip_before_action :verify_authenticity_token
@vpetrusenko LOL. Disabling security is not a fix.

2018-01-12 17:09 UTC, vpetrusenko commented on app/controllers/private/fund_sources_controller.rb
> +    skip_before_action :verify_authenticity_token
...my bad, sorry

2018-01-12 18:06 UTC, yivo commented
@vpetrusenko Please, continue @dkkoval's work at https://github.com/rubykube/peatio/pull/289.

2018-01-12 20:53 UTC, vpetrusenko commented
@yivo pls check if i understand and do everything correctly

2018-01-13 15:04 UTC, yivo commented
Connected issues: #276, #290.

2018-01-13 15:08 UTC, yivo requested changes

2018-01-13 15:08 UTC, yivo commented on app/assets/javascripts/funds.js.coffee
> +  app.config ['$httpProvider', ($httpProvider) ->
@vpetrusenko Sorry, but what this is doing here? Did you ever check this? app is undefined. Why do you place this into document ready?

2018-01-15 07:23 UTC, vpetrusenko commented
One more connected issue: #130

2018-01-15 11:08 UTC, yivo commented
@vpetrusenko doesn't work

<img width="814" alt="screen shot 2018-01-15 at 1 08 22 pm" src="https://user-images.githubusercontent.com/7421323/34939640-3732b9cc-f9f5-11e7-8fd5-d388e61d5494.png">
<img width="802" alt="screen shot 2018-01-15 at 1 08 08 pm" src="https://user-images.githubusercontent.com/7421323/34939641-374df2b4-f9f5-11e7-8240-fa5e6b1f8cb0.png">

2018-01-15 12:14 UTC, vpetrusenko commented
![2018-01-15-141201_1680x1050_scrot](https://user-images.githubusercontent.com/26842923/34941913-5b12db70-f9fe-11e7-8aaa-16047f1f1a02.png)
![2018-01-15-141148_1680x1050_scrot](https://user-images.githubusercontent.com/26842923/34941908-54895572-f9fe-11e7-8718-171d3d438a41.png)

2018-01-15 12:14 UTC, vpetrusenko commented
@yivo i think it works correctly now

2018-01-15 13:10 UTC, mod requested changes

2018-01-15 13:10 UTC, mod commented on app/controllers/concerns/withdraws/withdrawable.rb
> +      params.require(:withdraw).permit(:member_id, :currency, :sum)
please verify if the form is posting fund_source_id and allow it,
I guess when you select your wallet JS should set the id before we post the request.

2018-01-16 07:52 UTC, vpetrusenko commented
![2018-01-16-094135_1680x1050_scrot](https://user-images.githubusercontent.com/26842923/34977370-f429ce8c-faa2-11e7-9706-a01f0d7b56fc.png)
![2018-01-16-093958_1680x1050_scrot](https://user-images.githubusercontent.com/26842923/34977368-f0addb54-faa2-11e7-8660-97acb7174168.png)

2018-01-16 07:53 UTC, vpetrusenko commented
so it works with btc

2018-01-16 13:09 UTC, yivo approved these changes

2018-01-16 13:10 UTC, vpetrusenko commented
Following issues should be clossed: #285 #290 #276 #130

2018-01-16 18:23 UTC, mod approved these changes

2018-01-16 18:33 UTC, mkuvshynnikov commented
Reviewed and approved

2018-01-16 19:20 UTC, merged