Feature/multi networks currency
openware/peatio pull request #2890
Opened 2021-04-08 14:28 UTC by crm-skyach

Made all  necessary changes

2021-04-09 07:06 UTC, calj commented on db/migrate/20210403054638_add_columns_to_blockchain.rb
> +class AddColumnsToBlockchain < ActiveRecord::Migration[5.2]
- Let's put all changes in one migration
- We need to set the blockchain key for existing payment addresses

2021-04-09 07:08 UTC, calj commented
- [ ] we need to expose blockchains informations in a new endpoint (blockchain key, description, ...)

2021-04-09 14:25 UTC, crm-skyach commented on db/migrate/20210403054638_add_columns_to_blockchain.rb
> +class AddColumnsToBlockchain < ActiveRecord::Migration[5.2]
Hi @calj , I have pulled all the changes in one migration named AddBlockchainKeyForMultiCurrency, also added blockchain key to existing payment address.

2021-04-09 14:28 UTC, crm-skyach commented
Hi have exposed blockchains informations in a new endpoint named "blockchain_info" and exposed the fields blockchain_key, description, warning.

2021-04-12 06:06 UTC, calj commented on app/api/v2/admin/entities/blockchain_info.rb
> +          expose(
we don't need to expose the internal id, just the key string.

2021-04-12 06:07 UTC, calj commented on app/api/v2/admin/entities/blockchain_info.rb
> +            :client,
we don't want to expose the client

2021-04-12 06:07 UTC, calj commented on app/api/v2/admin/entities/blockchain_info.rb
> +          expose(
we don't want to expose the height

2021-04-12 06:08 UTC, calj commented on app/api/v2/admin/entities/blockchain_info.rb
> +          expose(
we can't skip created_at and updated_at

2021-04-12 07:40 UTC, calj commented on app/api/v2/admin/entities/blockchain_info.rb
> +# encoding: UTF-8
We already have an admin endpoint exposing blockchains.
We need a public endpoint.
In order to reduce the number of endpoints we would like to introduce a new synthetic endpoint which will return all data in one call:

/api/v2/public/config

the response would be something like :

```json
{
  markets: [],
  currencies: [],
  blockchains: [],
  trading_fees: [],
  withdraw_limits: []
}
```

2021-04-12 14:50 UTC, crm-skyach commented on app/api/v2/admin/entities/blockchain_info.rb
> +          expose(
Hi @calj been deleted, I have taken care of this while creating new end point in public.

2021-04-12 14:51 UTC, crm-skyach commented on app/api/v2/admin/entities/blockchain_info.rb
> +            :client,
Hi @calj , the file has been deleted, I have taken care of this while creating new end point in public.

2021-04-12 14:51 UTC, crm-skyach commented on app/api/v2/admin/entities/blockchain_info.rb
> +          expose(
Hi @calj , the file has been deleted, I have taken care of this while creating new end point in public.

2021-04-12 14:52 UTC, crm-skyach commented on app/api/v2/admin/entities/blockchain_info.rb
> +          expose(
Hi @calj , the file has been deleted, I have taken care of this while creating new end point in public.

2021-04-12 14:52 UTC, crm-skyach commented on app/api/v2/admin/entities/blockchain_info.rb
> +# encoding: UTF-8
Hi @calj I have create a new public endpoint /api/v2/public/config and made the changes as per your review comments on my previous file.

2021-04-13 06:50 UTC, calj commented on app/api/v2/entities/blockchain.rb
> +        expose(
Please remove created_at and updated_at

2021-04-13 06:52 UTC, calj commented on app/api/v2/public/config.rb
> +          present currencies: Currency.all, with: Entities::Currency,
I think it should be ```Currency.visible``` or something here, you can check existing endpoint and do the same query.
Please check this for each entry.

2021-04-13 06:53 UTC, calj commented on app/api/v2/entities/currency.rb
> +        expose(
Please remove blockchains from here.

2021-04-13 13:00 UTC, crm-skyach commented on app/api/v2/public/config.rb
> +          present currencies: Currency.all, with: Entities::Currency,
Hi @calj , I have added currency.visible, market.enabled and blockchain.active but kept the tradingfee and withdrawal limit without scopes, since they do not have any.

2021-04-13 13:00 UTC, crm-skyach commented on app/api/v2/entities/blockchain.rb
> +        expose(
@calj , I have removed that,

2021-04-13 13:00 UTC, crm-skyach commented on app/api/v2/entities/currency.rb
> +        expose(
Hi @calj , we have removed the blockchain.

2021-06-01 01:59 UTC, huuhait commented
when it is ready in master branch?

2021-06-01 06:33 UTC, chumaknadya requested changes

2021-06-01 06:33 UTC, chumaknadya commented on db/schema.rb
we need to delete min_deposit_amount/min_collection from currencies table

2021-06-01 06:33 UTC, chumaknadya commented on db/migrate/20210409100639_add_blockchain_key_for_multi_currency.rb
> +
it would be cool to add migration from old configuration to new without manual change

2021-06-04 12:01 UTC, closed without merging