Add retired status
openware/peatio pull request #2920
Opened 2021-04-29 12:12 UTC by crm-skyach

Display address from active wallets

Generate address from active wallets

deposit/withdraw from retired wallets

Add status for address

2021-04-29 12:58 UTC, chumaknadya commented
Could you add tests for this PR?

2021-04-29 12:59 UTC, calj commented on app/models/deposit.rb
> +      status:                   PaymentAddress.find_by_address(address)&.wallet&.status,
This looks wrong to me. Why would we need the status of the deposit address to be exposed for a deposit?

2021-04-29 13:05 UTC, chumaknadya requested changes

2021-04-29 13:05 UTC, chumaknadya commented on app/models/deposit.rb
> +      status:                   PaymentAddress.find_by_address(address)&.wallet&.status,
its very confusing to have state and status here, and its not deposit status, 
its more like wallet_state or payment_address_state

2021-05-03 12:24 UTC, crm-skyach commented on app/models/deposit.rb
> +      status:                   PaymentAddress.find_by_address(address)&.wallet&.status,
Hi @chumaknadya i have changed the status to wallet_state. Please check the comment @calj do we need to remove or do you have any other suggestions on that.

2021-05-03 12:24 UTC, crm-skyach commented
> Could you add tests for this PR?

I have added the test cases

2021-05-04 13:22 UTC, closed without merging