Read Json file to create blockchain wallets and currencies
openware/peatio pull request #2923
Opened 2021-05-07 15:52 UTC by crm-skyach

2021-05-10 08:25 UTC, chumaknadya requested changes

2021-05-10 08:25 UTC, chumaknadya commented on app/api/v2/admin/import_blockchain_currency_wallets.rb
> +        end
please, add tests

2021-05-10 08:25 UTC, chumaknadya commented on app/api/v2/admin/import_blockchain_currency_wallets.rb
> +        post '/import_blockchain_currency_wallets' do
lets name it  '/import_configs'
And name of plugin should be ImportConfig 

Also maybe lets use API helpers instead of helper in peatio lib

2021-05-10 08:25 UTC, chumaknadya commented on lib/peatio/import_blockchain_currency_wallet.rb
> +
here we should process first blockchains, then currencies, then wallets

2021-05-10 13:52 UTC, crm-skyach commented on app/api/v2/admin/import_blockchain_currency_wallets.rb
> +        end
Added test

2021-05-10 13:53 UTC, crm-skyach commented on app/api/v2/admin/import_blockchain_currency_wallets.rb
> +        post '/import_blockchain_currency_wallets' do
Changed according to the comments

2021-05-10 13:53 UTC, crm-skyach commented on lib/peatio/import_blockchain_currency_wallet.rb
> +
changed according to the comments

2021-05-10 16:01 UTC, chumaknadya requested changes

2021-05-10 16:01 UTC, chumaknadya commented on app/api/v2/import_config_helpers.rb
> +end
empty line here

2021-05-10 16:01 UTC, chumaknadya commented on app/api/v2/import_config_helpers.rb
> +    class ImportConfigHelpers
name - ImportConfigsHelper

2021-05-10 16:01 UTC, chumaknadya commented on app/api/v2/import_config_helpers.rb
> +          data.each do |record|
Are you sure that in case
{
currencies: [],
blockchains: [],
}
it will process blockchain first?

I think you need to have sort before, like every time to have blockchains first, then currencies, then wallets

2021-05-10 16:01 UTC, chumaknadya commented on app/api/v2/import_config_helpers.rb
> +              ::Wallet.create!(record) unless ::Wallet.find_by(blockchain_key: record[:blockchain_key], kind: record[:kind])
you should check Wallet by name
We have check only for name in wallet model

2021-05-11 06:51 UTC, chumaknadya requested changes

2021-05-11 06:51 UTC, chumaknadya commented on app/api/v2/import_configs_helper.rb
> +            end
else case should be here

2021-05-11 06:51 UTC, chumaknadya commented on spec/resources/import_config/data.json
> +      "precision": 8,
lets add options here

2021-05-11 06:55 UTC, chumaknadya requested changes

2021-05-11 06:55 UTC, chumaknadya commented on app/api/v2/import_configs_helper.rb
> +              ::Blockchain.create!(record) unless ::Blockchain.find_by(key: record[:key])
here we should skip blockchains which have already exist in system instead of raising error

2021-05-11 06:55 UTC, chumaknadya commented on app/api/v2/import_configs_helper.rb
> +end
please remove empty lines in files

2021-05-11 06:55 UTC, chumaknadya commented on app/api/v2/admin/import_configs.rb
> +        desc 'Import currency, blockchain and wallet from json file'
Import currencies, blockchains and wallets from json file

2021-05-11 06:55 UTC, chumaknadya commented on spec/resources/import_config/data.json
> +      "status": "active"
lets add wallet with options here too

2021-05-11 13:30 UTC, crm-skyach commented on app/api/v2/import_config_helpers.rb
> +end
Changes are done

2021-05-11 13:30 UTC, crm-skyach commented on app/api/v2/import_config_helpers.rb
> +    class ImportConfigHelpers
name is changed

2021-05-11 13:30 UTC, crm-skyach commented on app/api/v2/import_config_helpers.rb
> +          data.each do |record|
changes are done accordingly

2021-05-11 13:31 UTC, crm-skyach commented on app/api/v2/import_config_helpers.rb
> +              ::Wallet.create!(record) unless ::Wallet.find_by(blockchain_key: record[:blockchain_key], kind: record[:kind])
change this now it is checking by name

2021-05-11 13:31 UTC, crm-skyach commented on app/api/v2/import_configs_helper.rb
> +            end
else case added

2021-05-11 13:31 UTC, crm-skyach commented on spec/resources/import_config/data.json
> +      "precision": 8,
options are added

2021-05-11 13:31 UTC, crm-skyach commented on app/api/v2/import_configs_helper.rb
> +              ::Blockchain.create!(record) unless ::Blockchain.find_by(key: record[:key])
this is done

2021-05-11 13:31 UTC, crm-skyach commented on app/api/v2/import_configs_helper.rb
> +end
done

2021-05-11 13:31 UTC, crm-skyach commented on app/api/v2/admin/import_configs.rb
> +        desc 'Import currency, blockchain and wallet from json file'
changes are done

2021-05-11 13:32 UTC, crm-skyach commented on spec/resources/import_config/data.json
> +      "status": "active"
change are done

2021-05-12 06:44 UTC, chumaknadya requested changes

2021-05-12 06:44 UTC, chumaknadya commented on spec/resources/import_config/data.json
> +      "status": "active"
you havn't added settings here

2021-05-21 13:37 UTC, calj approved these changes

2021-05-24 09:41 UTC, mnaichuk approved these changes

2021-05-24 09:52 UTC, merged