Add WebhooksController for wallet deposits processing
openware/peatio pull request #322
Opened 2018-01-19 16:43 UTC by yssavchuk

2018-01-19 16:43 UTC, yssavchuk commented
@yivo review please

2018-01-19 16:54 UTC, yivo requested changes

2018-01-19 16:54 UTC, yivo commented on app/controllers/webhooks_controller.rb
> +  def tx
Use single quotes. Write code which handles situation when invalid or no data is given (respond 422). Don't use obsolete hash syntax. Change URL & action to `/webhooks/btc/tx_created => post btc_tx_created`. Respond with 204.

2018-01-19 16:54 UTC, yivo commented on config/routes.rb
> +  post '/webhooks/tx' => 'webhooks#tx', as: :deposit_webhook
Remove `:as`.

2018-01-21 12:22 UTC, yivo requested changes

2018-01-21 12:22 UTC, yivo commented on app/controllers/webhooks_controller.rb
> +    params.permit(:type, :hash, :ccy)
@yssavchuk don't use permit unless you are dealing with models

2018-01-21 12:22 UTC, yivo commented on app/controllers/webhooks_controller.rb
> +      render json: { status: :no_content }
@yssavchuk don't render unneeded JSON. Use head :no_content.

2018-01-21 12:22 UTC, yivo commented on app/controllers/webhooks_controller.rb
> +    if webhook_params[:type] == "transaction" && webhook_params[:hash].present? && Currency.coins.map(&:code)
@yssavchuk use single quotes.

2018-01-21 12:22 UTC, yivo commented on app/controllers/webhooks_controller.rb
> +  def webhook_params
@yssavchuk unneeded

2018-01-21 12:22 UTC, yivo commented on app/models/currency.rb
> +    @coins ||= Currency.where(coin: true)
@yssavchuk ok for now but we will remove it when dynamic configuration arrives.

2018-01-21 12:22 UTC, yivo commented on app/controllers/webhooks_controller.rb
> +# Service triggers webhook due to incoming bitcoin deposits.
@yssavchuk the descriptions must be updated.

2018-01-21 12:22 UTC, yivo commented on app/controllers/webhooks_controller.rb
> +  skip_before_filter :verify_authenticity_token
@yssavchuk use skipe_before_action

2018-01-21 12:22 UTC, yivo commented on app/controllers/webhooks_controller.rb
> +    if webhook_params[:type] == "transaction" && webhook_params[:hash].present? && Currency.coins.map(&:code)
@yssavchuk what it does? `&& Currency.coins.map(&:code)`

2018-01-21 12:31 UTC, yivo approved these changes

2018-01-22 15:36 UTC, merged