Update rest-client & rack-attack gems
openware/peatio pull request #348
Opened 2018-01-24 11:03 UTC by vpetrusenko

related to issue #337

2018-01-24 11:04 UTC, vpetrusenko commented
Updating ruby-advisory-db ...
From https://github.com/rubysec/ruby-advisory-db
 * branch            master     -> FETCH_HEAD
Already up to date.
Updated ruby-advisory-db
ruby-advisory-db: 293 advisories
No vulnerabilities found

2018-01-24 12:01 UTC, yivo commented
@vpetrusenko Please check that BTC & XRP deposits / trading / withdraws work. Also pls check API is able to limit requests by setting small limit and issuing multiple requests.

2018-01-24 13:12 UTC, yivo commented
@vpetrusenko Any feedback?

2018-01-24 13:25 UTC, vpetrusenko commented
@yivo deposits / trading / withdraws works correctly, now i try to check API limit

2018-01-24 14:32 UTC, yivo requested changes

2018-01-24 14:32 UTC, yivo commented on Gemfile
> +gem 'faraday', '~> 0.12.2'
@vpetrusenko I think we don't specify patch level in version for faraday.

2018-01-24 14:41 UTC, vpetrusenko commented on Gemfile
> +gem 'faraday', '~> 0.12.2'
@yivo okay

2018-01-24 14:55 UTC, vpetrusenko commented
@yivo deposits / trading / withdraws works correctly, rack-attack also seems to works correctly, bundle audit cannot find any vulnerabilities

2018-01-24 19:18 UTC, yivo requested changes

2018-01-24 19:18 UTC, yivo commented on Gemfile
> +gem 'faraday'
@vpetrusenko You should specify version range.

2018-01-24 19:18 UTC, yivo commented on lib/coin_rpc/xrp.rb
> +          Faraday.get(
@vpetrusenko Why you have lot a leading spaced for each `Faraday` statement?

2018-01-24 20:42 UTC, vpetrusenko commented
@yivo made changes according to last review

2018-01-25 10:31 UTC, yivo approved these changes

2018-01-25 21:24 UTC, merged