Generic JWT feature
openware/peatio pull request #35
Opened 2017-11-30 15:32 UTC by yivo

2017-11-30 16:09 UTC, mod requested changes

2017-11-30 16:09 UTC, mod commented on Gemfile
> +gem 'faraday', '~> 0.12.0'
not yet we will do a jwt branch

2017-11-30 16:09 UTC, mod commented on app/api/api_v2/auth/authenticator.rb
> +        if @request.env['HTTP_AUTHORIZATION'].present?
agreed but I think we should have a cleaner JWT check methods
and 
```
begin 
try jwt
try sdk
end
```

2017-11-30 16:09 UTC, mod commented on app/api/api_v2/auth/authenticator.rb
> +        @token ||= APIToken.joins(:member).where(access_key: access_key).first
ok

2017-11-30 16:09 UTC, mod commented on app/api/api_v2/auth/authenticator.rb
> +        if tonce < now - 30000 || tonce > now + 30000
ok

2017-11-30 16:09 UTC, mod commented on app/api/api_v2/auth/authenticator.rb
> +        "#{canonical_verb}|#{APIv2::Mount::PREFIX}#{canonical_path}|#{canonical_params}"
maybe

2017-11-30 16:09 UTC, mod commented on app/api/api_v2/auth/authenticator.rb
> +      def canonical_params
it seems a big change and it should work without those change
what is it for ?

2017-11-30 16:09 UTC, mod commented on app/api/api_v2/auth/middleware.rb
> +        env['HTTP_AUTHORIZATION'].present? ||
for the next patch.
I personally don't use HTTP_AUTHORIZATION for JWT

2017-11-30 16:09 UTC, mod commented on app/api/api_v2/auth/utils.rb
>          end
ok

2017-11-30 16:09 UTC, mod commented on app/api/api_v2/constraints.rb
>      end
ok

2017-11-30 16:09 UTC, mod commented on app/api/api_v2/deposits.rb
> +    get '/deposits' do
ok

2017-11-30 16:09 UTC, mod commented on app/api/api_v2/members.rb
> +    before { authenticate! }
interesting maybe now maybe later you pick you try

2017-11-30 16:09 UTC, mod commented on app/api/api_v2/named_params.rb
> -    end
I see, we can delay this change in JWT patch

2017-11-30 16:09 UTC, mod commented on app/api/api_v2/orders.rb
> +      use :market
I don't understand this change

2017-11-30 16:09 UTC, mod commented on app/api/api_v2/websocket_protocol.rb
> +require 'securerandom'
try removing the require

2017-11-30 16:09 UTC, mod commented on app/exceptions/auth0/bad_token_error.rb
> +module Auth0
not yet

2017-11-30 16:09 UTC, mod commented on app/models/token.rb
> +    self.expires_at = 30.minutes.from_now
ok

2017-11-30 16:09 UTC, mod commented on app/services/auth0/jwt.rb
> +require 'openssl/x509'
no yet; and not later we need to fetch using the oauth token through another patch

2017-11-30 16:09 UTC, mod commented on app/services/auth0/peatio_api_token_adapter.rb
> +module Auth0
so much code here, I am not sure we would need it

2017-12-05 13:58 UTC, yivo commented
@mod  Closing this as it contains too much rejected stuff

2017-12-05 13:58 UTC, closed without merging