Security fixes according to Brakeman
openware/peatio pull request #350
Opened 2018-01-24 11:50 UTC by vpetrusenko

Related to issue #336

2018-01-24 11:59 UTC, yivo requested changes

2018-01-24 11:59 UTC, yivo commented on app/controllers/test/module_controller.rb
> +    protect_from_forgery with: :exception
@vpetrusenko Do you know what this controller is used for any why it doesn't require such stuff?

2018-01-24 11:59 UTC, yivo commented on app/controllers/test/module_controller.rb
> +    protect_from_forgery with: :exception
You need to remove it.

2018-01-24 12:12 UTC, vpetrusenko commented on app/controllers/test/module_controller.rb
> +    protect_from_forgery with: :exception
@yivo sorry, i just follow brakeman advices, will be carefully

2018-01-24 12:34 UTC, yivo requested changes

2018-01-24 12:34 UTC, yivo commented on app/controllers/test/module_controller.rb
> +    protect_from_forgery with: :exception
@vpetrusenko Don't respect too much from automated tool for analysing static code. Will you continue fixing brakeman reports in this PR or create new one?

2018-01-24 13:19 UTC, vpetrusenko commented on app/controllers/test/module_controller.rb
> +    protect_from_forgery with: :exception
@yivo i will continue in this PR

2018-01-29 09:43 UTC, yivo commented
Hello @vpetrusenko. What is the progress on it?

2018-01-30 10:38 UTC, vpetrusenko commented
@yivo Hello, sorry i don't work on it in because of barong rush, but i work on it today

2018-01-30 19:31 UTC, yivo commented
@vpetrusenko I have checked PR and noticed you are doing many things wrong. Consider digging into the implementation details to understand hot things work. Remember it is STATIC code analysis. It is mostly stupid and fake-positive in 90% cases.

2018-01-31 09:37 UTC, vpetrusenko commented
@yivo okay i will try to understand and fix my mistakes, but actually i don't understand a lot of brakeman remarks about peatio

2018-01-31 22:02 UTC, vpetrusenko commented
@yivo So all other brakeman remarks for me seems unsolvable in case to keep peatio work correct, so if this changes looks good i guess we should leave only them in patch

2018-02-02 19:50 UTC, yivo reviewed
@vpetrusenko I will do changes by myself. Please DON'T push to this branch. Thanks.

2018-02-02 19:50 UTC, yivo commented on app/models/account_version.rb
> +    stmt   = sanitize_sql("INSERT INTO account_versions (#{attrs.keys.join(',')}) #{select}")
@vpetrusenko I am very sorry but WTF? Have you read the source of `sanitize_sql`? Do you understand it?

2018-02-02 19:50 UTC, yivo commented on app/views/private/assets/_usd_assets.html.erb
> +        <%= t('.description', @usd_assets['accounts'].first.symbolize_keys.html_safe) %>
@vpetrusenko Why you haven't run the project?
<img width="826" alt="screen shot 2018-02-02 at 9 45 09 pm" src="https://user-images.githubusercontent.com/7421323/35751818-7b39f862-0862-11e8-918e-4ff623f7677d.png">

2018-02-02 19:50 UTC, yivo commented on app/controllers/application_controller.rb
> +      redirect_to URI.parse(cookies[:redirect_to]).path
@vpetrusenko OK.

2018-02-02 19:52 UTC, yivo commented
@vpetrusenko I have pushed the changes. I will wait until all specs will success.

2018-02-02 20:51 UTC, yivo commented
It works well: deposits / withdraws / trading.

2018-02-02 20:52 UTC, yivo approved these changes

2018-02-02 21:02 UTC, mod approved these changes

2018-02-02 21:02 UTC, merged

2018-02-02 23:12 UTC, vpetrusenko commented
@yivo thank you for help with this patch!