BitGo support
openware/peatio pull request #355
Opened 2018-01-24 14:35 UTC by yivo

2018-01-24 22:10 UTC, yivo commented
@mkuvshynnikov I have good progress on it. I think tomorrow I will finish this PR.

2018-01-25 21:46 UTC, mod requested changes

2018-01-25 21:46 UTC, mod commented on lib/coin_api/bit_go.rb
> +      @endpoint     = 'https://test.bitgo.com/api/v2/t' + currency.code.downcase
We are going to need a VAR for this parameter

2018-01-25 21:46 UTC, mod commented on app/models/worker/deposit_coin.rb
> +          txout: 1,
what was the value of txout ?

2018-01-25 21:51 UTC, yivo commented on lib/coin_api/bit_go.rb
> +      @endpoint     = 'https://test.bitgo.com/api/v2/t' + currency.code.downcase
@mod Sure. I put it for the WIP period of patch.

2018-01-25 21:56 UTC, yivo commented on app/models/worker/deposit_coin.rb
> +          txout: 1,
@mod It was used as index in list of `transaction[:details]`. This list always contains one entry of `payment` category.

2018-01-29 20:42 UTC, merged