Issue refreshing the page creates new api token
openware/peatio pull request #356
Opened 2018-01-24 15:12 UTC by dinesh-skyach

Issue refreshing the page creates new api token

2018-01-24 19:15 UTC, yivo requested changes

2018-01-24 19:15 UTC, yivo commented on app/views/private/api_tokens/show.html.erb
> +<p><%= t('.desc') %></p>
@dinesh-skyach I see this code exists in another file. Why it is duplicated?

2018-01-25 06:58 UTC, dinesh-skyach commented
Hi @yivo  , Sorry about that, instead of avoiding duplicacy, we needed to remove the create.html.erb and shift its code to show.html.erb as create.html.erb should not have been there if we follow rails way. I missed to remove the file earlier. Please review.

2018-01-25 11:51 UTC, yivo commented
@dinesh-skyach Thanks. We will assign our QA to review it.

2018-01-25 11:51 UTC, yivo commented
ping @mkuvshynnikov

2018-01-25 13:14 UTC, yivo approved these changes

2018-01-25 13:14 UTC, yivo commented
ping @mkuvshynnikov

2018-01-25 21:20 UTC, merged