Create configuration variables which should be used to specify active…
openware/peatio pull request #357
Opened 2018-01-24 16:59 UTC by yssavchuk

… OAuth providers

2018-01-25 09:40 UTC, yivo requested changes

2018-01-25 09:40 UTC, yivo commented on lib/generators/config/templates/application.yml.erb
> -  # Configuration variables for webhooks.
@yssavchuk Pls rebase.Why have you removed it?

2018-01-25 09:40 UTC, yivo commented on lib/generators/config/templates/application.yml.erb
> +  # Development oauth2 providers
@yssavchuk Pls ALWAYS put dot at the end of comment and name thing according to their originals – OAuth2. Also lets change google_oauth2 to google. It is OK.

2018-01-25 21:23 UTC, mod commented
@yivo is it urgent ?
I would highly favor using a OR
it's auth0 or barong or google
and this code will stay for a while I believe

2018-01-25 21:23 UTC, yivo approved these changes

2018-01-25 21:26 UTC, yivo commented
@mod This is what you asked some time ago. It isn't urgent. Do you want to allow selecting only single provider? Or leave as it (separated by comma).

2018-01-26 08:53 UTC, yivo commented
Fixed.

2018-01-27 16:48 UTC, merged