Removed eco gem and installed ejs
openware/peatio pull request #358
Opened 2018-01-24 18:56 UTC by rklymenko

2018-01-24 19:13 UTC, yivo requested changes

2018-01-24 19:13 UTC, yivo commented on Gemfile
> +gem 'ejs'
@rklymenko You should always lock gem to version range.

2018-01-24 19:14 UTC, yivo commented
@rklymenko Please fix specs.

2018-01-24 19:51 UTC, rklymenko commented
@yivo I locked gem version. But for specs, I think need to create another branch, because issues not for this task, these issues exists in master branch

2018-01-24 19:57 UTC, yivo requested changes

2018-01-24 19:57 UTC, yivo commented on Gemfile
> +gem 'ejs', '1.1.1'
@rklymenko I am sure you are not doing wright. Have you previously used RubyGems & Bundler?

2018-01-24 19:57 UTC, yivo commented on Gemfile
> +gem 'ejs', '1.1.1'
Are you familiar with semver?

2018-01-24 19:59 UTC, yivo commented
@rklymenko You may check master branch or devel for working specs. Navigate to TravisCI and you will see all specs are passed.

2018-01-24 20:00 UTC, yivo commented
@rklymenko You should also update the PR to target to correct branch as in specs.

2018-01-24 20:04 UTC, rklymenko commented on Gemfile
> +gem 'ejs', '1.1.1'
yes, I used RubyGems and Bundler but don't used semver

2018-01-24 20:05 UTC, rklymenko commented
I checked specs in the master branch, and have 5 issues like in my branch

2018-01-24 20:05 UTC, yivo commented on Gemfile
> +gem 'ejs', '1.1.1'
@rklymenko You couldn't use Bundler without using semver.

2018-01-24 20:06 UTC, rklymenko commented
`Failed examples:

rspec ./spec/features/market_spec.rb:58 # show account info user can fill order form by clicking on an existing orders in the order book
rspec ./spec/features/market_spec.rb:24 # show account info user can place a buy order by filling in the order form
rspec ./spec/features/market_spec.rb:41 # show account info user can place a sell order by filling in the order form
rspec ./spec/features/market_spec.rb:81 # show account info user can view his account balance
rspec ./spec/features/market_trade_history_spec.rb:14 # show account info user can cancel his own order

Randomized with seed 59637

slan@asus /var/www/peatio $ git status
On branch master
Your branch is up-to-date with 'origin/master'.
`

2018-01-24 20:06 UTC, yivo commented
@rklymenko I don't see any issues with specs on master right now.

2018-01-25 11:49 UTC, yivo commented
@rklymenko Any progress on it?

2018-01-25 15:38 UTC, yivo commented
@rklymenko Any updates?

2018-01-26 09:55 UTC, rklymenko commented
I am working on specs. I have issue only with selenium

2018-01-28 10:37 UTC, rklymenko commented
Hi @yivo , I checked specs one more time. It's not my issues. They exist in master branch on my fork. Check please. And if you check one of specs - you see that issue different from my task.

2018-01-28 10:38 UTC, rklymenko commented
@yivo And if you want I can work with it but in another issue and task

2018-01-29 09:39 UTC, yivo commented
@rklymenko Hello. We don't have any broken specs now in master and in devel. I believe you should check the issue once again and update PR to match requirements.

2018-01-29 13:54 UTC, closed without merging