[WIP] change sql query to active record
openware/peatio pull request #362
Opened 2018-01-25 09:22 UTC by rorong

2018-01-25 09:35 UTC, yivo requested changes

2018-01-25 09:35 UTC, yivo commented on app/models/account.rb
> +    self.update_attributes(balance: self.balance + delta_b, locked: self.locked + delta_l)
@rorong I am very curious about transaction in this example? Can you add comments and check if everything works well? Test manually pls.

2018-01-25 09:35 UTC, yivo commented on spec/models/account_spec.rb
> +      subject.update_attributes(balance: subject.balance + 3, locked: subject.locked - 8)
@rorong For this example `update_attributes` works differently compared to plain SQL. Pls find out why.

2018-01-25 09:37 UTC, yivo commented
@rorong What this PR is related to?

2018-01-25 09:50 UTC, rorong commented on spec/models/account_spec.rb
> +      subject.update_attributes(balance: subject.balance + 3, locked: subject.locked - 8)
@yivo I am working on it

2018-01-25 09:50 UTC, rorong commented on app/models/account.rb
> +    self.update_attributes(balance: self.balance + delta_b, locked: self.locked + delta_l)
@yivo ok, i need to test it as 1 test is failing i need to find why and solve it

2018-01-25 09:56 UTC, yivo commented on app/models/account.rb
> +    self.update_attributes(balance: self.balance + delta_b, locked: self.locked + delta_l)
@rorong We don't good test coverage now. Pls consider testing manually deposits / withdraws / trading.

2018-01-25 10:40 UTC, rorong commented on app/models/account.rb
> +    self.update_attributes(balance: self.balance + delta_b, locked: self.locked + delta_l)
ok

2018-01-29 09:43 UTC, yivo commented
@rorong Hello. Please, describe what this PR is related to? Also what is the progress on it?

2018-01-29 09:45 UTC, rorong commented
@yivo 
This is related to https://github.com/rubykube/peatio/issues/207

2018-01-29 09:46 UTC, rorong commented
@yivo 
@calj Tell me to convert raw sql to active record but i am facing some issue init.

2018-02-01 13:14 UTC, rorong commented
@yivo can you please tell me when this event is fired

2018-02-01 13:18 UTC, yivo commented
@rorong Sorry, what event?

2018-02-02 04:40 UTC, rorong commented
@yivo Means when i do manually check then from where this actions is called.

2018-02-02 09:35 UTC, calj commented on spec/models/account_spec.rb
> +      subject.update_attributes(balance: subject.balance + 3, locked: subject.locked - 8)
Anyway we can't make the sum in ruby, we need this code to be [reentrant](https://en.wikipedia.org/wiki/Reentrancy_(computing)).

When the sum is made in SQL it's applied implicitly in a transaction, so if 2 concurrents threads try to increase the balance the final balance will be correct.

2018-02-02 10:12 UTC, yivo commented
@rorong I believe you should "grep" whole project for the method name. This is the one solution for finding usaged. The second other will be digging into source code details. I think you can also play with Peatio, get everything running and check if deposit / withdraw / trading work as expected.

2018-02-02 10:16 UTC, rorong commented
@yivo Ok, I have to play around it to check its functionality

2018-02-04 03:10 UTC, rorong commented on spec/models/account_spec.rb
> +      subject.update_attributes(balance: subject.balance + 3, locked: subject.locked - 8)
@calj ok

2018-02-05 13:21 UTC, rorong commented
@yivo @calj 

I've tried to do in active record but got the some unexpected behaviour of adding two transaction value with active record. I thoughts, we have to insatlled the MSSQL server and write the code and test the flow.

2018-02-05 15:01 UTC, yivo commented
@rorong Will you install MSSQL and test it?

2018-02-06 06:55 UTC, rorong commented
@yivo I will install MSSQL and test it.

2018-02-06 10:30 UTC, yivo commented
@rorong Can you finish this issue till Friday?

2018-02-07 06:55 UTC, rorong commented
@yivo I have installed the MSSQL server i will try to finish it till Friday

2018-02-12 17:08 UTC, closed without merging