[WIP] GOD logs to STDOUT/STDERR
openware/peatio pull request #363
Opened 2018-01-25 10:31 UTC by ashanaakh

Fix god logging #335.

2018-01-25 12:30 UTC, ashanaakh commented
@yivo Should work now

2018-01-25 12:37 UTC, yivo commented
@ashanaakh Pls don't manage labels.

2018-01-25 12:38 UTC, yivo requested changes

2018-01-25 12:38 UTC, yivo commented on lib/daemons/daemons.god
> +    if RAILS_ENV == "production"
@ashanaakh 

1. We use single quotes.
2. What is usr/bin/logger and what platforms have it?

2018-01-25 12:44 UTC, ashanaakh commented on lib/daemons/daemons.god
> +    if RAILS_ENV == "production"
@yivo 
1. All unix based systems
2. Fixed

2018-01-25 12:51 UTC, ashanaakh commented
All unix systems have `/usr/bin/logger`, I checked it with `journalctl` on Arch Linux

2018-01-25 12:52 UTC, ashanaakh commented
#
![deepinscreenshot_select-area_20180125143750](https://user-images.githubusercontent.com/15674738/35389167-51b6ed9e-01df-11e8-8536-4b43824a909d.png)

2018-01-25 13:02 UTC, yivo requested changes

2018-01-25 13:02 UTC, yivo commented on lib/daemons/daemons.god
> +      w.log_cmd     = '/usr/bin/logger'
@ashanaakh You should add tag and PID according to https://linux.die.net/man/1/logger.

2018-01-25 13:02 UTC, yivo commented on lib/daemons/daemons.god
> +      w.log_cmd     = '/usr/bin/logger'
Does it work in container?

2018-01-25 13:25 UTC, ashanaakh commented on lib/daemons/daemons.god
> +      w.log_cmd     = '/usr/bin/logger'
@yivo Yes, it works

2018-01-25 13:26 UTC, ashanaakh commented
@yivo I added tag for logging, trying to solve PID.

2018-01-25 13:52 UTC, ashanaakh commented
@yivo We don't need to define `pid_file`, it use: `$HOME/.god/pids`

2018-01-25 14:15 UTC, yivo requested changes

2018-01-25 14:15 UTC, yivo commented on lib/daemons/daemons.god
> +      w.err_log_cmd = '/usr/bin/logger -t GOD'
@ashanaakh Every log entry should include daemon PID and tag or it will be hard to separate output across daemons (check my prev comment). Also change PRs branch to devel. We don't work on master.

2018-01-25 14:49 UTC, ashanaakh commented
@yivo please review, it's ready

2018-01-25 15:02 UTC, yivo requested changes

2018-01-25 15:02 UTC, yivo commented on lib/daemons/daemons.god
> +      w.log_cmd     = "/usr/bin/logger -t #{filesafe_name} --id=#{w.pid}"
@ashanaakh There is an option ` -i'         Log the process id of the logger process with each line.`
https://linux.die.net/man/1/logger

Can you give me output from docker logs after you will fix it?

2018-01-26 08:50 UTC, yivo commented on lib/daemons/daemons.god
> +      w.log_cmd     = "/usr/bin/logger -t #{filesafe_name} --id=#{w.pid}"
Can you check `-i` output PIDs for each daemons or per logger instance?

2018-01-26 09:37 UTC, ashanaakh commented on lib/daemons/daemons.god
> +      w.log_cmd     = "/usr/bin/logger -t #{filesafe_name} --id=#{w.pid}"
@yivo Locally I can see it in syslog, but I have problems with docker logs

2018-01-26 11:04 UTC, ashanaakh commented on lib/daemons/daemons.god
> +      w.log_cmd     = "/usr/bin/logger -t #{filesafe_name} --id=#{w.pid}"
`-i` works fine, but I need some time to understand how to print exactly to STDOUT

2018-01-29 09:45 UTC, yivo commented
@ashanaakh Hello. When you will finish it?

2018-01-29 09:54 UTC, yivo commented
@ashanaakh Pls finish it today. It is urgent.

2018-01-29 12:19 UTC, ashanaakh commented
@yivo Working on it now.

2018-01-29 13:03 UTC, ashanaakh commented
@yivo Actually, I can't find solution for this task...

2018-01-31 17:34 UTC, yivo approved these changes

2018-01-31 22:21 UTC, merged