279 refactor currencies into ar model
openware/peatio pull request #368
Opened 2018-01-25 12:22 UTC by mitjok

The code prepared for refactoring. ActiveYamlBase Currency is isolated. Method calls still delegated to it.

2018-01-25 12:36 UTC, yivo requested changes

2018-01-25 12:36 UTC, yivo commented on app/models/configs/currency.rb
> +module Configs
@mitjok Pls don't add any Ruby modules.

2018-01-25 12:36 UTC, yivo commented on app/models/configs/currency.rb
> +module Configs
We need to fully replace currency with AR.

2018-01-25 12:36 UTC, yivo commented on config/initializers/mysql/json_data_type.rb
> +module ActiveRecord
@mitjok Wow. You should discard it. Use simple serializable attributes.

2018-01-25 12:36 UTC, yivo commented on db/migrate/20180124120251_add_currencies.rb
> +      t.timestamps
@mitjok timestamps should be not null.

2018-01-25 12:36 UTC, yivo commented on db/migrate/20180124120251_add_currencies.rb
> +      t.timestamps
For options add t.string :options, limit: 1000, default: '{}', null: false

2018-01-25 12:36 UTC, yivo commented on db/schema.rb
> +# Could not dump table "currencies" because of following StandardError
@mitjok Don't write comments here. They will disappear after I will run migrations.

2018-01-25 12:36 UTC, yivo commented on package.json
> +    "pusher-js": "^4.2.2",
@mitjok I know why you have added it but we don't use yarn for pusher (I added yarn for sentry some time ago). Just no need for this now.

2018-01-25 12:36 UTC, yivo commented on app/models/configs/currency.rb
> +module Configs
You may do it the dirty way. Don't waste time for doing it cool.

2018-01-25 12:45 UTC, mitjok commented on app/models/configs/currency.rb
> +module Configs
Eventually it will be replaced. Now it isolated for refactoring. I plan to bit method by method from `Currency < ActiveYamlBase`. Dirty way will hurt, as I don't know the project yet. Thx for the review

2018-01-25 12:47 UTC, yivo commented on config/initializers/mysql/json_data_type.rb
> +module ActiveRecord
Native JSON field is not what I am looking for (but this is great, I need support for different DB).

2018-01-25 12:48 UTC, yivo commented on app/models/configs/currency.rb
> +module Configs
@mitjok We have QA who can manually test whole project. He can test your PR when you will finish 👍

2018-01-25 13:10 UTC, mitjok commented on config/initializers/mysql/json_data_type.rb
> +module ActiveRecord
ok

2018-01-25 13:12 UTC, mitjok commented on db/schema.rb
> +# Could not dump table "currencies" because of following StandardError
@yivo they are autogenerated

2018-02-02 11:03 UTC, yivo commented
@mitjok Can you please change base branch to devel? I see your PR fetched too many merged commits.

2018-02-05 15:55 UTC, yivo commented
@mitjok 
* Remove /config, linked Ruby module and move code to real configs
* Hardcoded deposit / withdraw controllers & models should be kept and should work
* Apply minor fixes to currency table schema

2018-02-05 16:02 UTC, yivo commented
Can you also please check missing fields on currency model? We have added several. 

@mitjok

2018-02-09 09:51 UTC, yivo commented
Moved to #488.

2018-02-09 09:51 UTC, closed without merging