[WIP] Add support for Ethereum
openware/peatio pull request #381
Opened 2018-01-27 06:32 UTC by GildedHonour

2018-01-28 13:01 UTC, GildedHonour commented
It's unclear wheather or not there's the plural form for Ethereum. I suppose not.

2018-02-02 06:41 UTC, GildedHonour commented
Finished yesterday. Now I'm testing it.

2018-02-02 07:23 UTC, Vivek-Patil commented
@GildedHonour Is this the full code? i cant see the address generation code here and all the rpc methods which are added in coinrpc for ethereum, from where are these methods called? 🤔 Am i missing something?

2018-02-02 10:01 UTC, GildedHonour commented
@Vivek-Patil 

> all the rpc methods which are added in coinrpc for ethereum
I've implemeted  the methods from https://github.com/ethereum/wiki/wiki/JSON-RPC  . What methods do you mean? 

If these https://github.com/rubykube/peatio/blob/devel/lib/coin_api.rb ones, I started working on this task before the new methods were added to coin_api.rb

> the address generation code
Can you elaborate?

2018-02-02 11:01 UTC, yivo commented
@GildedHonour Will it be possible for you to start rebasing ETH branch to devel branch after testing the current implementation?

2018-02-02 16:04 UTC, Vivek-Patil commented
@GildedHonour I got that the methods are implemented from wiki, but how these integrate with the peatio code? Like for example listtransactions method from coins.rb is called to get transactions. How is this used in eth ?

2018-02-02 16:17 UTC, Vivek-Patil commented
@GildedHonour I currently have the master peatio rubykube branch pulled on my local and i am able to run the whole code and use btc, xrp deposits and withdrawals.Am i missing something? Am i having the old code?

2018-02-02 17:06 UTC, yivo commented
@Vivek-Patil The latest code lives in devel branch.

2018-02-03 10:51 UTC, GildedHonour commented
@Vivek-Patil I don't know -- different coins have different set of PRC procuderues or some procedures doing the same thing but named differently. Therefore there still will be some distinctions in the APIs, even if we agree on some common interface or set of methods that exist in all the coins.

2018-02-06 10:36 UTC, yivo commented
@GildedHonour Have you started moving to devel branch?

2018-02-06 11:21 UTC, GildedHonour commented
@yivo not yet, I plan to do that today.

2018-02-06 19:05 UTC, GildedHonour commented
@yivo 
1) I've tested Ethereum RPC client using the npm utility "ethereumjs-testrpc" as a testnet. Some of the methods aren't implemented in it but the main ones are. Therefore, in a nushell, the client works. The futher testing will be needed.

2) I've squashed all the commits into a single one and rebased issue_334:

     git rebase devel

and commited it. There're the conflicts here. I have the branch "devel" locally but no conflicts. How can I properly pull the conflicts or the current version from here so that I can resolve them and commit?

2018-02-06 19:06 UTC, GildedHonour commented
And I'm ready to take a new task.

2018-02-07 16:39 UTC, yivo commented
@GildedHonour Can you please rebase to deven, fix conflicts and then pick https://github.com/rubykube/peatio/pull/437? @mkuvshynnikov pinged you.

2018-02-07 19:13 UTC, GildedHonour commented
@yivo 
Ok, merging.
 #437 -- it's not been merged into "devel" yet, how can I pick the commits from it?

2018-02-08 06:42 UTC, GildedHonour commented
@yivo lib/coin_rpc.rb was added, then deleted. It's used by, for instance, lib/coin_rpc/eth.rb and bch.rb
Do we need it?

2018-02-08 09:24 UTC, GildedHonour commented
3. And also I'll rebase #348 into this PR as Nick asked me

2018-02-08 10:05 UTC, yivo commented
@GildedHonour 

1. #348 is not correct PR, https://github.com/rubykube/peatio/pull/437 is
2. We refactored CoinRPC and renamed it to CoinAPI by adding single API interface for all currencies. You should check CoinAPI::Base, other implementations and create your one for ETH & ERC20 (you can grab some good code from #437, and you should grab specs from it).
3. Please, please rebase very carefully to DEVEL branch. We have added many changes.
4. Use test.bitgo.com for testing currencies since it is easy way.
5. We need to assign «gold master» to the status of this PR tomorrow, I will review it and we will merge it on weekends.

2018-02-08 21:14 UTC, GildedHonour commented
@yivo 
4. How should they be tested?

Also - test.bitgo.com  requires google authenticator to login and there's no way to skip this.

2018-02-08 23:46 UTC, yivo commented
@GildedHonour 
4. Check that PR. It can be easily tested via stubbing HTTP requests.

BitGo: You can create tokens to be used by applications. There is paragraph in the docs.

2018-02-10 01:27 UTC, GildedHonour commented
@yivo

All has been rebased and merged, removed the old stuff from server.en.yml  

One issue: the login button has disappeared for some reason

![screenshot_2018-02-10_09-23-07](https://user-images.githubusercontent.com/2032888/36057027-93ca3620-0e44-11e8-91ea-91af738d35b5.png)

2018-02-10 06:49 UTC, GildedHonour commented
![screenshot_2018-02-10_14-45-08](https://user-images.githubusercontent.com/2032888/36059332-8922d9ca-0e71-11e8-97a4-9a7b5fc6f64a.png)

2018-02-10 09:39 UTC, GildedHonour commented
and ws too:

![screenshot_2018-02-10_17-38-42](https://user-images.githubusercontent.com/2032888/36060687-51a7526a-0e89-11e8-8ccd-0f1dc8a47680.png)

2018-02-12 10:58 UTC, yivo requested changes

2018-02-12 10:58 UTC, yivo commented on app/controllers/admin/deposits/ethereum_controller.rb
> +    class EthereumController < ::Admin::Deposits::BaseController
@GildedHonour Controller is outdated.

2018-02-12 10:58 UTC, yivo commented on app/controllers/admin/withdraws/ethereum_controller.rb
> +    class EthereumController < ::Admin::Withdraws::BaseController
@GildedHonour Outdated code.

2018-02-12 10:58 UTC, yivo commented on app/models/concerns/withdraws/coinable.rb
> -
@GildedHonour Rollback changes pls.

2018-02-12 10:58 UTC, yivo commented on app/views/admin/deposits/ethereum/index.html.erb
> +<%= table_for @ethereum, class: 'table table-condensed table-hover' do |t| %>
@GildedHonour Outdated.

2018-02-12 10:58 UTC, yivo commented on app/views/admin/withdraws/ethereum/_table.html.erb
> +<%= table_for ethereum, class: 'table table-condensed table-hover', model: Withdraws::Ethereum do |t| %>
@GildedHonour Outdated.

2018-02-12 10:58 UTC, yivo commented on app/views/admin/withdraws/ethereum/index.html.erb
> +<% unless @one_ethereum.empty? %>
@GildedHonour Outdated.

2018-02-12 10:58 UTC, yivo commented on app/views/admin/withdraws/ethereum/show.html.erb
> +<div class="row">
@GildedHonour Outdated.

2018-02-12 10:58 UTC, yivo commented on app/views/private/assets/_eth_assets.html.erb
> +<div class="panel panel-default">
@GildedHonour We removed this code.

2018-02-12 10:58 UTC, yivo commented on app/views/private/withdraws/ethereum/edit.html.erb
> +<% defaults = {as: :display, required: false, hint: false} %>
@GildedHonour We removed this code.

2018-02-12 10:58 UTC, yivo commented on app/views/private/withdraws/ethereum/new.html.erb
> +<%= simple_form_for @withdraw, as: :withdraw, scope: :ethereum do |f| %>
@GildedHonour Still outdated.

2018-02-12 10:58 UTC, yivo commented on config/locales/client.en.yml
> +
@GildedHonour What this is doing here?

2018-02-12 10:58 UTC, yivo commented on lib/coin_rpc.rb
> +module CoinRPC
@GildedHonour Why do you have both CoinAPI & CoinRPC?

2018-02-12 10:58 UTC, yivo commented on lib/coin_rpc/bch.rb
> +module CoinRPC
@GildedHonour Outdated.

2018-02-12 10:58 UTC, yivo commented on lib/coin_rpc/eth.rb
> +class CoinRPC::ETH < CoinRPC::BaseRPC
@GildedHonour Outdated.

2018-02-12 10:58 UTC, yivo commented on lib/coin_rpc/eth.rb
> +  def get_block_by_number(block_num_data, ret_val_as_objs)
@GildedHonour Don't use `get_` convention in Ruby.

2018-02-12 10:58 UTC, yivo commented on lib/coin_rpc/eth.rb
> +  def get_transaction_by_block_number_and_index(block_num_data, idx)
@GildedHonour Why do you have so many methods implemented?

2018-02-12 10:58 UTC, yivo commented on lib/coin_rpc/eth.rb
> +  def net_version
@GildedHonour Why this ie needed in Peatio.

2018-02-12 10:58 UTC, yivo commented on lib/coin_rpc/eth.rb
> +    http = Net::HTTP.new(@uri.host, @uri.port)
@GildedHonour Use Faraday.

2018-02-12 10:58 UTC, yivo commented on lib/generators/config/templates/currencies.yml.erb
> +  assets:
@GildedHonour Not needed.

2018-02-12 10:58 UTC, yivo commented on lib/generators/config/templates/currencies.yml.erb
> -  blockchain:         https://bithomp.com/explorer/#{txid}
@GildedHonour Why this is removed?

2018-02-12 10:58 UTC, yivo commented on lib/generators/config/templates/currencies.yml.erb
> +- id: 7
@GildedHonour Outdated configuration.

2018-02-12 10:58 UTC, yivo commented on lib/generators/config/templates/currencies.yml.erb
> +  symbol: "Ξ"
@GildedHonour Use single quotes.

2018-02-12 10:58 UTC, yivo commented on lib/generators/config/templates/currencies.yml.erb
> +- id: 8
@GildedHonour Outdated configuration.

2018-02-12 10:58 UTC, yivo commented on lib/generators/config/templates/markets.yml.erb
> +  # todo: add also: eth/ltc, eth/dash, etc...
@GildedHonour Agreed.

2018-02-12 10:58 UTC, yivo commented on spec/fixtures/currencies.yml
> +- id: 7
@GildedHonour Outdated configs.

2018-02-12 10:59 UTC, yivo commented
@GildedHonour Please recheck https://github.com/rubykube/peatio/pull/381#issuecomment-364062755

2018-02-12 11:42 UTC, GildedHonour commented on lib/coin_rpc/eth.rb
> +  def get_block_by_number(block_num_data, ret_val_as_objs)
1) What convention is that - not using "get_" ?

2) These methods mimic the names of the methods of Eth RPC and thus named accordingly, with camel_case.

2018-02-12 11:43 UTC, GildedHonour commented on lib/coin_rpc/eth.rb
> +  def get_transaction_by_block_number_and_index(block_num_data, idx)
These are the methods that exist in Eth RPC.

2018-02-13 05:09 UTC, GildedHonour commented on lib/generators/config/templates/currencies.yml.erb
> +  assets:
where do the values of blockchain and address_url come from?

2018-02-13 11:28 UTC, yivo commented
@GildedHonour Login works well. Check your configs.

2018-02-13 16:48 UTC, yivo requested changes

2018-02-13 16:48 UTC, yivo commented on lib/generators/config/templates/markets.yml.erb
> +  # todo: add also: eth/ltc, eth/dash, etc...
@GildedHonour Any progress?

2018-02-13 16:48 UTC, yivo commented on lib/coin_api/eth.rb
> +    def create_address!(password)
@GildedHonour It should not take argument. You can generate some random password and return { address: '12345', secret: password }.

2018-02-13 16:48 UTC, yivo commented on lib/generators/config/templates/currencies.yml.erb
> +
@GildedHonour please update the configs according to new format (with docs etc).

`blockchain` is used for exploring transaction details
`address_url` – for exploring address in blockchain
you can google some

2018-02-13 16:48 UTC, yivo commented on spec/fixtures/currencies.yml
> +  hot_wallet_address: '0x89Af4bF02126b56fc2c24BC324154fF3628Bd946'
@GildedHonour pls document what are these two in currencies.yml.erb

2018-02-13 17:38 UTC, GildedHonour commented on lib/generators/config/templates/currencies.yml.erb
> +
`ethereum blockchain` and `ethereum blockchain url` returns nothing usefull. Neither `erc20` does. Please elaborate.

2018-02-13 17:52 UTC, GildedHonour commented on spec/fixtures/currencies.yml
> +  hot_wallet_address: '0x89Af4bF02126b56fc2c24BC324154fF3628Bd946'
token_address and hot_wallet_address don't exist in currencies.yml.erb

However, this in particular was added by Vadim Sh. Should I remove   token_address and hot_wallet_address?

2018-02-13 17:55 UTC, GildedHonour commented on lib/coin_api/eth.rb
> +    def create_address!(password)
Where does the value  '12345' of address come from?

2018-02-13 19:11 UTC, yivo commented on spec/fixtures/currencies.yml
> +  hot_wallet_address: '0x89Af4bF02126b56fc2c24BC324154fF3628Bd946'
@GildedHonour I don't know what the are used for. I am not ETH expert. Can you check it?

2018-02-13 19:13 UTC, yivo commented on lib/coin_api/eth.rb
> +    def create_address!(password)
@GildedHonour You can generate password by yourself and return it's value assigned to `secret` while `address` is the address ETH should generate for you according to secret.

Example return value: `{address: 'rnYtF9YjLV2dbqQS4JFN9YRSxPQEWbMGWC', secret: 'LuohKDoZEq9u4Ysy7V5uHhrSmG5KspTE'}` for XRP.

2018-02-14 06:34 UTC, GildedHonour commented on lib/coin_api/eth.rb
> +    def create_address!(password)
@yivo 
The client calls `CoinAPI::ETH.new.create_address!(...)` and expects to get `address` and perhaps password and secret. What do you mean "generate by myself"? Is address a completely random value or length N? How's `secret` generated? Are there examples?

2018-02-14 06:38 UTC, GildedHonour commented on spec/fixtures/currencies.yml
> +  hot_wallet_address: '0x89Af4bF02126b56fc2c24BC324154fF3628Bd946'
@vshatravenko -- Are token_address and hot_wallet_address needed given that they aren't used in currencies.yml.erb? Can they be deleted?

2018-02-14 16:44 UTC, yivo commented on spec/fixtures/currencies.yml
> +  hot_wallet_address: '0x89Af4bF02126b56fc2c24BC324154fF3628Bd946'
@GildedHonour Again: I am not ETH expert. I don't know. Peatio should work 100% after your PR (deposit / withdraw / trading). If these configs are required you can keep them, if not – you can delete, or modify. But write docs for them.

2018-02-14 16:45 UTC, yivo commented on lib/coin_api/eth.rb
> +    def create_address!(password)
@GildedHonour You can generate some secret using ruby.

2018-02-15 04:52 UTC, GildedHonour commented on spec/fixtures/currencies.yml
> +  hot_wallet_address: '0x89Af4bF02126b56fc2c24BC324154fF3628Bd946'
@yivo my question was addressed to @vshatravenko  I didn't add those keys. They're used anywhere, it seems, but vshatravenko might've had an intention for adding them -- I don't know.

2018-02-15 05:06 UTC, GildedHonour commented on lib/coin_api/eth.rb
> +    def create_address!(password)
@yivo I didn't create `lib/coin_api/eth.rb`. I created another Eth class which already has been deleted because of the merge. 

And my questions aren't about the concrete implemention but rather interface of the class `lib/coin_api/eth.rb `. Why isn't `password` needed, for instance? Whom can I discuss that with?

2018-02-15 10:10 UTC, yivo commented on lib/coin_api/eth.rb
> +    def create_address!(password)
@GildedHonour Because API is designed so. It doesn't accept argument.

2018-02-19 11:39 UTC, GildedHonour commented on lib/coin_api/eth.rb
> +    def create_address!(password)
I'll fix this today.

2018-02-19 18:20 UTC, GildedHonour commented
@yivo I've made the requested changes.  Since the base has been changed from devel to master by @mod which will require some time to merge,  should I merge the changes with master or switch back to devel?

2018-02-21 10:03 UTC, closed without merging

2018-10-20 19:01 UTC, rraallvv commented
It seems branch `1-8-stable` has support for ETH, although I can't find any information on how to add the function to be notified of received transactions, just like Bitcoin's -walletnotify.
Could someone tell me if that function is documented somewhere.

2018-10-20 19:13 UTC, GildedHonour commented
Some idiots managing the development process on the top couldn't even remember what they were saying and what I was saying after a few days have gone, when I was working on this. Let alone doing programming -- too difficult.