POST /api/v2/withdraws
openware/peatio pull request #410
Opened 2018-01-30 15:36 UTC by yssavchuk

2018-01-30 16:04 UTC, ysv commented on app/api/api_v2/withdraws.rb
> +        currency = Currency.find_by!(code: [params[:currency].upcase, params[:currency].downcase])
@yivo what about this exception processing ?

2018-01-30 17:05 UTC, yivo requested changes

2018-01-30 17:05 UTC, yivo commented on app/api/api_v2/withdraws.rb
> +        currency = Currency.find_by!(code: [params[:currency].upcase, params[:currency].downcase])
@yssavchuk I believe this is bad design because you now handle all kind of exceptions with single `status 422`. 422 is used for exceptional situations but not for every fail. Also Rails maps several exceptions in ActionPack to appropriate status codes like ActiveRecord::RecordNotFound – 404. So, let's remove the rescue. Remember good pattern for handling exceptions – ActiveSupport::Rescuable (rescue_from).

2018-01-30 17:05 UTC, yivo commented on app/api/api_v2/withdraws.rb
> +        currency = Currency.find_by!(code: [params[:currency].upcase, params[:currency].downcase])
@yssavchuk Can you please change `[params[:currency].upcase, params[:currency].downcase]` to single `params[:currency].downcase`, fix grammar error in `bot` and describe params:
```
currencies = Currency.all.map(&:code).map(&:upcase)
       required :currency, type: String,  values: currencies + currencies.map(&:downcase), desc: "Any supported currency: #{currencies.join(',')}."
```
`amount – Withdraw amount without fees.`
`address_id – Stored withdraw address ID. You should create withdraw address before.`

Can you also fix grammar error in `currencies` at https://github.com/rubykube/peatio/pull/410/files#diff-e1379e2b5aebd4bd90d7ef6bc4988da5L27 ?

2018-01-31 11:53 UTC, yivo approved these changes

2018-01-31 22:20 UTC, mod approved these changes

2018-01-31 22:20 UTC, merged