[WIP][FIX #121] Migrate markets.yaml to DB.
openware/peatio pull request #412
Opened 2018-01-30 19:23 UTC by k1T4eR

2018-02-06 10:37 UTC, yivo commented
@k1T4eR we need to finish it till Sunday.

2018-02-06 10:38 UTC, k1T4eR commented
@yivo ok, I'll do my best.

2018-02-07 11:59 UTC, yivo commented
@k1T4eR Please rebase.

2018-02-07 13:26 UTC, yivo requested changes

2018-02-07 13:26 UTC, yivo commented on app/api/api_v2/named_params.rb
> +      requires :market, type: String, values: -> {
@k1T4eR Please format and optimize the query. I don't understand well what's going up here.

2018-02-07 13:26 UTC, yivo commented on app/controllers/application_controller.rb
> +    @current_market ||= Market.find_by(id: params[:market]) || Market.find_by(id: cookies[:market_id]) || Market.first
@k1T4eR We should not touch old behavior. Can you still support param `btcusd`?

2018-02-07 13:26 UTC, yivo commented on app/controllers/private/markets_controller.rb
> +      @market_groups = @markets.map(&:ask_unit).uniq.map(&:downcase)
@k1T4eR Can you double check if this is correct?

2018-02-07 13:26 UTC, yivo commented on app/models/market.rb
> +  # self.singleton_class.send :alias_method, :all
@k1T4eR Can you please drop comments?

2018-02-07 13:26 UTC, yivo commented on app/models/market.rb
> +  def base_unit
@k1T4eR Is this used for compatibility? If so mark it as deprecated. Example: http://docs.phpdoc.org/references/phpdoc/tags/deprecated.html

2018-02-07 13:26 UTC, yivo commented on app/models/market.rb
> +  def quote_unit
@k1T4eR Pls do the same as for #base_unit.

2018-02-07 13:26 UTC, yivo commented on app/models/market.rb
> +  def bid
@k1T4eR Same here.

2018-02-07 13:26 UTC, yivo commented on app/models/market.rb
> +  def ask
@k1T4eR Same here.

2018-02-07 13:26 UTC, yivo commented on app/models/market.rb
> +  def visible?
@k1T4eR Can you add it to DB? It should be not null and be true by default.

2018-02-07 13:26 UTC, yivo commented on app/models/market.rb
>    def self.to_hash
@k1T4eR Can you please use memoist for this method?

2018-02-07 13:26 UTC, yivo commented on app/models/market.rb
> +  def name
@k1T4eR Can you please alias the method to `to_s`?

2018-02-07 13:26 UTC, yivo commented on app/models/market.rb
>    def latest_price
@k1T4eR Can you please check migration for ID? I mean `btcusd` => `1`.

2018-02-07 13:26 UTC, yivo commented on app/models/market.rb
> +  def self.by_name(name)
@k1T4eR I think this should be `find_by_commodity_pair` or something else?

2018-02-07 13:26 UTC, yivo commented on app/models/market.rb
> +  def self.by_name(name)
Can you also reformat SQL query to use UPPERCASE keywords?

2018-02-07 13:26 UTC, yivo commented on app/models/market.rb
>      @global || Global[self.id]
@k1T4eR Can you also check migration for `btcusd` => `1`?

2018-02-07 13:26 UTC, yivo commented on app/models/market.rb
> +class Market < ActiveRecord::Base
@k1T4eR Can you please write ActiveRecord validations for all attributes?

2018-02-07 17:43 UTC, k1T4eR commented on app/controllers/private/markets_controller.rb
> +      @market_groups = @markets.map(&:ask_unit).uniq.map(&:downcase)
@yivo Rechecked. Yes, it's ok.

2018-02-07 17:59 UTC, k1T4eR commented on app/models/market.rb
> +class Market < ActiveRecord::Base
@yivo ok, I'll add validations with next update.

2018-02-07 18:03 UTC, k1T4eR commented on app/models/market.rb
> +  def base_unit
@yivo ok

2018-02-07 18:03 UTC, k1T4eR commented on app/models/market.rb
> +  # self.singleton_class.send :alias_method, :all
@yivo ok

2018-02-07 18:03 UTC, k1T4eR commented on app/models/market.rb
> +  def quote_unit
@yivo ok

2018-02-07 18:04 UTC, k1T4eR commented on app/models/market.rb
> +  def bid
@yivo ok

2018-02-07 18:04 UTC, k1T4eR commented on app/models/market.rb
> +  def ask
@yivo ok

2018-03-07 17:58 UTC, mod commented
@yivo is this something we will be able to achieve in this sprint?

2018-03-23 09:43 UTC, yivo commented
@k1T4eR you will need to move all the changes for the files above into peatio-trading-ui repo:

![image](https://user-images.githubusercontent.com/7421323/37822246-9b4bfb62-2e8e-11e8-8a4d-f19e367ecca5.png)

![github com_rubykube_peatio_pull_412_files 1](https://user-images.githubusercontent.com/7421323/37822255-9fb54906-2e8e-11e8-9ea7-a0a2ebe9a594.png)

I have rebased PR and deleted these files.

2018-03-25 12:17 UTC, yivo requested changes

2018-03-25 12:17 UTC, yivo commented on lib/tasks/markets.rake
> +      coin_currencies = Currency.where(type: 'coin').map(&:code)
@k1T4eR Use symbols for these type of things: `:coin`.

Use `pluck` for accumulating the code.

2018-03-25 12:17 UTC, yivo commented on lib/tasks/markets.rake
> +  task seed: :environment do
@k1T4eR Instead of having this task we need to have config/templates/seed/markets.yml.erb for all markets defined. This task must load markets from the file and seed DB.

2018-03-25 12:17 UTC, yivo commented on lib/tasks/markets.rake
> +  task seed: :environment do
Similar to currencies:seed.

2018-03-25 12:17 UTC, yivo commented on lib/tasks/markets.rake
> +  task seed: :environment do
Also we need to have both `BTC/UAH` & `UAH/BTC`.

2018-03-25 12:17 UTC, yivo commented on app/controllers/private/markets_controller.rb
> +      @market_groups = @markets.map(&:ask_unit).uniq
@k1T4eR Better to use `pluck`.

2018-04-02 17:01 UTC, yivo approved these changes

2018-04-03 08:13 UTC, mod commented
@k1T4eR @yivo Please update README install steps
Does the Dockerfile need any changes?
Also I don't think it's necessary to keep things related to markets.old.yml
But I am curious about the upgrade instructions, can you start the release notes with this patch.

2018-04-03 08:19 UTC, yivo commented
@mod Dockerfile doesn't require any changes. Fresh peatio installation steps haven't been changed. The release notes will include all the migration steps (they are pretty easey by the way.).

2018-04-03 08:20 UTC, merged