WIP Markets page should update list of orders when order is created
openware/peatio pull request #435
Opened 2018-02-02 10:42 UTC by amir-budaychiev

WIP Markets page should update list of orders when order is created

2018-02-05 14:55 UTC, yivo requested changes

2018-02-05 14:55 UTC, yivo commented on Gemfile
> +  gem 'spirit_hands'
@amir-budaychiev Can you please remove this? We use `pry-byebug` instead.

2018-02-05 14:55 UTC, yivo commented on app/controllers/concerns/order_creation.rb
> -      rescue => e
@amir-budaychiev Please change base branch to devel and rebase. We have this problem fixed.

2018-02-05 16:15 UTC, amir-budaychiev commented on Gemfile
> +  gem 'spirit_hands'
@yivo done

2018-02-05 17:43 UTC, amir-budaychiev commented on app/controllers/concerns/order_creation.rb
> -      rescue => e
@yivo Do I need create new PULL REQUEST into rubykube:devel from amir-budaychiev:devel?

2018-02-06 08:13 UTC, amir-budaychiev commented on app/controllers/concerns/order_creation.rb
> -      rescue => e
@yivo I did it for devel branch in the new PR: https://github.com/rubykube/peatio/pull/455. Can we close that issue?

2018-02-06 10:23 UTC, yivo commented on app/controllers/concerns/order_creation.rb
> -      rescue => e
@amir-budaychiev Yes, sure. I will close it.

2018-02-06 10:24 UTC, yivo commented
Moved to #455.

2018-02-06 10:24 UTC, closed without merging