[WIP] implement support for erc20
openware/peatio pull request #437
Opened 2018-02-02 18:30 UTC by vadshalamov

https://github.com/rubykube/peatio/issues/384

2018-02-02 18:56 UTC, mod commented
That's a good start ^^
You missing unit tests though

2018-02-02 19:08 UTC, yivo requested changes

2018-02-02 19:08 UTC, yivo commented on lib/coin_api/eth.rb
> +  class Eth < BaseAPI
@vadshalamov The convention is to use `ETH`.

2018-02-04 10:59 UTC, vadshalamov commented
@mod @yivo  how should I handle if user want to connect several token addresses(contract addresses)? or user will have the opportunity to work with only one contract address and wallet address at one time?

2018-02-04 12:40 UTC, yivo requested changes

2018-02-04 12:40 UTC, yivo commented on lib/coin_api/json_rpc/base_api.rb
> +    class BaseAPI < ::CoinAPI::BaseAPI
@vadshalamov Consider moving this stuff to ETH.

2018-02-04 12:40 UTC, yivo commented on .rubocop.yml
> +AllCops:
@vadshalamov Rubocop is not in scope of this PR.

2018-02-04 12:40 UTC, yivo commented on Gemfile
> +  gem 'webmock'
@vadshalamov Consider locking gem version range.

2018-02-04 12:43 UTC, yivo commented
@vadshalamov We are not very familiar with all ETH stuff. Can you push the simplest implementation you think?

2018-02-06 08:39 UTC, vadshalamov commented
@yivo up

2018-02-07 16:38 UTC, closed without merging