[WIP] Still a problem with the withdraw, here with BTC
openware/peatio pull request #478
Opened 2018-02-07 19:30 UTC by yssavchuk

2018-02-07 19:32 UTC, yssavchuk commented on app/models/worker/withdraw_coin.rb
> +        # TODO: (yssavchuk) implement #coin_api_withdrawal_error where log error and call withdraw.fail
@yivo your suggestions ?

2018-02-07 19:32 UTC, yssavchuk commented on lib/coin_api/bit_go.rb
> +    rescue Faraday::Error => e
@yivo do wee need to define CoinAPI::WithdrawalError or something like this processing this scenario  ?

2018-02-07 20:40 UTC, yivo requested changes

2018-02-07 20:40 UTC, yivo commented on lib/coin_api/bit_go.rb
> +    rescue Faraday::Error => e
@yssavchuk I am sure no. This makes no sense.

2018-02-07 20:40 UTC, yivo commented on app/models/worker/withdraw_coin.rb
> +        # TODO: (yssavchuk) implement #coin_api_withdrawal_error where log error and call withdraw.fail
@yssavchuk I think we can omit all rescues by wrapping whole process in single transaction. So we open transaction only if withdraw.processing?, we process it and if it fails DB will rollback us to `processing` so we will retry it. Just think simple.

2018-02-07 20:40 UTC, yivo commented on app/models/worker/withdraw_coin.rb
>          raise Account::BalanceError, 'Insufficient coins' if balance < withdraw.sum
@yssavchuk Instead of raising error you can set status `suspect` for this case.

2018-02-08 16:03 UTC, yivo approved these changes

2018-02-09 12:08 UTC, merged