[WIP] #279: refactor currencies.yml into ar model
openware/peatio pull request #488
Opened 2018-02-09 09:02 UTC by mitjok

2018-02-09 09:49 UTC, yivo commented
@mitjok Why new PR?

2018-02-09 10:12 UTC, yivo requested changes

2018-02-09 10:12 UTC, yivo commented on app/api/api_v2/services/currencible.rb
> +module APIv2
@mitjok Have you created it because you have issues with loading app I think?

2018-02-09 10:12 UTC, yivo commented on app/api/api_v2/services/currencible.rb
> +module APIv2
You should remove it.

2018-02-09 10:12 UTC, yivo commented on app/api/api_v2/named_params.rb
> +      requires :currency,   type: String, values: ::APIv2::Services::Currencible.codes(bothcase: true), desc: 'Currency code. Both upcase (BTC) and downcase (btc) are supported.'
@mitjok If you will do `values: ~> { Currency.pluck(:code).map(&:upcase) }` it will load codes on demand.

2018-02-09 10:12 UTC, yivo commented on app/api/api_v2/services/currencible.rb
> +module APIv2
Check my comment for app/api/api_v2/named_params.rb.

2018-02-09 10:12 UTC, yivo commented on app/api/api_v2/withdraws.rb
> +      optional :currency, type: String,  values: ::APIv2::Services::Currencible.codes(bothcase: true), desc: "Any supported currencies: #{::APIv2::Services::Currencible.codes(bothcase: true).join(','
@mitjok The same. Can you use lambda here?

2018-02-09 10:12 UTC, yivo commented on app/api/api_v2/withdraws.rb
> +      optional :currency, type: String,  values: ::APIv2::Services::Currencible.codes(bothcase: true), desc: "Any supported currency: #{::APIv2::Services::Currencible.codes(bothcase: true).join(',')}
@mitjok The same. Can you use lambda here?

2018-02-09 10:12 UTC, yivo commented on app/api/api_v2/withdraws.rb
> +      requires :currency,   type: String,  values: ::APIv2::Services::Currencible.codes(bothcase: true), desc: "Any supported currency: #{::APIv2::Services::Currencible.codes(bothcase: true).join(','
@mitjok The same. Can you use lambda here?

2018-02-09 10:12 UTC, yivo commented on app/api/api_v2/services/currencible.rb
> +module APIv2
I think bothcase is cool. Can we embed it into currency model?

2018-02-09 10:12 UTC, yivo commented on app/models/account.rb
> +  scope :enabled, -> { where(currency: Currency.ids) }
@mitjok Since we decided to use code as primary key we can write `where(currency: Currency.pluck(:code))`. It will work since we prefer case insensitive collation.

2018-02-09 10:12 UTC, yivo commented on app/models/concerns/currencible.rb
> +    scope :with_currency, -> (code) { where(currency: Currency.find_by(code: code)) }
@mitjok I think this should use code column too.

2018-02-09 10:12 UTC, yivo commented on app/models/currency.rb
>    def quick_withdraw_max
@mitjok Can we just alias deprecated quick_withdraw_max to new quick_withdraw_limit?

2018-02-09 10:12 UTC, yivo commented on app/models/currency.rb
> +    write_attribute(:code, code.to_s.upcase)
@mitjok You can just use `self[:code] = ...` which is the same.

2018-02-09 10:12 UTC, yivo commented on app/models/member.rb
> +    less = Currency.ids - self.accounts.map(&:currency)
@mitjok I think this also needs changed for ID => code.

2018-02-09 10:12 UTC, yivo commented on db/migrate/20180208084954_add_currencies.rb
> +    create_table :currencies, :force => true do |t|
@mitjok Will we specify ID => :code here?

2018-02-09 10:12 UTC, yivo commented on lib/peatio.rb
> -      Currency.first.code.upcase
@mitjok Can you just return `Currency.order(id: :asc).where(type: :fiat).first || raise ArgumentError, 'Base fiat currency is not specified.'`?

2018-02-09 10:12 UTC, yivo commented on lib/tasks/currencies.rake
> +namespace :currencies do
@mitjok Can you exec this from db:seed and create currencies if they don't exist? I mean if not USD => create USD, if not BTC => create BTC and so on.

2018-02-09 10:12 UTC, yivo commented on lib/tasks/currencies.rake
> +namespace :currencies do
Task should be idempotent.

2018-02-13 11:25 UTC, yivo requested changes
@mitjok Please recheck my previous review since the current implementation is missing a lot.

2018-02-13 11:25 UTC, yivo commented on Gemfile
> +gem 'grape', '~> 1.0.2'
@mitjok Sorry, why this is needed? If grape released new version we can update it in another PR. It is very important for us to keep grape working stable.

2018-02-13 11:25 UTC, yivo commented on app/api/api_v2/deposits.rb
> +      optional :currency, type: String, values: -> { ::APIv2::Services::Currencible.codes(bothcase: true) }, desc: "Currency value contains  #{::APIv2::Services::Currencible.codes(bothcase: true).joi
@mitjok Desc should also be lambda.

2018-02-13 11:25 UTC, yivo commented on app/api/api_v2/deposits.rb
> +      requires :currency, type: String, values: -> { ::APIv2::Services::Currencible.codes(bothcase: true) }, desc: "The account to which you want to deposit. Available values: #{::APIv2::Services::Cu
@mitjok Desc should also be lambda. Use it for all places where currency is used (grape APIs).

2018-02-13 11:25 UTC, yivo commented on app/api/api_v2/entities/withdraw.rb
> +      expose(:currency) { |w| w.currency_obj&.code&.upcase }
@mitjok We should expect currency to be present. Always. No currency === you have broken project. It is OK.

2018-02-13 11:25 UTC, yivo commented on app/api/api_v2/entities/withdraw_address.rb
> +      expose(:currency) { |w| w.currency_obj&.code&.upcase }
@mitjok Same as above. If we will care about it in all places inside project it will become the hell.

2018-02-13 11:25 UTC, yivo commented on app/api/api_v2/named_params.rb
> -    params :withdraw_address do
@mitjok Why it was removed?

2018-02-13 11:25 UTC, yivo commented on app/api/api_v2/services/currencible.rb
> +  module Services
@mitjok Please check my review again for this module.

2018-02-13 11:25 UTC, yivo commented on app/api/api_v2/withdraws.rb
> +      optional :currency, type: String,  values: -> { ::APIv2::Services::Currencible.codes(bothcase: true) }, desc: "Any supported currencies: #{::APIv2::Services::Currencible.codes(bothcase: true).j
@mitjok Desc should be lambda.

2018-02-13 11:25 UTC, yivo commented on app/api/api_v2/withdraws.rb
> +        .tap { |q| q.where!(currency: currency.id) if params[:currency].present? }
@mitjok Why do we use ID here? I thought we use code as primary key for currencies. Isn't it?

2018-02-13 11:25 UTC, yivo commented on app/api/api_v2/withdraws.rb
> +        .tap { |q| q.where!(currency: currency.id) if params[:currency].present? }
@mitjok Instead of storing numerical ID we can store currency code.

2018-02-13 11:25 UTC, yivo commented on app/api/api_v2/withdraws.rb
> +      optional :currency, type: String,  values: -> { ::APIv2::Services::Currencible.codes(bothcase: true) }, desc: "Any supported currency: #{::APIv2::Services::Currencible.codes(bothcase: true).joi
@mitjok Desc needs lambda.

2018-02-13 11:25 UTC, yivo commented on app/api/api_v2/withdraws.rb
> +      requires :currency,   type: String, values: -> { ::APIv2::Services::Currencible.codes(bothcase: true) }, desc: 'Currency code. Both upcase (BTC) and downcase (btc) are supported.'
@mitjok Needs lambda.

2018-02-13 11:27 UTC, yivo commented
@mitjok Please rebase first, check previous review, check latest review. Can we use code as primary key by removing numerical ID at full? I thought we talked about it but your code is not updated.

2018-02-14 10:05 UTC, mitjok commented on app/api/api_v2/services/currencible.rb
> +module APIv2
Why logic related to API should go into Currency model?

2018-02-14 10:05 UTC, mitjok commented on app/models/currency.rb
>    def quick_withdraw_max
sure, thx

2018-02-14 10:17 UTC, mitjok commented on app/models/currency.rb
> +    write_attribute(:code, code.to_s.upcase)
write_attribute handles aliases, etc.. seems to be more safe at that point, but I'll change

2018-02-14 10:22 UTC, subaru9 commented on lib/tasks/currencies.rake
> +namespace :currencies do
I think the task should be isolated from `db:seed` as it will be run in production. db/seed.rb may have other seeding data meant for development/test purposes.

2018-02-14 10:25 UTC, mitjok commented on Gemfile
> +gem 'grape', '~> 1.0.2'
Primary goal was to use procs in values, but right 1.0.1 have support for it too

2018-02-14 10:25 UTC, mitjok commented on app/api/api_v2/deposits.rb
> +      optional :currency, type: String, values: -> { ::APIv2::Services::Currencible.codes(bothcase: true) }, desc: "Currency value contains  #{::APIv2::Services::Currencible.codes(bothcase: true).joi
thx

2018-02-14 10:25 UTC, mitjok commented on app/api/api_v2/deposits.rb
> +      requires :currency, type: String, values: -> { ::APIv2::Services::Currencible.codes(bothcase: true) }, desc: "The account to which you want to deposit. Available values: #{::APIv2::Services::Cu
thx

2018-02-14 10:25 UTC, mitjok commented on app/api/api_v2/entities/withdraw.rb
> +      expose(:currency) { |w| w.currency_obj&.code&.upcase }
thx

2018-02-14 10:26 UTC, mitjok commented on app/api/api_v2/entities/withdraw_address.rb
> +      expose(:currency) { |w| w.currency_obj&.code&.upcase }
thx

2018-02-14 10:26 UTC, mitjok commented on app/api/api_v2/services/currencible.rb
> +  module Services
yeah, not sure api logic should be thrown into model.

2018-02-14 10:27 UTC, mitjok commented on app/api/api_v2/withdraws.rb
> +      requires :currency,   type: String, values: -> { ::APIv2::Services::Currencible.codes(bothcase: true) }, desc: 'Currency code. Both upcase (BTC) and downcase (btc) are supported.'
desc is a string without interpolation

2018-02-14 10:48 UTC, mitjok commented on app/api/api_v2/services/currencible.rb
> +module APIv2
`Currency.codes` already overloaded with some domain logic

2018-02-14 12:24 UTC, mitjok commented on lib/peatio.rb
> -      Currency.first.code.upcase
When running Currency migration this file is loaded before the migration and prevent it from running. 
What is the logic to have first currency as base fiat, this is not error proof, imo.
Why not:
1. Peatio.base_fiat_ccy -> Currency.base_fiat_code(options={}) options could be `downcase`
2. Currency::BASE_FIAT_CODE = :usd

2018-02-14 12:32 UTC, mitjok commented on app/api/api_v2/named_params.rb
> -    params :withdraw_address do
It's used in one place so no need to share it

2018-02-16 16:34 UTC, mitjok commented on lib/peatio.rb
> -      Currency.first.code.upcase
@yivo Pls take a look at `Currency.base_fiat`. The build is failing now even though the tests are pass. As far as I understand the peatio module get lodaded in a container during the time the mysql container isn't ready. My idea: remove`Peatio` module ant use `Currency.base_fiat` everywhere. Second idea: add `currencies.base_fiat` column and not use `Currency.base_fiat` static method. Thus we decouple from logic the first currency is always base fiat. Thoughts?

2018-02-19 13:22 UTC, mitjok commented
@yivo pls review, all checks pass

2018-02-19 14:06 UTC, yivo requested changes

2018-02-19 14:06 UTC, yivo commented on .gitignore
> +/config/configs/currencies.yml
@mitjok Remove pls

2018-02-19 14:06 UTC, yivo commented on app/api/api_v2/entities/market.rb
> +      documentation = "Unique market id. "\
@mitjok Pls open API doc at /documents/api_v2 and fix invalid error message for this. Don't use local vars. Use tap if you need it.

2018-02-19 14:06 UTC, yivo commented on app/api/api_v2/entities/order.rb
> +      expose :price, documentation: "Price for each unit. e.g. If you want to sell/buy 1 btc at 3000 #{ -> { Peatio.base_fiat_ccy } }, the price is '3000.0'"
@mitjok The same as in entities/market.rb

2018-02-19 14:06 UTC, yivo commented on app/api/api_v2/entities/order.rb
> +      expose :currency, as: :market, documentation: "The market in which the order is placed, e.g. 'btc#{ -> { Peatio.base_fiat_ccy.downcase } }'. All available markets can be found at /api/v2/market
@mitjok The same as in entities/market.rb

2018-02-19 14:06 UTC, yivo commented on app/api/api_v2/services/currencible.rb
> +  module Services
@mitjok Pls move this to currency. The all code should look like:
```
def codes(options = {})
  pluck(:codes).map(&:upcase).yield_self do |up_codes|
    options.fetch(:bothcase, false) ? up_codes + up_codes.map(&:downcase) : ( options(:upcase, true) ? up_codes : up_codes.map(&:downcase) )
  end
end
```

2018-02-19 14:06 UTC, yivo commented on app/api/api_v2/services/currencible.rb
> +  module Services
We may use this in places different to API.

2018-02-19 14:06 UTC, yivo commented on app/controllers/application_controller.rb
>          code: currency[:code],
@mitjok Pls change this to use top-level methods in favor of [] method.

2018-02-19 14:06 UTC, yivo commented on app/controllers/application_controller.rb
> +        isCoin: currency.coin?
@mitjok Like here.

2018-02-19 14:06 UTC, yivo commented on app/controllers/private/order_bids_controller.rb
> +
@mitjok Blank line detected.

2018-02-19 14:06 UTC, yivo commented on app/models/currency.rb
> +      return {} unless ActiveRecord::Base.connection.table_exists?('currencies')
@mitjok No need for this.

2018-02-19 14:06 UTC, yivo commented on app/models/currency.rb
> +    def assets(code)
@mitjok Just drop this method and it's usages. Or place a TODO mark: `# TODO: Remove this.`.

2018-02-19 14:06 UTC, yivo commented on app/models/currency.rb
> +    @quick_withdraw_limit ||= BigDecimal.new self[:quick_withdraw_limit].to_s
@mitjok Use super here.

2018-02-19 14:06 UTC, yivo commented on app/models/withdraw.rb
> -
@mitjok Extra line.

2018-02-19 14:06 UTC, yivo commented on app/models/worker/withdraw_coin.rb
> +      Rails.logger.debug { "Failed to process #{Currency.find(withdraw.currency).code} withdraw with ID #{withdraw.id}: #{e.inspect}." }
@mitjok Use `withdraw.currency_obj` here.

2018-02-19 14:06 UTC, yivo commented on app/views/private/markets/_account_summary.html.erb
> +                         "yarn_components/currency-flags/src/flags/#{account.currency_obj&.code&.downcase}.png" %>
@mitjok No, please don't try try catch and try again. We expect currency to be ALWAYS available.

2018-02-19 14:06 UTC, yivo commented on app/views/private/markets/_account_summary.html.erb
> +              <div><%= account.currency_obj&.code&.upcase %></div>
@mitjok The same as above.

2018-02-19 14:06 UTC, yivo commented on db/migrate/20180215144646_add_currencies.rb
> +      t.string  :hot_wallet_address,       limit: 200, null: false #remove
@mitjok Pls remove this field.

2018-02-19 14:06 UTC, yivo commented on db/migrate/20180215144646_add_currencies.rb
> +    create_table :currencies, :force => true do |t|
@mitjok Better to keep force: false (just remove, it is default).

2018-02-19 14:06 UTC, yivo commented on db/migrate/20180215144646_add_currencies.rb
> +      t.string  :api_client
@mitjok Pls mark as not null.

2018-02-19 14:06 UTC, yivo commented on lib/peatio.rb
> + module Peatio
@mitjok Extra space detected.

2018-02-19 14:06 UTC, yivo commented on lib/peatio.rb
> +      return '' unless ActiveRecord::Base.connection.table_exists?('currencies')
@mitjok Remove it. Code should be EXACTLY `Currency.order(id: :asc).where(type: :fiat).first || raise ArgumentError, 'Base fiat currency is not specified.'`.

2018-02-19 14:06 UTC, yivo commented on lib/tasks/currencies.rake
> +namespace :currencies do
@mitjok I talked to Louis. We need to take existing currencies.yml, move it to config/seed/currencies.yml, update naming (we renamed some columns) and fetch data from this file in db/seed.rb or exec rake task from db/seed.rb. Pls do so.

2018-02-19 14:06 UTC, yivo commented on spec/api/api_v2/deposits_spec.rb
> +      pending 'Need to find out wjy there\'re no currencies present at the beginning of the test'
@mitjok Is this finished?

2018-02-19 14:06 UTC, yivo commented on spec/api/api_v2/withdraws_spec.rb
> +  before do
@mitjok No need for it. Use real database and factory_bot.

2018-02-19 14:06 UTC, yivo commented on spec/factories/fund_source.rb
> +    currency { Currency.exists?(code: :btc) ? Currency.find_by(code: :btc).id : create(:currency_btc).id }
@mitjok Pls change to `Currency.find_by!(code: :btc).id`. Currencies MUST BE before specs run. Please change this in all other places. I found many.

2018-02-19 15:06 UTC, mitjok commented on lib/peatio.rb
> +      return '' unless ActiveRecord::Base.connection.table_exists?('currencies')
https://www.evernote.com/l/AYOgw_BrjylBWb0IxqfsKKhxprIb8nCb64AB/image.png

2018-02-19 15:24 UTC, yivo commented on lib/peatio.rb
> +      return '' unless ActiveRecord::Base.connection.table_exists?('currencies')
@mitjok Yes, return code.

`Currency.order(id: :asc).where(type: :fiat).first.code || raise ArgumentError, 'Base fiat currency is not specified.'`

2018-02-20 13:24 UTC, mitjok commented on spec/factories/fund_source.rb
> +    currency { Currency.exists?(code: :btc) ? Currency.find_by(code: :btc).id : create(:currency_btc).id }
fixed

2018-02-21 06:28 UTC, mitjok commented on app/controllers/private/order_bids_controller.rb
> +
fixed )

2018-02-21 06:32 UTC, mitjok commented on app/models/worker/withdraw_coin.rb
> +      Rails.logger.debug { "Failed to process #{Currency.find(withdraw.currency).code} withdraw with ID #{withdraw.id}: #{e.inspect}." }
fixed

2018-02-21 06:32 UTC, mitjok commented on app/models/withdraw.rb
> -
fixed

2018-02-21 06:33 UTC, mitjok commented on app/views/private/markets/_account_summary.html.erb
> +              <div><%= account.currency_obj&.code&.upcase %></div>
fixed

2018-02-21 06:33 UTC, mitjok commented on app/views/private/markets/_account_summary.html.erb
> +                         "yarn_components/currency-flags/src/flags/#{account.currency_obj&.code&.downcase}.png" %>
fixed

2018-02-21 06:33 UTC, mitjok commented on db/migrate/20180215144646_add_currencies.rb
> +    create_table :currencies, :force => true do |t|
done

2018-02-21 06:35 UTC, mitjok commented on db/migrate/20180215144646_add_currencies.rb
> +      t.string  :hot_wallet_address,       limit: 200, null: false #remove
done

2018-02-21 06:36 UTC, mitjok commented on db/migrate/20180215144646_add_currencies.rb
> +      t.string  :api_client
does base fiat has such field?

2018-02-21 08:19 UTC, yivo commented on db/migrate/20180215144646_add_currencies.rb
> +      t.string  :api_client
@mitjok No. Leave it in table, we will refactor later.

2018-02-21 22:24 UTC, mitjok commented on db/migrate/20180215144646_add_currencies.rb
> +      t.string  :api_client
@yivo sorry, "Leave it in table, we will refactor later." means add no null to api_client field or leave as is without not null?

2018-02-21 22:27 UTC, mitjok commented on lib/tasks/currencies.rake
> +namespace :currencies do
@yivo now rake task `currencies:seed` invoked from `db/seeds.rb`

2018-02-26 10:50 UTC, yivo commented on lib/peatio.rb
> -      Currency.first.code.upcase
@mitjok Pls do like I described.

2018-03-01 15:40 UTC, yivo approved these changes

2018-03-06 15:18 UTC, merged

2018-03-13 03:56 UTC, sramsden commented on app/models/currency.rb
>    end
☝️ why is this initiating from `super.to_s` when attribute is empty?  If I'm not wrong `BigDecimal.new(super.to_s)` will result in `ArgumentError (invalid value for BigDecimal(): "")` when that attribute it empty.

2018-03-13 04:04 UTC, sramsden commented on app/models/currency.rb
>    end
Okay, so I can see this ..
`validates :quick_withdraw_limit, numericality: { greater_than_or_equal_to: 0 }`
.. which prevents it from being empty (or zero) in the database anyhow. 
So, what is the purpose of this method?