Revert "Create admin rubric which allows to manually deposit USD" (#483)
openware/peatio pull request #504
Opened 2018-02-12 13:19 UTC by Liapin

2018-02-12 16:24 UTC, yivo requested changes

2018-02-12 16:24 UTC, yivo commented on app/models/currency.rb
>    field :visible, default: true
@Liapin Pls revert the changes to be up to date with devel.

2018-02-12 16:24 UTC, yivo commented on app/models/currency.rb
>    field :visible, default: true
For this file.

2018-02-12 16:38 UTC, Liapin commented
@yivo done

2018-02-12 16:56 UTC, yivo approved these changes

2018-02-13 13:40 UTC, mod commented
@yivo why reverting instead of creating a new withdraw?
I still think we need the admin section.

2018-02-13 14:56 UTC, yivo commented
@mod We need to revert it since it is not needed anymore. It doesn't relate to withdraw. It related to fiat deposit.

2018-02-13 20:18 UTC, mod commented
@yivo we still need the ability just we need to create a Deposits.new instead of updating the balance, but as admin, I should be able to create a deposit for a customer.

2018-02-13 21:36 UTC, yivo commented
@mod That's why we have #506 & #507 for it. The feature this PR contains is not needed anymore.

2018-02-14 12:44 UTC, merged