Refactor fiat deposits to match new behavior
openware/peatio pull request #509
Opened 2018-02-13 14:32 UTC by yssavchuk

2018-02-13 18:34 UTC, yssavchuk commented
@yivo how we can process exceptions for example invalid currency code etc

2018-02-13 19:14 UTC, yivo commented
@yssavchuk everything should be validates using activemodel validators.

2018-02-13 19:15 UTC, yivo commented
I think this is not in the scope for this PR.

2018-02-13 19:19 UTC, yssavchuk commented
@yivo review please

2018-02-13 19:29 UTC, yivo requested changes

2018-02-13 19:29 UTC, yivo commented on app/models/currency.rb
> +    def fiats
@yssavchuk pls refactor this to scope.

2018-02-13 19:29 UTC, yivo commented on app/views/admin/deposits/banks/new.html.erb
> +              <!--TODO: Currency.fiats.map(&:code)-->
@yssavchuk Not ready?

2018-02-13 19:29 UTC, yivo commented on app/views/admin/deposits/banks/new.html.erb
> +              <dd><%= f.collection_radio_buttons :currency, [['USD'],['EUR'],['UAH']], :first, :last %></dd>
@yssavchuk TODO

2018-02-13 19:29 UTC, yivo commented on app/views/admin/deposits/banks/new.html.erb
> +              <%= f.submit 'Accept', class: 'btn btn-primary pull-right'%>
@yssavchuk Can you add space before `%>`?

2018-02-13 19:29 UTC, yivo commented on app/views/admin/deposits/banks/new.html.erb
> +          <span><%= 'User info' %></span>
@yssavchuk Why ERB is needed here?

2018-02-13 19:29 UTC, yivo commented on app/views/admin/deposits/banks/new.html.erb
> +                <dt><%= 'SN' %></dt>
@yssavchuk Why ERB is needed here?

2018-02-13 19:29 UTC, yivo commented on app/views/admin/deposits/banks/new.html.erb
> +              <dt><%= 'Currency' %></dt>
@yssavchuk Why ERB is needed here?

2018-02-13 19:29 UTC, yivo commented on app/views/admin/deposits/banks/new.html.erb
> +              <dt><%= 'Amount' %></dt>
@yssavchuk Why ERB is needed here?

2018-02-13 19:29 UTC, yivo commented on app/views/admin/deposits/banks/new.html.erb
> +              <dt><%= 'Account' %></dt>
@yssavchuk Why ERB is needed here?

2018-02-13 19:29 UTC, yivo commented on app/views/admin/deposits/banks/new.html.erb
> +              <dt><%= 'Bank' %></dt>
@yssavchuk Why ERB is needed here?

2018-02-13 19:29 UTC, yivo commented on app/views/admin/deposits/banks/new.html.erb
> +          <span><%= 'Deposit info' %></span>
@yssavchuk Why ERB is needed here?

2018-02-13 19:29 UTC, yivo commented on app/models/concerns/fund_sourceable.rb
> +    if fund_extra.nil? && fund_uid.nil? && fund_source = FundSource.find_by(id: fund_source_id)
@yssavchuk Can you explain what fund_extra, fund_uid are?

2018-02-13 19:29 UTC, yivo commented on app/models/concerns/fund_sourceable.rb
> +    validates :fund_extra, :fund_uid, presence: true, on: :create
@yssavchuk Can you explain the changes?

2018-02-13 19:29 UTC, yivo commented on app/controllers/admin/deposits/banks_controller.rb
> +        ::Deposits::Bank.create!(deposit_params)
@yssavchuk Can you display errors? Something like: `if deposit.save then redirect else display errors`.

2018-02-13 19:29 UTC, yivo commented on app/controllers/admin/deposits/banks_controller.rb
> +        ::Deposits::Bank.create!(deposit_params)
Typical for Rails.

2018-02-13 19:29 UTC, yivo commented on app/controllers/admin/deposits/banks_controller.rb
> +      def fetch_member!
@yssavchuk I don't like this behavior. Let's create `def sn=(new_sn)` at bank deposit model. Insite the method we can look up member by SN and `self.member = member`. There should be validation on deposit for presence of member so if no member is available deposit will notify about error and could not be saved. Also try to omit modifying params.

2018-02-13 19:29 UTC, yivo commented on app/controllers/admin/deposits/banks_controller.rb
> +        redirect_to admin_deposits_banks_path
@yssavchuk Can we use redirect_to :back?

2018-02-13 19:29 UTC, yivo commented
@yssavchuk done

2018-02-14 12:46 UTC, yssavchuk commented on app/models/concerns/fund_sourceable.rb
> +    validates :fund_extra, :fund_uid, presence: true, on: :create
@yivo actually we don't need fund_source (which represents bank account) to create bank deposit all we need  is fund_extra(bank account) & fund_uid(user account in bank)

2018-02-14 12:46 UTC, yssavchuk commented on app/models/concerns/fund_sourceable.rb
> +    if fund_extra.nil? && fund_uid.nil? && fund_source = FundSource.find_by(id: fund_source_id)
fund_extra - sender bank name
& fund_uid - user account in bank

2018-02-14 12:48 UTC, yssavchuk commented on app/models/currency.rb
> +    def fiats
@yivo we cant because ActiveYmlBase doesn't provide such method

2018-02-14 14:04 UTC, yivo approved these changes

2018-02-15 11:58 UTC, merged