[WIP ] #490 Add support for PostgreSQL
openware/peatio pull request #572
Opened 2018-02-21 21:24 UTC by mitjok

2018-02-27 15:50 UTC, yivo requested changes

2018-02-27 15:50 UTC, yivo commented on Gemfile
> +gem 'pg', '~> 0.21'
@mitjok The task is not to replace MySQL but support PG as alternate DB.

2018-03-02 14:04 UTC, mitjok commented
@yivo fixed

2018-03-02 14:07 UTC, yivo requested changes

2018-03-02 14:07 UTC, yivo commented on config/initializers/abstract_mysql2_adapter.rb
> +return unless File.exists?('active_record/connection_adapters/mysql2_adapter.rb')
@mitjok It is better to check for ruby constant.

2018-03-02 14:07 UTC, yivo commented on app/models/account_version.rb
> +    # to produce sql with `RETURNING "id"`at the end of the `INSERT` SQL statement
@mitjok space is missing before `at`.

2018-03-02 14:07 UTC, yivo commented on app/models/account_version.rb
> +    # 3. mssql returns id = nil
@mitjok Can you please use `MSSQL`?

2018-03-02 14:09 UTC, yivo requested changes
@mitjok Can you please include guide on how to ge PG with Peatio at `docs/databases/postgresql.md`.

2018-03-02 14:09 UTC, yivo commented on app/models/account_version.rb
> +  # Use account balance and locked columnes as optimistic lock column. If the
@mitjok It should be `columns`.

2018-03-02 15:25 UTC, mitjok commented
@yivo not sure why this build is [failing](https://www.evernote.com/l/AYMiBDb7gTxI_I53vEKa_tPeQbfyfIAn6XAB/image.png)

2018-03-03 11:55 UTC, yivo approved these changes

2018-03-05 12:49 UTC, merged