Extra fields for fiat withdraw(closes #548)
openware/peatio pull request #620
Opened 2018-03-01 16:39 UTC by yssavchuk

2018-03-04 12:37 UTC, yivo requested changes

2018-03-04 12:37 UTC, yivo commented on app/assets/javascripts/funds/models/withdraw.js.coffee
> +  @configure 'Withdraw', 'sn', 'account_id', 'member_id', 'currency', 'amount', 'fee', 'address', 'label',
Don't add all these fields here. Add only `details`.

2018-03-04 12:37 UTC, yivo commented on app/models/withdraw.rb
> +  validates \
@yssavchuk I think we can skip validations for now to speed up PR.

2018-03-07 12:49 UTC, yssavchuk commented
@yivo review please

2018-03-07 16:10 UTC, ysv commented on app/models/member.rb
> +          members = joins(:withdraw_destinations).where('withdraw_destinations.details LIKE ?', "%#{term}%")
Look attentive to this line please

2018-03-07 16:10 UTC, ysv commented on app/validators/withdraw_blacklist_validator.rb
> +    if record.channel.blacklist && record.channel.blacklist.include?(record.address)
Do we still need this validation ?

2018-03-09 13:00 UTC, yivo requested changes

2018-03-09 13:00 UTC, yivo commented on app/validators/withdraw_blacklist_validator.rb
> +    if record.channel.blacklist && record.channel.blacklist.include?(record.address)
@yssavchuk No, this is going to be configurable from barong I think.

2018-03-09 13:00 UTC, yivo commented on app/models/withdraw_destination.rb
> +#  currency    :integer
@yssavchuk Must be currency_id, not null, required 100%

2018-03-09 13:00 UTC, yivo commented on app/models/withdraw_destination.rb
> +#  member_id   :integer
@yssavchuk Must be required, not null.

2018-03-09 13:00 UTC, yivo commented on app/models/withdraw_destination.rb
> +#  currency_id :integer
@yssavchuk Drop this.

2018-03-09 13:00 UTC, yivo commented on app/models/withdraw_destination.rb
> +  def as_json(options = {})
@yssavchuk Why this change is needed?

2018-03-09 13:00 UTC, yivo commented on app/models/member.rb
> +          members = joins(:withdraw_destinations).where('withdraw_destinations.details LIKE ?', "%#{term}%")
@yssavchuk No, this is very terrible. Drop this feature at all. We will bring this back when we will have time to use sphinx, elasticsearch, or simple table with fulltext index.

2018-03-09 13:00 UTC, yivo commented on app/models/member.rb
> +  has_many :withdraw_destinations
@yssavchuk set some default ordering

2018-03-09 13:00 UTC, yivo commented on app/controllers/private/withdraw_destinations_controller.rb
> +        head :bad_request
@yssavchuk never use this status unless you understand it. use unprocessable_entity

2018-03-09 17:44 UTC, yssavchuk commented on app/models/withdraw_destination.rb
> +  def as_json(options = {})
because we need to respond with {..., address: '123', label: 'abc', ...}
but not {..., details: {address: '123', label: 'abc'} , ...}

2018-03-10 20:41 UTC, yivo approved these changes

2018-03-11 10:47 UTC, merged