[WIP] Remove KeyPair authentication
openware/peatio pull request #629
Opened 2018-03-03 13:54 UTC by ashanaakh

2018-03-04 12:13 UTC, yivo commented
@ashanaakh You are missing a lot of things. Websocket API must be refactored to use JWT. You should not rewrite existing code (example: auth middleware). Also don't forget to cleanup helpers everywhere. Be VERY attentive.

2018-03-04 13:27 UTC, ashanaakh commented
@yivo, It is not finished, I just want you to check if I doing it in right way. Sorry, what do you mean

> should not rewrite existing code (example: auth middleware).

Should I completely remove `keypairs` and from peatio?

Old auth miidleware was:
```ruby
class Middleware < Grape::Middleware::Base
  def before
    if auth_by_keypair?
      auth = KeypairAuthenticator.new(request, params)
      env['api_v2.keypair_token']       = auth.authenticate!
      env['api_v2.authentic_member_id'] = env['api_v2.keypair_token'].member_id
    elsif auth_by_jwt?
      env['api_v2.authentic_member_email'] = \
        JWTAuthenticator.new(headers['Authorization']).authenticate!
    end
  end
end
```

2018-03-06 08:35 UTC, yivo requested changes

2018-03-06 08:35 UTC, yivo commented on app/api/api_v2/websocket_protocol.rb
> +      payload = JSON.dump(method: data )
@ashanaakh Fix please.

2018-03-06 12:17 UTC, ashanaakh commented
@yivo Fixed

2018-03-06 12:17 UTC, ashanaakh commented
@yivo Fixed

2018-03-08 16:25 UTC, yivo approved these changes

2018-03-08 21:01 UTC, merged