Refactor environment variables for Pusher (closes #681)
openware/peatio pull request #687
Opened 2018-03-13 14:01 UTC by yssavchuk

2018-03-13 14:04 UTC, yssavchuk commented on config/initializers/pusher.rb
> +Pusher.secret     = ENV.fetch('PUSHER_SECRET')
I think we need to require this variables because they are specific for each application

2018-03-13 14:04 UTC, yssavchuk commented on config/initializers/pusher.rb
> +Pusher.cluster    = ENV['PUSHER_CLUSTER'] unless ENV.key?('PUSHER_HOST')
cluster will be specified only if host wasn't specified before

2018-03-15 10:46 UTC, yivo requested changes

2018-03-15 10:46 UTC, yivo commented on app/controllers/application_controller.rb
>        wsHost:    ENV.fetch('PUSHER_HOST', 'ws.pusherapp.com'),
@yssavchuk No default!!! All must be placed in application.yml.

Delete PUSHER_CLUSTER.

2018-03-15 10:46 UTC, yivo commented on config/initializers/pusher.rb
> +Pusher.cluster    = ENV['PUSHER_CLUSTER'] unless ENV.key?('PUSHER_HOST')
@yssavchuk Delete PUSHER_CLUSTER and require PUSHER_HOST

2018-03-15 10:46 UTC, yivo commented on config/initializers/pusher.rb
> +Pusher.encrypted  = ENV.key?('PUSHER_ENCRYPTED')
@yssavchuk This will not work. Change to `ENV.fetch('PUSHER_ENCRYPTED').present?`

2018-03-15 10:46 UTC, yivo commented on config/initializers/pusher.rb
> +Pusher.port       = ENV['PUSHER_PORT'].to_i
@yssavchuk Require this var. No need for `to_i`.

2018-03-15 13:44 UTC, yssavchuk commented on config/initializers/pusher.rb
> +Pusher.encrypted  = ENV.key?('PUSHER_ENCRYPTED')
but this will require `PUSHER_ENCRYPTED` to be set

2018-03-15 14:26 UTC, yivo commented on config/initializers/pusher.rb
> +Pusher.encrypted  = ENV.key?('PUSHER_ENCRYPTED')
@yssavchuk Yes, you should list ALL ALL variables in single file.

![image](https://user-images.githubusercontent.com/7421323/37469270-9448beee-286d-11e8-8923-e4faf491f2e8.png)

2018-03-19 12:37 UTC, mod approved these changes

2018-03-19 12:58 UTC, yivo approved these changes

2018-03-19 13:11 UTC, merged