Ability to set collation on database.yml via env variable (#closes 672)
openware/peatio pull request #688
Opened 2018-03-13 14:13 UTC by yssavchuk

2018-03-14 17:00 UTC, yivo requested changes

2018-03-14 17:00 UTC, yivo commented on config/database.yml
> +  colation: <%= ENV.fetch('DATABASE_HOST', 'utf8_general_ci') %>
@yssavchuk Interesting...

It also must no in application.yml. No *ing hidden defaults please!

2018-03-14 17:03 UTC, yivo commented on config/database.yml
> +  colation: <%= ENV.fetch('DATABASE_HOST', 'utf8_general_ci') %>
Hey @yssavchuk 

I checked this again. We don't want ENV here. Hardcode please

2018-03-16 09:33 UTC, yivo approved these changes

2018-03-16 10:03 UTC, mod requested changes

2018-03-16 10:03 UTC, mod commented on config/database.yml
> +  colation: utf8_general_ci
is it not a spelling mistake?

2018-03-16 10:12 UTC, yivo commented on config/database.yml
> +  colation: utf8_general_ci
@mod this is...

@yssavchuk could you pls update it?

2018-03-18 13:37 UTC, mod approved these changes

2018-03-19 11:37 UTC, merged