Possible fix of WS authorization (#699)
openware/peatio pull request #700
Opened 2018-03-15 18:04 UTC by dkrokhmal

2018-03-16 09:06 UTC, yivo requested changes
@dkrokhmal Hi

Thanks you for the contribution. Could you please update PR according to the review?

Thanks.

2018-03-16 09:06 UTC, yivo commented on app/api/api_v2/websocket_protocol.rb
> +      token   = msg['jwt_token']
@dkrokhmal Could you please update it to `jwt` since acronym `JWT` already includes `token`? I found it as tautology for myself.

2018-03-16 10:30 UTC, dkrokhmal commented
@yivo agree with you, renamed it

2018-03-17 15:35 UTC, yivo approved these changes

2018-03-18 13:25 UTC, merged