Ability to retrieve assets information through API (closes #566)
openware/peatio pull request #701
Opened 2018-03-15 19:42 UTC by yssavchuk

2018-03-21 14:40 UTC, yivo requested changes

2018-03-21 14:40 UTC, yivo commented on app/api/api_v2/assets.rb
> +module APIv2
I think we should go with peatio convention for it:

There should not any index proofs actions. Only get.

Get latest proof should be: `/solvency/liability_proofs/latest?currency=btc`

You must not allow fiat currencies to be accepted. Please, don't waste time for writing detailed description. Set desc for params to: `The code of any currency with type set to "coin".`. This param is mandatory.

Get my partial tree: `/solvency/liability_proofs/partial_tree/mine?currency=btc`.

Please, update the names for grape entity and API classes (we need to keep all solvency entities namespaced).

2018-03-21 14:40 UTC, yivo commented on app/api/api_v2/assets.rb
> +module APIv2
Also please write some very simple specs.

2018-03-22 11:17 UTC, yssavchuk commented
@yivo review please

2018-03-22 11:20 UTC, yivo requested changes

2018-03-22 11:20 UTC, yivo commented on app/api/api_v2/solvency.rb
> +    get '/solvency/liability_proofs/latest' do
@yssavchuk It should return only the latest proofs, one per currency, check `Proof.current`

2018-03-22 11:20 UTC, yivo commented on app/api/api_v2/solvency.rb
> +    get '/solvency/liability_proofs/partial_tree/mine' do
@yssavchuk It should return single partial tree extracted from the latest proof for specified currency. Check `Private::AssetsController#partial_tree`.

2018-03-22 11:20 UTC, yivo commented on app/api/api_v2/solvency.rb
> +    get '/solvency/liability_proofs/latest' do
Check Check `Private::AssetsController#index`.

2018-03-22 11:23 UTC, yivo commented
@yssavchuk Also please fix this:
![image](https://user-images.githubusercontent.com/7421323/37767864-4426fbb2-2dd4-11e8-93a3-1de34e3e0ba6.png)

2018-03-22 11:54 UTC, yssavchuk commented on app/api/api_v2/solvency.rb
> +    get '/solvency/liability_proofs/partial_tree/mine' do
```Private::AssetsController#partial_tree``` is broken
![deepinscreenshot_select-area_20180322135335](https://user-images.githubusercontent.com/19859122/37769111-98cc587a-2dd8-11e8-861a-2d7acea75cab.png)

2018-03-22 11:55 UTC, yssavchuk commented on app/api/api_v2/solvency.rb
> +    get '/solvency/liability_proofs/partial_tree/mine' do
I will submit issue

2018-03-22 13:31 UTC, yivo requested changes

2018-03-22 13:31 UTC, yivo commented on app/api/api_v2/solvency.rb
> +        .with_currency(params[:currency])
@yssavchuk Better to use `Member#get_account` here.

2018-03-22 13:31 UTC, yivo commented on spec/api/api_v2/solvency_spec.rb
> +      it 'should not fails if proofs doesn\'t exist' do
`should not fail if proofs don't exist`

2018-03-22 13:31 UTC, yivo commented on spec/api/api_v2/solvency_spec.rb
> +      it 'should not fails if proofs doesn\'t exist' do
`doesn\'t fail if proofs don\'t exist`

2018-03-22 13:31 UTC, yivo commented on spec/api/api_v2/solvency_spec.rb
> +    context 'without liability proof' do
`when no liability proofs available in database`

2018-03-22 13:31 UTC, yivo commented on spec/api/api_v2/solvency_spec.rb
> +    context 'with liability proof' do
`when liability proofs available in database`

2018-03-22 13:31 UTC, yivo commented on spec/api/api_v2/solvency_spec.rb
> +      it 'should return liability proof and it should be freshest' do
`latest`

2018-03-22 13:31 UTC, yivo commented on spec/api/api_v2/solvency_spec.rb
> +    context 'without partial tree' do
`no partial trees available in database`

2018-03-22 13:31 UTC, yivo commented on spec/api/api_v2/solvency_spec.rb
> +    context 'with partial tree' do
`when partial trees available in database`

2018-03-22 13:31 UTC, yivo commented on spec/api/api_v2/solvency_spec.rb
> +      let!(:partial_trees) { create_list(:partial_tree, 10, account: member.accounts.find_by_currency_id(Currency.find_by_code(:btc).id)) }
`member.ac(:btc).id`

2018-03-22 13:31 UTC, yivo commented on spec/api/api_v2/solvency_spec.rb
> +      it 'should return partial trees and it should be freshest' do
`latest`

2018-03-22 13:31 UTC, yivo commented on app/api/api_v2/solvency.rb
> +    get '/solvency/liability_proofs/latest' do
@yssavchuk Add desc: `Returns newest liability proof record for given currency.`.

2018-03-22 13:31 UTC, yivo commented on app/api/api_v2/solvency.rb
> +    get '/solvency/liability_proofs/partial_tree/mine' do
@yssavchuk Desc needed: `Returns newest partial tree record for member account of specified currency.`.

2018-03-22 13:57 UTC, yivo approved these changes

2018-03-22 19:50 UTC, yivo commented
@yssavchuk I rebased the branch.

2018-03-22 20:10 UTC, yivo commented
@yssavchuk Seems OK.

![image](https://user-images.githubusercontent.com/7421323/37795646-c25c720c-2e1d-11e8-9268-ad0e9372276f.png)

2018-03-22 20:11 UTC, yivo commented
![image](https://user-images.githubusercontent.com/7421323/37795693-e76abf54-2e1d-11e8-9e73-7bb3b0e24daa.png)

2018-03-23 10:48 UTC, merged