Remove translations not used by Peatio (closes #714)
openware/peatio pull request #726
Opened 2018-03-22 14:03 UTC by yssavchuk

2018-03-22 14:21 UTC, yivo commented
@yssavchuk Tests are failing :(

2018-03-23 10:16 UTC, yivo commented
@yssavchuk please 1) rebase; 2) update russian lang locales

2018-03-24 16:19 UTC, yssavchuk commented
@yivor rebased russian locales are up to date

2018-03-25 12:07 UTC, yivo requested changes

2018-03-25 12:07 UTC, yivo commented on config/locales/server.en.yml
> +        latest_trade: Latest Trade
@yssavchuk Can you explain what is this?

2018-03-25 12:07 UTC, yivo commented on config/locales/server.en.yml
>        settings:
@yssavchuk I don't think these vars are used on peatio...

2018-03-29 16:30 UTC, yivo requested changes

2018-03-29 16:30 UTC, yivo commented on config/locales/server.en.yml
>        settings:
@yssavchuk I reviewed this code. Seems like stupid chine coders put some transactions in JS file and some in gon vars...

2018-03-29 16:30 UTC, yivo approved these changes

2018-03-29 17:23 UTC, merged