Add management API v1
openware/peatio pull request #740
Opened 2018-03-24 15:24 UTC by yivo

2018-03-30 09:29 UTC, antonror commented
`spec/models/withdraw_spec.rb:216`
 you have after_commit callback on cancel event in withdraw model, which reverts created withdraw to canceled and tries to unlock funds. created event locks no funds. a possible fix is to ensure aasm_state in callback method `models/withdraw:152`: 
```
  def unlock_funds
    unless self.aasm.from_state.eql?(:created)
      account.lock!
      account.unlock_funds sum, reason: Account::WITHDRAW_UNLOCK, ref: self
    end
  end
```

2018-04-03 08:44 UTC, yivo commented
![image](https://user-images.githubusercontent.com/7421323/38239034-58d1bb42-3734-11e8-946b-b86bca864719.png)

2018-04-03 18:53 UTC, mod requested changes

2018-04-03 18:53 UTC, mod commented on app/api/management_api_v1/jwt_authentication_middleware.rb
> +      env['rack.input'] = StringIO.new(payload.fetch(:data, {}).to_json)
Normally payload is base 64 encoded, please double check the RFC
```
   payload
      The "payload" member MUST be present and contain the value
      BASE64URL(JWS Payload).
```

2018-04-03 19:01 UTC, yivo commented on app/api/management_api_v1/jwt_authentication_middleware.rb
> +      env['rack.input'] = StringIO.new(payload.fetch(:data, {}).to_json)
@mod It is handled by jwt-multisig gem. Check this https://github.com/rubykube/jwt-multisig/blob/master/lib/jwt-multisig.rb#L115

2018-04-04 11:01 UTC, mod approved these changes

2018-04-04 11:03 UTC, merged