fix gemfile warning
openware/peatio pull request #751
Opened 2018-03-28 12:11 UTC by dpaluy

Fixes the following warning while running `bundle install`

> The git source `git://github.com/oauth-xx/oauth2.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.

2018-03-29 13:38 UTC, yivo commented
Hi @dpaluy 

Thanks for the contribution. You should always renew Gemfile.lock after changes to Gemfile.

2018-03-29 13:39 UTC, yivo requested changes
Updated Gemfile.lock needed.

2018-03-29 21:10 UTC, dpaluy commented
@yivo,  I didn't renew the `Gemfile.lock` because it changes the version:

```
-  remote: git://github.com/oauth-xx/oauth2.git
-  revision: 49ab9a3c0d021e8d954396f33d102079588279d6
+  remote: https://github.com/oauth-xx/oauth2
+  revision: a934b65872f2141aca56bf1f8bba0960ff50e248
```

You should never include github without specifying a version. For example:

```
gem 'foo', github: 'alice/github', ref: '4abec'
#or
gem 'foo', github: 'alice/github', branch: 'pre-release'
#or
gem 'foo', github: 'alice/github', tag: 'abc'
```

@yivo If you agree, I will set a revision (see https://github.com/rubykube/peatio/pull/751/commits/14f4d72ae379cfdcf55abcff0033762e86205633 )

2018-03-30 09:18 UTC, yivo commented
@dpaluy Please, take a look into Gemfile.lock. This is the place where actual version lives.

2018-03-30 09:18 UTC, yivo commented
Bundler tries to update it since you changed the source.

2018-03-31 13:06 UTC, dpaluy commented on Gemfile
> +git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }
@yivo this method overwrites default Rails and requests secured source

2018-04-05 13:04 UTC, yivo commented
@dpaluy We don't store versions if Gemfile. This is what Gemfile.lock is used for. Could you update it?

2018-04-05 13:35 UTC, dpaluy commented
@yivo I can't remove the revision from Gemfile, because it changes the version, as following:

```
-  remote: git://github.com/oauth-xx/oauth2.git
-  revision: 49ab9a3c0d021e8d954396f33d102079588279d6
+  remote: https://github.com/oauth-xx/oauth2
+  revision: a934b65872f2141aca56bf1f8bba0960ff50e248
```

Pay attention that you can't lock a gem version if you include it directly via Github.
You have several options:
1. lock for a specific branch (not master) - not relevant in this case
2. fork a version to your company Github and include the version from there
3. Set a version in Github, as I did

2018-04-05 13:40 UTC, yivo commented
@dpaluy I don't mind updating the version. We use master because the latest released version requires `jwt ~> 1.5` but we need newer `jwt` gem. We have issue for this: https://github.com/rubykube/peatio/issues/667

2018-04-05 13:40 UTC, yivo commented
You are free to do as you prefer so we will merge this PR faster.

2018-04-05 13:45 UTC, dpaluy commented
@yivo I updated the version per your request

2018-04-06 11:32 UTC, yivo commented
@dpaluy Great!. Thanks!

2018-04-06 11:34 UTC, yivo approved these changes

2018-04-06 18:59 UTC, merged