bullet gem added
openware/peatio pull request #762
Opened 2018-03-29 21:43 UTC by dpaluy

Watch SQL queries during development
https://github.com/flyerhzm/bullet

Set `ENV['BULLET'] = 'true'` to turn it on.

Best practise adding this as a part of CI

2018-03-30 09:16 UTC, yivo requested changes

2018-03-30 09:16 UTC, yivo commented on Gemfile
> +  gem 'bullet'
@dpaluy please put version range for it, we also don't need it in `test`

2018-03-30 09:17 UTC, yivo commented
Hi @dpaluy 

Thank you for the contribution. Could you please fix above issues? Thanks.

2018-03-31 13:03 UTC, dpaluy commented
@yivo I included it in `test` env as well in order to include it as a part of your integration test in Jenkins

2018-04-05 14:20 UTC, yivo requested changes

2018-04-05 14:20 UTC, yivo commented on config/environments/development.rb
> +    Bullet.enable = (ENV['BULLET'] == 'true') ? true : false
@dpaluy Can you change this to `ENV['BULLET'].in?(%w[1 true])`. It seems more logically to me.

2018-04-05 14:55 UTC, dpaluy commented
@yivo I updated per your request

2018-04-05 16:24 UTC, yivo commented
@dpaluy Sorry but I meant to keep just `Bullet.enable = ENV['BULLET'].in?(%w[1 true])`. Why do you add `true`, `false` here? It makes no sense. Also duplication of configs makes no sense. I mind to include this kind of tools in test. They are already very slow and dirty.

2018-04-05 19:38 UTC, dpaluy commented
@yivo My mistake on `ENV`.
The config is different between `development` and `test`.

The best practise is running a nightly build (slow tests) with Bullet to provide a report on query quality.
Other builds won't use this tool in test environment.

If you skip it from test env, you won't be able to track all problematic cases. Because, testing manually doesn't scale.

2018-04-06 11:34 UTC, yivo commented
@dpaluy Thank you.

2018-04-06 11:34 UTC, yivo approved these changes

2018-04-06 11:35 UTC, merged