add missing step for PostgreSQL
openware/peatio pull request #769
Opened 2018-04-02 09:35 UTC by dpaluy

2018-04-05 13:06 UTC, yivo requested changes

2018-04-05 13:06 UTC, yivo commented on docs/databases/postgresql.md
> +4. Remove `config/initializers/abstract_mysql2_adapter.rb`
@dpaluy I don't think this is necessary step. For such scenario you may want to cleanup whole project for code specific to MySQL. I think `bundle install` is OK for people but this step is just useless.

2018-04-05 13:39 UTC, dpaluy commented on docs/databases/postgresql.md
> +4. Remove `config/initializers/abstract_mysql2_adapter.rb`
@yivo I just added it as a reference for other working with PG. It's a readme file.

 I don't think we should waste our time on the discussion 😉

2018-04-06 11:35 UTC, yivo approved these changes

2018-04-06 11:38 UTC, merged