Ability to manage market pairs using admin panel
openware/peatio pull request #781
Opened 2018-04-04 13:18 UTC by yssavchuk

2018-04-05 09:31 UTC, yivo requested changes

2018-04-05 09:31 UTC, yivo commented on spec/models/market_spec.rb
> +  context 'fields validations' do
No need for context since you need it when you want to have another let,subeject scope.

2018-04-05 09:31 UTC, yivo commented on spec/models/market_spec.rb
> +      expect(record.errors.full_messages).to include(/Bid unit can't be blank/i)
@yssavchuk please use small letters for this regex expressions

2018-04-05 09:31 UTC, yivo commented on spec/models/market_spec.rb
> +    it 'validates units non equivalence' do
@yssavchuk please write the next text: `validates equivalence of units`

2018-04-05 09:31 UTC, yivo commented on spec/models/market_spec.rb
> +    it 'validates units presence' do
`it validates presence of units`

2018-04-05 09:31 UTC, yivo commented on config/routes/admin.rb
> +  resources :markets
allow only GET, POST, PUT, delete is prohibited!

2018-04-05 09:31 UTC, yivo commented on app/views/layouts/admin.html.erb
> +              <%= link_to t('.menus.sections.markets'), admin_markets_path %>
@yssavchuk please no translations for admin panel!!!

2018-04-05 09:31 UTC, yivo commented on app/views/admin/markets/index.html.erb
> +      <span><%= t('.markets') %></span>
@yssavchuk no i18n in admin please

2018-04-05 09:31 UTC, yivo commented on app/views/admin/markets/index.html.erb
> +          <%= link_to t('actions.view'), admin_market_path(x), target: '_blank' %>
@yssavchuk no i18n in admin please

2018-04-05 09:31 UTC, yivo commented on app/controllers/admin/deposits/fiats_controller.rb
> +        binding.pry
@yssavchuk don't forget to rollback this file

2018-04-05 09:31 UTC, yivo commented on app/controllers/admin/markets_controller.rb
> +      @markets = Market.all.page params[:page]
@yssavchuk please wrap in `()`

2018-04-05 09:31 UTC, yivo commented on app/controllers/admin/markets_controller.rb
> +          .tap { |p| p.merge!(id: p[:bid_unit] + p[:ask_unit]) if p[:bid_unit].present? && p[:ask_unit].present? }
@yssavchuk don't touch ID here. Always remove ID from params, like `delete(:id)`. Check this please. I also need specs!

2018-04-05 09:31 UTC, yivo commented on app/controllers/application_controller.rb
> +    #gon.market = current_market.attributes
@yssavchuk I don't know why this is commented out but don't forget to rollback changes.

2018-04-05 10:24 UTC, ysv commented on app/controllers/application_controller.rb
> +    #gon.market = current_market.attributes
Because params[:market] is used in this line also https://github.com/yssavchuk/peatio/blob/99d7cce00c38014b5e176f62a6bef90f78914d60/app/controllers/application_controller.rb#L17

2018-04-05 10:24 UTC, ysv commented on app/controllers/application_controller.rb
> +    #gon.market = current_market.attributes
that is why MarketController requests brokes ApplicationController

2018-04-05 10:51 UTC, yssavchuk commented on app/controllers/admin/markets_controller.rb
> +          .tap { |p| p.merge!(id: p[:bid_unit] + p[:ask_unit]) if p[:bid_unit].present? && p[:ask_unit].present? }
delete(:id) returns nil if params don't include it so I used except(:id)

2018-04-05 13:00 UTC, yivo commented on app/controllers/application_controller.rb
> +    #gon.market = current_market.attributes
Oh I don't understand @yssavchuk

2018-04-06 09:28 UTC, yivo requested changes

2018-04-06 09:28 UTC, yivo commented on spec/models/market_spec.rb
> +    def market_params
@yssavchuk Use `let(:valid_attributes) { ... }`

2018-04-06 13:46 UTC, yssavchuk commented
@yivo review please

2018-04-06 18:52 UTC, yivo commented
@yssavchuk I have rebased PR.

2018-04-06 19:29 UTC, yivo commented
![image](https://user-images.githubusercontent.com/7421323/38440397-fe4c9d32-39e9-11e8-9120-b61af9f0db73.png)

![image](https://user-images.githubusercontent.com/7421323/38440407-04726494-39ea-11e8-96d9-1db54c7738e8.png)

2018-04-06 19:38 UTC, merged