Fix typos and update details for Ubuntu installation instruction
openware/peatio pull request #783
Opened 2018-04-04 20:20 UTC by msylvestre

Fix the repo URL
Fix the ruby version
Added detail how to setup MySQL
Added detail about setuping the Google Auth
Added detail if you run peatio form a server and not from a local machine
Added info about the "working trade UI"

2018-04-04 21:07 UTC, yivo requested changes

2018-04-04 21:07 UTC, yivo commented on docs/setup-ubuntu.md
> +NOTE : Looks like the trading/MArket UI is broken.  Install an run https://github.com/rubykube/peatio-trading-ui in parallel of peatio.
@msylvestre I don't think we can merge this. Trading UI is fully working. Check https://github.com/rubykube/peatio/blob/master/docs/releases/1.5.0.md

2018-04-04 23:39 UTC, msylvestre commented on docs/setup-ubuntu.md
> +NOTE : Looks like the trading/MArket UI is broken.  Install an run https://github.com/rubykube/peatio-trading-ui in parallel of peatio.
Hi yivo, What I mean is that _now_ you need to install trading-ui as a separate server, you can't just run peatio "as-is" as it was originally written in the installation instruction.

But I understand, your point, it's not clear, let me me rephrase.  I'm also understanding better "why and how", after chatting more with the folk on Telegram !

2018-04-05 13:07 UTC, yivo requested changes

2018-04-05 13:07 UTC, yivo commented on docs/setup-ubuntu.md
> +NOTE : Looks like the trading/MArket UI is broken.  Install an run https://github.com/rubykube/peatio-trading-ui in parallel of peatio.
@msylvestre Hi
Could you just pul link to 1.5 release notes or to trading-ui README file instead of this paragraph?

2018-04-05 14:07 UTC, yivo commented
@msylvestre Thank you

2018-04-06 10:14 UTC, merged