[WIP] #823 Recode Slim templates to ERB and remove gem slim
openware/peatio pull request #836
Opened 2018-04-10 11:25 UTC by dinesh-skyach

Recoded Slim templates to ERB and removed gem slim #823

2018-04-10 13:29 UTC, yivo requested changes
@dinesh-skyach I see many issues with code style in pagination views. Have you used automatic tools for converting slim to erb? I would not use them since they produce bad results. I think we need to try generate ERB views by using kaminari gem. Please update the gem to the latest version, generate erb views using generator from the gem and test paginators in admin panel.

2018-04-10 13:29 UTC, yivo commented on app/views/kaminari/_prev_page.html.erb
> +<li class="previous <%= (current_page.first?)? 'disabled' : '' %>">
Please, use `<%= 'disable' if current_page.first? %>` everywhere. It is hard to understand this line.

2018-04-10 13:29 UTC, yivo commented on app/views/kaminari/_prev_page.html.erb
> +<%= link_to raw(t 'views.pagination.previous'), url, :rel => 'prev', :remote => remote %>
Use new Ruby hash syntax. Pls update everywhere.

2018-04-10 13:29 UTC, yivo commented on app/views/kaminari/_paginator.html.erb
> +      <% end %><%= next_page_tag %>
@dinesh-skyach Please maintain positions of code: `<%= next_page_tag %>` should be on the next line.

2018-04-10 13:29 UTC, yivo commented on app/views/kaminari/_paginator.html.erb
> +- available local variables
@dinesh-skyach I see the problems with the alignment of comments. Please, check original comments from slim.

2018-04-10 15:59 UTC, dinesh-skyach commented
@yivo, I have made the changes.

2018-04-16 10:10 UTC, yivo approved these changes

2018-04-16 12:58 UTC, merged