[WIP] Add support field Currency#visible (#818)
openware/peatio pull request #855
Opened 2018-04-12 15:16 UTC by ashanaakh

2018-04-17 08:54 UTC, yivo requested changes
Check app/api VERY carefully.


Use this scope to fetch enabled accounts:
<img width="712" alt="2018-04-17--11-27-18" src="https://user-images.githubusercontent.com/7421323/38859003-ccaf0df6-4235-11e8-82c4-e13086c8668e.png">
<img width="622" alt="2018-04-17--11-27-14" src="https://user-images.githubusercontent.com/7421323/38859005-ccdc933e-4235-11e8-945e-f895e87185f0.png">

Visible ony:
<img width="1104" alt="2018-04-17--11-25-24" src="https://user-images.githubusercontent.com/7421323/38859006-cd26609a-4235-11e8-9f1f-3e0fa2125fc1.png">
<img width="1090" alt="2018-04-17--11-24-28" src="https://user-images.githubusercontent.com/7421323/38859008-cd7a1a3c-4235-11e8-9b3d-58c7dc6a4ee0.png">
<img width="1102" alt="2018-04-17--11-24-11" src="https://user-images.githubusercontent.com/7421323/38859009-cdbd26e2-4235-11e8-9e9e-72a7f8cd3d7d.png">
<img width="1089" alt="2018-04-17--11-23-40" src="https://user-images.githubusercontent.com/7421323/38859010-ce468964-4235-11e8-814d-d340f0e392f5.png">
<img width="871" alt="2018-04-17--11-22-57" src="https://user-images.githubusercontent.com/7421323/38859011-ce88df12-4235-11e8-8645-c3f9dc6b9836.png">

app/api:
<img width="1091" alt="2018-04-17--11-21-33" src="https://user-images.githubusercontent.com/7421323/38859013-cf413378-4235-11e8-9a98-68e0be76e6e2.png">
<img width="1081" alt="2018-04-17--11-21-29" src="https://user-images.githubusercontent.com/7421323/38859015-cfcc675e-4235-11e8-879d-6f36faf19719.png">
<img width="1081" alt="2018-04-17--11-20-53" src="https://user-images.githubusercontent.com/7421323/38859017-d01bfad0-4235-11e8-8710-62214ca881e7.png">
<img width="1110" alt="2018-04-17--11-20-34" src="https://user-images.githubusercontent.com/7421323/38859018-d083e62c-4235-11e8-8856-46c7bfa17511.png">
<img width="1110" alt="2018-04-17--11-19-57" src="https://user-images.githubusercontent.com/7421323/38859019-d0ef7964-4235-11e8-8791-ac3fb0de02d4.png">
<img width="1106" alt="2018-04-17--11-19-51" src="https://user-images.githubusercontent.com/7421323/38859021-d1a0dc0e-4235-11e8-9d85-e36e25decd82.png">

2018-04-24 10:36 UTC, yivo requested changes

2018-04-24 10:36 UTC, yivo commented on spec/factories/currencies.rb
> +    trait :invisible do
@ashanaakh This is not good and should be removed. We seed currencies and markets before every example so it is not possible to use factories for currencies or markets as usually. Please use `before` & `after` callback for the spec.

2018-04-24 10:36 UTC, yivo commented on spec/api/management_api_v1/withdraws_spec.rb
> +    after { Currency.destroy(invisible_currency) }
@ashanaakh This should be removed too.

2018-04-24 10:36 UTC, yivo commented on spec/api/management_api_v1/withdraws_spec.rb
> +    it 'validates currency visibility' do
@ashanaakh Better to use `validates visibility of currency`

2018-04-24 10:36 UTC, yivo commented on spec/api/management_api_v1/withdraws_spec.rb
> +    let :bad_data do
@ashanaakh Use `context 'invisible currency'` and `before` `after` changing visibility instead of producing lot of magic `lets`.

2018-04-24 10:36 UTC, yivo commented on spec/api/api_v2/solvency_spec.rb
> +      it 'should validate currency visibility' do
@ashanaakh Don't use `should`, just `it 'validates visibility of currency'`.

2018-04-24 10:36 UTC, yivo commented on spec/api/management_api_v1/withdraws_spec.rb
> +    let :bad_data do
```ruby
context 'invisible currency' do
  before { currency.update!(visible: false) }
  after { currency.update!(visible: true) }
  it '...' do
    # ...
  end
end
```

2018-05-05 10:14 UTC, ashanaakh commented
@yivo rebased on master.

2018-05-14 12:02 UTC, yivo commented
@ashanaakh Please, change base to 1-8-stable.

2018-05-14 14:44 UTC, ashanaakh commented
@yivo Done :smile:

2018-05-15 11:19 UTC, yivo requested changes
Looks good.

2018-05-15 11:19 UTC, yivo commented on spec/api/management_api_v1/withdraws_spec.rb
> +        params = {
@ashanaakh In this call we don't need amount and rid since is returns collection.

2018-05-15 11:19 UTC, yivo commented on spec/api/management_api_v1/deposits_spec.rb
> +          amount:   0.1
@ashanaakh No need for field amount for this call.

2018-05-15 11:19 UTC, yivo commented on app/models/currency.rb
>    def summary
@ashanaakh This is used in admin panel on dashboard page. Admin should see all accounts.

2018-05-15 14:50 UTC, yivo approved these changes

2018-05-16 08:21 UTC, yivo commented
@ashanaakh Yesterday we discussed this with QA. We found some bugs with address generation. I will submit them later. Also we found that name `enabled` fits much better than `visible`. Please, do `visible` -> `enabled` including database migration & admin panel.

2018-05-23 13:12 UTC, yivo requested changes

2018-05-23 13:12 UTC, yivo commented on app/api/api_v2/deposits.rb
<img width="1141" alt="2018-05-23--16-06-06" src="https://user-images.githubusercontent.com/7421323/40426561-17191712-5ea4-11e8-9e80-c7851b8a6fb3.png">
<img width="569" alt="2018-05-23--15-59-29" src="https://user-images.githubusercontent.com/7421323/40426562-173c3e0e-5ea4-11e8-877b-bf791ab4bcfb.png">
<img width="1104" alt="2018-05-23--15-59-24" src="https://user-images.githubusercontent.com/7421323/40426563-175f2bd0-5ea4-11e8-99f8-ccdb9c6bea84.png">
<img width="1104" alt="2018-05-23--15-57-53" src="https://user-images.githubusercontent.com/7421323/40426564-17848ee8-5ea4-11e8-964e-2285780ea76b.png">
<img width="1097" alt="2018-05-23--15-57-44" src="https://user-images.githubusercontent.com/7421323/40426565-17ab05e6-5ea4-11e8-8c86-58df26c6eb16.png">
<img width="1095" alt="2018-05-23--15-57-34" src="https://user-images.githubusercontent.com/7421323/40426566-17cdc018-5ea4-11e8-860d-b2c386652c54.png">
<img width="1106" alt="2018-05-23--15-57-16" src="https://user-images.githubusercontent.com/7421323/40426567-17f1ad98-5ea4-11e8-97a5-5c50bbd0ec49.png">
<img width="1089" alt="2018-05-23--15-55-37" src="https://user-images.githubusercontent.com/7421323/40426568-1817514c-5ea4-11e8-8448-720898980544.png">

2018-05-24 11:44 UTC, yivo approved these changes

2018-05-24 14:10 UTC, merged