[WIP] #831 Finish Capybara tests in features/admin/withdraw_spec.rb
openware/peatio pull request #860
Opened 2018-04-13 14:17 UTC by dinesh-skyach

Finished Capybara tests in features/admin/withdraw_spec.rb #831

2018-04-13 15:10 UTC, yivo requested changes

2018-04-13 15:10 UTC, yivo commented on spec/features/admin/withdraw_spec.rb
>      member.get_account(:usd).tap { |a| a.update_attributes locked: 8000, balance: 10_000 }
@dinesh-skyach Can you use `update!` and round braces `()` here and in other places?

2018-04-13 15:10 UTC, yivo commented on spec/features/admin/withdraw_spec.rb
> +  it 'admin view usd withdraws' do
@dinesh-skyach please use different way of writing messages. For example (the current) case: `it 'allows admin to view USD withdraws'`. Please, update other messages too.

2018-04-13 15:10 UTC, yivo commented on spec/features/admin/withdraw_spec.rb
> +      expect(page).to have_content(I18n.t('actions.process'))
@dinesh-skyach You can feel free to omit I18n for admin panel. In admin we support only English.

2018-04-16 07:30 UTC, dinesh-skyach commented on spec/features/admin/withdraw_spec.rb
>      member.get_account(:usd).tap { |a| a.update_attributes locked: 8000, balance: 10_000 }
@yivo changes done

2018-04-16 10:30 UTC, yivo approved these changes

2018-04-16 12:59 UTC, merged