[WIP] #384 Add support for ERC20
openware/peatio pull request #913
Opened 2018-04-19 10:28 UTC by dinesh-skyach

Add support for ERC20 #384

2018-04-19 10:30 UTC, yivo requested changes

2018-04-19 10:30 UTC, yivo commented on config/templates/seed/currencies.yml.erb
> +    # BitGo specific configuration.
@dinesh-skyach We don't need BitGo with ERC20 for now.

2018-04-19 10:47 UTC, dinesh-skyach commented on config/templates/seed/currencies.yml.erb
> +    # BitGo specific configuration.
@yivo ok will remove this

2018-04-26 07:03 UTC, yivo requested changes

2018-04-26 07:03 UTC, yivo commented on config/templates/seed/currencies.yml.erb
> +    contract_address:   "0x87099adD3bCC0821B5b151307c147215F839a110"
@dinesh-skyach Can you include docs for options?

2018-05-01 17:47 UTC, yivo approved these changes

2018-05-02 20:45 UTC, merged