Deposit fee feature (closes #886)
openware/peatio pull request #915
Opened 2018-04-19 13:41 UTC by yssavchuk

2018-04-24 10:41 UTC, yivo requested changes

2018-04-24 10:41 UTC, yivo commented on app/models/concerns/fee_chargeable.rb
> +    validates :fee, numericality: { greater_than_or_equal_to: 0 }
@yssavchuk You can combine these two in single statement: `presence: true, numericality: { greater_than_or_equal_to: 0 }`

2018-04-24 10:41 UTC, yivo commented on spec/models/withdraw_spec.rb
> +    it 'should compute fee' do
@yssavchuk Can you exclude `should` from msg? `it 'computes fee'`.

2018-04-24 20:39 UTC, yivo commented
@yssavchuk Can you also check if you have updated admin panel with this fee field?

2018-04-25 15:45 UTC, yssavchuk commented
@yivo Rebased
Also I've deleted active yaml base in this pr because I've forgot about it

2018-04-27 15:27 UTC, yivo approved these changes

2018-04-27 17:43 UTC, merged