Add API calls to get percent of the fees (resolved #852)
openware/peatio pull request #935
Opened 2018-04-24 09:59 UTC by ashanaakh

2018-04-24 10:13 UTC, yivo commented
@ashanaakh Don't forget about docs and specs.

2018-04-26 11:48 UTC, yivo requested changes

2018-04-26 11:48 UTC, yivo commented on app/api/api_v2/fees.rb
> +        fee = Fee.new 'fixed', c.withdraw_fee
@ashanaakh Please wrap in `(` & `)`. In Ruby it is better to use symbols for `:fixed`.

2018-04-26 11:48 UTC, yivo commented on app/api/api_v2/fees.rb
> +    Fee         = Struct.new :type, :value
@ashanaakh Please use `(` `)` more often because it adds readability.

2018-04-26 11:48 UTC, yivo commented on app/api/api_v2/fees.rb
> +    desc 'Returns markets and their fees.'
@ashanaakh Better to write `Returns trading fees for markets.`.

2018-04-26 11:48 UTC, yivo commented on app/api/api_v2/fees.rb
> +    desc 'Returns currencies and their withdraw fees.'
@ashanaakh Better to write `Returns withdraw fees for currencies`.

2018-04-26 11:48 UTC, yivo commented on spec/api/api_v2/fees_spec.rb
> +    it 'returns currencies withdraw fees' do
@ashanaakh better to write `it returns withdraw fees for every visible currency`.

2018-04-26 11:48 UTC, yivo commented on spec/api/api_v2/fees_spec.rb
> +      expect(response).to be_success
@ashanaakh This must be before reading response body.

2018-04-26 11:48 UTC, yivo commented on spec/api/api_v2/fees_spec.rb
> +      currency = result.find do |c|
@ashanaakh Write this in single line.

2018-04-26 11:48 UTC, yivo commented on app/api/api_v2/fees.rb
> +        ask_fee = Fee.new 'relative', m.ask_fee
@ashanaakh Send fees as strings: `m.ask_fee.to_s('F')`.

2018-04-26 11:48 UTC, yivo commented on app/api/api_v2/fees.rb
> +        bid_fee = Fee.new 'relative', m.bid_fee
@ashanaakh Send fees as strings: `m.ask_fee.to_s('F')`.

2018-04-26 11:48 UTC, yivo commented on app/api/api_v2/fees.rb
> +        fee = Fee.new 'fixed', c.withdraw_fee
@ashanaakh Send fees as strings: `m.ask_fee.to_s('F')`.

2018-04-26 11:48 UTC, yivo commented on spec/api/api_v2/fees_spec.rb
> +      Currency.find_by_code(:usd).update(withdraw_fee: 0.99)
@ashanaakh You can't just make any uncontrolled changes to this in specs or they will randomly fail. Just drop this line and compare directly: `Currency.find_by_code!(:usd).withdraw_fee`.

2018-04-26 11:48 UTC, yivo commented on spec/api/api_v2/fees_spec.rb
> +    it 'returns markets fees' do
@ashanaakh Just write `it returns trading fees`.

2018-04-26 11:48 UTC, yivo commented on spec/api/api_v2/fees_spec.rb
> +    it 'returns correct currency withdraw fee' do
@ashanaakh Invalid message. Write `it returns correct trading fees`.

2018-04-26 11:48 UTC, yivo commented on spec/api/api_v2/fees_spec.rb
> +      market = result.find do |c|
@ashanaakh Use single line for this.

2018-04-26 11:48 UTC, yivo commented on spec/api/api_v2/fees_spec.rb
> +      expect(response).to be_success
@ashanaakh The same problem: don't parse result before checking if request is OK.

2018-04-26 13:41 UTC, ashanaakh commented
@yivo Thanks for review. I will fix it shortly

2018-04-27 14:56 UTC, yivo requested changes
@ashanaakh Please, add one more endpoint: `/api/v2/fees/deposit`. Use `Currency#deposit_fee` for getting the value. Please add specs. It will fail until we merge #915 – it is OK.

2018-04-27 14:56 UTC, yivo commented on spec/api/api_v2/fees_spec.rb
> +
@ashanaakh It is better to not put an extra line here. Better to group linked operations: parsing result and them using it.

2018-04-27 14:56 UTC, yivo commented on app/api/api_v2/fees.rb
> +
@ashanaakh Extra line detected.

2018-04-27 15:28 UTC, yivo approved these changes

2018-05-01 09:12 UTC, merged